### ISSUE TITLE
JDK net test failures on test-macincloud-macos1014-x64-2

### ISSUE THREAD

**Issue by adam-thorpe** [adoptium/infrastructure#1085]
Set of 5 ipv6 tests have failed for the second time on the same machine since 3rd Jan.
Only seems to be affecting this machine on jdk8.

Last passing build on this machine (3rd Jan)
https://ci.adoptopenjdk.net/user/adam-thorpe/my-views/view/Nightly%20test%20openjdk%20openJ9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_xl/109/

Most recent failure (10th Jan)
https://ci.adoptopenjdk.net/user/adam-thorpe/my-views/view/Nightly%20test%20openjdk%20openJ9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_xl/115/

Failing tests:
```
java/net/Inet6Address/B6206527.java.B6206527
java/net/InetAddress/CheckJNI.java.CheckJNI
java/net/Socket/LinkLocal.java.LinkLocal
java/net/ipv6tests/B6521014.java.B6521014
java/net/ipv6tests/TcpTest.java.TcpTest
```

**Comment by sxa555** [comment]
I don't believe I have access - @gdams can you look at this please?

**Comment by sxa555** [comment]
@adam-thorpe Can we verify via a Grinder whether the old build still works on this machine?

**Comment by adam-thorpe** [comment]
Good idea don't know why I didn't think to try that

**Comment by adam-thorpe** [comment]
Grinder failed on both
Newest build: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1689/
Older build: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1691/

Which confirms that this is a recent change to something on the machine

**Comment by sxa** [comment]
There is no current machine by that name so I've no idea which one this was, so closing. macincloud machines are 10.10 and are being replaced with 12.0.2 ones.

JDK8/J9/sanity.openjdk passes on the 12.0.2 machine: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/641/
