### ISSUE TITLE
JTReg Test Failure: java/nio/channels/AsyncCloseAndInterrupt.java

### ISSUE THREAD

**Issue by adam-thorpe** [adoptium/infrastructure#1173]
Original issue: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1597

Machines:
test-packet-ubuntu1604-x64-2
test-softlayer-ubuntu1604-x64-​1
(There are definitely more but no way of determining unless I ran on every single linux and aix machine)

Hangs on:
```
11:42:34  Wait for initial Pump
11:42:34  Start pumping refuser ...
```

I think there may just be some old processes running on these machines that need clearing out. I don't believe it's a setup problem as `test-packet-ubuntu1604-x64-1` passes the test just fine

**Comment by sxa555** [comment]
No obvious sign of rogue processes on the softlayer machine:

```
jenkins@test-softlayer-ubuntu1604-x64-1:~$ ps -fu jenkins
UID        PID  PPID  C STIME TTY          TIME CMD
jenkins   3832     1  0  2019 ?        00:00:00 dbus-launch --autolaunch=f534585208a14c28b8eb05f53245aa6d --binary-syntax --clo
jenkins   3838     1  0  2019 ?        00:00:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
jenkins   5688  5652  0 15:20 ?        00:00:00 sshd: jenkins@pts/0
jenkins   5689  5688  9 15:20 pts/0    00:00:00 -bash
jenkins   5703  5689  0 15:20 pts/0    00:00:00 ps -fu jenkins
jenkins  22326     1  0  2019 ?        00:00:03 Xvfb -displayfd 2 -screen 0 1024x768x24 -fbdir /home/jenkins/xvfb-96-..fbdir296
jenkins  26298     1  0  2019 ?        00:03:05 /lib/systemd/systemd --user
jenkins  26303 26298  0  2019 ?        00:00:00 (sd-pam)
jenkins  31415 31335  0 Feb17 ?        00:15:35 sshd: jenkins@notty
jenkins  31500 31415  0 Feb17 ?        00:00:00 bash -c cd "/home/jenkins" && java  -jar remoting.jar -workDir /home/jenkins -j
jenkins  31501 31500  1 Feb17 ?        02:33:01 java -jar remoting.jar -workDir /home/jenkins -jar-cache /home/jenkins/remoting
jenkins@test-softlayer-ubuntu1604-x64-1:~$ 
```

**Comment by adam-thorpe** [comment]
I've ran the job on the packet machine twice (double checking) and twice on the passing machine, so I'm pretty confident this isn't inconsistent but I'll do a re-run on the softlayer one. Is it worth comparing between the two packet machines as they would have been setup very similarly so finding an outlier might be easier?

**Comment by adam-thorpe** [comment]
Failed run on the softlayer machine: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2324/

**Comment by sxa555** [comment]
Can you update this issue with the appropriate grinder parameters for reproducing this please?

**Comment by adam-thorpe** [comment]
```
PLATFORM = linux or aix
BUILD_LIST = openjdk
TARGET = jdk_custom
CUSTOM_TARGET = test/jdk/java/nio/channels/AsyncCloseAndInterrupt.java
JDK_VERSION = 11+
JDK_IMPL = openj9 or hotspot
LABEL = machine being tested
```
Give this a go

**Comment by sxa** [comment]
Needs re-runs to check if it's still failing. Adding to June milestone to perform initial verification as a minimum.

**Comment by Haroon-Khel** [comment]
Fresh grinders

Linux

* https://ci.adoptium.net/job/Grinder/7075/console [test-docker-fedora35-x64-1](https://ci.adoptium.net/manage/computer/test-docker-fedora35-x64-1/)
* https://ci.adoptium.net/job/Grinder/7076/console [test-docker-ubuntu2004-x64-2](https://ci.adoptium.net/manage/computer/test-docker-ubuntu2004-x64-2/)
* https://ci.adoptium.net/job/Grinder/7077/console [test-docker-ubuntu2004-x64-1](https://ci.adoptium.net/manage/computer/test-docker-ubuntu2004-x64-1/)
* https://ci.adoptium.net/job/Grinder/7078/console [test-docker-ubuntu2204-x64-1](https://ci.adoptium.net/manage/computer/test-docker-ubuntu2204-x64-1/)
* https://ci.adoptium.net/job/Grinder/7079/console [test-docker-debian11-x64-1](https://ci.adoptium.net/manage/computer/test-docker-debian11-x64-1/)
* https://ci.adoptium.net/job/Grinder/7080/console [test-equinix_esxi-ubuntu2204-x64-1](https://ci.adoptium.net/manage/computer/test-equinix_esxi-ubuntu2204-x64-1/)
* https://ci.adoptium.net/job/Grinder/7081/console [test-ibmcloud-ubuntu1604-x64-1](https://ci.adoptium.net/manage/computer/test-ibmcloud-ubuntu1604-x64-1/)
* https://ci.adoptium.net/job/Grinder/7082/console [test-equinix_esxi-ubuntu2204-x64-2](https://ci.adoptium.net/manage/computer/test-equinix_esxi-ubuntu2204-x64-2/)
* https://ci.adoptium.net/job/Grinder/7083/console [test-docker-fedora37-x64-1](https://ci.adoptium.net/manage/computer/test-docker-fedora37-x64-1/)
* https://ci.adoptium.net/job/Grinder/7084/console [test-docker-fedora37-x64-2](https://ci.adoptium.net/manage/computer/test-docker-fedora37-x64-2/)
* https://ci.adoptium.net/job/Grinder/7085/console [test-docker-fedora35-x64-2](https://ci.adoptium.net/manage/computer/test-docker-fedora35-x64-2/)
* https://ci.adoptium.net/job/Grinder/7086/console [test-docker-debian11-x64-2](https://ci.adoptium.net/manage/computer/test-docker-debian11-x64-2/)
* https://ci.adoptium.net/job/Grinder/7087/console [test-docker-ubi8-x64-2](https://ci.adoptium.net/manage/computer/test-docker-ubi8-x64-2/)
* https://ci.adoptium.net/job/Grinder/7088/console [test-docker-centos8-x64-1](https://ci.adoptium.net/manage/computer/test-docker-centos8-x64-1/)
* https://ci.adoptium.net/job/Grinder/7089/console [test-docker-ubi8-x64-1](https://ci.adoptium.net/manage/computer/test-docker-ubi8-x64-1/)

Aix

* https://ci.adoptium.net/job/Grinder/7090/console [test-osuosl-aix72-ppc64-1](https://ci.adoptium.net/manage/computer/test-osuosl-aix72-ppc64-1/)
* https://ci.adoptium.net/job/Grinder/7091/console [test-osuosl-aix715-ppc64-4](https://ci.adoptium.net/manage/computer/test-osuosl-aix715-ppc64-4/)
* https://ci.adoptium.net/job/Grinder/7092/console [test-osuosl-aix72-ppc64-2](https://ci.adoptium.net/manage/computer/test-osuosl-aix72-ppc64-2/)
* https://ci.adoptium.net/job/Grinder/7093/console [test-osuosl-aix715-ppc64-1](https://ci.adoptium.net/manage/computer/test-osuosl-aix715-ppc64-1/)
* https://ci.adoptium.net/job/Grinder/7094/console [test-osuosl-aix715-ppc64-2](https://ci.adoptium.net/manage/computer/test-osuosl-aix715-ppc64-2/)
* https://ci.adoptium.net/job/Grinder/7095/console [test-osuosl-aix715-ppc64-3](https://ci.adoptium.net/manage/computer/test-osuosl-aix715-ppc64-3/)
* https://ci.adoptium.net/job/Grinder/7096/console [build-osuosl-aix71-ppc64-2](https://ci.adoptium.net/manage/computer/build-osuosl-aix71-ppc64-2/)

**Comment by Haroon-Khel** [comment]
The linux grinders pass. The aix ones are seeing timeouts. This looks like a known upsteam bug https://bugs.openjdk.org/browse/JDK-8160716. Furthermore java/nio/channels/AsyncCloseAndInterrupt.java is excluded on aix for all major java versions

8 https://github.com/adoptium/aqa-tests/blob/f63615c6a160008504732607623952002bb4024d/openjdk/excludes/ProblemList_openjdk8.txt#L198

11 https://github.com/adoptium/aqa-tests/blob/1061a877efc5fb26d08a426438dccba77ba8f8c4/openjdk/excludes/ProblemList_openjdk11.txt#L159

17 https://github.com/adoptium/aqa-tests/blob/d2b88d54a95d1f553cdb49f1c0350a49b6987e57/openjdk/excludes/ProblemList_openjdk17-openj9.txt#L227
