### ISSUE TITLE
test-macincloud-macos1013-x64-1 laggy filesystem

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#1402]
**Test_openjdk8_j9_sanity.openjdk_x86-64_mac_xl:**
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_xl/240/console
```
20:04:27  Cannot contact test-macincloud-macos1013-x64-1: java.lang.InterruptedException
20:12:32  wrapper script does not seem to be touching the log file in /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_xl@tmp/durable-4c07c72e
20:12:32  (JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
```

**Comment by andrew-m-leonard** [comment]
problem again: https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_x86-64_mac/277/console

**Comment by Willsparker** [comment]
Seems to be a duplication of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1395 , which I've closed, however, this is still an issue: 
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_x86-64_mac/321/console

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_x86-64_mac/336/console
An example of it working as expected - either this is intermittent, or it 'fixed itself'. I'll see if I can find any recent examples of it failing.

**Comment by sxa** [comment]
Haven't heard of any additional problems with this machine in recent months ... It still seems to be online. Thoughts?

**Comment by sxa** [comment]
Machine no longer exists - closing
