### ISSUE TITLE
Offer: sparc64 Linux build machine

### ISSUE THREAD

**Issue by zv-io** [adoptium/infrastructure#1486]
I would like to make a SPARC T3-2 server running Linux available to the AdoptOpenJDK project.

It is large enough to be shared (currently used by [GCC Compile Farm](https://cfarm.tetaneutral.net/news/26#) project).

@sxa is evaluating the possibility of using this machine for JVM builds and suggested I create a ticket for tracking purposes.

**Comment by gdams** [comment]
@zv-io is it only running Linux or is there the option to get some Solaris VM's?

**Comment by zv-io** [comment]
At present, it only runs Linux due to what is likely a hardware bug (it can dual-boot Solaris, but only one OS will run at a time). In brief, LDOMs work fine except the network stack crashes after one or two packets are transferred so they're effectively useless. Trust me, we tried.

See also: https://openjdk.java.net/jeps/381. Does this mean SPARC is more, or less, important now?

**Comment by sxa** [comment]
For now it will continue to be important to us for JDK8. In theory we could build JDK11 too on the right level of Solaris. That JEP refers to later versions so we wouldn't be able to build the next LTS (JDK17) for Solaris or SPARC :-(

**Comment by zv-io** [comment]
I am commenting on behalf of Adélie Linux, who are working on a SPARC port of musl libc and eventually the distro itself. Adélie's goals probably align well enough here to make it worth mentioning that we'd be interested in hosting SPARC hardware for Adoptium (Solaris and/or Linux).

Do you know if any of the member organizations would be interested in supplying hardware or funding for it?

**Comment by karianna** [comment]
> I am commenting on behalf of Adélie Linux, who are working on a SPARC port of musl libc and eventually the distro itself. Adélie's goals probably align well enough here to make it worth mentioning that we'd be interested in hosting SPARC hardware for Adoptium (Solaris and/or Linux).
> 
> Do you know if any of the member organizations would be interested in supplying hardware or funding for it?

Hi @zv-io - Do you already have Sparc Hardware that's being hosted or is this a case of offering some Rackspace so to speak?

**Comment by zv-io** [comment]
The only SPARC hardware we have available today is:
* The T3-2 (mine personally) but it can only run one OS at a time due to a hardware defect and it needs to run Linux to support the cfarm.
* An unknown model Fujitsu in a storage unit somewhere that we could probably dig up, but is unlikely worth the time

Regarding the offer above, Adélie has its own (not mine) rack space and will happily host an additional SPARC machine in exchange for being allowed to test things on it.

**Comment by karianna** [comment]
> The only SPARC hardware we have available today is:
> 
> * The T3-2 (mine personally) but it can only run one OS at a time due to a hardware defect and it needs to run Linux to support the cfarm.
> * An unknown model Fujitsu in a storage unit somewhere that we could probably dig up, but is unlikely worth the time
> 
> Regarding the offer above, Adélie has its own (not mine) rack space and will happily host an additional SPARC machine in exchange for being allowed to test things on it.

Hi @zv-io - thanks for the kind offer from yourself and Adélie.  We do already have rackspace hosting with a few providers for our Solaris hosts (and are also going to engage a cloud provider.  we'd certainly welcome folks with Solaris / Sparc / Linux expertise on the project.  Our community tends to work out of slack adoptium.net/slack.html and we have a dedicated solaris channel there.

**Comment by sxa** [comment]
> The T3-2 (mine personally) but it can only run one OS at a time due to a hardware defect and it needs to run Linux to support the cfarm.

@zv-io Genuinely curious - what's the hardware defect? I always assumed Solaris and Linux LDoms would always just work side by side.

**Comment by zv-io** [comment]
@sxa
> what's the hardware defect? I always assumed Solaris and Linux LDoms would always just work side by side
Essentially with Solaris installed fresh, LDOMs can be created as normal, except the network stack crashes after 1-2 packets are transferred. The primary domain continues to work fine while any others need to be fully stopped and started. It doesn't matter which interface(s) are used, or how the network is configured, but we've had a half dozen people look at it and it seems to be a problem only with this specific system.

And so an LDOM without a reliable network connection is effectively useless. Doesn't matter if it's their "reference" Linux, Debian, Ubuntu, or another instance of Solaris.

@karianna
> Our community tends to work out of slack adoptium.net/slack.html and we have a dedicated solaris channel there.
Thanks! I may check it out at some point.

**Comment by koachan** [comment]
> That JEP refers to later versions so we wouldn't be able to build the next LTS (JDK17) for Solaris or SPARC :-(

I cannot comment on Solaris but on Linux SPARC, at least, OpenJDK 15 and 16 still manages to build and run fine in the interpreter-only "Zero" configuration, using GCC 9.
(Building with GCC 8 or 10 causes the resulting JDK to crash with "longjmp causes uninitialized stack frame", sadly)

**Comment by sxa** [comment]
I'm going to close this. Unfortunately it is unlikely to be practical for us to release on this platform since we would need to be able to run the restricted TCK which is a not insignificant amount of work which the people authorised to do would not be able to take on :-(
