### ISSUE TITLE
Travis cleanup failing on aarch64

### ISSUE THREAD

**Issue by gdams** [adoptium/infrastructure#1506]
https://travis-ci.com/github/AdoptOpenJDK/openjdk-infrastructure/jobs/371226590

TASK [Clean_Up : Remove yum dependencies that are no longer required - RedHat and CentOS] ***
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["yum", "-y", "autoremove"], "delta": "0:00:04.912507", "end": "2020-08-12 12:16:35.702330", "msg": "non-zero return code", "rc": 1, "start": "2020-08-12 12:16:30.789823", "stderr": "Error in PREUN scriptlet in rpm package kernel-core-4.18.0-193.1.2.el7.aarch64", "stderr_lines": ["Error in PREUN scriptlet in rpm package kernel-core-4.18.0-193.1.2.el7.aarch64"], "stdout": "Loaded plugins: fastestmirror, ovl\nResolving Dependencies\n--> Running transaction check\n---> Package dbus-python.aarch64 0:1.1.1-9.el7 will be erased\n---> Package hostname.aarch64 0:3.13-3.el7_7.1 will be erased\n---> Package kernel-modules.aarch64 0:4.18.0-193.1.2.el7 will be erased\n---> Package python-gobject-base.aarch64 0:3.22.0-1.el7_4.1 will be erased\n--> Finished Dependency Resolution\n--> Finding unneeded leftover dependencies\n---> Marking kernel-core to be removed - no longer needed by kernel-modules\n---> Marking gobject-introspection to be removed - no longer needed by python-gobject-base\nFound and removing 2 unneeded dependencies\n--> Running transaction check\n---> Package gobject-introspection.aarch64 0:1.56.1-1.el7 will be erased\n---> Package kernel-core.aarch64 0:4.18.0-193.1.2.el7 will be erased\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package                 Arch      Version                 Repository      Size\n================================================================================\nRemoving:\n dbus-python             aarch64   1.1.1-9.el7             @instCentOS    906 k\n hostname                aarch64   3.13-3.el7_7.1          @instCentOS     71 k\n kernel-modules          aarch64   4.18.0-193.1.2.el7      @instUpdates   7.8 M\n python-gobject-base     aarch64   3.22.0-1.el7_4.1        @instCentOS    1.1 M\nRemoving for dependencies:\n gobject-introspection   aarch64   1.56.1-1.el7            @instCentOS    886 k\n kernel-core             aarch64   4.18.0-193.1.2.el7      @instUpdates    57 M\n\nTransaction Summary\n================================================================================\nRemove  4 Packages (+2 Dependent packages)\n\nInstalled size: 68 M\nDownloading packages:\nRunning transaction check\nRunning transaction test\nTransaction test succeeded\nRunning transaction\n  Erasing    : kernel-modules-4.18.0-193.1.2.el7.aarch64                    1/6 \n  Erasing    : python-gobject-base-3.22.0-1.el7_4.1.aarch64                 2/6 \n/var/tmp/rpm-tmp.gtLN7K: line 1: /usr/sbin/new-kernel-pkg: No such file or directory\nerror: %preun(kernel-core-4.18.0-193.1.2.el7.aarch64) scriptlet failed, exit status 127\n  Erasing    : gobject-introspection-1.56.1-1.el7.aarch64                   3/6 \nerror: kernel-core-4.18.0-193.1.2.el7.aarch64: erase failed\n  Erasing    : hostname-3.13-3.el7_7.1.aarch64                              4/6 \n  Erasing    : dbus-python-1.1.1-9.el7.aarch64                              5/6 \n  Verifying  : kernel-modules-4.18.0-193.1.2.el7.aarch64                    1/6 \n  Verifying  : dbus-python-1.1.1-9.el7.aarch64                              2/6 \n  Verifying  : hostname-3.13-3.el7_7.1.aarch64                              3/6 \n  Verifying  : python-gobject-base-3.22.0-1.el7_4.1.aarch64                 4/6 \n  Verifying  : kernel-core-4.18.0-193.1.2.el7.aarch64                       5/6 \n  Verifying  : gobject-introspection-1.56.1-1.el7.aarch64                   6/6 \n\nRemoved:\n  dbus-python.aarch64 0:1.1.1-9.el7                                             \n  hostname.aarch64 0:3.13-3.el7_7.1                                             \n  kernel-modules.aarch64 0:4.18.0-193.1.2.el7                                   \n  python-gobject-base.aarch64 0:3.22.0-1.el7_4.1                                \n\nDependency Removed:\n  gobject-introspection.aarch64 0:1.56.1-1.el7                                  \n\nFailed:\n  kernel-core.aarch64 0:4.18.0-193.1.2.el7                                      \n\nComplete!", "stdout_lines": ["Loaded plugins: fastestmirror, ovl", "Resolving Dependencies", "--> Running transaction check", "---> Package dbus-python.aarch64 0:1.1.1-9.el7 will be erased", "---> Package hostname.aarch64 0:3.13-3.el7_7.1 will be erased", "---> Package kernel-modules.aarch64 0:4.18.0-193.1.2.el7 will be erased", "---> Package python-gobject-base.aarch64 0:3.22.0-1.el7_4.1 will be erased", "--> Finished Dependency Resolution", "--> Finding unneeded leftover dependencies", "---> Marking kernel-core to be removed - no longer needed by kernel-modules", "---> Marking gobject-introspection to be removed - no longer needed by python-gobject-base", "Found and removing 2 unneeded dependencies", "--> Running transaction check", "---> Package gobject-introspection.aarch64 0:1.56.1-1.el7 will be erased", "---> Package kernel-core.aarch64 0:4.18.0-193.1.2.el7 will be erased", "--> Finished Dependency Resolution", "", "Dependencies Resolved", "", "================================================================================", " Package                 Arch      Version                 Repository      Size", "================================================================================", "Removing:", " dbus-python             aarch64   1.1.1-9.el7             @instCentOS    906 k", " hostname                aarch64   3.13-3.el7_7.1          @instCentOS     71 k", " kernel-modules          aarch64   4.18.0-193.1.2.el7      @instUpdates   7.8 M", " python-gobject-base     aarch64   3.22.0-1.el7_4.1        @instCentOS    1.1 M", "Removing for dependencies:", " gobject-introspection   aarch64   1.56.1-1.el7            @instCentOS    886 k", " kernel-core             aarch64   4.18.0-193.1.2.el7      @instUpdates    57 M", "", "Transaction Summary", "================================================================================", "Remove  4 Packages (+2 Dependent packages)", "", "Installed size: 68 M", "Downloading packages:", "Running transaction check", "Running transaction test", "Transaction test succeeded", "Running transaction", "  Erasing    : kernel-modules-4.18.0-193.1.2.el7.aarch64                    1/6 ", "  Erasing    : python-gobject-base-3.22.0-1.el7_4.1.aarch64                 2/6 ", "/var/tmp/rpm-tmp.gtLN7K: line 1: /usr/sbin/new-kernel-pkg: No such file or directory", "error: %preun(kernel-core-4.18.0-193.1.2.el7.aarch64) scriptlet failed, exit status 127", "  Erasing    : gobject-introspection-1.56.1-1.el7.aarch64                   3/6 ", "error: kernel-core-4.18.0-193.1.2.el7.aarch64: erase failed", "  Erasing    : hostname-3.13-3.el7_7.1.aarch64                              4/6 ", "  Erasing    : dbus-python-1.1.1-9.el7.aarch64                              5/6 ", "  Verifying  : kernel-modules-4.18.0-193.1.2.el7.aarch64                    1/6 ", "  Verifying  : dbus-python-1.1.1-9.el7.aarch64                              2/6 ", "  Verifying  : hostname-3.13-3.el7_7.1.aarch64                              3/6 ", "  Verifying  : python-gobject-base-3.22.0-1.el7_4.1.aarch64                 4/6 ", "  Verifying  : kernel-core-4.18.0-193.1.2.el7.aarch64                       5/6 ", "  Verifying  : gobject-introspection-1.56.1-1.el7.aarch64                   6/6 ", "", "Removed:", "  dbus-python.aarch64 0:1.1.1-9.el7                                             ", "  hostname.aarch64 0:3.13-3.el7_7.1                                             ", "  kernel-modules.aarch64 0:4.18.0-193.1.2.el7                                   ", "  python-gobject-base.aarch64 0:3.22.0-1.el7_4.1                                ", "", "Dependency Removed:", "  gobject-introspection.aarch64 0:1.56.1-1.el7                                  ", "", "Failed:", "  kernel-core.aarch64 0:4.18.0-193.1.2.el7                                      ", "", "Complete!"]}
PLAY RECAP *********************************************************************
localhost                  : ok=119  changed=69   unreachable=0    failed=1    skipped=109  rescued=0    ignored=12

**Comment by gdams** [comment]
temporarily skipped in https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1505

**Comment by sxa** [comment]
We no longer user Travis, therefore closing.
