### ISSUE TITLE
AIX playbooks - version 2

### ISSUE THREAD

**Issue by aixtools** [adoptium/infrastructure#1582]
Opening a new issue - to keep track/follow other playbook issues.

As a first PR step I would like to add a new directory for the aix playbooks, with it's own README(.md) to document what is going on. This way the existing files will not be affected - and when complete - either copy the new files to the old locations - or point at the new playbook (from wherever that is managed).

**Comment by aixtools** [comment]
maybe add tag 'aix' as well. What I learn re: ansible will be generic, but what I am doing is definitely platform specific.

**Comment by aixtools** [comment]
I have created a repository where I am doing my development work - before I make a new PR for here.

Further, I have a sandbox environment that @Haroon-Khel and I are using to work on this. One key element - a playbook to reinstall the test (managed) node - on demand - from/by the Ansible Control Node.

**Comment by aixtools** [comment]
Waiting for #1633 to be reviewed and merged, before i can proceed with additional enhancements.

**Comment by aixtools** [comment]
I see I have a new collection to learn. Just checking - AdoptOpenJDK are normally using Ansible 2.9 or later?
Asking because IBM is hosting a new collection for AIX - I may not get to write my own after all 😛 

See: https://galaxy.ansible.com/ibm/power_aix

**Comment by Haroon-Khel** [comment]
The [docs](https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/master/ansible#how-do-i-run-the-playbooks) recommend 2.4 or later. I personally use `2.9.13`

**Comment by aixtools** [comment]
Well, I am very happy for myself - that I am starting with `Ansible-2.10`. All that stuff I do not need to unlearn.

And, I am thinking I'll just take a fork - give credit where credit is due - and work on my own version of it. As much as possible use the same module names - but fix things (assumptions) that I see will already go wrong on some systems.

Still a great source for learning for me!

**Comment by Haroon-Khel** [comment]
@aixtools Seeing as https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1633 is now merged, do we want to close this issue, or are you keeping it open for further additions to the aix playbook?

**Comment by aixtools** [comment]
Keeping it open - as discussion for other changes. #1633 was just the first step. No content was really changed - only splitting it out into smaller chunks.

**Comment by aixtools** [comment]
So - moving forward - keep the discussions here - or open (many) PR's as we move, bit by bit, through the files.

e.g., looking at the "role" X11.

a) as this is actually a pre-requisite - the call should be moved up.
b) I think it is wrong to assume there is a tar file (with no instructions on how to make it) is there to install on demand. Instead, just check for availability - and fail playbook if all are not there.
c) Actual requirements:
When working through manually the fileset I needed to add was `X11.base.lib`. `X11.adt.ext` may still be required, but `X11.vfb` clearly is not _required_ as the last system was built and passed testing without it.
- maybe the tests need fixing, i.e., something essential is not being done by the build process and tests are not finding it. FYI X11.vfb is for `Virtual Frame Buffer Software`.

Again, moving forward - while it will be a hassle for me - I would prefer for the changes I make to be on a role/by/role basis, rather than all at once.

Also, as I want to test where the build breaks - if something that has been, historically, required (e.g., X11.vfb) - rather than fail the playbook - I'll use a warning message, and continue.

**Comment by aixtools** [comment]
Just added for PR as a start to the next phase: #1695, #1696, #1697 and #1698.

1695: change the order of execution - perquisites first
1696 - 1698: atm - do not fail in the role. Only check that software is installed.

Logic: assuming that there are 'Vendor' files to install, by default, is incorrect. Instead, work through the tests and report, there, or not. TBD: add a set_fact statement at the end of a 'role' task so that the main playbook can `fail`, or better, give a summary at the end (all passed, or list what failed).

TBD: verify which software packages is really needed. On at least one host - software that is supposed to be installed - is not - yet the build of openJDK passes.

**Comment by aixtools** [comment]
Add #1704 to list of opened PR's

**Comment by aixtools** [comment]
Also - tag ansible?
