### ISSUE TITLE
windows: Dynamic Machines don't have cygwin + other dependencies on them

### ISSUE THREAD

**Issue by karianna** [adoptium/infrastructure#1617]
The dynamic machines do not have cygwin or any other dependencies installed on them. For now I've pinned the sign job to use the static win2012 machines

_Originally posted by @gdams in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1616#issuecomment-707601803_

**Comment by karianna** [comment]
See https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1615

**Comment by Willsparker** [comment]
@gdams Where is the setup for the dynamic machines (if there is any)?

**Comment by gdams** [comment]
there is no setup, they are currently using vanilla windows with docker preinstalled

**Comment by Willsparker** [comment]
Ahh, right - presumably there's no way we can automate setup on them?

**Comment by gdams** [comment]
We actually can I believe, we might be able to add an init script that installs cygwin

**Comment by Willsparker** [comment]
That'd be cool - I'm not really sure how the dynamic machines are provisioned, or what they're necessarily used for? But if we can put on the dependencies for them to do the sign-build and installer jobs, that'd be cool :)

**Comment by sxa** [comment]
Given that we now sign via third-party Eclipse server I presume this can now be closed as we don't sign on our own systems any more - is it ok to close this @karianna ?
