### ISSUE TITLE
unzip of the jdk under test fails on  test-osuosl-aix72-ppc64-1

### ISSUE THREAD

**Issue by lumpfish** [adoptium/infrastructure#1758]
Tests fail to run on test-osuosl-aix72-ppc64-1 because the unzip of the jdk under test fails:
Failing job: https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk11_j9_sanity.functional_ppc64_aix/31/console
Output at time of failure:
```
10:46:52  + ./openjdk-tests/get.sh -s /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64_aix -t /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64_aix/openjdk-tests -p ppc64_aix -r upstream -j 11 -i openj9 --openj9_repo https://github.com/eclipse/openj9.git --openj9_branch master --tkg_repo https://github.com/AdoptOpenJDK/TKG.git --tkg_branch master
10:46:52  TESTDIR: /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64_aix/openjdk-tests
10:46:52  get jdk binary...
10:46:52  --sdkdir is set to upstream. Therefore, skip download jdk binary
10:46:52  unzip file: OpenJDK11U-jdk_ppc64_aix_openj9_2020-12-10-09-13.tar.gz ...
10:47:03  unzip file: OpenJDK11U-jre_ppc64_aix_openj9_2020-12-10-09-13.tar.gz ...
10:47:07  unzip file: OpenJDK11U-testimage_ppc64_aix_openj9_2020-12-10-09-13.tar.gz ...
10:47:10  unzip OpenJDK11U-debugimage_ppc64_aix_openj9_2020-12-10-09-13.tar.gz in ./j2sdk-image...
10:47:13  File --strip not present in the archive.
10:47:13  File 1 not present in the archive.
```
Maybe the version of tar on the machine doesn't support --strip?

**Comment by sxa** [comment]
`--strip` is not a standard `tar` operation, although I thought we'd removed most uses of GNU specific optionsI'm surprised we're still using that as a required option. It is GNU specific so isn't in a standard `tar` command.

The AIX72 machines are the new ones we've added in recently via https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1644

**Comment by aixtools** [comment]
I created a .profile for the jenkins user with:
```
-bash-5.0$ cat .profile
PATH=/opt/freeware/bin:${PATH}
export PATH
```

If this fixes this - then we can add this bit to the aixPB: for the jenkins_user role.

**Comment by lumpfish** [comment]
test-osuosl-aix72-ppc64-1 test now passing: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_ppc64_aix/289/console (Dec 13, 2020 6:39 PM ).

test-osuosl-aix72-ppc64-2 failing with same issue: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_ppc64_aix/80/console (Dec 13, 2020 7:01 PM ).

**Comment by andrew-m-leonard** [comment]
I've taken https://ci.adoptopenjdk.net/computer/test-osuosl-aix72-ppc64-2/ offline until this is fixed

**Comment by andrew-m-leonard** [comment]
@Haroon-Khel looks like this still failed last night on test-osuosl-aix72-ppc64-2
https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk11_j9_sanity.functional_ppc64_aix/39/console

**Comment by andrew-m-leonard** [comment]
and on test-osuosl-aix72-ppc64-1
https://ci.adoptopenjdk.net/view/Failing%20Test%20Jobs/job/Test_openjdk8_j9_sanity.functional_ppc64_aix/82/console

**Comment by andrew-m-leonard** [comment]
@Haroon-Khel I added a bit of debug, and it's still picking up the wrong "tar":
```
10:36:22  /usr/bin/tar
```

**Comment by andrew-m-leonard** [comment]
Machine
test-ibm-aix71-ppc64-1 node has it set correctly
```
11:12:23  PATH=/opt/freeware/bin:/opt/IBM/xlC/13.1.3/bin:/usr/bin:/etc:/usr/sbin:/usr/ucb:/usr/bin/X11:/sbin:/usr/java7_64/jre/bin:/usr/java7_64/bin
```

**Comment by andrew-m-leonard** [comment]
I've added the update to PATH to the Jenkins Node Configuration, as I saw LIBPATH was already done the same way:
![image](https://user-images.githubusercontent.com/31470007/102342804-a9697280-3f91-11eb-9403-025c2ce57d84.png)

**Comment by andrew-m-leonard** [comment]
The other AIX machines seem to set the PATH in /etc/environment, which should work also, not sure which is best.

**Comment by aixtools** [comment]
imho: it is better to have it in the jenkins settings - because having it in the environment breaks standard AIX management commands. GNU versions are not compatible - the most noticeable being `grep`. Sadly, GNU has repeatedly refused to add the paragraph (-p) option.

So, as AIX admin - request that these kinds of settings be at user (account) level, rather than expecting them at global level.

**Comment by aixtools** [comment]
The problem on `test-osuosl-aix72-ppc64-2` was a missing execute bit on .profile:
```
-bash-5.0$ cat .profile
PATH=/opt/freeware/bin:${PATH}
export PATH
-bash-5.0$ ls -l .profile
-rw-r--r-- 1 jenkins staff 43 Dec 15 08:01 .profile
-bash-5.0$ chmod u+x .profile
-bash-5.0$
```
Should work normally now - since it seems to have fixed it on `test-osuosl-aix72-ppc64-1`

Waiting for some other merges on aixPB. I'll add this setting to the jenkins_user part of the aixPB.

**Comment by karianna** [comment]
So is this resolved?

**Comment by andrew-m-leonard** [comment]
openj9 AIX & mac failed to build last night due to cross_compile error, so we haven't had a test run through yet..

**Comment by sxa** [comment]
I'm not sure `.profile` will be used for jobs run through jenkins ...

**Comment by andrew-m-leonard** [comment]
> I'm not sure `.profile` will be used for jobs run through jenkins ...

Correct, from what i've read it isn't

**Comment by aixtools** [comment]
On AIX - without changing anything on AIX - you could use `gtar` as that is a symbolic link to the GNU tar installed in /opt/freeware/bin.

However, in the interests of `speed` I have setup both AIX 7.2 systems with the following:

```
# ls -l gtar* tar*
lrwxrwxrwx    1 root     system           26 Jul 29 2019  gtar -> ../../opt/freeware/bin/tar
lrwxrwxrwx    1 root     system           29 Jul 29 2019  gtar_32 -> ../../opt/freeware/bin/tar_32
lrwxrwxrwx    1 root     system           29 Jul 29 2019  gtar_64 -> ../../opt/freeware/bin/tar_64
lrwxrwxrwx    1 root     system            4 Jan 08 06:57 tar -> gtar
-r-xr-xr-x    1 bin      bin           85299 Jul 05 2018  tar.aix
```

**Comment by aixtools** [comment]
> 
> 
> > I'm not sure `.profile` will be used for jobs run through jenkins ...
> 
> Correct, from what i've read it isn't

Perhaps this would need the creation, or update, of .bashrc and/or .kshrc

**Comment by sxa** [comment]
The PR listed above stops using `strip` so this has been resolved, just wasn't closed along with the issue :-)
