### ISSUE TITLE
test-macstadium-macos1015-x64-1 linker incompatibility? ld: unsupported tapi file type '!tapi-tbd' in YAML

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#1777]
Any testcase that tries to compile build-natives-unix, fails with the following on this node:
```
02:20:41       [exec] gcc -m64 -dynamiclib -o /Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_mac/openjdk-tests/system/openjdk-systemtest/openjdk.test.modularity/bin/tests/com.test.jlink/native/bin/osx_x86-64/libJniTest.dylib /Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_mac/openjdk-tests/system/openjdk-systemtest/openjdk.test.modularity/bin/tests/com.test.jlink/native/lib/osx_x86-64/JniTest.o
02:20:42       [exec] ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd' for architecture x86_64
02:20:42       [exec] clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk11_j9_extended.system_x86-64_mac/431/console

Ref: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2133

**Comment by andrew-m-leonard** [comment]
Try compiling a hello world C program:
```
test-macstadium-macos1015-x64-1:andrew jenkins$ gcc HelloWorld.c 
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by andrew-m-leonard** [comment]
I've removed the ci.role.test from this node until we can fix the setup
@smlambert

**Comment by sxa** [comment]
Will likely need a reinstall of Xcode (can that be done via ansible?) as there seems some incompatibility between something on the machine. May be worth trying to compare with a known good machine at the same Xcode level if one of the others ones is in a suitable state.

**Comment by sxa** [comment]
Since this is a systemdown I'm marking it as critical as it's currently a waste of a machine ...

**Comment by sxa** [comment]
@Haroon-Khel If this is potentially a reinstall of Xcode is it something that can be/will be/has been covered by your ansible playbook executions under #695 ?

**Comment by sxa** [comment]
Noting that it is likely we will replace this system with a machine from orka as part of https://github.com/adoptium/infrastructure/issues/2536

**Comment by sxa** [comment]
> As per [discussion yesterday](https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1608655007389600?thread_ts=1608652657.383600&cid=C53GHCXL4) this is yours @gdams :-)

@gdams Should we just shut this system down in macstadium for now on the basis we'll likely create equivalents in orka and this machine has been chewing up costs while unusable?

**Comment by sxa** [comment]
Machine was decommissioned as part of the orka migration - closing.
