### ISSUE TITLE
Ansible request for x11 server installed for all platforms

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#1791]
We are enabling extended.openjdk tests which contain jdk_awt, jdk_swing tests.  Many tests require x11 DISPLAY variable to be set.  There is already an open request to ensure Macs have this enabled (see https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/211).  x11 server has been installed/enabled on most Linux systems and AIX, but is still missing on Macs, and aarch64.  This issue is to ensure we have the ability to enable it on all platforms (as we currently will have to disable many tests if it is not enabled).

Details (from [jdk11 aarch64 extended.openjdk test job](https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_extended.openjdk_aarch64_linux/1/testReport/sun_java2d_DirectX_InfiniteValidationLoopTest_InfiniteValidationLoopTest/java/InfiniteValidationLoopTest/)):
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
	at java.desktop/java.awt.Window.<init>(Window.java:548)
	at java.desktop/java.awt.Frame.<init>(Frame.java:423)
	at InfiniteValidationLoopTest.<init>(InfiniteValidationLoopTest.java:49)
	at InfiniteValidationLoopTest.main(InfiniteValidationLoopTest.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:834)

JavaTest Message: Test threw exception: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
JavaTest Message: shutting down test

**Comment by sxa** [comment]
As far as I can see that ran on test-aws-rhel76-armv8-3 which does have the required Xvfb package installed and it looks like Xvfb runs ok (I started it manually but haven't checked further than that) so this doesn't appear to be an infrastructure issue

**Comment by sxa** [comment]
Oh hang on that was a test which was run 11 months ago

**Comment by smlambert** [comment]
I just wanted an infra issue that would run through the set of machines and verify that xvfb / x11 were installed and running on all of them, so I have created this one (though feel free to combine it with #211 if you want a single issue that checks we have that prereq on all machines (not just macs).

**Comment by sxa** [comment]
I didn't think it was expected to be running - isn't that done dynamically in the test scripts? We don't have anything that would start it in a persistent way.

**Comment by smlambert** [comment]
These tests are run during a release (as release pipelines launch [nightly](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/build_base_file.groovy#L65) and [weekly](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/build_base_file.groovy#L77) test lists), and the intent was to get a weekly build pipeline running, so we can triage the weekly tests.   

This still needs to happen, though I am now leaning towards a running nightly pipelines 5 days a week, and run a weekly release pipeline (with no publish) on the weekends, as then we would then accomplish 2 open goals (running the 'weekly' test list, and dry-running a release pipeline).

**Comment by sxa** [comment]
I'm going to close this as I believe it is available on all test machines, other than the issue specific to macos auto-logins which is covered separately.
