### ISSUE TITLE
test-osuosl-aix72-ppc64-1 sanity.functional cmdLineTester_pltest_aix_0 j9sysinfo_testOnlineProcessorCount fails

### ISSUE THREAD

**Issue by lumpfish** [adoptium/infrastructure#1808]
Failing job link: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_ppc64_aix/103/

Output of failing test:
```
03:39:01   [ERR] Starting test j9sysinfo_testOnlineProcessorCount
03:39:01   [ERR] si.c line 1331: j9sysinfo_testOnlineProcessorCount Invalid online processor count found.
03:39:01   [ERR] 
03:39:01   [ERR] 		LastErrorNumber: -102
03:39:01   [ERR] 		LastErrorMessage: The file access permissions do not allow the specified action.
03:39:01   [ERR] 
03:39:01   [ERR] Ending test j9sysinfo_testOnlineProcessorCount
```
Test fails on test-osuosl-aix72-ppc64-1 (https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_ppc64_aix/103/), passes on test-osuosl-aix72-ppc64-2 (https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_ppc64_aix/101/)

**Comment by aixtools** [comment]
I am having trouble finding the text above. Which link is it - the time I find starts with 06:XX;YY.

Note also - the system was passing just (a few) days prior: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_ppc64_aix/101/

![image](https://user-images.githubusercontent.com/10852597/104041514-748bbc80-51d9-11eb-88a0-1c02ef270062.png)

The pass for test-osuosl-aix72-ppc64-2 is https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_ppc64_aix/102/

**Comment by sxa** [comment]
Verifying again at https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.functional_ppc64_aix/112/

**Comment by aixtools** [comment]
As the test links above are no longer available - is this still an open issue that needs attention?

**Comment by sxa** [comment]
If it's not happening on the latest ones we should try kicking it off again on the machine that originally showed the error `test-osuosl-aix72-ppc64-1` as the job hasn't run on that in any of the ones that still have logs available.

**Comment by Haroon-Khel** [comment]
Running a grinder on `test-osuosl-aix72-ppc64-1`
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1169/

**Comment by Haroon-Khel** [comment]
```
[2021-08-03T12:51:33.355Z]  [ERR] Starting test j9sysinfo_testOnlineProcessorCount
[2021-08-03T12:51:33.355Z]  [ERR] /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-openj9/workspace/build/src/openj9/runtime/tests/port/si.c line 1331: j9sysinfo_testOnlineProcessorCount Invalid online processor count found.
[2021-08-03T12:51:33.355Z]  [ERR] 
[2021-08-03T12:51:33.355Z]  [ERR] 		LastErrorNumber: -102
[2021-08-03T12:51:33.355Z]  [ERR] 		LastErrorMessage: The file access permissions do not allow the specified action.
[2021-08-03T12:51:33.355Z]  [ERR] 
[2021-08-03T12:51:33.355Z]  [ERR] Ending test j9sysinfo_testOnlineProcessorCount
```
The error continues to occur. Will try running on the machine directly

**Comment by aixtools** [comment]
I looked on the console output of the job you posted above (#1169), but I do not find the error you refer to.

**Comment by Haroon-Khel** [comment]
You will have to open it in plain text because the console output is too long. https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1169/consoleText

Also, the thing you linked is an issue, not the grinder

**Comment by aixtools** [comment]
> 
> 
> You will have to open it in plain text because the console output is too long. https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1169/consoleText
> 
> Also, the thing you linked is an issue, not the grinder

I should have put a space between the hash and the number. github did it's thing with hashNumber.

**Comment by Haroon-Khel** [comment]
With some help, I was able to get the test running on the machine. I get the same error as the grinder

```
 [ERR] FAILURES DETECTED. Number of failed tests: 1
 [ERR] 
 [ERR] 1: j9sysinfo_testOnlineProcessorCount
 [ERR]  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-openj9/workspace/build/src/openj9/runtime/tests/port/si.c line 1331: Invalid online processor count found.
 [ERR] 
 [ERR]          LastErrorNumber: -102
 [ERR]          LastErrorMessage: The file access permissions do not allow the specified action.
 [ERR] 
>> Success condition was not found: [Output match: ALL TESTS COMPLETED AND PASSED]
>> Failure condition was not found: [Output match: ASSERTION FAILED]
```

Weirdly, the test still looks in `/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-openj9/workspace/build/src/openj9/runtime/tests/port/si.c` to run a file, despite this test not being associated with a build job

**Comment by smlambert** [comment]
@pshipton @llxia - have either of you seen this functional test failure on AIX on https://openj9-jenkins.osuosl.org/ ?

**Comment by Haroon-Khel** [comment]
The file `si.c` is no where to be found on the system, so I do not know what exactly it is trying to find

**Comment by pshipton** [comment]
The failure and si.c is here https://github.com/eclipse-openj9/openj9/blob/master/runtime/tests/port/si.c#L1331

I haven't seen it, at least not in recent history. There isn't really enough information in the output to say exactly what is wrong. Possibly perfstat_cpu_total() or perfstat_cpu(0 is returning the error, although probably not since that error isn't listed as a possibility. @jdekonin might have an idea from getting AIX machines working in the past.

If we can't guess the problem, we could modify the test to provide more information.

**Comment by Haroon-Khel** [comment]
@pshipton Could you post a link to the test code? I've been trying to look for it all morning 😄

**Comment by smlambert** [comment]
@Haroon-Khel - its posted in the comment above (functional test code lives in the openj9 repository):
https://github.com/eclipse-openj9/openj9/blob/master/runtime/tests/port/si.c#L1331

**Comment by Haroon-Khel** [comment]
Yeah I had just realised, and hence removed my comment

**Comment by jdekonin** [comment]
> @jdekonin might have an idea from getting AIX machines working in the past.

Not on this type of failure I don't think.  I find nothing in old issues anyways.

**Comment by aixtools** [comment]
If someone has this test failing in a command-line environment I can try using audit/trace to try and locate what the error message is coming from. It may be something similiar to what we have had with settings such as capabilities=CAP_NUMA_ATTACH,CAP_BYPASS_RAC_VMM,CAP_PROPAGATE``(ie, RBAC like settings embedded into an undocumented `capabilities` argument.

p.s., if the localized test fails as jenkins, does it pass when running same as `root`or `zeus`?

**Comment by aixtools** [comment]
The last run has this failure summary:
```
06:38:47.631  TOTAL: 282   EXECUTED: 235   PASSED: 227   FAILED: 8   DISABLED: 6   SKIPPED: 41
06:38:47.631  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
06:38:47.631  To rebuild the failed test in a jenkins job, copy the following link and fill out the <Jenkins URL> and <FAILED test target>:
06:38:47.631  <Jenkins URL>/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=<FAILED test target>
06:38:47.631  
06:38:47.631  For example, to rebuild the failed tests in <Jenkins URL>=https://ci.adoptopenjdk.net/job/Grinder, use the following links:
06:38:47.631  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=RuntimeAnnotationTests_0
06:38:47.631  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=cmdLineTester_GCCheck_0
06:38:47.631  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=cmdLineTester_GCCheck_1
06:38:47.631  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=cmdLineTester_GCCheck_2
06:38:47.631  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=cmdLineTester_GCCheck_3
06:38:47.631  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=cmdLineTester_GCCheck_4
06:38:47.631  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=cmdLineTester_pltest_aix_0
06:38:47.632  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=cmdLineTester_pltest_numcpus_bound_aix_0
06:38:47.632  rebuild the failed tests in one link:
06:38:47.632  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=testList%20TESTLIST=RuntimeAnnotationTests_0,cmdLineTester_GCCheck_0,cmdLineTester_GCCheck_1,cmdLineTester_GCCheck_2,cmdLineTester_GCCheck_3,cmdLineTester_GCCheck_4,cmdLineTester_pltest_aix_0,cmdLineTester_pltest_numcpus_bound_aix_0```
* I'll work through them one-by one.

**Comment by sxa** [comment]
@Haroon-Khel Ref your [earlier comment](https://github.com/adoptium/infrastructure/issues/1808#issuecomment-895332780) can you work with @aixtools to replicate this from the command line too?

**Comment by aixtools** [comment]
@Haroon-Khel - I should be online some next week. Ping me when you have time to assist.

**Comment by aixtools** [comment]
@lumpfish @Haroon-Khel - please check if this is still an issue. If not - feel free to close. I am leaving open - waiting for your satisfication.

**Comment by sxa** [comment]
Closing as discussed in Slack :-)
