### ISSUE TITLE
LFSingleThreadCachingTest fails on testc-packet-ubuntu2010-intel-1

### ISSUE THREAD

**Issue by karianna** [adoptium/infrastructure#1857]
https://github.com/AdoptOpenJDK/TSC/issues/197

jdk_lang_0 => deep history 11/13 passed. - Reran in Grinder successfully on a different machine - https://ci.adoptopenjdk.net/job/Grinder/6015/ - upstream bug

Any other details:

The following passes on https://ci.adoptopenjdk.net/computer/test-ibmcloud-rhel6-x64-1/ but fails on https://ci.adoptopenjdk.net/computer/testc-packet-ubuntu2010-intel-1/

https://trss.adoptopenjdk.net/output/test?id=600881252bad78506651d8f7

```
[2021-01-20T12:59:50.370Z] command: build LFSingleThreadCachingTest
[2021-01-20T12:59:50.370Z] reason: Named class compiled on demand
[2021-01-20T12:59:50.370Z] elapsed time (seconds): 0.0
[2021-01-20T12:59:50.370Z] 
[2021-01-20T12:59:50.370Z] ACTION: main -- Failed. Unexpected exit from test [exit code: 137]
[2021-01-20T12:59:50.370Z] REASON: User specified action: run main/othervm LFSingleThreadCachingTest 
[2021-01-20T12:59:50.370Z] TIME:   213.73 seconds
```

**Comment by sxa** [comment]
Note: This machine is now [test-docker-ubuntu2010-x64-2](https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2010-x64-2/)

**Comment by adamfarley** [comment]
Ok, jdk_lang has passed 100% of the time on [the most recent runs](https://trss.adoptopenjdk.net/deepHistory?testId=609f384cd7656077061bea38), and there's [no sign of an exclusion](https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk8.txt).

However, we've not had a recent run on the specifically-mentioned failing machine, so [here's a 100-string grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/648/) for that specific test, and a [single run of jdk_lang](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/649/).

**Comment by adamfarley** [comment]
100 runs, 100 tests passed. Advocating closure.
