### ISSUE TITLE
Unable to build on https://ci.adoptopenjdk.net/computer/build-packet_esxi-solaris10u11-x64-1

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#1871]
https://ci.adoptopenjdk.net/computer/build-packet_esxi-solaris10u11-x64-1
```
18:06:03  + ./build-farm/make-adopt-build-farm.sh 
18:06:03  /export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot@tmp/durable-05519395/script.sh: ./build-farm/make-adopt-build-farm.sh: not found
```
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/606/console

Oddly the above file exists...! but the machine will repeatedly not find it...
Comparing with https://ci.adoptopenjdk.net/computer/build-inspira-solaris10u11-sparcv9-2
the "/export" filesystem is mounted slightly differently, so wondering if that may have something to do with it?

**Comment by andrew-m-leonard** [comment]
I've taken the node offline under this issue.

**Comment by sxa** [comment]
`/bin/bash` is not available on the machine's filesystem therefore the `#!` at the start of `make-adopt-build-farm.sh` does not work

**Comment by sxa** [comment]
I've symlinked `/bin/bash -> /usr/bin/bash` ... If that doesn't work, someone else can deal with it as I wasn't involved in the setup of this machine.

**Comment by ptribble** [comment]
"I've symlinked /bin/bash -> /usr/bin/bash"

That doesn't quite seem right. On Solaris, /bin is a symlink to /usr/bin

# ls -l /bin
lrwxrwxrwx   1 root     root           9 Dec 15 13:55 /bin -> ./usr/bin/

which would tend to point to a deeper problem.

**Comment by sxa** [comment]
Agreed @ptribble  - I'm more than a bit worried about what's happened on that system in the past ...

**Comment by sxa** [comment]
Mostly resolved ([JDK8 build on the machine](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/612/console)). @gdams created another link `/bin/sh -> /usr/bin/bash` (Ref: https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1611830964042600?thread_ts=1611824089.035900&cid=C09NW3L2J) but it's showing this error very close to the end of the build:
```
20:54:54  Compiling 240 files for BUILD_SECURITY
20:54:54  Note: Some input files use or override a deprecated API.
20:54:54  Note: Recompile with -Xlint:deprecation for details.

20:54:56  "/export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/jdk/src/share/native/sun/misc/URLClassPath.c", line 58: warning: implicitly declaring function to return int: VerifyFixClassname()
20:54:56  "/export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/jdk/src/share/native/sun/misc/URLClassPath.c", line 60: warning: implicitly declaring function to return int: VerifyClassname()
20:54:56  "/export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/jdk/src/share/native/sun/misc/URLClassPath.c", line 68: warning: implicitly declaring function to return int: free()

20:54:59  CC: stdlibfilt failed for /export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp
20:54:59  gmake[2]: *** [lib/CoreLibraries.gmk:322: /export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/build/solaris-x86_64-normal-server-release/jdk/objs/libunpack/zip.o] Error 2
20:54:59  gmake[2]: *** Waiting for unfinished jobs....
20:54:59  CC: stdlibfilt failed for /export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/jdk/src/share/native/com/sun/java/util/jar/pack/unpack.cpp
20:54:59  gmake[2]: *** [lib/CoreLibraries.gmk:322: /export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/build/solaris-x86_64-normal-server-release/jdk/objs/libunpack/unpack.o] Error 2
20:54:59  gmake[1]: *** [BuildJdk.gmk:70: libs-only] Error 2
20:54:59  gmake: *** [/export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src//make/Main.gmk:117: jdk-only] Error 2
```

**Comment by ptribble** [comment]
I think stdlibfilt calls /bin/sed

But basically, remove the current /bin and replace it with a symlink to usr/bin, and you fix all the errors of this type.
