### ISSUE TITLE
Ansible request for audit of freemarker role in the UNIX playbook

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#1898]
Do we actively use this role? It puts freemarker.jar into `/home/jenkins` (which seems a little risky since it could be overridden by any rogue jenkins job) and we seem to download it from apache.org during the build scripts for OpenJ9 anyway, so we probably don't even use it from there:
```
12:53:35  Checking and downloading Freemarker dependency
12:53:35  Checking for FREEMARKER
12:53:35  --2021-02-04 12:53:35--  https://www.apache.org/dist/freemarker/engine/2.3.30/binaries/apache-freemarker-2.3.30-bin.tar.gz
```
My personal feeling? For performance/reliability we should download it to somewhere else on the machine (Maybe `/usr/local/lib`) and point the build process at it in that location.

Ref: https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/prepareWorkspace.sh#L386

**Comment by sxa** [comment]
This could do with a PR and then a few runs in [VagrantPlaybookCheck](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) to verify. bumping into October milestone to try and get it cleaned up

**Comment by sxa** [comment]
@AdamBrousseau What do you do with the freemarker dependency - do you rely on it being available on the machines as part of the playbook installation, or is that unnecessary for all versions given that it seems to be downloaded during the build process?

**Comment by AdamBrousseau** [comment]
Freemarker is no longer required for platforms building with cmake which is all but riscv (by default). That platform is still in development anyway so we likely don't need the Semeru build at this point. However we can probably enable cmake for riscv on the Semeru build to try. It has been failing for quite some time.

Running a test build for that now.

I had hacked out the freemarker download in the build code on our side a while back for some other reason which I can't recall without going to look. So at the moment the riscv build (which runs in the cent6 x64 container) it skips the download then fails when it's not there.

If my test build passes we should be able to remove it and cleanup the build code too. I had it on my backlog just don't have priority for it.

**Comment by AdamBrousseau** [comment]
Build passes so I vote to remove all freemarker stuff.

**Comment by sxa** [comment]
NOTE that we have NOT cleaned up the old freemarker.jar installations on the existing machines.
