### ISSUE TITLE
Ansible request for macos_codesign (version check incorrect?)

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#1902]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [x] Bug in ansible playbook
- [ ] Request for new playbook addition

Details: When running the `ansible-playbook` operation on the UNIX playbooks with verison 2.6.3 the following error occurs. We should either resolve this or adjust the version check in https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/2925d55ff93ca8bbbbaf6ada6184b7aa18847a69/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Version/tasks/main.yml#L5 if a later version is required. Error output below:
```
[ansible@sainz ansible]$ ansible-playbook -i hosts --tags debug playbooks/AdoptOpenJDK_Unix_Playbook/main.yml 
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/ansible/infra.docker/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/macos_codesign/tasks/main.yml': line 41, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Reboot macOS after setting Default keychain
  ^ here
```
The "offending line" is https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/2925d55ff93ca8bbbbaf6ada6184b7aa18847a69/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/macos_codesign/tasks/main.yml#L41

I'd prefer a fix if possible rather than upgrading the requirement, but it would be good to identify the cuase and see if it can be resolved since this is the only role that seems to cause a problem.

**Comment by Willsparker** [comment]
This is because the `reboot` module was added to Ansible in `2.7`: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/reboot_module.html . 

If you _really_ don't want to upgrade, this can be done: https://www.jeffgeerling.com/blog/2018/reboot-and-wait-reboot-complete-ansible-playbook

**Comment by sxa** [comment]
I'm not keen on having the reboot in there at all to be honest, especially when it's not guarded by any test - presumably it will /always/ reboot the machinem regardless of whether or not the keychain has been adjusted? So if we regularly redeploy the playbooks so all machines get updates it's going to reboot it automatically, which is not ideal when the machines can be in constant use via jenkins.

**Comment by Haroon-Khel** [comment]
From what I have experienced, ansible version greater than 2.11 is needed when running (atleast) the mac playbooks

**Comment by sxa** [comment]
> From what I have experienced, ansible version greater than 2.11 is needed when running (atleast) the mac playbooks

Can you add in a check for this?

**Comment by Haroon-Khel** [comment]
Closing since https://github.com/adoptium/infrastructure/pull/2573 is merged
