### ISSUE TITLE
Ansible request for AWX to deploy to AIX

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#1909]
Our AWX server does not currently have a template for deploying to AIX systems. We should add that and ensure that it is "safe" to deploy across all machiens

**Comment by Haroon-Khel** [comment]
So far ive created a basic AIX deploy template similar to the setup of the existing UNIX one

**Comment by Haroon-Khel** [comment]
Where does the ansible tower server keeps its vendor files?

**Comment by Haroon-Khel** [comment]
```
TASK [bootjdk7 : Transfer and Extract Java7] ***********************************
fatal: [build-osuosl-aix71-ppc64-1]: FAILED! => {"changed": false, "msg": "Could not find or access '/Vendor_Files/aix/openjdk-7u-aix.tar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
```

**Comment by sxa** [comment]
Hmmm that's odd ... it's definitely there in the same `/Vendor_Files` that the UNIX one is able to pick stuff up from.

**Comment by sxa** [comment]
The log that I looked aton AWX seemed to be from about 40 minutes ago. I re-ran and it seemed to find it

**Comment by sxa** [comment]
(Ooops just realised your "Apparently not" was also posted an hour ago and I just missed it. All working now :-) If there's anything else missing just let me know

**Comment by Haroon-Khel** [comment]
Tried running a check job to test the playbook through awx but the check job does not evaluate tasks which use conditions, which causes failures such as 
```
fatal: [build-osuosl-aix71-ppc64-1]: FAILED! => {"msg": "The conditional check 'does_openssl_exist.rc != 0' failed. The
error was: error while evaluating conditional (does_openssl_exist.rc != 0):
```

**Comment by sxa** [comment]
> I think this is a sufficient check of whether awx can find the vendor files.

We still need to know whether we can run the playbooks across existing machines as well as new ones, as that should be the primary mechanism for deploying playbook changes onto the existing machines.

**Comment by Haroon-Khel** [comment]
The awx server cannot reach test-ibm-aix71-ppc64-1 via ssh

```
fatal: [test-ibm-aix71-ppc64-1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: no 
such identity: /var/lib/awx/.ssh/id_rsa: No such file or directory\r\nroot@129.33.196.209: Permission denied 
(publickey,keyboard-interactive).", "unreachable": true}
```

**Comment by Haroon-Khel** [comment]
I get the same error for test-ibm-aix71-ppc64-2

**Comment by Haroon-Khel** [comment]
Does this awx setup place subsequent jobs in a queue? Or does it run them in parallel?

**Comment by Haroon-Khel** [comment]
The playbook ran successfully on `test-osuosl-aix72-ppc64-1`

**Comment by sxa** [comment]
> @sxa Does this awx setup place subsequent jobs in a queue? Or does it run them in parallel?

In a queue I think, otherwise there's a risk of it trying to do the same thing on a machine twice which could get messy

**Comment by sxa** [comment]
Bastillion had a couple of incorrect entries for the root user - now fixed so AWX should be able to connect to both of them now.

**Comment by Haroon-Khel** [comment]
@sxa Is the awx server appears to be missing one of the vendor files
`Could not find or access '/Vendor_Files/aix/OpenGL_X11.tar' on the Ansible Controller`

**Comment by sxa** [comment]
Looks like it was in `/Vendor_Files/aix/adt` - I've symlinked it so that it shows in the place the playbooks are expecting it

**Comment by Haroon-Khel** [comment]
Playbook runs fine on
build-osuosl-aix71-ppc64-1
test-ibm-aix71-ppc64-1
test-ibm-aix71-ppc64-2
test-osuosl-aix72-ppc64-1
test-osuosl-aix72-ppc64-2

test-osuosl-aix71-ppc64-1 is unreachable

Trying again on build-osuosl-aix71-ppc64-2

**Comment by sxa** [comment]
> test-osuosl-aix71-ppc64-1 is unreachable

Hmmm the machines seems alive to me and I think it has the correct AWX key on it - can you share the exact error?

**Comment by Haroon-Khel** [comment]
Its the usual unreachable error
```
fatal: [test-osuosl-aix71-ppc64-1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh:
 Shared connection to 140.211.9.99 closed.", "unreachable": true}
```

**Comment by sxa** [comment]
Just ran it again and got the same error - not obvious why ...

**Comment by sxa** [comment]
OK I run again with verbose level "Connection debug" and the issue is that python is broken rather than an SSH connection issue:
`<140.211.9.99> (255, b'Could not load program /usr/bin/python:\r\n        Dependent module libgcc_s.a(shr.o) could not be loaded.\r\nCould not load module libgcc_s.a(shr.o).\r\nSystem error: No such file or directory\r\n', b"OpenSSH_8.0p1, OpenSSL 1.1.1c FIPS  28 May 2019\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 51: Including file /etc/ssh/ssh_config.d/05-redhat.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf\r\ndebug2: checking match for 'final all' host 140.211.9.99 originally 140.211.9.99\r\ndebug3: /etc/ssh/ssh_config.d/05-redhat.conf line 3: not matched 'final'\r\ndebug2: match not found\r\ndebug3: /etc/ssh/ssh_config.d/05-redhat.conf line 5: Including file /etc/crypto-policies/back-ends/openssh.config depth 1 (parse only)\r\ndebug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config\r\ndebug3: gss kex names ok: [gss-gex-sha1-,gss-group14-sha1-]\r\ndebug3: kex names ok: [curve25519-s…`

**Comment by Haroon-Khel** [comment]
Playbook ran to completion on build-osuosl-aix71-ppc64-2. Thats all aix machines besides test-osuosl-aix71-ppc64-1

**Comment by Haroon-Khel** [comment]
Playbook ran sucessfully on test-osuosl-aix71-ppc64-1. Thats all the aix machines

**Comment by Haroon-Khel** [comment]
Closing since all the machines have had the playbook run on them
