### ISSUE TITLE
Solaris10 failing in VagrantPlaybookCheck job 

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#1938]
Ref: https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/OS=Solaris10,label=vagrant/1033/console
```
16:56:33 TASK [Gathering Facts] *********************************************************
16:56:33 fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Unable to negotiate with 127.0.0.1 port 2222: no matching key exchange method found. Their offer: gss-group1-sha1-toWM5Slw5Ew8Mqkay+al2g==,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1", "unreachable": true}
16:56:33 
16:56:33 PLAY RECAP *********************************************************************
16:56:33 127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
```
It's generally going ok in the github checks so hopefully this won't be complicated to fiux

**Comment by Willsparker** [comment]
Recreated the issue on my local machine - I wasn't able to run `vagrant ssh` to it either, no error message, it just didn't run anything it seemed.
I was able to ssh to it with the following:
```
ssh -o KexAlgorithms=diffie-hellman-group1-sha1 vagrant@127.0.0.1 -p 2222
```
As that's one of the key-exchanges that the VM allows. The way we can do this with Ansible is by appending `-o KexAlgorithms=diffie-hellman-group1-sha1` to the `ssh_args` field in _ansible.cfg_. I did this and was able to ping the VM locally.

For some reason Googling the issue seems to come up with the answer of 'don't host key check' - but that seems silly.

**Comment by Willsparker** [comment]
Branch with the fix is : https://github.com/willsparker/openjdk-infrastructure/tree/1938
VPC Run: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Solaris10,label=vagrant/1080/console

**Comment by Willsparker** [comment]
For that run, the VM didn't boot before the timeout. Retrying - if it fails again for the same reason, I'll try upping the timeout.

**Comment by Willsparker** [comment]
Alright, I've configured VPC to run the right branch, and it works! The playbook works, but we're running into a couple of issues:
```
08:39:58 TASK [Common : Extract cups 1.4.4] *********************************************

08:40:00 [WARNING]: Consider using the unarchive module rather than running 'tar'.  If
08:40:00 you need to use command because unarchive is insufficient you can add 'warn:
08:40:00 false' to this command task or set 'command_warnings=False' in ansible.cfg to
08:40:00 get rid of this message.
08:40:00 fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "tar -xf cups-1.4.4-source.tar.gz", "delta": "0:00:00.008565", "end": "2021-02-25 08:39:57.631097", "msg": "non-zero return code", "rc": 2, "start": "2021-02-25 08:39:57.622532", "stderr": "tar: directory checksum error", "stderr_lines": ["tar: directory checksum error"], "stdout": "", "stdout_lines": []}
```
Attempting the `unarchive` module gives: 
```
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to validate the SSL certificate for github.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine  (the python executable used (/opt/csw/bin/python2.6) is version: 2.6.9 (unknown, Mar  3 2016, 10:49:36) 
```
So.... Looks like I'll be trying to install Python 2.7.18 on Solaris 10, too! _yay_.

**Comment by Willsparker** [comment]
For some reason, the GH check doesn't run the Solaris common role, it seems - it doesn't run the `cups` tasks at all - hence why it works on GHChecks, but not VPC. Not sure why ...

**Comment by Willsparker** [comment]
My mistake - the Common role does run, but the `cups` role is skipped as per:
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/bda7a1a743a6d85ec0490344998afbc82836a0dc/.github/workflows/build_vagrant.yml#L41

It also appears the cup installation depends on SolarisStudio, as it's put to the front of the path before compiling: 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/c933d1bcf3b0a02ba7a6fa0bdedcf43ad0f113dc/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Solaris.yml#L120
However, the solaris studio task is tagged with `adoptopenjdk`, so it is skipped in VPC. Therefore, we should tag the cup installation with `adoptopenjdk` too. The concern with this, however, is that if/when it comes to setting up a new Solaris machine, the cups role is still likely to be broken - so I should probably try to fix that issue as opposed to ignoring it right now.

**Comment by sxa** [comment]
> It also appears the cup installation depends on SolarisStudio, as it's put to the front of the path before compiling: 
> https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/c933d1bcf3b0a02ba7a6fa0bdedcf43ad0f113dc/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Solaris.yml#L120
> However, the solaris studio task is tagged with `adoptopenjdk`, so it is skipped in VPC. Therefore

Nope. If it's being skipped then we need to resolve that. Not having a compiler on the machine is not conducive to having a useful test. We should enable that role in VPC one way or another

**Comment by Willsparker** [comment]
The Solaris Studio role is tagged with `adoptopenjdk` due to the `SolarisStudio12_solaris_x86_SAS_TOKEN` variable - ping @gdams

**Comment by sxa** [comment]
Something else that ought to be documented in #1974 perhaps as I don't believe it's documented anywhere else

**Comment by sxa** [comment]
I'd say it's something else we should possibly look at covering with a local `/Vendor_Files` fallback

**Comment by Willsparker** [comment]
Maybe? But VPC doesn't run with Vendor_Files. 
As you suggested on the call earlier, we could store SolarisStudio locally on the `infra-*` machine. Then it'd just be a case of copying it to the VM's shared folder, in vagrantPlaybookCheck.sh, and putting it where it is meant to be, in the provision script in the Vagrantfile. 
Only concern there is that Solaris in VPC isn't then a good show of our playbooks being useful for non-adopt people.

And I thought that `SolarisStudio12_solaris_x86_SAS_TOKEN` was in the Vendor Files ..?

**Comment by sxa** [comment]
> And I thought that `SolarisStudio12_solaris_x86_SAS_TOKEN` was in the Vendor Files ..?

It's in the version in `secrets` but that doesn't help us ;-)

> Only concern there is that Solaris in VPC isn't then a good show of our playbooks being useful for non-adopt people.

Correct, although I don't think it's too much of an ask for a Solaris user to obtain a compiler themselves. It's no different for AIX and macos (it just shows up as an issue her because we don't have either of those two in VPC). In many cases the non-open source world is always going to be a bit more problematic ;-)

I saw either put it on the Vagrant image of possible (May not be if we have to be able to pull it from the box website) or allow it to be picked up from `/Vendor_Files` in the same way as for AIX.

**Comment by Willsparker** [comment]
Okay, I'll look into the latter fix, as we do pull the box from the website :-)

**Comment by Willsparker** [comment]
I have come up with a solution that can be found at https://github.com/willsparker/tree/1938_2 . 

These changes are assuming that the compiler directory is in `/tmp/SolarisStudio12.3-solaris-x86-pkg`, on the machine that runs he VPC script. When this is the case, Solaris Studio is installed via  the Vagrantfile's provision script.

Unfortunately I am still having the issue of `cups` : 
```
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "tar -xf cups-1.4.4-source.tar.gz", "delta": "0:00:00.030145", "end": "2021-04-07 10:41:06.238814", "msg": "non-zero return code", "rc": 2, "start": "2021-04-07 10:41:06.208669", "stderr": "tar: directory checksum error", "stderr_lines": ["tar: directory checksum error"], "stdout": "", "stdout_lines": []}
```
However, at least once that issue is fixed, we will actually be able to compile it

**Comment by Willsparker** [comment]
I have managed to fix the above issue with using `gzip` and `tar` commands separately to decompress the archive. The above error message is given when `tar` decompresses an archive that isn't decompress-able with `tar` alone. This may be a particular quirk of Solaris' `tar`, as Solaris is the platform that comes up most often when you Google search the error message. 

With those changes put in, I'm going to attempt to run this via VPC. I've put the compiler directory on the `infra-ibmcloud-vagrant-x64-1` at `/tmp/SolarisStudio12.3-solaris-x86-pkg`.

**Comment by Willsparker** [comment]
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1129/

yay! The playbook ran through cleanly. The ssh commands that build / test the JDKs need to be altered to use the `diffie-helman-sha1` connection method. I've made those changes and it works locally, so trying on [VPC](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1130/)

**Comment by Willsparker** [comment]
It seems that an awful lot of configuration options wasn't set (or in the case of `JAVA_TO_BUILD`, completely ignored):

```
buildJDK.sh DEBUG:
08:39:13         TARGET_OS=
08:39:13         ARCHITECTURE=
08:39:13         JAVA_TO_BUILD=jdk8u
08:39:13         VARIANT=
08:39:13         JDK_BOOT_DIR=
08:39:13         JAVA_HOME=
08:39:13         WORKSPACE=/export/home/vagrant
08:39:13         FORK=AdoptOpenJDK
08:39:13         BRANCH=master:-}
08:39:13         FILENAME=
08:39:13 Cloning new openjdk-build folder
08:39:13 Cloning into '/export/home/vagrant/openjdk-build'...
08:39:13 ARCHITECTURE not defined - assuming x64
08:39:16 TARGET_OS not defined - assuming you want SunOS
08:39:16 JAVA_TO_BUILD not defined - defaulting to jdk11u
08:39:16 VARIANT not defined - assuming hotspot
08:39:16 FILENAME not defined - assuming jdk11u-hotspot.tar.gz
08:39:16 BUILD TYPE: 
08:39:16 VERSION: jdk11u
08:39:16 ARCHITECTURE x64
08:39:16 VARIANT: hotspot
08:39:16 OS: sunos
08:39:16 SCM_REF: 
08:39:16 Detecting boot jdk for: jdk11u
08:39:16 Found build version: 11
08:39:16 Required boot JDK version: 10
08:39:16 [ERROR] No local file detected at /export/home/vagrant/openjdk-build/build-farm/platform-specific-configurations/sunos.sh and PLATFORM_CONFIG_LOCATION is not set. Please set PLATFORM_CONFIG_LOCATION to a repository path of a platform config file (e.g. AdoptOpenJDK/openjdk-build/master/build-farm/platform-specific-configurations).
```
If nothing else, the OS is going to need to be set as `Solaris` (as we have a `solarish.sh` file).

**Comment by Willsparker** [comment]
So, the reason it's defaulting to `SunOS`, is because the output of `echo $OSTYPE` (as per https://github.com/AdoptOpenJDK/openjdk-build/blob/cf0a0473ff3e1f60a06c8ffadaf99a1989730381/build-farm/make-adopt-build-farm.sh#L43), is actually `solaris2.10`, not `SunOS`. On the physical Solaris machines, I don't know what the output of `uname` or value of  `OSTYPE` is, so I can't make changes to the build repo until I've confirmed that.

**Comment by Willsparker** [comment]
I made a branch that set OS correctly to Solaris, however, I don't think Solaris actually installs any JDKs: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1133/OS=Solaris10,label=vagrant/console

Confirming this locally, then I'll have a look at the build repo issue

**Comment by Willsparker** [comment]
Solaris only installs JDK8, as we only build JDK8/HS on Solaris. As such, I've restricted this in `buildJDK.sh` (as well as setting `TARGET_OS`, to get round the openjdk-build issue mentioned before). Test at: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1134/

**Comment by Willsparker** [comment]
Not sure why I haven't updated this issue.. The last few Solaris10 VPC runs had a few issues: 
Run [1135](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Solaris10,label=vagrant/1135/) and [1138](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Solaris10,label=vagrant/1138/):
```
08:26:28 changed: [127.0.0.1] => (item=freetype)
08:26:45 fatal: [127.0.0.1]: FAILED! => {"msg": "Timeout (32s) waiting for privilege escalation prompt: sudo: unable to resolve host adoptopenjdkSol10: node name or service name not known\r\r\n"}
```
Can be fixed by adding more to the timeout in `ansible.cfg` - however I'd like to try and avoid this. This is an intermittent issue currently.

Run [1134](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Solaris10,label=vagrant/1134/). 
```
11:10:32 Detecting boot jdk for: jdk8u
11:10:32 Found build version: 8
11:10:32 Required boot JDK version: 7
11:10:32 [SUCCESS] Executing local file at /export/home/vagrant/openjdk-build/build-farm/platform-specific-configurations/solaris.sh
11:10:32 Setting JDK_BOOT_DIR to $JAVA_HOME
11:10:32 [ERROR] No JDK Boot Directory has been found, the likelihood is that neither JDK7_BOOT_DIR or JAVA_HOME are set on this machine
11:10:32 ++ date +%T
```
Having restricted the JDK to JDK8/HS, it is still unable to find a BOOTJDK. Therefore, I've tried to set `JAVA_HOME` manually, as per: https://github.com/Willsparker/openjdk-infrastructure/commit/8c69db9c69d10b92ca8c86bed0e3e0cc5e6dadc7 . The new VPC run can be seen here: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Solaris10,label=vagrant/1146/console . If this one hits timeout again, I'll increase the timeout in `ansible.cfg` again.

**Comment by Willsparker** [comment]
It worked! It just failed on installing `zip`, so I've added that to the package list :-)

**Comment by karianna** [comment]
@Willsparker can this be closed now?

**Comment by Willsparker** [comment]
Sadly not - I'm still yet to get the build and tests working. This is the error message: 
```
17:50:11 WARNING: Cannot get tag due to previous failures. /export/home/vagrant/openjdk-build/workspace/target//metadata/scmref.txt will NOT be created!
17:50:11 checkoutRequiredCodeToBuild failed rc=128
17:50:11 RETRYWARNING: Checkout required source failed, cleaning workspace and retrying...
17:50:11 /export/home/vagrant/openjdk-build/sbin/prepareWorkspace.sh: line 93: cd: /export/home/vagrant/openjdk-build/workspace/./build/: I/O error
```
I'm yet to properly look into it

**Comment by sxa** [comment]
This is generally working now with a final fix to https://github.com/adoptium/infrastructure/pull/2250 going in, so I'm going to close this since the original symptoms have now been resolved.
