### ISSUE TITLE
Verify downloads in static Dockerfiles

### ISSUE THREAD

**Issue by aahlenst** [adoptium/infrastructure#1954]
#1925 introduced Dockerfiles in `ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/` that download a couple of things (ant, ant-contrib). We should check their checksums after downloading.

**Comment by jeffalder** [comment]
@sxa I'm going to grab this as well; I've got a PR ready.
