### ISSUE TITLE
Test machines for AdoptOpenJDK for Windows on ARM

### ISSUE THREAD

**Issue by aahlenst** [adoptium/infrastructure#1977]
@gdams and @karianna [have stated](https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1614162805028800) that they want AdoptOpenJDK 16 for Windows on ARM in March which is currently blocked on lack of suitable test machines. So here's the tracking ticket for the machine request.

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Windows
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): aarch64
- Provider (leave blank if it does not matter):
- Desired usage: Testing AdoptOpenJDK 16+ for Windows on ARM
- Any unusual specification/setup required: 
- How many of them are required: 2

Please explain what this machine is needed for:
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2224

**Comment by aahlenst** [comment]
According to my testing, using Mac Minis with an M1, Parallels Desktop and the Windows 10 Insider Preview is a viable option an can be quickly procured. The usual price for a rented Mac Mini for one year equals the price to purchase one. Everything else is either hard to buy, untested, or both. Purchased Mac Minis could be put on TCK duty or offer additional testing capacity once there's an official offering from Azure.

**Comment by aahlenst** [comment]
We got a quote (not public) for an Ampere Altra system with limited on-site service to be installed at Colozüri (our colo site). For those who haven't been in the loop: The Ampere Altra is the newest ARMv8 CPU from Ampere System. It is based no the ARM Neoverse N1 design that is also being used by the Amazon Graviton 2. Altra systems started shipping in very limited quantities at the beginning of March 2021.  There are systems "available" from two manufacturers: Wiwynn (Mt. Snow and Mt. Jade, [review](https://www.servethehome.com/ampere-altra-wiwynn-mt-jade-server-review-the-most-significant-arm-server/4/)) and [Gigabyte](https://www.gigabyte.com/Industry-Solutions/5G-Data-Center/ampere-altra-server-solution). The quote is for a system made by Gigabyte (because that's what we can get with on-site service). So far, only single socket systems are available from Gigabyte. All systems a 2u designs. Seems like the Altra needs a big heatsink.

Base system:

1x 64 Core Ampere 1st Gen Altra "Quicksilver" 3.3GHz Processor (Q64-33)
128GB DDR4 3200MHz ECC Server Memory (8x 16GB / 8 free slots)
4 x 960GB SATAIII Intel S4610 Enterprise SSD in a RAID 10 (2 TB)
2 x Intel 1G RJ45 Network Controller (rear)
2 x Intel 10G RJ45 Network Controller (rear)
1 x IP KVM (rear)
2 x 800 W power supplies (redundant)
1 x Rackmount kit

I calculate with 8-10 cores, 16 GB memory, 256 GB disk per VM. With the base system, we could get 6-8 VMs out of it. To keep the density in the rack high, I'd opt for the biggest CPU (80 cores), double the storage (total of 4 TB usable) and double the memory. This should give us enough headroom.

Pricing is comparable to what [Avantek is offering](https://store.avantek.co.uk/arm-servers.html). @gdams is currently looking for money. 

Any comments re: specs?

**Comment by smlambert** [comment]
While this is an item that we would wish to progress, we either need funding or donation of machines to move it forward.  WG discussion of April 1st indicates we will have neither funding or machines in a known timeline, so will remove from Top Priorities.

Obviously if either funding or machines show up, we can progress it (but won't leave it as Top Priority based on WG decision to not fund).

**Comment by smlambert** [comment]
It should also be noted that test material currently does not compile on this platform (based on talking through someone with hardware and hitting issues but not being able to see or debug directly).  Without hardware to troubleshoot we do not know what effort is required to enable testing on this platform.  It is safe to assume there will be some effort required.
