### ISSUE TITLE
Prepare for Ubuntu 16.04 End of Standard Support

### ISSUE THREAD

**Issue by aahlenst** [adoptium/infrastructure#1986]
[Standard support for the Ubuntu 16.04 line ends at the end of April 2021](https://wiki.ubuntu.com/Releases). Afterwards, patches are only available if ESM is purchased from Canonical. Affected machines according to our inventory:

* [ ] ci.adoptopenjdk.net ([Issue](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2108))
* [x] trss.adoptopenjdk.net **Already upgraded to 18.04 - will update inventory**
* [ ] ansible.adoptopenjdk.net (No longer in use, kept for reference when setting up new server)
* [ ] ubuntu1604-armv7-1 (Scaleway, replacement in progress)
* [ ] ubuntu1604-armv7-2 (Scaleway, replacement in progress)
* [ ] build-ubuntu1604-x64-1 (Scaleway) **[Only machine tagged for fpm](https://github.com/AdoptOpenJDK/openjdk-build/issues/1044#issuecomment-803318114) (installers)** Now offline as [test-packet-ubuntu-1804-x64-2](https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1804-x64-2) can now do this.
* [ ] docker-ubuntu1604-x64-1 (AWS) **Marked offline**
* [ ] ubuntu1604-s390x-1 (Marist) **Marked offline**
* [x] ubuntu1604-s390x-2 (Marist) **Upgraded to 18.04**
* [x] ubuntu1604-s390x-3 (Marist) **Upgraded to 18.04**
* [x] ubuntu1604-s390x-4 (Marist) **Upgraded to 18.04**
* [ ] test-ubuntu1604-armv8-1 (Packet) **To be decomissioned when Altras fully in place**
* [x] test-ubuntu1604-armv8-2 (Packet) **Already upgraded to 18.04 - needs renamed**
* [x] docker-ubuntu1604-armv8-1 (Packet) **Marked offline - had 3 `docker` executors**
* [ ] ubuntu1604-x64-1 (Packet) **Marked offline**
* [ ] ubuntu1604-x64-2 (Packet) **Marked offline**
* [ ] ubuntu1604-x64-3 (Packet) **Upgrade completed but won't restart properly**
* [ ] ubuntu1604-ppc64le-1 (OSUOSL) **Marked offline**
* [ ] ubuntu1604-ppc64le-2 (OSUOSL) **Marked offline**
* [x] ubuntu1604-ppc64le-3 (OSUOSL) **Decomissioned**
* [x] ubuntu1604-ppc64le-4 (OSUOSL) **Decomissioned**
* [ ] ubuntu1604-x64-1 (IBM Cloud) **Marked offline**

**Comment by sxa** [comment]
In general for upgrades with new configuration files:
- grub: Don't update - may be provider specific things in there
- sshd: Don't update - may affect our ability to connect to it if our setup is changed
- NTP: Take updates

I had an issue on one machine where it repeatedly asked about my timezone. In that case I broke out of the `do-release-upgrade` process and run `apt-get dist-upgrade` which helped it to go past that point

**Comment by sxa** [comment]
Note that after upgrading from `16.04` to `18.04` the `git` that we build in the `GIT_source` role does not work:
`stderr: /usr/local/libexec/git-core/git-remote-https: /usr/lib/s390x-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/local/libexec/git-core/git-remote-https)`
Fix is to remove the version of `git` in /usr/local/bin and allow the default installed one with Ubuntu 18.04 (which is `2.17.1`) tobe used (May require override of the git tool location in jenkins for those agents if it has been explicitly set to `/usr/local/bin/git`
Slack reference thread: https://adoptium.slack.com/archives/C53GHCXL4/p1619448983268400

**Comment by sxa** [comment]
Also note: At present all [xLinux sw.tool.docker nodes](https://ci.adoptopenjdk.net/label/ci.role.test&&hw.arch.x86&&sw.os.linux&&sw.tool.docker/) are Ubuntu 16.04

**Comment by sxa** [comment]
Ubuntu 16.04 [docker image created](https://github.com/adoptium/infrastructure/pull/2201) for arm32 so they can be "hidden" from the network as we do for CentOS6, which will enable us to decomission the scaleway systems and move to alternate hosts

**Comment by sxa** [comment]
I believe we only have the 32-bit docker containers used for building arm32 images live running that level of the OS, along with the jenkins server.
