### ISSUE TITLE
Apply for RHEL for OSS Infrastructure subscription

### ISSUE THREAD

**Issue by aahlenst** [adoptium/infrastructure#2008]
https://www.redhat.com/en/blog/extending-no-cost-red-hat-enterprise-linux-open-source-organizations

[Following up on a Slack conversation](https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1614511308045400), I mailed the ROSI program people today.

**Comment by sxa** [comment]
This has now been granted. I just need to find the time to figure out how to make use of it, so adding to October milestone

**Comment by sxa** [comment]
This is available and active (details will go into the secrets repository) so I'm going to close this with a few notes:

To activate a machine ([ref for subscription](https://access.redhat.com/solutions/253273), [ref for container registry](https://catalog.redhat.com/software/containers/rhel7/57ea8cee9c624c035f96f3af?architecture=s390x&container-tabs=gti))
- `subscription-manager register --username adoptium`
- `subscription-manager refresh`
- `subscription-manager attach --auto`
- `subscription-manager list --available --all | grep Pool.ID` then `subscription-manager attach --pool=...`
For docker registry access:
- `docker login -u adoptium`
- `docker pull registry.redhat.io/rhel7` (or if unauthenticated `registry.redhat.com/rhel7` may work...)

**Comment by sxa** [comment]
Noting that this subscription needs to be renewed annually. I've done it for 2024.
For reference, you can login and go to https://access.redhat.com/management/subscriptions to renew.
