### ISSUE TITLE
Request access to ARM test system

### ISSUE THREAD

**Issue by JamesKingdon** [adoptium/infrastructure#203]
Requesting access to a 32 bit ARM system for testing OpenJDK builds.

**Comment by gdams** [comment]
approved, @JamesKingdon has used our systems before so I am happy to sponsor this access

**Comment by sxa555** [comment]
For anyone reading this @JamesKingdon has now been granted the access

**Comment by JamesKingdon** [comment]
...for which many thanks, this is going to be extremely useful.

**Comment by bblondin** [comment]
@JamesKingdon do you still require access? if so how much longer do you require it for?

**Comment by JamesKingdon** [comment]
Hi Brad. Yes, and as long as possible. This isn't going to be a short term effort unfortunately.

**Comment by karianna** [comment]
@JamesKingdon Checking in to see if you still require access

**Comment by JamesKingdon** [comment]
Hmm, haven't 'finished' by any stretch of the imagination, but I will have very little time to put to this over the summer, so it probably makes sense to drop me for now. 

Many thanks for the access!

**Comment by karianna** [comment]
@gdams Can you walk me through removing the temp access on Slack at some stage?

**Comment by JamesKingdon** [comment]
I created a user account for the work (to reduce the chance of breaking something), you'll probably want to remove that as well. Username: jkingdon

**Comment by sxa555** [comment]
@karianna We need it documented really if it's not already there. Will we generally give ssh key access to the jenkins account, or a user account, have the option for either? Ought to be managed through keybox.

This is something that's likely to be needed more if we have people accessing the JCK systems to run the manual tests (where a decision was made to use a shared ID)

**Comment by karianna** [comment]
@sxa555 agreed - when I next pin down George I'll doc it :-)

**Comment by sxa** [comment]
I assume this was on one of the scaleway machines which no longer exists, therefore closing.
