### ISSUE TITLE
Various errors in MacOS Common role due to different ansible versions

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2042]
Im experiencing various playbook errors while running the Unix playbook on test-macstadium-macos1014-x64-2.
 
This following error is due to the fact that `cask` has been disabled as of Brew 2.7.0
```
failed: [test-macstadium-macos1014-x64-2] (item=adoptopenjdk10) => {"ansible_loop_var": "item", "changed": false, "item": "adoptopenjdk10", "msg": "Error: Unknown command: cask"}
failed: [test-macstadium-macos1014-x64-2] (item=packages) => {"ansible_loop_var": "item", "changed": false, "item": "packages", "msg": "Error: Unknown command: cask"}
```
Ive tried to resolve this by changing the [`homebrew_cask`](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/53ddb4ec7a54f978a9556fb092cbc046bba38f44/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml#L105) task to `homebrew` and by adding `install_options: cask`, but then I get this error
```
failed: [207.254.29.44] (item=['adoptopenjdk10', 'packages']) => {"ansible_loop_var": "item", "changed": false, "item": ["adoptopenjdk10", "packages"], "msg": "Updating Homebrew...\n==> Auto-updated Homebrew!\nUpdated 1 tap (homebrew/cask).\n==> Updated Casks\nUpdated 1 cask.\n\nWarning: Cask 'adoptopenjdk10' is already installed.\n\nTo re-install adoptopenjdk10, run:\n  brew reinstall adoptopenjdk10"}
```
Two things are happening in the above error. This first is that despite there being two packages in the install list, ansible will only attempt to install one. The second is that ansible is throwing an error message in a situation where the packages are already installed on the machine. This shouldnt be an error message. This does not happen with some of the earlier tasks which use brew to install a package that is already present on a machine.

Ansible also seems to have a problem resolving the [`"{{ ansible_user }}"`](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/53ddb4ec7a54f978a9556fb092cbc046bba38f44/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/MacOSX.yml#L104) variable when iterating through a list of packages to install. 
```
 FAILED! => {"msg": "The field 'become_user' has an invalid value, which includes an undefined variable. The error was: 'ansible_user' is undefined"}
```
The ansible version on my machine is 2.9. I am now updating it to 3.0 to see if these problems persist

**Comment by Haroon-Khel** [comment]
Still receiving the same 
```
FAILED! => {"msg": "The field 'become_user' has an invalid value, which includes an undefined variable. The error was: 'ansible_user' is undefined"}
```
error. It appears because of
```
  become: yes
  become_user: "{{ ansible_user }}"
```
which I dont think needs to be in the playbooks; {{ ansible_user }} represents the user which is running the playbook on the remote machine, ie root, admin, administrator. Ansible already runs each task as this user so I think these lines are redundant

**Comment by Haroon-Khel** [comment]
Also, depsite brew saying it upgraded my machine's ansible to 3.0.0
```
==> Upgrading 1 outdated package:
ansible 2.9.13_1 -> 3.0.0
==> Upgrading ansible 2.9.13_1 -> 3.0.0 
```
I got the latest ansible, which is 2.10
```
hkhel-mac:playbooks hkhel$ ansible --version
ansible 2.10.6
  config file = None
  configured module search path = ['/Users/hkhel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/3.0.0/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 24 2021, 13:30:36) [Clang 12.0.0 (clang-1200.0.32.29)]
```

**Comment by Haroon-Khel** [comment]
Fortunately this version solves the `cask` issue, and the issue concerning ansible thinking its an error when a package is already installed on a machine

**Comment by karianna** [comment]
@Haroon-Khel can this be closed in that case?

**Comment by Haroon-Khel** [comment]
Closing
