### ISSUE TITLE
Ansible request for CentOS8 Dockerfile

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2044]
We had intended to add in a CentOS dockerfile as part of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1809 but for reasons I can't recall just now the Dockerfile was not suitable. It needs to be investigated and added so we have coverage on this OS.

**Comment by aahlenst** [comment]
Let's wait a week and use Rocky Linux right away (the CentOS replacement) because CentOS 8 goes EOL in 9 months.

**Comment by sxa** [comment]
To be fair, whatever work is needed to get the existing CentOS one working (probably not a lot - it just didn't work first time and I didn't get back to it) would likely be needed for that too.

**Comment by gdams** [comment]
@sxa is this a request for a Centos8 Dockerfile like the 7 one here? https://github.com/adoptium/infrastructure/blob/master/ansible/Dockerfile.CentOS7

Or something else?

**Comment by karianna** [comment]
Kalyan will pick this one up.

**Comment by sxa** [comment]
It's for the DockerStatic role, so not the same as those @gdams

**Comment by karianna** [comment]
So this: https://github.com/adoptium/infrastructure/tree/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles which already has a cento8 file which apparently is not working as of yet...

Test locally first and then we can work towards deploying it on a real server.

**Comment by karianna** [comment]
See #2257 as well

**Comment by karianna** [comment]
This works locally.  There's a separate issue with running it on Podman on Ampere Altra Aarch64. #2257

**Comment by sxa** [comment]
@karianna Has this been tested on a machine connected to jenkins? If not it should be kept open until we have such as setup live on at least one architecture. Issue 2257 is not directly related to this.

**Comment by karianna** [comment]
@KalyanJoseph - Can you work with @sxa to try this?  He'll need to give you some access to infra (or perhaps install an agent in a docker container)

**Comment by sxa** [comment]
@Haroon-Khel In light of the above can you get a CentOS8 static docker container brought up somewhere (On any of the hosts we have) and get it connected to jenkins for @KalyanJoseph to test please?

**Comment by Haroon-Khel** [comment]
@sxa On it

**Comment by Haroon-Khel** [comment]
I may have fixed it. Supposedly the file `/run/nologin` prevents non root users from logging in. The content of the file is simply
`"System is booting up. Unprivileged users are not permitted to log in yet. Please come back later. For technical details, see pam_nologin(8)." `
I have renamed it to `nologin-old` for now and am now able to attempt to login to the jenkins user on the docker container from my machine, I'm presented with a password prompt which is further than I got before. And Jenkins is able to connect to the machine; I've made a temp Jenkins node entry at https://ci.adoptopenjdk.net/computer/test-docker-centos8-x64-1/ for a centos 8 docker container on port 2232 of docker-packet-ubuntu2004-x64-1.

@sxa What else needs to be done for this issue to be complete?

**Comment by Haroon-Khel** [comment]
I'll add a step in the Centos 8 Dockerfile which removes this file

**Comment by sxa** [comment]
All sounds good to me :-)

**Comment by sxa** [comment]
@Haroon-Khel Is this now complete?

**Comment by Haroon-Khel** [comment]
Was the container removed by anyone? It's no longer on docker-packet-ubuntu2004-x64-1/dockerhost-equinix-ubuntu2004-x64-1

**Comment by sxa** [comment]
Its ossible that got removed as part of a quick attempt to clear disk space as per the discussion on the 15th in #infrastructure.  If it's now expected to be fully working and it's not there just now we should redeploy another CentOS8 into the machine

**Comment by Haroon-Khel** [comment]
Up and running. Moved the container over to dockerhost-equinix-ubuntu2004-x64-2 for space
