### ISSUE TITLE
System unavailable: Both test-nine-macos1015-x64-1&2 down

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2050]
https://ci.adoptopenjdk.net/label/macos10.15/

**Comment by aahlenst** [comment]
Both machines have lost their IPv6 addresses.

**Comment by aahlenst** [comment]
Both are back. I'm still not sure what the problem exactly is. The thing that ultimately brought things back to order was a restart of the RA service on the router. The machines received their IPs immediately afterwards. I have also cleaned up the machine name mismatch on `test-nine-macos1015-x64-1`.

**Comment by sxa** [comment]
Restarted RA service again and brought the machines back online.

**Comment by sxa** [comment]
This is a recurring issue - I'm going to bounce it from close to open for a few days as I want to do a capacity test for another issue and leaving this open will remind me to reactive them later :-)

**Comment by sxa** [comment]
Closing as the real issue is the one referenced above
