### ISSUE TITLE
Define and document policy for updating static docker host systems

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2070]
Details:

We now have multiple hosts on various architectures (x64, aarch64 and ppc64le) which we are using for hosting docker containers for running tests. Now that we have ironed out the problems associated with doing this we need to formalise things a bit more with the following steps:

- [x] Define and implement patching policy
- [ ] Define update process when the docker files are updated
- [ ] Determine optimal capacities for the containers based on host size and implement via the playbook role

There is a separate issue regarding the naming of these host systems

**Comment by sxa** [comment]
This should probably include having some information on the policies when we need to update to new OS levels e.g. [Ubuntu 21.10](https://github.com/adoptium/infrastructure/issues/2395) and [Fedora 35](https://github.com/adoptium/infrastructure/issues/2396)

**Comment by sxa** [comment]
@Haroon-Khel Can this be closed now?

**Comment by Haroon-Khel** [comment]
Actually, I would like to review the last 2 tasks before closing this issue

**Comment by Haroon-Khel** [comment]
I think this can be closed now. Documentation is in and the improvements that I would like to make, as per my last comment, do not belong to this issue
