### ISSUE TITLE
Ansible request for git and cmake

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2091]
In the GIT_Source role we build and install git from source if the version on the default version of `git` on the machine is either too old or not present.

On some distributions (Such as Debian11) if the distribution's own `git` is new enough but not already present, we don't try to install it and still fall back to compiling it yourself. We should look at this and ensure we use the distribution's `git` where possible.

(same appears to be true for cmake)

Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [x] Missing install
- [ ] Bug in ansible playbook
- [ ] Request for new playbook addition

Details:

**Comment by sxa** [comment]
@Haroon-Khel Are you able to take a look at this one. We seem to be wasting a lot of time during the ansible playbooks on the newer platforms which shouldn't need to build `git` `cmake` and possibly `ccache` as well which suggests the version checks aren't adequate (i.e. it's not properly detecting the right version that comes from the package respositories, so it's causing the playbooks to take longer than they need to on a brand new machine - `cmake` in particular seems to take ages to build from source).

**Comment by Haroon-Khel** [comment]
@sxa Currently the Unix playbook installs the packages at these versions

```
Git 2.15
cmake 3.11.4
ccache 3.4.2
```
Do we still want to maintain these versions? Or are we comfortable with installing later versions of the packages. These specific versions may not be available on all package repositories

**Comment by sxa** [comment]
Later versions are fine if they're available in the default repositories

**Comment by Haroon-Khel** [comment]
Latest package versions offered by repos

Ubuntu

```
Git 2.30.2
Cmake 3.18.4
Ccache 4.2
```

Centos 6 repo

```
Git 1.7.1
Cmake 2.8.12
Ccache 3.1.6
```

Rhel 8 repo

```
Git 2.27.0
Cmake 3.18.2
Ccache 3.7.7
```

Rhel 7 

```
Git 1.8.3
Cmake 2.8.12
Ccache 3.7.7
```

**Comment by Haroon-Khel** [comment]
For the OS's whose repositories offer a version of git, cmake or ccache lower than the version acquired via compiling, we can stick with compiling our own. Otherwise, it will be quicker to download from the repos. Still have to check Debian

**Comment by karianna** [comment]
@Haroon-Khel can this now be closed?

**Comment by sxa** [comment]
Much better - previously for Ubuntu 20.04:
```
13:49:01 TASK [Extract cmake] ***********************************************************
13:49:06 changed: [127.0.0.1]
13:49:06 
13:49:06 TASK [Running ./configure & make for cmake] ************************************
14:12:05 changed: [127.0.0.1]
14:12:05 
14:12:05 TASK [Remove downloaded packages for cmake] ************************************
```
Now:
```
11:49:50 TASK [Extract cmake] ***********************************************************
11:49:50 skipping: [127.0.0.1]
11:49:50 
11:49:50 TASK [Running ./configure & make for cmake] ************************************
11:49:50 skipping: [127.0.0.1]
11:49:50 
11:49:50 TASK [Remove downloaded packages for cmake] ************************************
```
Almost 25 minutes saved :-D

I'll close on Haroon's behalf sine he's away this week
