### ISSUE TITLE
Secure the public Jenkins server

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2108]
This issue is to encapsulate the requirements and work needed to replace our existing Jenkins server with a new one:

Existing Jenkins server is suffering from some instability.  Recent difficult updates have shown that we need a better disaster recovery plan (this is also related to: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1295)  It is also a ubuntu-16.04 machine.  For all of these reasons, and likely reasons not yet listed, we should begin the work to replace the existing Jenkins server with a new one.

Requirements:
- Similar requirements to existing server
- Ansible playbook for creation/spinup
- Staging server to try out upgrades and major features or changes
- Clearly documented process for deploying updates
- Back up / disaster recovery process (in place and tested) / training for multiple people in multiple timezones to be able to assist
- Policy & documentation for how many jobs to keep in history, how many days to keep jobs
- How many of them are required: 1

Please explain what this machine is needed for: 
- nightly/weekly/release builds and testing
- Grinders for debugging and triage
- building tools and dependencies
- building Docker images
- building installers

Considerations:
- Given that this server is for our production builds, should we limit freeform builds, personal duplicates of existing pipelines, etc.?
- Should we have a separate sandbox for 'experimental' jobs and work?
- We should have a script that checks for jobs that have not been run/used in X months to remove old/stale jobs (may not need if all jobs have policy for how many days to keep jobs)
- Consider pushing artifacts to artifactory or other storage so that they are available for longer than

**Comment by karianna** [comment]
I'd personally like to see this bootstrapped via ansible and that we also build a staging server to test out any major pipeline changes, jenkins upgrades, and so forth.

**Comment by smlambert** [comment]
re: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2108#issuecomment-814417860 - added to the requirements section

**Comment by sxa** [comment]
@karianna Since you've been pushing for this and suggesting requirements, are you able to take ownership of this item and progress it?

**Comment by karianna** [comment]
> @karianna Since you've been pushing for this and suggesting requirements, are you able to take ownership of this item and progress it?

I can own it, but I'll be pulling in folks who actually know how to ansible :-).  Typical Engineering manager eh ;-)

**Comment by karianna** [comment]
https://github.com/jenkins-x/jx

**Comment by sxa** [comment]
I also think that for security we should disallow jobs from running on the master node unless there's a clear and explicit need for it.

**Comment by karianna** [comment]
In addition to Shelley's requirements, I'm also going to add VPN security - this Jenkins should no longer be accessible on the public internet.

**Comment by sxa** [comment]
> In addition to Shelley's requirements, I'm also going to add VPN security - this Jenkins should no longer be accessible on the public internet.

To be absoltely clear here - that statement is about non-HTTPS ports right?
(I agree and was thinking the same, however we also need incoming ports enabled for several of our machines to connect)

**Comment by karianna** [comment]
After further investigation jenkins-x is not a great option as its pipeline implementation and syntax is not compatible with regular Jenkins, forcing us to have a massive rewrite (and forcing jenkins x on other vendors using our scripts).

**Comment by karianna** [comment]
By using Ansible we can be fairly hosting provider agnostic.  But we do need a provider that hosts a VPN easily and has sufficient disk storage (3-4TB) at a decent price point.

**Comment by karianna** [comment]
We'll prototype:

* Ansible Playbook for Jenkins
* Deploying to Hetzner Cloud in a Docker Container
* Apply Networking, Firewalling and OpenVPN for security

**Comment by sxa** [comment]
As discussed elsewhere while the full set of items descried in the prototype comment above has now been put on pause we should as a priority look at upgrading the OS underneath the jenkins server (ideally to 20.04) after taking a Hetzner snapshot to avoid any problems with the OS upgrade.

**Comment by sxa** [comment]
Eclipse WorkGroup finance approval acquired for the snapshot costs

**Comment by sxa** [comment]
Snapshot created, however deploying it to an alternate server to do an upgrade test would require additional costs.

**Comment by sxa** [comment]
Approval for costs to deploy the snapshot was given by the WG last Thursday, although it seems we can only deploy to a comparably large server. @karianna will contact the provider to see if we can deploy on a less expensive system.

**Comment by sxa** [comment]
Discovered yesterday that the backups have not been executing correctly. The absence of a `config.xml` under `/jobs/build-scripts/jobs/jobs/jobs/jdk9u` was causing a `SEVERE` error to occur, at which point it left a partial backup in place and did not continue with the rest of it:

```
2022-03-18 05:57:37.925+0000 [id=2409973]       SEVERE  o.j.h.p.t.ThinBackupPeriodicWork#backupNow: Cannot perform a backup. Please be sure jenkin
s/hudson has write privileges in the configured backup path '/mnt/backup-server/jenkins_backup'.
java.io.FileNotFoundException: Source '/home/jenkins/.jenkins/jobs/build-scripts/jobs/jobs/jobs/jdk9u/config.xml' does not exist
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1074)
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
        at org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup.backupJobsDirectory(HudsonBackup.java:227)
        at org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup.backupJobsDirectory(HudsonBackup.java:228)
        at org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup.backupJobsDirectory(HudsonBackup.java:228)
        at org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup.backupJobs(HudsonBackup.java:209)
        at org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup.backup(HudsonBackup.java:168)
        at org.jvnet.hudson.plugins.thinbackup.ThinBackupPeriodicWork.backupNow(ThinBackupPeriodicWork.java:89)
        at org.jvnet.hudson.plugins.thinbackup.ThinBackupPeriodicWork.execute(ThinBackupPeriodicWork.java:66)
        at org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork.lambda$doRun$0(AsyncPeriodicWork.java:53)
        at java.lang.Thread.run(Thread.java:748)
```
While I have put that file in place and been able to take a successful backup I'm currently seeing instability on the jenkins server so I have disabled the automatic backup schedule for now (It was `H 5 * * *`)

**Comment by sxa** [comment]
OOM kill again this evening. Given that it's an OOM condition it seems unlikely that a heap size increase will make a difference, but in the absence of any better ideas or options just now I've given the JVM another 2Gb to play with. It's back again.

**Comment by sxa** [comment]
The following jobs were causing errors in the jenkins logs due to having zero length build.xml files - they have been backed up as `zeroLengthDirectories.tar.gz` in the `sxabackups` directory

**Comment by sxa** [comment]
Note: There was a spike in heap usage at around 1656 yesterday - there didn't seem to be too much unexpected things in the log around that time:
```
2022-03-30 16:54:00.621+0000 [id=22812] INFO    o.j.p.workflow.job.WorkflowRun#finish: Grinder #4212 completed: SUCCESS
2022-03-30 16:54:00.622+0000 [id=22812] INFO    h.p.t.l.JenkinsRunListener#onCompleted: onCompleted: Grinder #4212
2022-03-30 16:54:20.289+0000 [id=21908] INFO    hudson.slaves.ChannelPinger$1#onDead: Ping failed. Terminating the channel build-macstadium-macos11-arm64-2.
java.util.concurrent.TimeoutException: Ping started at 1648659020288 hasn't completed by 1648659260288
        at hudson.remoting.PingThread.ping(PingThread.java:134)
        at hudson.remoting.PingThread.run(PingThread.java:90)
2022-03-30 16:54:36.812+0000 [id=23047] OFF     hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started OpenStack slave cleanup
2022-03-30 16:54:39.832+0000 [id=23047] OFF     hudson.model.AsyncPeriodicWork#lambda$doRun$0: Finished OpenStack slave cleanup. 3,019 ms
2022-03-30 16:55:07.311+0000 [id=22249] INFO    o.j.p.ghprb.GhprbRootAction#handleAction: Checking PR #3,476 for adoptium/aqa-tests
2022-03-30 16:56:32.744+0000 [id=65]    INFO    o.j.p.P.u.DropCachePeriodicWork#doRun: begin schedule clean...
2022-03-30 16:56:32.744+0000 [id=65]    INFO    o.j.p.P.u.DropCachePeriodicWork#doRun: end schedule clean...
2022-03-30 16:56:33.330+0000 [id=22805] INFO    h.p.t.l.JenkinsRunListener#onCompleted: onCompleted: git-mirrors/adoptium/git-skara-jdk #7391
2022-03-30 16:56:33.377+0000 [id=22805] INFO    j.p.s.l.SlackNotificationsLogger#info: [git-mirrors » adoptium » git-skara-jdk #7391] found #7390 as previous completed, non-aborted build
2022-03-30 16:56:35.602+0000 [id=23068] INFO    hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started Periodic background build discarder
2022-03-30 16:56:39.800+0000 [id=23068] INFO    hudson.model.AsyncPeriodicWork#lambda$doRun$0: Finished Periodic background build discarder. 4,197 ms
2022-03-30 16:57:21.698+0000 [id=23121] INFO    c.s.o.i.Platform$JdkWithJettyBootPlatform#getSelectedProtocol: ALPN callback dropped: SPDY and HTTP/2 are disabled. Is alpn-boot on the boot class path?
2022-03-30 16:57:46.870+0000 [id=23139] INFO    hudson.model.AsyncAperiodicWork#lambda$doAperiodicRun$0: Started Update IdP Metadata from URL PeriodicWork
2022-03-30 16:57:46.871+0000 [id=23139] INFO    hudson.model.AsyncAperiodicWork#lambda$doAperiodicRun$0: Finished Update IdP Metadata from URL PeriodicWork. 1 ms
```
![image](https://user-images.githubusercontent.com/6487691/161019534-b3ffbbb0-6b59-4313-aa5f-51b6215c63f0.png)

**Comment by sxa** [comment]
Updated to LTS 2.332.3 and updating some of the plugins too.

**Comment by sxa** [comment]
Usage over the last 24 hours has been similar to the graph posted a couple of comments ago. System is now runnign on Ubuntu 20.04 with the latest LTS and all plugins that were being reported as security concerns have been updated.

We will continue to look at improving the reliability of the server and keeping it up to date, but the initial concerns relating to this issue have now been resolved. Backups were validated prior to the OS upgrade.

**Comment by sxa** [comment]
Remaining plugins upgraded last week.
I've brought up [a new agent](https://ci.adoptopenjdk.net/computer/C3jenkins/) (it's running on the current AWX server as it had lots of capacity) to offload jobs which were running on the `master` node to try and stop it running things on the server.
There have been some side effects of this that will need some attention: 
- [build-pipeline-generator does not work on the new node](https://github.com/adoptium/ci-jenkins-pipelines/issues/318)
- [refactor-openjdk-release-tool does not work on the new node](https://github.com/adoptium/ci-jenkins-pipelines/issues/319)

**Comment by sxa** [comment]
Todays plugin updates:
```
pipeline-stage-tags-metadata.jpi
email-ext.jpi
azure-vm-agents.jpi
pipeline-model-api.jpi
pipeline-model-extensions.jpi
github-oauth.jpi
pipeline-model-definition.jpi
ssh-slaves.jpi
Parameterized-Remote-Trigger.jpi
azure-vm-agents
Parameterized-Remote-Trigger
pipeline-model-extensions
github-oauth
pipeline-model-api
pipeline-model-definition
ssh-slaves
email-ext
pipeline-stage-tags-metadata
job-dsl.jpi
job-dsl
```

**Comment by sxa** [comment]
Ref: https://www.jenkins.io/blog/2022/06/28/require-java-11/

At the time of writing this comment we are on Jenkins 2.332.3

Jenkins 2.357 (June 28, 2022) and the next LTS in September will require Java 11. We area already running under java 11 after a previous upgrade.

Jenkins 2.355 (June 14, 2022) and Jenkins 2.346.1 LTS (released on June 22, 2022) also now formally support being run on java 17, so we should consider moving ours up to java 17 either at the same time as doing that upgrade or shortly afterwards, and look at how much that impacts CPU/RAM usage.

Plugins have already been prepared in [JENKINS-68446](https://issues.jenkins.io/browse/JENKINS-68446) and the recommendation is to use the Plugin Manager to upgrade all plugins before and after upgrading to Jenkins 2.357.

**Comment by sxa** [comment]
Adding this for reference - memory usage chart of jenkins before upgrading to latest LTS today (Currently on `2.332.3` on `Temurin-11.0.15+10`)
![image](https://user-images.githubusercontent.com/6487691/177288655-b0474be1-ccfa-4b9c-8fea-0d825923664a.png)

**Comment by sxa** [comment]
NOTE: Jenkins pipeline issue that required `-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true` is covered in https://github.com/adoptium/ci-jenkins-pipelines/issues/313

**Comment by sxa** [comment]
The other visible impact of this upgrade is more warnings in the log:
```
WARNING	h.p.g.i.GradleBuildScanInjection#inject: Error: HOME is not set
```
NOTE: Since we have a release due later this month we do not plan to perform any additional maintenance on the jenkins server for the rest of this month.

**Comment by sxa** [comment]
Upgraded today to 2.346.3 along with must plugin updates. Added issue for this one which we haven't upgraded for a while: #2720

**Comment by sxa** [comment]
Split out task to upgrade the agents so they are running on JDK11+ which will be required for the next LTS upgrade: https://github.com/adoptium/infrastructure/issues/2763

**Comment by sxa** [comment]
Other than the regular upgrades, the next steps here will be to document and remediate all access control on the server. We have various groups and individual ACLs for each job so need to define what is required, how to revalidate and decide how many of the groups can be shifted to the general temurin project committers list instead of AdoptOpenJDK* ones. I'm going to split this out into a separate issue: https://github.com/adoptium/infrastructure/issues/2814

**Comment by sxa** [comment]
The latest version of the Matrix Authorization plugin is flagging group names in jenkins as ambiguous as a user with the same name could gain elevated permissions. The fix (can be done with one click in the UI but we have it in workflows too) is to prefix the name with `GROUP:` (or `USER:` where appropriate) For example:
```
       <permission>hudson.model.Item.Build:AdoptOpenJDK*infrastructure</permission>
```
Becomes:
```
       <permission>GROUP:hudson.model.Item.Build:AdoptOpenJDK*infrastructure</permission>
```
We have a number of places in our pipelines repository (and maybe more) that will require this change.

**Comment by sxa** [comment]
Looking through some jobs that have custom permissions - can we get rid of any of these? There are a few `sxa` named jobs I'll get cleared up too...
- [grinder_sandbox_new](https://ci.adoptium.net/job/grinder_sandbox_new/) (April 2022)
- [wen-build-pipeline-generator](https://ci.adoptium.net/job/wen-build-pipeline-generator/) (Dec 2022)
- [wen-build-pipeline-generator2](https://ci.adoptium.net/job/wen-build-pipeline-generator2/) (Nov 2022)
- [Grinder_ParamsSeparate](https://ci.adoptium.net/job/Grinder_ParamsSeparate/) (Feb 2021)
- [Grinder_SM_Trigger](https://ci.adoptium.net/job/Grinder_SM_Trigger/) (April 2021)
- [tt](https://ci.adoptium.net/job/tt/jobConfigHistory/) (No runs, last edit Nov 2021 from Sophia)
- [nightly_counter](https://ci.adoptium.net/job/tt/jobConfigHistory/) (Scheduled regularly but failing - sxa job)
- [openjdk8_jcov](https://ci.adoptium.net/job/openjdk8_jcov/) (March 2021)
- wen-evaluation-pipeline_generator_jdk](https://ci.adoptium.net/job/wen-evaluation-pipeline_jobs_generator/) (Dec 2022)
- [wen-evaluation-pipeline_Jobs-generator_jdk](https://ci.adoptium.net/job/wen-evaluation-pipeline_jobs_generator_jdk/) (Dec 2022)
- [jdk8-alpine-linux-x64-hotspot](https://ci.adoptium.net/job/jdk8-alpine-linux-x64-hotspot) (Not in build-scripts - set up by George, run by Stephanie - presumably used for testing)
- [andrew_grinder](https://ci.adoptium.net/job/andrew_grinder/) (Nov 2022)
- [openjdk_release_tool](https://ci.adoptium.net/job/openjdk_release_tool/) (Not run since Sept 2018, Superceded by [refactor_](https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/) version
- [wen_evaluation-openjdk11-pipeline](https://ci.adoptium.net/job/wen_evaluation-openjdk11-pipeline/) (Jan 2023)
- Anything under [john](https://ci.adoptium.net/job/john/)

Also need an audit of stuff under [build-scripts/release](https://ci.adoptium.net/job/build-scripts/job/release/) to remove duplicates to avoid confusion e.g. `refactor_` and `standablone_` prefixed jobs

**Comment by sxa** [comment]
Will investigate https://plugins.jenkins.io/job-restrictions/ as a way of locking down where build jobs can be executed.

**Comment by sxa** [comment]
Most user-based permissions have now been removed outside the build scripts (which will still need work).
The remaining valid ones are for [jdk8-alpine-linux-x64-hotspot](https://ci.adoptium.net/job/jdk8-alpine-linux-x64-hotspot/) (calderest for debugging) and [create_release_notes](https://ci.adoptium.net/job/create_release_notes/) (for bethgriggs, who developed the tooling.

**Comment by sxa** [comment]
Note: [Jenkins LTS model](https://www.jenkins.io/download/lts/) is to have a version update every 12 weeks, so roughly every 3 months. Patch versions will come out every four weeks We should book a regular maintenance slot to ensure we keep up to date with those maintenance releases.

**Comment by sxa** [comment]
Jenkins now upgraded to the latest LTS version (2.387.1) and all plugins updated to latest other than `SAML` and `SSH Build Agents` which have warning messages associated with them so may require remedial action.

**Comment by sxa** [comment]
> Will investigate https://plugins.jenkins.io/job-restrictions/ as a way of locking down where build jobs can be executed.

This has now been installed alongside last week's jenkins upgrade.

**Comment by sxa** [comment]
Now all removed other than bethgriggs on the release notes job, and an explicit entry for anonymous on build-pipeline-generator.

**Comment by sxa** [comment]
@karianna Are you still planning to own looking at moving the jenkins server setup/config to configuration-as-code with ansible as per the [earlier comment](https://github.com/adoptium/infrastructure/issues/2108#issuecomment-815149261)?

**Comment by sxa** [comment]
@karianna I'm also going to suggest we schedule a maintenance window on the first Tuesday of each month to perform jenkins plugin updates and Jenkins LTS updates that are required. We currently have [quarterly listed in the infra readme](https://github.com/adoptium/infrastructure#maintenance-information) but I think that should be revised to be more frequent.

**Comment by karianna** [comment]
> @karianna Are you still planning to own / interesting in persuing looking at moving the jenkins server setup/config to configuration-as-code with ansible as per the [earlier comment](https://github.com/adoptium/infrastructure/issues/2108#issuecomment-815149261)?

I ungracefully remove myself from owning that - I'll never get to it I'm afraid.

**Comment by sxa** [comment]
Thinbackup plugin has been adjusted to do a full backup on the first of the month and incrementals for the rest of the days as per https://github.com/adoptium/infrastructure/issues/1295#issuecomment-1470571936

**Comment by sxa** [comment]
With a successful backup taken (`/home/jenkins/.jenkins/backups/FULL-2023-04-14_19-17`) I was able to restore to a new machine and start up the server successfully (`nodes` directory removed before restarting to avoid it conneting to the same slaves as the real server, and also removing the `<securityRealm class="org.jenkinsci.plugins.GithubSecurityRealm">` section from the config.xml (which prevents github logins)

**Comment by karianna** [comment]
Hmm,, annoying that we don't see the true underlying cause.  I wonder if we can test writing a large file from the O/S

**Comment by sxa** [comment]
> Hmm,, annoying that we don't see the true underlying cause.  I wonder if we can test writing a large file from the O/S

The (NFS IIRC) filesystem is noticeably slow so that can definitely be reproduced outside Jenkins. It's writing the individual files directly to the filesystem as opposed to a zip file so a lot of individual random wires to open lots of files which won't be helping

**Comment by sxa** [comment]
I'm going to close this now. Remaining action items that are explicitly planned can be done in the separate items mentioned elsewhere in this issue but we now have policies in place for keeping the server up to date.
