### ISSUE TITLE
Ansible request for platform AIX re: config setting sys0.maxuproc

### ISSUE THREAD

**Issue by aixtools** [adoptium/infrastructure#2111]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [x] Missing install
- [x] Bug in ansible playbook
- [ ] Request for new playbook addition

Details:
This is suppossed to be arranged in the playbooks already - but a review of the systems shows an inconsistent value.

This issue is to track and repair AIX ansible playbook for AIX so that it is stable.

**Comment by sxa** [comment]
What operations (build/tests) is this required for? Can you provide a description of the symptoms in the issue for historic reference please.

**Comment by aixtools** [comment]
As a picture - as not everyone maybe able to follow a slack URL:

![image](https://user-images.githubusercontent.com/10852597/114521175-75057a80-9c42-11eb-8b50-8b6850bf1b3b.png)

* imho: this is related to the way gmake generates sub-processes.
* Actually, not needed - as it is already in the playbooks - just not getting executed for some reason
```
aixtools@nim.bak:[/home/aixtools/openjdk-infrastructure]find . -name \*.sh | xargs grep chdev
./ansible/playbooks/scripts/AIX_filesystem_config.sh:   chdev -l sys0 -a maxuproc=512
```
THUS: this issue can be closed - because the setting is already there - but a review of the AIX playbooks and why this script is not running properly - needs examination.
