### ISSUE TITLE
Getting tl 2 sp 5 on our AIX 7.2 Machines

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2125]
ref https://adoptium.slack.com/archives/C53GHCXL4/p1618260028198800?thread_ts=1617783998.135400&cid=C53GHCXL4

Using this issue to keep track on upgrading the AIX 7.2 machines test-osuosl-aix72-ppc64-1 and -2 to TL 2 and SP 5 for the purpose of writing correct core dump files

**Comment by sxa** [comment]
If we're going to do an upgrade, let's start by only doing it on one of them for now so we can confirm that the SP upgrade is definitely what resolves this (as there's little point in upgrading both if it doesn't solve anything, also this may affect supported platform listings)

**Comment by aixtools** [comment]
Sounds good. I'll update ojdk03 - unless it is busy. Then I'll do ojdk04 (first).

And - as it is easier to upgrade a second time (SP06 is released - and the LAST SP for AIX 7.2 TL2) - I'll take it to SP05.

**Comment by aixtools** [comment]
Doing a bit of cleanup - seems there were some ifixes - should not be related to anything, but for the record - letting you know these go away.
```
# emgr -l

ID  STATE LABEL      INSTALL TIME      UPDATED BY ABSTRACT
=== ===== ========== ================= ========== ======================================
1    S    IJ06908s2a 07/05/18 12:28:54            Fix for rmsock security vulnerability
2    S    IJ05818s2a 07/05/18 12:29:07            a potential security issue exists
3    S    IJ02920s0a 07/05/18 12:29:44            IJ02920 for AIX 7.2 TL2 SP00
```

**Comment by aixtools** [comment]
Update completed - BUT - there are little things (I hope little) such as messages:
```
Can't locate Switch.pm in @INC (you may need to install the Switch module) (@INC contains: /opt/freemarker/lib/perl5 /opt/freeware/lib64/perl5/5.30/site_perl/ /opt/freeware/share/perl5/site_perl/ /opt/freeware/lib64/perl5/5.30/vendor_perl
/ /opt/freeware/share/perl5/vendor_perl/ /opt/freeware/lib64/perl5/5.30/ /opt/freeware/share/perl5/5.30/) at /usr/ecc/bin/dial_manager line 22.
BEGIN failed--compilation aborted at /usr/ecc/bin/dial_manager line 22.
Can't locate Switch.pm in @INC (you may need to install the Switch module) (@INC contains: /opt/freemarker/lib/perl5 /opt/freeware/lib64/perl5/5.30/site_perl/ /opt/freeware/share/perl5/site_perl/ /opt/freeware/lib64/perl5/5.30/vendor_perl
/ /opt/freeware/share/perl5/vendor_perl/ /opt/freeware/lib64/perl5/5.30/ /opt/freeware/share/perl5/5.30/) at /usr/ecc/bin/dial_manager line 22.
BEGIN failed--compilation aborted at /usr/ecc/bin/dial_manager line 22.
Can't locate Switch.pm in @INC (you may need to install the Switch module) (@INC contains: /opt/freemarker/lib/perl5 /opt/freeware/lib64/perl5/5.30/site_perl/ /opt/freeware/share/perl5/site_perl/ /opt/freeware/lib64/perl5/5.30/vendor_perl
/ /opt/freeware/share/perl5/vendor_perl/ /opt/freeware/lib64/perl5/5.30/ /opt/freeware/share/perl5/5.30/) at /usr/ecc/bin/dial_manager line 22.
BEGIN failed--compilation aborted at /usr/ecc/bin/dial_manager line 22.

```
* But system is updated - and reboot started
```
# oslevel -s
7200-02-05-1938
# hostname
p8-aix2-ojdk04
```

**Comment by Haroon-Khel** [comment]
Update: only 1 test from https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk11_j9_extended.functional_ppc64_aix/125/tapResults/ fails on test-osuosl-aix72-ppc64-2. That is the `cmdLineTest_J9test_console_0` test. This test passes when run on the machine directly, as the jenkins user. Fails when run in a grinder or as part of the extended functional job

Grinder parameters https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=nightly&TARGET=cmdLineTest_J9test_console_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&TEST_PARALLELIZATION_PARAMS=&PLATFORM=ppc64_aix&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&LABEL=test-osuosl-aix72-ppc64-2&TEST_OPTIONS_PARAMS=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&NON_AQA_TEST_REPOS_HELP_TEXT=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&TEST_REPO_PARAMS=&TEST_SELECTION_PARAMS=&TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&JDK_SELECTION_PARAMS=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=11&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=&PLATFORM_AND_MACHINE_HELP_TEXT=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&UPSTREAM_JOB_NAME=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&POST_RUN_PARAMS_HELP_TEXT=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_SELECTION_PARAMS_HELP_TEXT=&JDK_IMPL=openj9&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&TKG_SHA=&TEST_SELECTION_PARAMS_HELP_TEXT=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=functional%2FcmdLineTests&UPSTREAM_JOB_NUMBER=&TEST_REPO_PARAMS_HELP_TEXT=&POST_RUN_PARAMS=&TIME_LIMIT=10&TEST_OPTIONS_PARAMS_HELP_TEXT=&JVM_OPTIONS=&PARALLEL=None

To rerun on the machine directly, follow the steps here, https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally#run-the-sanity-tests-in-the-functionaljlm_tests-directory-on-jdk10_x86-64_linux_openj9-sdk, but replace the first line with a jdk 11 openj9 AIX jdk, and replace the final 3 steps with 

```
export BUILD_LIST=functional/cmdLineTests
gmake compile
gmake _cmdLineTest_J9test_console_0
```

**Comment by Haroon-Khel** [comment]
The test pass in the latest grinder run. https://ci.adoptopenjdk.net/job/Grinder/115/console. I changed nothing on the machine. The only differnece between this grinder and the ones that [failed yesterday](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/100/parameters/) is that the BUILD_LIST variable is `functional` and not `functional/cmdlineTESTS`. 

Im running another one with the BUILD_LIST parameter as `functional/cmdLineTests` https://ci.adoptopenjdk.net/job/Grinder/116/console

**Comment by Haroon-Khel** [comment]
116 failed. Both failed with

```
===============================================
Running test cmdLineTest_J9test_console_0 ...
===============================================
cmdLineTest_J9test_console_0 Start Time: Fri Apr 16 06:47:22 2021 Epoch Time (ms): 1618573642141
variation: NoOptions
JVM_OPTIONS:  
Error: Unable to access jarfile /home/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_tester/cmdlinetester.jar
cmdLineTest_J9test_console_0_FAILED
```

I assume then that `BUILD_LIST=functional` is required to generate the required jars to run the test, and `functional/cmdLineTests` is too narrow a subset (even though `functional/cmdLineTests` is sufficient when running on the machine directly)

**Comment by Haroon-Khel** [comment]
https://ci.adoptopenjdk.net/job/Grinder/119/console passed, BUILD_LIST was `functional`. Rerunning this on https://ci.adoptopenjdk.net/job/Grinder/120/. If this passes, im going to run another extended functional test job on the machine. It may be that the first failure was intermittent

**Comment by sxa** [comment]
[extended.functional run](https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.functional_ppc64_aix/127/)

**Comment by aixtools** [comment]
And - reinstall the second system - or more time needed?

**Comment by sxa** [comment]
> And - reinstall the first system - update the second system - or more time needed?

We don't do anything during a release week

**Comment by sxa** [comment]
[OpenJ9 support 7.2TL3 ](https://www.eclipse.org/openj9/docs/openj9_support/) so if we're going to upgrade I suggest we have one machine at that level as a minimum, so when we update the second one I suggest we go to that level and verify that the problems we've seen on TL2 are resolved.

**Comment by aixtools** [comment]
Roger. Next week I suppose.

FYI - Monday next week (27 April) is a holiday - so I would not start before the 28th.

**Comment by aixtools** [comment]
Ping me when you want something done - enjoy your holiday though! ie, no rush.

**Comment by Haroon-Khel** [comment]
Are well still proceeding with upgrading test-osuosl-aix72-ppc64-**2**?

**Comment by sxa** [comment]
Summary:
- [aix72-ppc64-2](https://ci.adoptopenjdk.net/computer/test-osuosl-aix72-ppc64-2/) is now on 7.2TL02SP05
- [aix72-ppc64-2](https://ci.adoptopenjdk.net/computer/test-osuosl-aix72-ppc64-2/) is still on 7.2TL02SP05 and we should check with some of the IBM POWER team whether the core dump problems we were experiencing on that SP level are fixable.

FYI @sej-jackson may be one that you can look into or help us with.

**Comment by sxa** [comment]
After a reinstall of `-1` this week it is now also at TL05 - closing
