### ISSUE TITLE
Ensure AIX repos are enabled before running the yum role

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2126]
If the repos are not enabled before running the `yum update` task, ansible will hit this error

```
fatal: [test-ibm-aix71-ppc64-1]: FAILED! => {"changed": false, "msg": "There are no enabled repos.\n
Run \"yum repolist all\" to see the repos you have.\n 
You can enable repos with yum-config-manager --enable <repo>\n"
, "rc": 1, "results": []}
```

The repos we use are 
```
AIX_Toolbox
AIX_Toolbox_71
AIX_Toolbox_noarch
```

Disabled repos listed in /opt/freeware/etc/yum/yum.conf will have `enabled=0` listed under each repo entry. Its just a case of having an ansible task which ensures that `enabled=1` is present, or something equivalent, before running the `yum update` task

**Comment by Haroon-Khel** [comment]
Using the ansible [yum_repository module ](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html) is a bit tricky since it expects repos to be in their own `.repo` file, and not in `/opt/freeware/etc/yum/yum.conf` as they are on our AIX machines

**Comment by sxa** [comment]
We need to try and get some of the backlog of AIX issues closed - let's aim to resolve this during July.

**Comment by sxa** [comment]
Is there a reason we ended up with a machine in that state? Odd to have to correct for it since I'd normally expect it to always be enabled once it's installed.

**Comment by Haroon-Khel** [comment]
If I recall correctly, the repos on the two ibm machines were disabled out of the box

**Comment by Haroon-Khel** [comment]
Closing as https://github.com/adoptium/infrastructure/pull/2287 is merged
