### ISSUE TITLE
Auto update all machines with latest Playbooks

### ISSUE THREAD

**Issue by bblondin** [adoptium/infrastructure#214]
By way of AWX (Ansible Tower) configure a weekly schedule to deploy the latest Ansible playbooks to all systems.
- This will ensure there isn't any drift between how the systems are configured and the latest changes to the playbooks are applied.

* This is easily setup using AWX's scheduler, however we need away to ensure they are not currently in use by Jenkins. A method to temporarily disable the system(s) (take off-line) run the playbook then re-enable the system(s).

**Comment by geraintwjones** [comment]
It's possible via the Jenkins web interface to mark a node as temporarily offline. Maybe that's what we need to do, and maybe there's an API that would allow us to do that from Ansible. I'll see what I can find. We'd still need to make sure the node was not busy when we did that though.

**Comment by geraintwjones** [comment]
Issue #185 discusses the challenges faced when running a Jenkins backup. That discusses putting Jenkins into "quiet" mode before the backup is made, but tat there's a known bug where doing that can cause job to freeze. If that gets fixed, then maybe the same approach (or even the same window) could be used to update all machines with the latest playbooks. However, both the backup and the machine update needs to figure out what to do with busy nodes. Wait for them all to finish?

**Comment by AdamBrousseau** [comment]
Other option would be to run the playbook without considering if its busy with a job. Once a machine has been configured, a weekly update ideally wouldn't change anything unless something new is added. The playbooks shouldn't be reinstalling the same thing over and over.

**Comment by bblondin** [comment]
Scheduling the playbooks to update all systems from within AWX is simple enough to do.
Utilizing the ``` limit ``` feature would allow us to split or stager it to run on a per vendor/provider basics, limiting our exposer in the event of failure (miss configuration) caused by an erroneous playbook.

We need to take into consideration performance jobs, jobs that are timed, etc. Although in most cases very little to nothing will change on the system and the additional low will be minimal, it doesn’t sound like a great idea to allow changes to occur while a job is running. 

Trigger it from Jenkins seems like a better way to go about it.

**Comment by AdamBrousseau** [comment]
If you were to have a Jenkins job that "occupied" a machine, kicked off the playbook, for only that machine, and somehow waited around till the playbook was finished, it would work. I'm not sure exactly how you would do it. I was under the impression that kicking off a playbook for a single machine wasn't easy, maybe it is now with the inventory file?

**Comment by geraintwjones** [comment]
You'd need to ensure that all machines eventually ran the playbook.

**Comment by bblondin** [comment]
I want to look into a method to do this via Jenkins.
The [Ansible Tower Plugin](https://wiki.jenkins.io/display/JENKINS/Ansible+Tower+Plugin) looks promising 

This solution would ensure there aren't any jobs running the systems at the same time the playbooks are running.

**Comment by geraintwjones** [comment]
On AWX...
1. Create a userid that you want Jenkins to use when it sends jobs over.
1. Allow this user to be able to use/execute playbooks/inventories/templates.

On Jenkins...
1. Create a credential for the userid you created in AWX.
1. Install the Ansible Tower plugin.
1. Set up the Ansible Tower settings in `Configure System`.
1. Create a freestyle project (job) for running the playbooks (I'll refer to it as `awx-job` here) that has an Ansible Tower build step.
1. In that build step, fill in the details of the AWX server...
   1. Set `Tower server` to the one you defined in `Configure System` (pick it from the dropdown).
   1. Set `Template type` to `job`  (pick it from the dropdown).
   1. Set `Template ID` to the name of the playbook you want to run.
   1. Set `Limit` to `$NODE_NAME`
   1. Set `Inventory` to the name of the inventory on AWX.
   1. Set `Credential` to the credential defined on AWX.
1. Create a pipeline project (job) for orchestrating the running of the playbook across all slaves that are online. Use the following pipeline script...
```
def getSlaves() {
    def slaves = []
    hudson.model.Hudson.instance.slaves.each {
        computer = it.getComputer()
        if ( computer.isOnline() ) {
            println it.name + " is online - adding job"
            slaves << it.name
        }
        else {
            println it.name + " is offline - not adding job"
        }
    }
    return slaves
}

def jobs = [:]

getSlaves().each {
    def slave = it
    jobs[slave] = {
        node(slave) {
            build '<name-of-the-playbook-project>' // Replace this with the name of that job
        }
    }
}

parallel jobs
```

**Comment by AdamBrousseau** [comment]
Happy to help out here. I'll PM you

**Comment by karianna** [comment]
@geraintwjones and @AdamBrousseau - did this get completed?

**Comment by sxa555** [comment]
Related #695

**Comment by sxa555** [comment]
Related #695

**Comment by sxa** [comment]
I'm going to close this and allow the work to progress under 695
