### ISSUE TITLE
MBCS_Tests_annotation_Ja_JP_aix_0 fails on all AIX machines for jdk 8 hotspot

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2153]
ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2149

I thought id create a separate issue since https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2149 seems to only affect test-ibm-aix71-ppc64-1 and -2.

`MBCS_Tests_annotation_Ja_JP_aix_0` appears to fail on both IBM and OSUOSL boxes, with the following error log

```
[2021-04-20T22:17:20.884Z] Running test MBCS_Tests_annotation_Ja_JP_aix_0 ...
[2021-04-20T22:17:20.884Z] ===============================================
[2021-04-20T22:17:20.884Z] MBCS_Tests_annotation_Ja_JP_aix_0 Start Time: Tue Apr 20 18:17:20 2021 Epoch Time (ms): 1618957040143
[2021-04-20T22:17:20.884Z] Nothing to be done for setup.
[2021-04-20T22:17:20.884Z] variation: NoOptions
[2021-04-20T22:17:20.884Z] JVM_OPTIONS:  
[2021-04-20T22:17:20.884Z] { itercnt=1; \
[2021-04-20T22:17:20.884Z] mkdir -p "/home/jenkins/workspace/Test_openjdk8_hs_special.functional_ppc64_aix/openjdk-tests/TKG/../TKG/output_16189570312245/MBCS_Tests_annotation_Ja_JP_aix_0"; \
[2021-04-20T22:17:20.884Z] cd "/home/jenkins/workspace/Test_openjdk8_hs_special.functional_ppc64_aix/openjdk-tests/TKG/../TKG/output_16189570312245/MBCS_Tests_annotation_Ja_JP_aix_0"; \
[2021-04-20T22:17:20.884Z] LANG=Ja_JP ksh /home/jenkins/workspace/Test_openjdk8_hs_special.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/annotation/test.sh > output.txt 2>error.txt; \
[2021-04-20T22:17:20.884Z] if [ $? -eq 0 ] ; then echo ""; echo "MBCS_Tests_annotation_Ja_JP_aix_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk8_hs_special.functional_ppc64_aix/openjdk-tests/TKG/..; rm -f -r "/home/jenkins/workspace/Test_openjdk8_hs_special.functional_ppc64_aix/openjdk-tests/TKG/../TKG/output_16189570312245/MBCS_Tests_annotation_Ja_JP_aix_0"; else echo ""; echo "MBCS_Tests_annotation_Ja_JP_aix_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk8_hs_special.functional_ppc64_aix/openjdk-tests/TKG/../TKG/output_16189570312245/TestTargetResult";
[2021-04-20T22:17:34.306Z] 
[2021-04-20T22:17:34.306Z] MBCS_Tests_annotation_Ja_JP_aix_0_FAILED
[2021-04-20T22:17:34.306Z] 
[2021-04-20T22:17:34.306Z] Nothing to be done for teardown.
[2021-04-20T22:17:34.306Z] MBCS_Tests_annotation_Ja_JP_aix_0 Finish Time: Tue Apr 20 18:17:33 2021 Epoch Time (ms): 1618957053916
```

The test failure was noticed in https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_hs_special.functional_ppc64_aix/28/

Reproducible in a grinder here

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/236/console

I have only tested this so far with jdk 8 hotspot

**Comment by Haroon-Khel** [comment]
According to the log, 
```
ksh /home/jenkins/workspace/Test_openjdk8_hs_special.functional_ppc64_aix/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/annotation/test.sh > output.txt 2>error.txt
```
the output should be saved into two files, `output.txt` and `error.txt`

Upon inspection after a failing test and with the Keep workspace parameter enabled, `error.txt` appeared to be empty, while `output.txt` contained

```
creating source file...
compiling...
execute javap
execute javac with processor option with RELEASE_6
execute javac with processor option with RELEASE_7
execute javac with processor option with RELEASE_8
```

**Comment by Haroon-Khel** [comment]
The code for the test can be found here https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/functional/MBCS_Tests/annotation/test.sh

**Comment by Haroon-Khel** [comment]
>I have only tested this so far with jdk 8 hotspot

Rerunning the test using jdk11 hotspot
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/282/console

**Comment by Haroon-Khel** [comment]
The above grinder failed. Re ran with openj9
jdk 8 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/283/console
jdk 11 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/284/console

**Comment by Haroon-Khel** [comment]
Related issue https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/704

**Comment by sxa** [comment]
@sej-jackson FYI (as discussed earlier). `locale -a` on the machine does show a few JP entries:
```
JA_JP.UTF-8
JA_JP
Ja_JP.IBM-932
Ja_JP.IBM-943
Ja_JP
ja_JP.IBM-eucJP
ja_JP.UTF-8
ja_JP
```

**Comment by Haroon-Khel** [comment]
Passes on test-ibm-2 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/298/console

**Comment by Haroon-Khel** [comment]
An update:

After running a series of grinders, I can confirm that `MBCS_Tests_annotation_Ja_JP_aix_0` fails on jdk8 hotspot for all aix machines except for test-osuosl-aix72-ppc64-2. 

This isnt a problem for jdk 8 openj9 or jdk11 openj9 and hotspot, however on these grinders the test passed but the grinder still reported a failure, for example

openj9 jdk 8 on test-ibm-aix71-ppc64-1 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/327/console 

hotspot jdk11 on test-osuosl-aix71-ppc64-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/344/console

openj9 jdk 11 on build-osuosl-aix71-ppc64-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/361/console

ref https://github.com/AdoptOpenJDK/openjdk-tests/issues/2225#issuecomment-825939405

**Comment by Haroon-Khel** [comment]
Speaking to @toshiona, he reports that this test failure isnt due to the environment of the machine, but with the jdk 8 hotspot. He also referenced this java bug https://bugs.openjdk.java.net/browse/JDK-8202329. He mentioned that a Ja_JP locale may have trouble handing displaying the Yen sign, so this may be the issue that we are seeing. He also provided a some code for a simple test case

```
import java.io.*;
class CheckName {
    public static void main(String[] args) {
        if (args.length == 0) return;
        char ch;
        StringBuffer valid = new StringBuffer();
        String target = args[0];
        
        for(int i = 0; i < target.length(); i++) {
            ch = target.charAt(i);
            if (valid.length() == 0) {
                if (Character.isJavaIdentifierStart(ch)) valid.append(ch);
            } else {
                if (Character.isJavaIdentifierPart(ch)) valid.append(ch);
            }
        }
        System.out.println(valid.toString());
    }
}
```
Then on the command line

```
$ export LANG=Ja_JP
```
The backslash character reads in a Ja_JP locale as a Yen sign
Expected result
```
$ java CheckName "ab\\cd"
abcd
```

Result with jdk 8 hotspot
```
# OpenJDK 8 with Hotspot
$ java CheckName "ab\\cd"
ab\cd
```

**Comment by Haroon-Khel** [comment]
Ive confirmed the above test case on build-osuosl-aix71-ppc64-1 (a failing machine). The failing machine shows the failing output while when using hotspot jdk8 and shows the expected result with openj9 jdk8

**Comment by sxa** [comment]
So this is potentially an upstream issue. If so we should probably exclude the test from the suites ...

**Comment by aixtools** [comment]
Any update on this (@Haroon-Khel )

**Comment by aixtools** [comment]
I recommend closing this: https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_hs_special.functional_ppc64_aix/ shows all as passed (for several weeks). Actually, I cannot even find an example of it failing (anymore).

The latest: 3 days ago: https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_hs_special.functional_ppc64_aix/52/

```
14:01:05  TEST TARGETS SUMMARY
14:01:05  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
14:01:05  PASSED test targets:
14:01:05  	MBCS_Tests_Compiler_JA_JP_aix_0
14:01:05  	MBCS_Tests_Compiler_ko_KR_aix_0
14:01:05  	MBCS_Tests_Compiler_KO_KR_aix_0
14:01:05  	MBCS_Tests_Compiler_ZH_CN_aix_0
14:01:05  	MBCS_Tests_Compiler_ZH_TW_aix_0
14:01:05  	MBCS_Tests_IDN_JA_JP_aix_0
14:01:05  	MBCS_Tests_IDN_KO_KR_aix_0
14:01:05  	MBCS_Tests_IDN_ZH_CN_aix_0
14:01:05  	MBCS_Tests_IDN_ZH_TW_aix_0
14:01:05  	MBCS_Tests_annotation_JA_JP_aix_0
14:01:05  	MBCS_Tests_annotation_ko_KR_aix_0
14:01:05  	MBCS_Tests_annotation_KO_KR_aix_0
14:01:05  	MBCS_Tests_annotation_Zh_CN_aix_0
14:01:05  	MBCS_Tests_annotation_ZH_CN_aix_0
14:01:05  	MBCS_Tests_annotation_ZH_TW_aix_0
...
```

**Comment by sxa** [comment]
For completeness I'm going to re-run this on the `build-1` machine that Haroon said it failed on earlier, however since that machine does not have `ci.role.test` on it I will probably close this regardless once it's done:

https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_hs_special.functional_ppc64_aix/54/

**Comment by sxa** [comment]
Link in the previous comment worked, therefore this has been resolved one way or another :-) Closing.

**Comment by toshiona** [comment]
FYI:
https://github.com/adoptium/aqa-tests/pull/2767
This change skipped the test for Java8.

**Comment by sxa** [comment]
> FYI: [adoptium/aqa-tests#2767](https://github.com/adoptium/aqa-tests/pull/2767) This change skipped the test for Java8.

That explains it :-)

**Comment by aixtools** [comment]
Surprise, surprise.
