### ISSUE TITLE
MBCS_Tests_datetime related formatting test failures on IBM Cloud - RHEL only

### ISSUE THREAD

**Issue by karianna** [adoptium/infrastructure#2163]
[**Test_openjdk16_hs_special.functional_x86-64_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_special.functional_x86-64_linux/14/) 
MBCS_Tests_datetime_0 => [deep history 4/5 passed](https://trss.adoptopenjdk.net/deepHistory?testId=608083b551eeb61d64296747) | [possible issues](https://trss.adoptopenjdk.net/possibleIssues?buildId=6080822751eeb61d64295ae7&buildName=Test_openjdk16_hs_special.functional_x86-64_linux&testId=608083b551eeb61d64296747&testName=MBCS_Tests_datetime_0) - **OK to Release test only fails on test-ibmcloud-rhel6-x64-1 - test or host needs updating - expected:<2021-04-21T17:48:12Z> but was:<2021-04-21T17:48:12.001Z>** 

MBCS_Tests_datetime_formatter_0 => [deep history 4/5 passed](https://trss.adoptopenjdk.net/deepHistory?testId=608083b551eeb61d64296748) | [possible issues](https://trss.adoptopenjdk.net/possibleIssues?buildId=6080822751eeb61d64295ae7&buildName=Test_openjdk16_hs_special.functional_x86-64_linux&testId=608083b551eeb61d64296748&testName=MBCS_Tests_datetime_formatter_0) - **OK to Release test only fails on test-ibmcloud-rhel6-x64-1 - test or host needs updating - expected:<2021-04-21T17:48:12Z> but was:<2021-04-21T17:48:12.001Z>**

**Comment by sxa** [comment]
Hmmm it would be good to be 100% certain that this doesn't occur on RHEL7/RHEL8 so we'd need to run some Grinders on that. We should also bear in mind that RHEL6 is now out of support for most people, so a valid option may be to exclude it on that system if possible (or remove the machine, but since we build against that version it would seem not ideal to not test on it)

**Comment by sxa** [comment]
If we get the info on being able to recreate this, then it can probably be verified in a CentOS6 docker container and see if any other workaround is possible, therefore adding this as a `good first issue`

**Comment by Haroon-Khel** [comment]
Rerunning with jdk17 5 iterations
https://ci.adoptium.net/job/Grinder/8475/console
