### ISSUE TITLE
SSL Certificate for new subdomain

### ISSUE THREAD

**Issue by LongyuZhang** [adoptium/infrastructure#2166]
Currently I am working on adding a new web server on [Adopt TRSS machine](ec2-54-78-186-5.eu-west-1.compute.amazonaws.com). 
The TRSS url is https://trss.adoptopenjdk.net/, and the new url I plan to add can be either https://trssml.adoptopenjdk.net or https://ml.trss.adoptopenjdk.net. Two things I need help with are:
- link the new url to [Adopt TRSS machine](ec2-54-78-186-5.eu-west-1.compute.amazonaws.com), which deploys both the TRSS server and the new server.
- SSL certificate for this new subdomain.

Thanks a lot for the help!
Related Issue: https://github.com/adoptium/aqa-test-tools/issues/355

**Comment by smlambert** [comment]
@sxa - can you give us advice on how to proceed on this one?  It relates to the Deep AQAtik / Outreachy project that starts next week?

**Comment by sxa** [comment]
@smlambert Chase me up again next week on this - hopefully one of us will remember - it may need input/approval from Eclipse now.

**Comment by sxa** [comment]
Have allowed ports 8080 and 8443 through to the machine - current discussion on DNS/SSL Certs are with the PMC

**Comment by sxa** [comment]
Based on latest PMC call we're going to get entries for trss.adoptium.net and trssml.adoptium.net created and pointing to the existing server.

**Comment by LongyuZhang** [comment]
@sxa Thanks for the update!

**Comment by sxa** [comment]
`trss.adoptium.net` and `trssml.adoptium.net` are now in place and pointing to the server. We'll need to get the SSL certificates setup (probably with letsencrypt) to finalise this. With this change (not fronted by Cloudflare) it may now be feasible to do this on a single port, but I'll let you decide whether you'd prefer to continue on a separate port or not before proceeding :-)

**Comment by LongyuZhang** [comment]
@sxa Thanks for getting the urls working. Could we use two ports, with port 443 for trss, and port 8443 for trssml? Thanks!

**Comment by sxa** [comment]
@gdams I believe you offered to deploy the LE SSL certificates onto this system, so I'll leave the follow-on action here with you.

**Comment by gdams** [comment]
let's encrypt has been setup to run on trss.adoptium.net

CRON to automatically renew: `/etc/cron.daily/letsencrypt-renew`

I'll now proceed with a Cloudflare redirect to send all trss.adoptium.net/* traffic to trss.adoptium.net

**Comment by gdams** [comment]
Redirect is complete. @smlambert can you please ensure that the adoptopenjdk is removed from TRSS now that it is being hosted on an adoptium domain?

I'll begin work on the trssml.adoptium.net project

**Comment by gdams** [comment]
I've also deployed a let's encrypt cert to trssml.adoptium.net. The CRON file from above will renew both certs.

I do only see `TRSS ML model deployed!` though so I'm not sure if anything else needs to be done?

**Comment by smlambert** [comment]
re: https://github.com/adoptium/infrastructure/issues/2166#issuecomment-859428131 that is exactly what we expect to see at that link at this time.  The ML deployment work is being done under one of our Outreachy projects (Deep AQAtik) this summer.  

As mentioned in the PMC, ideally the ML deployment server will get its own machine at some point (and not be colocated on same machine as trss (achieving more stability for trss and more resources for trssml).  But shared machine can work for now.

**Comment by LongyuZhang** [comment]
@gdams @sxa Both trss and trssml work successfully now! Thanks a lot for all the help!
