### ISSUE TITLE
test-azure-win2016-x64-1: java/io/File/TimeZoneLastModified.java fails due to java.io.IOException: Access is denied

### ISSUE THREAD

**Issue by lumpfish** [adoptium/infrastructure#2181]
Test fails on: test-azure-win2016-x64-1: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/634/console
Test passes on test-ibmcloud-win2012r2-x64-1: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/633/console
Test passes on test-azure-win2019-x64-1: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/633/console

As far as I can tell from the test case source (https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/master/test/jdk/java/io/File/TimeZoneLastModified.java), it is trying to create a file `test-timezone.txt` in I assume current directory.

The test can be rerun on the same machine with:
https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=nightly&amp;TARGET=jdk_custom&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;TEST_PARALLELIZATION_PARAMS=&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=true&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=test-azure-win2016-x64-1&amp;TEST_OPTIONS_PARAMS=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;NON_AQA_TEST_REPOS_HELP_TEXT=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;NON_AQA_TEST_REPOS=&amp;ARTIFACTORY_SERVER=&amp;TEST_REPO_PARAMS=&amp;TEST_SELECTION_PARAMS=&amp;TEST_PARALLELIZATION_PARAMS_HELP_TEXT=&amp;JDK_SELECTION_PARAMS=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=11&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;PLATFORM_AND_MACHINE_HELP_TEXT=&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;PLATFORM_AND_MACHINE=&amp;CUSTOM_TARGET=test%2Fjdk%2Fjava%2Fio%2FFile%2FTimeZoneLastModified.java&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;POST_RUN_PARAMS_HELP_TEXT=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_SELECTION_PARAMS_HELP_TEXT=&amp;JDK_IMPL=openj9&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;TKG_SHA=&amp;TEST_SELECTION_PARAMS_HELP_TEXT=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=&amp;TEST_REPO_PARAMS_HELP_TEXT=&amp;POST_RUN_PARAMS=&amp;TIME_LIMIT=10&amp;TEST_OPTIONS_PARAMS_HELP_TEXT=&amp;JVM_OPTIONS=&amp;PARALLEL=None

**Comment by sxa** [comment]
Rebooted the machine to resolve another issue and it looks like this one now passes ... https://ci.adoptopenjdk.net/job/Grinder/643/

**Comment by sxa** [comment]
Needs a retest - bumping to June so we can clear it up one way or another.

**Comment by Haroon-Khel** [comment]
Rerunning https://ci.adoptium.net/job/Grinder/7122/console

**Comment by Haroon-Khel** [comment]
Passed 5/5 times https://ci.adoptium.net/job/Grinder/7122/testReport/java_io_File_TimeZoneLastModified/java/
