### ISSUE TITLE
System unavailable: infra-ibmcloud-vagrant-x64-*

### ISSUE THREAD

**Issue by Willsparker** [adoptium/infrastructure#2182]
- Link to any log file showing the problem:

Any log from here: https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1170/

- Please describe the issue:
The machine is out of disk space. It's not immediately obvious what's caused this. Judging from when some other [VPC runs](https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1169/) hung, it seemed to happen around 19:50-20:00, where I personally wasn't doing anything on the machine, but I'll clear it up and comment what I removed.

**Comment by Willsparker** [comment]
- Removed a stray qemu image, and some old infrastructure directories in the Root user home directory.
- Removed an awful lot of old `VagrantPlaybookCheck@<Number>` directories from the workspace, in the `vagrant<number>` user workspace directories.
- Removed the FreeBSD Vagrant box from wherever I found it, as VPC doesn't support it anymore.
- Removed the `qpc1` (and `qpc1@2`) directories from workspaces, if they haven't be modified/used for awhile (i.e. Since November).
- For the sake of easily clearing up, I've removed all of the QEMUPlaybookCheck directories for each user's workspace, as this should remove any leftover or old directories from testing other branches.
- Removed some unnecessary QEMU images from my user directory.

After all of that, There's 200GB free on the machine. Though that leaves a lot of space unaccounted for.

In `/`, running `du -h | sort -h -r | head -25` has shown that a huge amount of space is being taken up by leftover (Windows) Virtualbox VMs, that apparently weren't removed as part of VPC. Given that there's no VPC jobs currently running, I'm going to just remove all of these, Vagrant creates new ones whenever new VMs are bought online.

And with that 575gb is free!

**Comment by sxa** [comment]
Thanks for the comprehensive write up. Can you summarise the specific actions you took to make it clear for people in the future e.g. for

> Given that there's no VPC jobs currently running, I'm going to just remove all of these

Was that deleting the directories from under `VirtualBox VMs` in each of the `vagrant` users' home directories?

**Comment by Willsparker** [comment]
Yep - so for each user, there's a `VirtualBox VMs` directory in their home directory. Within this, will be directories corresponding to each VM currently on the system. i.e.
```
will@will-XPS-13-9360:~/VirtualBox VMs$ ls
ansible_adoptopenjdkC6_1620718855647_98564
ansible_adoptopenjdkW2012_1620720289767_21812
```
It's as easy as running `rm -r` on whichever one directory needs to be removed :-)

**Comment by Willsparker** [comment]
@sxa Happy for this to be closed..?

**Comment by sxa** [comment]
> @sxa Happy for this to be closed..?

Yes since we have it documented here. Although I'm now wondering if a "troubleshooting" section in the pbTestScripts README.md world be useful ...

**Comment by Willsparker** [comment]
Not a bad idea, considering it breaks so much :joy: ... I'll look into it!
