### ISSUE TITLE
New Machine requirement: Fedora 34 for test

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2183]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Linux
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): x64/aarch64/ppc64le
- Provider (leave blank if it does not matter):
- Desired usage: Test
- Any unusual specification/setup required: Inclusion into Dockerstatic (We could probably *replace* Fedora 33 with 34 for new deployments)
- How many of them are required: 1 for now

Please explain what this machine is needed for: Testing on the new version of the OS.

**Comment by sxa** [comment]
Needs an equivalent of the [Fedora 33 Dockerfile ](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f33) created and tested and the appopriate changes made to the code that creates them. We could probably replace f33 with f34 for future setups in the [role's main.yml](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml)

**Comment by sxa** [comment]
This probably needs to be Fedora 35 now ...

**Comment by zdtsw** [comment]
Made a commit which does for fedora 34 and 35 both (not sure if 35 is needed)

**Comment by zdtsw** [comment]
commit #2521 has been merged, ticket can be closed

**Comment by Haroon-Khel** [comment]
I deployed https://ci.adoptopenjdk.net/computer/test-docker-fedora34-x64-1/ this morning thanks to https://github.com/adoptium/infrastructure/pull/2521. This can be closed

**Comment by Haroon-Khel** [comment]
> This probably needs to be Fedora 35 now ...
I think we've had https://ci.adoptopenjdk.net/computer/test-docker-fedora35-x64-1/ for sometime now
