### ISSUE TITLE
New Machine requirement: CentOS stream for test

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2184]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Linux
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): x64/aarch64/ppc64le
- Provider (leave blank if it does not matter):
- Desired usage: Test
- Any unusual specification/setup required: DockerStatic systems
- How many of them are required: One for each `dockerhost` system we have

Please explain what this machine is needed for: Testing on the CentOS stream release since this is the primary CentOS head stream now.

**Comment by trytop** [comment]
hello world

**Comment by sxa** [comment]
I would imagine there's a [CentOS stream](https://www.centos.org/centos-stream/) docker container on dockerhub somewhere so we should try to create a version of the [cent8 dockerfile](https://github.com/adoptium/infrastructure/tree/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles) in the DockerStatic role

**Comment by sxa** [comment]
Superceded by:
- https://github.com/adoptium/infrastructure/issues/2487
- https://github.com/adoptium/infrastructure/issues/2478
Therefore closing.
