### ISSUE TITLE
Functional ID and token needed for TRSS to be able to retrieve build results

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2195]
Now that the build pipelines are restricted access, TRSS can no longer anonymously query the Jenkins server to report on build results.  

In order to achieve this, we'll need to set up a functional ID for TRSS to have access to the Jenkins server, and set up a token that will be used by the trss instance (currently at: https://trss.adoptopenjdk.net/).  

Noting that TRSS does NOT fetch artifacts from Jenkins server.  It only reports on status and gives console log information.  This request is not going to compromise the restricted access to build artifacts.

**Comment by llxia** [comment]
Jenkins API token can be set at `https://ci.adoptopenjdk.net/user/<functional ID email>/configure`

**Comment by smlambert** [comment]
@gdams @sxa - based on conversation in the last PMC meeting, we can use one of the already existing bots for this purpose. Please give @llxia or myself the details so we can retrieve console logs and result info in TRSS.  Thanks!
