### ISSUE TITLE
Access request to test-ibm-aix71-ppc64-1 for lumpfish

### ISSUE THREAD

**Issue by lumpfish** [adoptium/infrastructure#2197]
Access level:

- [X] Non-privileged
- [ ] jenkins user
- [ ] root/Administrative
- [ ] other (Please specify):

System for which access is needed: test-ibm-aix71-ppc64-1.

I'm trying to create a standalone test case for https://github.com/adoptium/aqa-tests/issues/2535, which is AIX specific, so would like access to test the test case.

**Comment by lumpfish** [comment]
Thanks @sxa. I've reproduced the failure in https://github.com/adoptium/aqa-tests/issues/2535 and updated the issue.

I've removed the files I created.

**Comment by sxa** [comment]
Access removed.
