### ISSUE TITLE
Access request to test-osuosl-aix72-ppc64-2 for lumpfish

### ISSUE THREAD

**Issue by lumpfish** [adoptium/infrastructure#2200]
Access level:

- [X] Non-privileged
- [ ] jenkins user
- [ ] root/Administrative
- [ ] other (Please specify):

System for which access is needed: test-osuosl-aix72-ppc64-2.

I'm investigating adoptium/aqa-tests#2535.  The test fails differently on test-osuosl-aix72-ppc64-2 to test-ibm-aix71-ppc64-1 (already worked out why the test fails there).

**Comment by sxa** [comment]
Access granted to `lumpfish@140.211.9.36`

**Comment by lumpfish** [comment]
Finished - updated https://github.com/adoptium/aqa-tests/issues/2535 with my findings.

**Comment by sxa** [comment]
Account removed.
