### ISSUE TITLE
Ansible request for AIX: osuosl (and others?)

### ISSUE THREAD

**Issue by aixtools** [adoptium/infrastructure#2205]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [ ] Bug in ansible playbook
- [x] Request for new playbook addition

Details:
Recent security scans at OSUOSL show potential vulerabilities.

This issue is to track the changes being tested - before being put into a new playbook, or modifying an existing playbook.

Deeper details are discussed within the security related slack channel.

**Comment by aixtools** [comment]
a) stop the inetd: there are several unsecured daemons, none are needed. Stopping the inetd service clears all these errors.
b) stop the cas_agent, if running. While the agent is secure - when utilized - it appears insecure when it continues to be in handshake mode. Stopping on all nodes - as it is not used.

**Comment by sxa** [comment]
@aixtools Did we manage to mitigate and "ansibilise" all necessary remediations for this or is there still work needed on it?

**Comment by aixtools** [comment]
No. Not finished yet. Will start now. Been traveling - finally.

**Comment by aixtools** [comment]
I had been testing on adopt08. Shall start testing on something else (adopt09 likely) asap.

**Comment by aixtools** [comment]
Fixed. Just needs merge.

Can be run on all AIX nodes using: ansible-playbook --tags aixsec main.yml` # once cfg and inventory are set, or provided as additional arguments.

**Comment by sxa** [comment]
Related PR is merged. Closing
