### ISSUE TITLE
Check and Replace Name Servers for Scaleway Hosts from 10.0.2.6 --> 10.194.3.2 and 10.194.3.4

### ISSUE THREAD

**Issue by karianna** [adoptium/infrastructure#2212]
- [ ] Missing install
- [ ] Bug in ansible playbook
- [X] Request for new playbook addition

Details:

The Scaleway Host (docker-scaleway-ubuntu1604-armv7l-1 as an example) have their nameservers set to: 10.0.2.6 (some sort of internal name server) this was causing lookups to fail.  Swapping them to 

10.194.3.2
10.194.3.4

Resolved the issue.  It may be the case that since we're getting rid of Scaleway that this isn't necessary.

**Comment by sxa** [comment]
The DNS servers on the other machines are set to:
```
nameserver 10.194.3.2
nameserver 10.194.3.4
```
and still seem to be working. On that basis I'd suggest switching the problematic machine to match the others instead of using an external one. I'm not supportive of just switching away from the provider's DNS servers as a default.

**Comment by karianna** [comment]
OK done, thanks.

**Comment by karianna** [comment]
> The DNS servers on the other machines are set to:
> 
> ```
> nameserver 10.194.3.2
> nameserver 10.194.3.4
> ```
> 
> and still seem to be working. On that basis I'd suggest switching the problematic machine to match the others instead of using an external one. I'm not supportive of just switching away from the provider's DNS servers as a default.

OK, done and this issue updated - thanks!

**Comment by sxa** [comment]
Scaleway arm machines now no longer in use. Closing
