### ISSUE TITLE
System unavailable: jenkins server (Unable to start Grinder jobs)

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2221]
- Please put the system name in the title of this issue - jenkins server ci.adoptium.net

- Link to any log file showing the problem: Nothing as the jobs aren't initiating

- Please describe the issue: Attempt to run Grinder job, job does not start - no apparent record of the sytsem starting.
Reported in [slack #infrastructure](https://adoptium.slack.com/archives/C53GHCXL4/p1623845746081000) by @kumpfish and @smlambert

**Comment by sxa** [comment]
Possibly as a result of some of the docker images I've been creating as part of #2201 the `/` filesystem had less than 10Gb free, and as per jenkins server settings that meant that the jenkins master node had been taken offline. After clearing up some of the old images and some others things on `/` the master node was able to be re-enabled and grinder jobs could then be initiated. Rather oddly when I tried to kick off a non-grinder job the job was created but said it was stuck waiting on the `master` node which is what alerted me to the underlying cause.

**Comment by sxa** [comment]
I propose keeping this open for a while until we can determine where the disk space is being used as this will not be a long term solution since there is only 19Gb of 564gb free on `/` and this excludes the jenkins `workspace` and `jobs` directories which are on a separate filesystem.

**Comment by sxa** [comment]
Looks like we have 380Gb from a backup of the jenkins master `workspace` directory from before we moved that to it's own filesystem which we can likely remove. @karianna are you happy for us to remove that?

**Comment by karianna** [comment]
> Looks like we have 380Gb from a backup of the jenkins master `workspace` directory from before we moved that to it's own filesystem which we can likely remove. @karianna are you happy for us to remove that?

Yes please!

**Comment by sxa** [comment]
Done
