### ISSUE TITLE
Investigate improving security of Ansible get_url download using GPG signature verification

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2233]
As part of improving the security of the supply chain and reproducible builds (https://github.com/adoptium/temurin-build/issues/2522), I have investigated some of the Ansible playbooks which download dependencies using get_url from the internet. The risk of such downloads are:
- Are they malicious websites?
- Have the website content being tampered with?
- Has a man-in-the-middle intercepted?
These equally apply to manually downloaded and stored Ansible content as well.

Currently get_url task for most(but not all) of the downloads uses a checksum. This is reasonable, assuming the accuracy of the checksum is assured? for example was the content manually downloaded actually tampered prior to checksum creation? We can't be sure it is from the origin, especially in man-in-the-middle, which could even tamper with checksum files when downloaded, to match tampered content.

Using GPG signatures is far more safe.
Currently Ansible does not provide a builtin way of using GPG sigs. So we would need to provide our own extension?

**Comment by Haroon-Khel** [comment]
| File | Checksum validation | Other signature file? |
| --------------- | --- | --- |
| Ant | Supplies a checksum, but no validation | .asc file |
| Ant-contrib | Doesn't supply a checksum, but we have one in the playbooks |  |
| Autoconf | Doesn't supply a checksum, but we have one in the playbooks | .sig file |
| cmake | Not sure but the playbooks have one | PGP signature |
| expat | Doesn't supply a checksum, but we have one in the playbooks |  |
| zlib | Doesn't supply a checksum, but we have one in the playbooks | gpg signature |
| IBM Java 8 for SLES (Link has expired ) | | |

**Comment by sxa** [comment]
The more of these we can validate the better, so adding `good first issue` for anyone that wants to start working on doing the validation for any in the table that are missing it currently.

**Comment by Haroon-Khel** [comment]
An issue has been raised with Ansible already about their support gpg signature validation on downloads using their `get_url` module
https://github.com/ansible/ansible/issues/69364

**Comment by sxa** [comment]
Related: #2553

**Comment by zdtsw** [comment]
for those using "get_url" if can be replaced by using "apt" "yum"or "package" module, we replace them. check is by default enabled in these modules.

**Comment by sxa** [comment]
> for those using "get_url" if can be replaced by using "apt" "yum"or "package" module, we replace them. check is by default enabled in these modules.

But only if the artifact it's supplied in one of those formats. This should cover source tarball downloads etc. too.

**Comment by zdtsw** [comment]
> > for those using "get_url" if can be replaced by using "apt" "yum"or "package" module, we replace them. check is by default enabled in these modules.
> 
> But only if the artifact it's supplied in one of those formats. This should cover source tarball downloads etc. too.

sure! for the others like tarball, which cannot use module, we still need gpg to verify

**Comment by Haroon-Khel** [comment]
Closing as https://github.com/adoptium/infrastructure/pull/2881 is merged
