### ISSUE TITLE
Access permission for build-azure-win2012r2-x64-2

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2236]
Try a window jdk and got permission denied in jenkins job. I'd like to access build-azure-win2012r2-x64-2 to figure out if it's jdk issue or it's jenkins or machine issue.

@sxa

**Comment by sxa** [comment]
User account `sophia-guo` created - will send password via another mechanism :-)

As an aside, please use the [request access to a machine](https://github.com/adoptium/infrastructure/issues/new?assignees=sxa&labels=Temp+Infra+Access&template=machineaccess.md&title=Access+request+for+%3Cyour+username%3E) issue template if you need to do this in the future. Thanks

**Comment by sxa** [comment]
@sophia-guo Do you still need this access or can it be removed now?

**Comment by sxa** [comment]
Account deleted
