### ISSUE TITLE
Ansible request for single parameterised adoptopenjdk role on AIX

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2239]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [ ] Bug in ansible playbook
- [x] Request for new playbook addition

Details:
Currently we have multiple `bootjdk*` roles in the AIX playbook. These should be consolidated into a single paramterised one as we do for Windows and UNIX playbooks to make maintenance simpler.

**Comment by Haroon-Khel** [comment]
Will take a look at this

**Comment by Haroon-Khel** [comment]
All but bootjdk7 qualify for consolidation into one role. The bootjdk7 role transfers a jdk7 binary from the host instead of downloading it from the adoptopenjdk api

**Comment by sxa** [comment]
Yep JDK7 being another method is fine as it'll be required for bootstrapping JDK8 for quite a long time - The need here is  to make it as simple as possible when a new release comes out to just switch the numbers :-)

**Comment by sxa** [comment]
Related PR merged, therefore closing
