### ISSUE TITLE
Solaris VagrantPlaybookCheck fails due to change of ssh host key during playbook execution

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2244]
Ref: https://github.com/adoptium/infrastructure/pull/2216#issuecomment-871586799
Probably introduced by https://github.com/adoptium/infrastructure/pull/2220

**Comment by gdams** [comment]
@sxa is it worth removing Solaris from the jenkins vagrant check job. The GitHub actions check that we have in place seems far more stable and provides the same level of coverage

**Comment by sxa** [comment]
(On a separate note, as Andreas did I have a preference for not relying on free github minutes for hefty stuff like this but that's a separate discussion)

VPC is testing more than just the playbooks so the assertion that it has the same level of coverage is false. The only reason that the actions check is not failing is because it doesn't try to connect to the machine after the playbook has finished executing (i.e. when the host key has changed). This has flagged a legitimate problem I believe, and we should try and retain the key if it is possible to do so.

**Comment by sxa** [comment]
Confirmed again that https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1211/ has resolved this problem so this is ready for approval.
