### ISSUE TITLE
sxa cannot log into test-azure-win2019-x64-1

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2245]
- Please put the system name in the title of this issue.

- Link to any log file showing the problem:

- Please describe the issue: Offline.

**Comment by sxa** [comment]
I can't log into that machine just now so will need further investigation - getting `ERRCONNECT_LOGON_FAILURE`

**Comment by sxa** [comment]
@Willsparker Since you've been on this machine in the past can you confirm if you are still able to log into it please?

**Comment by Haroon-Khel** [comment]
I am able to log on to the jenkins user via remote desktop

**Comment by sxa** [comment]
Now fixed.
