### ISSUE TITLE
test-aahlenst-armv7-raspbian-pi4-2 Xvfb does not initialise

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2246]
Xvfb is consistently failing to initialise on node test-aahlenst-armv7-raspbian-pi4-2
See: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.perf_arm_linux/60/console
```
19:39:38  Running tests...
[Pipeline] echo
19:39:38  ITERATION: 1/1
[Pipeline] wrap
19:39:38  $ Xvfb -displayfd 2 -screen 0 1024x768x24 -fbdir /home/jenkins/xvfb-60-..fbdir16664620678485907224
[Pipeline] // wrap
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Post)
[Pipeline] timestamps
[Pipeline] {
[Pipeline] step
19:39:59  TAP Reports Processing: START
19:39:59  Looking for TAP results report in workspace using pattern: **/*.tap
19:40:16  Did not find any matching files. Setting build result to FAILURE.
```
Times out after 20seconds...

**Comment by andrew-m-leonard** [comment]
I've DISABLEd the ci.role.test on this node: https://ci.adoptopenjdk.net/computer/test-aahlenst-armv7-raspbian-pi4-2/

**Comment by sxa** [comment]
It's running an old Xvfb process whicvh prevents it from starting a new one:
```
Result: UID        PID  PPID  C STIME TTY          TIME CMD
jenkins   2236 21410  0 Jun30 ?        00:00:00 Xvfb -displayfd 2 -screen 0 1024x768x24 -fbdir /home/jenkins/xvfb-60-..fbdir16664620678485907224
jenkins  15253 21410  0 Jun28 ?        00:00:00 Xvfb -displayfd 2 -screen 0 1024x768x24 -fbdir /home/jenkins/xvfb-59-..fbdir4540191866309367311
jenkins  21410     1  1 Apr02 ?        1-08:06:43 /usr/lib/jvm/jdk-11/bin/java -jar agent.jar -jnlpUrl https://ci.adoptopenjdk.net/computer/test-aahlenst-armv7-raspbian-pi4-2/slave-agent.jnlp -secret 957882187932733d2f65d689936b7ad1a0219c7fc561ee7820ef80892fd7de06 -workDir /home/jenkins
jenkins  29770 21410  0 15:23 ?        00:00:00 ps -fu jenkins
```
Please don't take the tag off machines - martk them offline with a description linking to the issue, otherwise it's hard to track why a machine has been "broken".

**Comment by sxa** [comment]
Both `Xvfb` processes have been removed and I've re-instated the tag.

**Comment by smlambert** [comment]
As a follow-up note: 
in a normal run, where a test job is not aborted before completing, I believe that the xvfb Jenkins plugin invoked in Jenkinsfilebase will try to stop the xvfb process it started.    

To avoid in future:
1) discourage aborting jobs, let them run to completion 
2) if job is aborted, know there will likely be dangling processes left hanging around - run a process check job on machine
3) consider adding xvfb to the process check, if its not already included
