### ISSUE TITLE
Ansible request for build-packet_esxi-solaris10u11-x64-2 (ant missing)

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#2254]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [x] Missing install
- [ ] Bug in ansible playbook
- [ ] Request for new playbook addition

Details:
build-packet_esxi-solaris10u11-x64-2 is missing a copy of "ant", as shown [here](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_special.functional_x86-64_solaris/1/console). 

Please put ant on this machine. Thank you.

**Comment by sxa** [comment]
Resolved for now by patching the `PATH` definition on the jenkins agent configuration for now as `ant` was already on there.

**Comment by sxa** [comment]
Passed at https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_special.functional_x86-64_solaris/3/console - closing.

**Comment by adamfarley** [comment]
Thanks Stewart :)
