### ISSUE TITLE
Access request for kalyanjoseph to https://github.com/orgs/AdoptOpenJDK/teams/adoptopenjdk-infrastructure

### ISSUE THREAD

**Issue by karianna** [adoptium/infrastructure#2259]
The onboarding doc might be out of date WRT to the name of the team (is adoptopenjdk-infrastructure now infrastructure-triage?) but in essence.

Team requested:

- [X] infrastructure-triage
- [ ] infrastructure
- [ ] infrastructure-core
- [ ] infrastructure-secret

Please explain why you need this access:

We'd like him added to the team where he can self-assign issues to work on.

I can vouch for him as an LJC member working on the project.

**Comment by sxa** [comment]
I Approve :-)

**Comment by sxa** [comment]
(But it'll need to go through the Eclipse process!)

**Comment by karianna** [comment]
@gdams was able to action this directly through the Eclipse project.
