### ISSUE TITLE
Error cloning remote repo on test-osuosl-aix72-ppc64-2 

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2282]
To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name?
ALL tests affected, can not git clone test material on this machine

- Is there an existing issue elsewhere covering this? No

- Which machine(s) does it work on?

- Which machine(s) does it fail on?
test-osuosl-aix72-ppc64-2

- Do you have a link to a Grinder re-run if the test with the failure?

Weekend test jobs that landed on this machine failed immediately due to not being able to setup test material
<img width="298" alt="Screen Shot 2021-07-18 at 11 24 49 AM" src="https://user-images.githubusercontent.com/2836948/126072897-ac636b69-1154-4864-8c7d-0c5a219871ee.png">

See all:
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.functional_ppc64_aix/156/console
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.functional_ppc64_aix/156/console
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_special.functional_ppc64_aix/36/console
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.system_ppc64_aix/208/console

Grinder job that tests a short running test target (LABEL=test-osuosl-aix72-ppc64-2):
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1115

Any other details:
```
The recommended git tool is: git
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/adoptium/aqa-tests.git
 > git init /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_ppc64_aix/aqa-tests # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /home/jenkins/workspace/Test_openjdk8_hs_sanity.system_ppc64_aix/aqa-tests
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:994)

```

**Comment by sxa** [comment]
Looks like again this is the [JDK16/J9 extended system test](https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk16_j9_extended.system_ppc64_aix/) generating multiple 10GB core dump files and chewing all the disk space:
```
/home/jenkins/workspace/Test_openjdk16_j9_extended.system_ppc64_aix/aqa-tests/TKG/output_16263244194946/SC_Softmx_JitAot_0/20210715-015031-SharedClassesWorkloadTest_Softmx_Increase_JitAot/results
# ls -ld *dmp
-rw-r--r--    1 jenkins  staff    9296015446 Jul 15 01:52 core.20210715.015127.25035096.0001.dmp
-rw-r--r--    1 jenkins  staff    5555257344 Jul 15 01:52 core.20210715.015127.25035096.0004.dmp
-rw-r--r--    1 jenkins  staff    9296081022 Jul 15 01:52 core.20210715.015200.25035096.0009.dmp
# 
```

**Comment by Haroon-Khel** [comment]
>Looks like again this is the JDK16/J9 extended system test generating multiple 10GB core dump files and chewing all the disk space

Yeah, I think the failed tests from https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk16_j9_extended.system_ppc64_aix/101/console must have generated those files

```
07:51:00  FAILED test targets:
07:51:00  	SC_Softmx_JitAot_0
07:51:00  	SC_Softmx_JitAot_1
07:51:00  	SharedClasses.SCM01.SingleCL_0
07:51:00  	SharedClasses.SCM01.SingleCL_1
07:51:00  	SharedClasses.SCM01.MultiCL_0
07:51:00  	SharedClasses.SCM01.MultiCL_1
07:51:00  	SharedClasses.SCM01.MultiThread_0
07:51:00  	SharedClasses.SCM01.MultiThread_1
07:51:00  	SharedClasses.SCM01.MultiThreadMultiCL_0
07:51:00  	SharedClasses.SCM01.MultiThreadMultiCL_1
07:51:00  	SharedClasses.SCM23.SingleCL_0
07:51:00  	SharedClasses.SCM23.SingleCL_1
07:51:00  	SharedClasses.SCM23.MultiCL_0
07:51:00  	SharedClasses.SCM23.MultiCL_1
07:51:00  	SharedClasses.SCM23.MultiThread_0
07:51:00  	SharedClasses.SCM23.MultiThread_1
07:51:00  	SharedClasses.SCM23.MultiThreadMultiCL_0
07:51:00  	SharedClasses.SCM23.MultiThreadMultiCL_1
```

**Comment by sxa** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1147/ did not show the same failure on the machine. Would be good to identify how repeatable this failure is - if at all.

**Comment by sxa** [comment]
40 iterations of that test on test-osuosl-aix72-ppc64-2 passed at https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1148.

Now running the extended suite on the machine again at https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk16_j9_extended.system_ppc64_aix/104/

**Comment by sxa** [comment]
Looks to have been ok at https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk16_j9_extended.system_ppc64_aix/112/ and https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk16_j9_extended.system_ppc64_aix/112/ and https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk16_j9_extended.system_ppc64_aix/114 on the machine.

**Comment by sxa** [comment]
Space looks ok now - will close and we can reopen if it recurs.
