### ISSUE TITLE
Ansible request for <fakeroot> on aarch64

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2291]
- [ fakeroot on aarch64 ] Missing install

Details:
tools/jpackage/* failed on aarch64 with the error message `jdk.jpackage.internal.ConfigException: Can not find fakeroot. Reason: Cannot run program "fakeroot": error=2, No such file or directory`. Looks like the environment setup issue. Fake root need to be installed. 

Related with https://github.com/adoptium/adoptium/issues/63

https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.openjdk_aarch64_linux/31/#showFailuresLink

**Comment by sxa** [comment]
@Haroon-Khel Can you take this one? Should just be a matter of adding the `fakeroot` package (whatever it's called, and assuming it's available) to the playbooks and the `DockerStatic` dockkerfiles. We should also verify that fakeroot works correctly in a docker container without additional permissions.

Recreate is in the Grinder mentioned [here](https://github.com/adoptium/aqa-tests/issues/2138#issuecomment-896036876)

**Comment by sxa** [comment]
@sophia-guo Are you aware of this failure in the previous comment?

**Comment by sophia-guo** [comment]
No, I'm not aware of this failure.

**Comment by sxa** [comment]
@sophia-guo OK Sounds like that particular might be separate then and so would need to be raised as a separate test issue rather then a conclusion being reached in this infrastructure issue.

**Comment by sophia-guo** [comment]
I can see same failure on test-docker-ubuntu2004-armv7l-2 on Sep 9 build:
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_0/9/#showFailuresLink

**Comment by sxa** [comment]
Now installed on the three Ubuntu 20 armv7l containers - thanks for re-opening

**Comment by sophia-guo** [comment]
Still failures on test-docker-ubuntu2010-armv8l-2 :28 test failures.
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux/26/

**Comment by sophia-guo** [comment]
Also same on test-docker-ubuntu1604-armv8l-2 
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux/25/#showFailuresLink

**Comment by sxa** [comment]
Installed on all remaining containers on dockerhost-ubuntu2004-armv8-1.
@Haroon-Khel this is a good example of why we'll need to start progressing https://github.com/adoptium/infrastructure/issues/2070 otherwise this sort of thing is going to be a nightmare going forwards :-) )
