### ISSUE TITLE
 test-ibm-aix71-ppc64-1 got `ERROR: Error cloning remote repo 'origin'`

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2294]
test-ibm-aix71-ppc64-1 got `ERROR: Error cloning remote repo 'origin'`

```
 > git fetch --tags --force --progress -- https://github.com/sophia-guo/openjdk-tests.git +refs/heads/*:refs/remotes/origin/* # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://github.com/sophia-guo/openjdk-tests.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://github.com/sophia-guo/openjdk-tests.git/': Resolving timed out after 300003 milliseconds
```
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/261/
Rerun on build-osuosl-aix71-ppc64-2 works fine:
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/262/

**Comment by sxa** [comment]
The DNS on the IBM Garage machines was set to `32.97.185.3` which no longer appears to be available. I've switched both of the IBM machines to the CloudFlare DNS servers.

However bear in mind that both of those machines will likely disappear shortly as we will no longer have that provider available.
