### ISSUE TITLE
VPC (and QPC?) cannot handle new Adoptium repository names

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2295]
At present the VagrantPlaybookCheck job's `FORK` parameters take a username for the infrastructure and build repository forks. It assumes that the repository underneath there will be the origin AdoptOpenJDK names of `openjdk-infrastructure` and `openjdk-build` whereas anyone forking from the adoptium repositories will have names of `infrastructure` and `temurin-build` instead, this preventing them from executing. We should either:

1. Switch to the new names and assume everyone is using them
2. Detect which of the two exists and use that
3. Change the definition of the `FORK` parameter to allow specification of the respository name too e.g. `sxa/infrastructure`

**Comment by sxa** [comment]
@Haroon-Khel Is this now complete?

**Comment by Haroon-Khel** [comment]
It's complete for the VPC. I haven't yet investigated the damage on the QPC. WIll do soon
