### ISSUE TITLE
xvfb unexpected result on test-aahlenst-armv7-raspbian-p​i4-2

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2302]
Aqa-test jenkins job consistently got unexpected result on test-aahlenst-armv7-raspbian-p​i4-2. Job terminated once run command `Xvfb`. The issue only happened to test-aahlenst-armv7-raspbian-p​i4-2.

```
17:22:51  Running tests...
[Pipeline] echo
17:22:51  ITERATION: 1/1
[Pipeline] wrap
17:22:51  $ Xvfb -displayfd 2 -screen 0 1024x768x24 -fbdir /home/jenkins/xvfb-31-..fbdir15885600368890494798
[Pipeline] // wrap
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Post)
[Pipeline] timestamps
[Pipeline] {
```

rerun on test-aahlenst-armv7-raspbian-p​i4-1, looks good:
https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.perf_arm_linux/30/
rerun on test-aahlenst-armv7-raspbian-p​i4-2 consistently failed. https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.perf_arm_linux/31/

Related https://github.com/adoptium/adoptium/issues/63

**Comment by sxa** [comment]
Machines are offline just now which avoids the immediate problem ...

**Comment by sxa** [comment]
Closing as this machine is not likely to come back.
