### ISSUE TITLE
Access request to two Solaris machines for afarley

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#2305]
Access level:

- [x] Non-privileged
- [ ] jenkins user
- [ ] root/Administrative
- [ ] other (Please specify):

System for which access is needed:

https://ci.adoptopenjdk.net/computer/build-packet_esxi-solaris10u11-x64-2/
and
https://ci.adoptopenjdk.net/computer/build-siteox-solaris10u11-sparcv9-1/

Please explain why you need this access including whether it is a temporary or permanent request:

I need temporary access (a few days maybe) to verify whether a display bug occurs on the solaris sparc machine, but not the x86 one. 

My intention is to set up a vncserver display, port forward via putty, connect remotely via my UltraVNC Viewer (Windows), and run a small Java program. Should only take a minute or two on each.

**Comment by sxa** [comment]
Done.

**Comment by adamfarley** [comment]
Update: I don't need this access anymore. Thanks @sxa :)
