### ISSUE TITLE
jdk16+ some tools/jpackage test failed with `Error executing ICE action 'ICE01` on build-ibmcloud-win2012r2-x64-2 

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2310]
jdk16+ some tools/jpackage test failed with `Error executing ICE action 'ICE01` on build-ibmcloud-win2012r2-x64-2 .

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1/10/#showFailuresLink

Tests on test-packet-win2012r2-x64-1 work.
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/303/

Failure tests:
tools/jpackage/share/AppImagePackageTest.java.AppImagePackageTest
tools/jpackage/share/EmptyFolderPackageTest.java.EmptyFolderPackageTest
tools/jpackage/share/FileAssociationsTest.java#id0.FileAssociationsTest_id0
tools/jpackage/share/InstallDirTest.java#id0.InstallDirTest_id0
tools/jpackage/share/LicenseTest.java#id0.LicenseTest_id0
tools/jpackage/share/MultiLauncherTwoPhaseTest.java.MultiLauncherTwoPhaseTest
tools/jpackage/share/MultiNameTwoPhaseTest.java.MultiNameTwoPhaseTest
tools/jpackage/share/RuntimePackageTest.java#id0.RuntimePackageTest_id0
tools/jpackage/share/SimplePackageTest.java.SimplePackageTest
tools/jpackage/share/jdk/jpackage/tests/BasicTest.java.BasicTest
tools/jpackage/share/jdk/jpackage/tests/VendorTest.java#id1.VendorTest_id1
tools/jpackage/windows/WinDirChooserTest.java.WinDirChooserTest
tools/jpackage/windows/WinInstallerUiTest.java.WinInstallerUiTest
tools/jpackage/windows/WinL10nTest.java.WinL10nTest
tools/jpackage/windows/WinMenuGroupTest.java.WinMenuGroupTest
tools/jpackage/windows/WinMenuTest.java.WinMenuTest
tools/jpackage/windows/WinPerUserInstallTest.java.WinPerUserInstallTest
tools/jpackage/windows/WinScriptTest.java.WinScriptTest
tools/jpackage/windows/WinShortcutPromptTest.java.WinShortcutPromptTest
tools/jpackage/windows/WinShortcutTest.java.WinShortcutTest
tools/jpackage/windows/WinUpgradeUUIDTest.java#id1.WinUpgradeUUIDTest_id1
tools/jpackage/windows/WinUrlTest.java.WinUrlTest
tools/jpackage/share/AddLauncherTest.java#id1.AddLauncherTest_id1
tools/jpackage/windows/WinInstallerIconTest.java

Detail error message:

```
[10:43:15.931] Running C:\Program Files (x86)\WiX Toolset v3.14\bin\light.exe in E:\jenkins\jenkinstmp\jdk.jpackage7415977171295040786\images\win-msi.image\AppImagePackageTest
[10:43:42.927] Command [PID: 7080]:
    C:\Program Files (x86)\WiX Toolset v3.14\bin\light.exe -nologo -spdb -ext WixUtilExtension -out E:\jenkins\jenkinstmp\jdk.jpackage7415977171295040786\images\win-exe.image\AppImagePackageTest-1.0.msi -sice:ICE27 -loc E:\jenkins\jenkinstmp\jdk.jpackage7415977171295040786\config\MsiInstallerStrings_en.wxl -cultures:en-us E:\jenkins\jenkinstmp\jdk.jpackage7415977171295040786\wixobj\main.wixobj E:\jenkins\jenkinstmp\jdk.jpackage7415977171295040786\wixobj\bundle.wixobj E:\jenkins\jenkinstmp\jdk.jpackage7415977171295040786\wixobj\uui.wixobj
[10:43:42.927] Output:
    light.exe : error LGHT0217 : Error executing ICE action 'ICE01'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
```

**Comment by smlambert** [comment]
for reference: https://github.com/adoptium/infrastructure/pull/1241

**Comment by sxa** [comment]
I'm struggling to understand the problem here - is the test job running WiX tools directly?

**Comment by sxa** [comment]
Job re-running at https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk16_j9_extended.openjdk_x86-64_linux/39/ since the previous one is now lost.

**Comment by sophia-guo** [comment]
Another [tools/jpackage/share/AppContentTest.java.AppContentTest](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_2/27/testReport/junit/tools_jpackage_share_AppContentTest/java/AppContentTest/)

https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_2/27/#showFailuresLink

**Comment by karianna** [comment]
Failed during [19 release](https://trss.adoptium.net/output/test?id=632a240093ac60470bc48ee8)

**Comment by smlambert** [comment]
Yes, the jdk_tools test target appears to require the wix toolkit on Windows.

Closing this issue as there is a fresher one reporting the same problem, so dup of: https://github.com/adoptium/infrastructure/issues/2885
