### ISSUE TITLE
fakeroot is not installed on some linux machine.

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2311]
Some jpackage tests failed on some linux machines.
Knows affected machine: 
test-docker-ubuntu2010-x64-2

Works machine: 
test-docker-ubuntu1804-x64-1

Tests:
tools/jpackage/linux/AppAboutUrlTest.java#id0.AppAboutUrlTest_id0
tools/jpackage/linux/AppCategoryTest.java.AppCategoryTest
tools/jpackage/linux/LinuxBundleNameTest.java.LinuxBundleNameTest
tools/jpackage/linux/LinuxResourceTest.java.LinuxResourceTest
tools/jpackage/linux/MaintainerTest.java.MaintainerTest
tools/jpackage/linux/PackageDepsTest.java.PackageDepsTest
tools/jpackage/linux/ShortcutHintTest.java#id0.ShortcutHintTest_id0
tools/jpackage/share/AddLauncherTest.java#id1.AddLauncherTest_id1
tools/jpackage/share/AppImagePackageTest.java.AppImagePackageTest
tools/jpackage/share/EmptyFolderPackageTest.java.EmptyFolderPackageTest
tools/jpackage/share/FileAssociationsTest.java#id0.FileAssociationsTest_id0
tools/jpackage/share/IconTest.java.IconTest
tools/jpackage/share/InstallDirTest.java#id0.InstallDirTest_id0
tools/jpackage/share/LicenseTest.java#id0.LicenseTest_id0
tools/jpackage/share/LicenseTest.java#id1.LicenseTest_id1
tools/jpackage/share/MultiLauncherTwoPhaseTest.java.MultiLauncherTwoPhaseTest
tools/jpackage/share/MultiNameTwoPhaseTest.java.MultiNameTwoPhaseTest
tools/jpackage/share/SimplePackageTest.java.SimplePackageTest
tools/jpackage/share/jdk/jpackage/tests/BasicTest.java.BasicTest
tools/jpackage/share/jdk/jpackage/tests/VendorTest.java#id1.VendorTest_id1
tools/jpackage/linux/ReleaseTest.java.ReleaseTest
tools/jpackage/linux/jdk/jpackage/tests/UsrTreeTest.java.UsrTreeTest
tools/jpackage/share/RuntimePackageTest.java#id0.RuntimePackageTest_id0

Rerun: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/305/

**Comment by sophia-guo** [comment]
Ref https://github.com/adoptium/infrastructure/issues/2291

**Comment by sxa** [comment]
Should be on all the ubuntu and Fedora ones now. We'll need an alternate solution for CentOS8 since there doesn't seem to be a `fakeroot` package on that OS. Will create another issue for that
