### ISSUE TITLE
CentOS8 does not have the "fakeroot" package

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2312]
Should be on all the ubuntu and Fedora ones now. We'll need an alternate solution for CentOS8 since there doesn't seem to be a `fakeroot` package on that OS. Will create another issue for that

_Originally posted by @sxa in https://github.com/adoptium/infrastructure/issues/2311#issuecomment-916838875_

**Comment by Haroon-Khel** [comment]
Centos8 didn't seem to have a problem installing it at https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1236/OS=CentOS8,label=vagrant/console

I'll add it to the ubuntu and fedora playbooks too

**Comment by Haroon-Khel** [comment]
It is already on the fedora dockerfiles https://github.com/adoptium/infrastructure/blob/e06449aac173a47d35f7121519b31a435c43fa8d/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.f33#L24

**Comment by sxa** [comment]
Ahhh it's in the EPEL repository, but not in the base CentOS ones. Yep in that case we should be able to add it into the `DockerStatic` files too 👍🏻 @Haroon-Khel Can you handle ensuring that fakeroot is deployed into all our CentOS8/RHEL8 systems?

This will avoid us considering disabling those machines during the release period as we had discussed as an option last week.

**Comment by Haroon-Khel** [comment]
As mentioned earlier, I was not able to install fakeroot onto build-marist-rhel77-s390x-1 and 2. I think this may be because there is not epel 7 repo for s390x

**Comment by sxa** [comment]
@Haroon-Khel Ah ok that's not quite so critical as they're bulid machines and not used for testing (which is where fakeroot is required. We don't currently do any testing on RHEL/CentOS on s390x, which is definitly somethign we should fix going forward, but doesn't need to be done under this issue :-)
