### ISSUE TITLE
Some java/beans/* test failed with error message: `Caused by: java.lang.NullPointerException: ...because "sun.awt.FontConfiguration.head" is null`on arm containers. 

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2318]
Following jdk_bean tests  got error message: `Caused by: java.lang.NullPointerException: Cannot load from *** because "sun.awt.FontConfiguration.head" is null.` 
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_0/12/
java/beans/PropertyChangeSupport/Test4682386.java.Test4682386
java/beans/PropertyEditor/TestFontClassJava.java.TestFontClassJava
java/beans/PropertyEditor/TestFontClassValue.java.TestFontClassValue
java/beans/XMLEncoder/Test4631471.java.Test4631471
java/beans/XMLEncoder/Test4903007.java.Test4903007
java/beans/XMLEncoder/javax_swing_DefaultCellEditor.java.javax_swing_DefaultCellEditor
java/beans/XMLEncoder/javax_swing_JTree.java.javax_swing_JTree

 Tests passed on non-docker containers. Reran on test-sxa-armv7l-ubuntu1804-odroid-1. reran passed.:
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/322/console

https://github.com/adoptium/aqa-tests/issues/2854

**Comment by sxa** [comment]
Do you know whay's needed for this to pass?

**Comment by sophia-guo** [comment]
one more javax/imageio/plugins/shared/ImageWriterCompressionTest.java
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_2/31/testReport/javax_imageio_plugins_shared_ImageWriterCompressionTest/java/ImageWriterCompressionTest/

**Comment by smlambert** [comment]
some related discussion that describes a workaround: https://github.com/AdoptOpenJDK/openjdk-docker/issues/75

**Comment by sophia-guo** [comment]
This also happened to linux-x64 containers
https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_2/26/

**Comment by sxa** [comment]
Based on the other issues this will need the fontconfig package (which pulls in fonts-dejavu-core`, `fontconfig-config` `libfontconfig1` on Ubuntu) added to the [DockerStatic](https://github.com/adoptium/infrastructure/tree/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic) containers.
