### ISSUE TITLE
System unavailable: docker-packet-ubuntu2004-amd-1

### ISSUE THREAD

**Issue by jerboaa** [adoptium/infrastructure#2324]
- Link to any log file showing the problem:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-hotspot/1032/console

- Please describe the issue:
System seems to be out of disk space:
```
java.nio.file.FileSystemException: /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-x64-hotspot: No space left on device
```

**Comment by sxa** [comment]
Clearing up now - it's the Alpine docker containers that are causing the issue https://github.com/adoptium/infrastructure/issues/2320
