### ISSUE TITLE
Access request for longyuzhang

### ISSUE THREAD

**Issue by LongyuZhang** [adoptium/infrastructure#2325]
Previously I can run [Grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/) after login, but now I cannot see the "Build with Parameters" option even after login. I did not change any settings/info about my account (username: longyuzhang). Really appreciate the help with this problem.

In addition, the error shows "Access Denied:  is missing the Job/Build permission" when I tried to re-run an existing build.

**Comment by LongyuZhang** [comment]
FYI @smlambert @llxia

**Comment by smlambert** [comment]
That is odd, you should be in the test-core team that has access but you were not.  I have just added you.  You will have to accept the github invitation and then you will have access to the Grinder jobs again.

**Comment by LongyuZhang** [comment]
It works now! Thanks @smlambert

**Comment by LongyuZhang** [comment]
The same problem of no "Build with Parameters" option for Grinder after login happens again to my account. I did not make any changes, wondering if anything changed for the Grinder access? Thanks. @sxa @smlambert

**Comment by smlambert** [comment]
Strange, I am not aware of any changes, but I have manually added access for  https://github.com/orgs/AdoptOpenJDK/teams/test-core which should give you access now, though you should already have had access, but I do not know what may have changed.

**Comment by LongyuZhang** [comment]
@smlambert It is working again now. Thanks!
