### ISSUE TITLE
System unavailable: vagrant host

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2328]
Multiple [VPC](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) jobs failng with JNLP connection errors e.g. `13:00:51 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 150.239.60.120/150.239.60.120:57154` e.g. https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/1243/OS=Debian10,label=vagrant/console

**Comment by Willsparker** [comment]
Throughout the testing for #2348 and #2372 , I haven't seen this issue. I'm going to tentatively close this issue, however, I'll reopen if I see the same errors. :-)
