### ISSUE TITLE
Ansible request for aixPB: rewrite AIX_filesystem_config.sh into appropriate playbooks

### ISSUE THREAD

**Issue by aixtools** [adoptium/infrastructure#2336]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [x] Bug in ansible playbook
- [x] Request for new playbook addition

Details:
This script is not the 'ansible' way and it's contents deal with issues other than AIX filesystems. And, when it has an issue (cannot perform an action) the main playbook often is not informed - and the playbook user assumes everything was done properly.

So, to finish the migration of the `flatfile aix.yml + this script` to `aixPB version2` rewrite/migrate these commands into the new ansible role-based task execution (and in playbooks rather than scripts).

**Comment by Haroon-Khel** [comment]
The `maxuproc` line is now in a separate role as of https://github.com/adoptium/infrastructure/pull/2335

**Comment by aixtools** [comment]
As to role `aixfs` - it is a seperate role, imho, because a default install of AIX had sizes too small. In the *Unix* playbooks I have not been able to find something similiar, so I would assume that the filesystem definition is part of the VM definition (also possible I do not know the proper Linux command to search for (that compares with AIX `chfs`.

I believe the existing playbooks need to be scanned for system/platform settings - a role `platform` might be better (more generic) where all platform related settings are performed.

I consider it a weakness in the current setup that `platform` settings are spread out over multiple .yml files, some in roles, some not.

**Comment by sxa** [comment]
Correct - in most of the other UNIX based VMs the file systems are generally already set up in an appropriate manner when we get them from the provider and frequently without separate file systems for `/opt` `/usr` `/var` and `/home` so the whole disk is allocated to `/` (Our OUSOSL Linux/ppc64le ones are like that for example)

**Comment by aixtools** [comment]
Well, I am willing to take on the task of re-working the AIX pb - there have been several starts, but lot's of issues surronding vendor_files - which I still believe should be dropped as a principle (but acceptable for exceptions).

As you imply above - at least I read that into it - there has been a discussion/planning session with providers about what **Adopt** needs before a platform is ready to go.

IMHO - ISP is responsible for:
- OpenSSL/OpenSSH
- X11
- Language files

Optionally (read preferred)
- source for C compilers.
- latest platform Java (for AIX Java8_64) - or, not at all (if possible).

Likely I am missing something (off the top) - but that is what discussions/requirement documents are for.

**Comment by aixtools** [comment]
afaik - this was fixed, among other things, by #2483
