### ISSUE TITLE
Solaris PR checks are failing

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2349]
- Please put the system name in the title of this issue. All playbook checks on Solaris

- Link to any log file showing the problem: https://github.com/adoptium/infrastructure/runs/3861091264?check_suite_focus=true

- Please describe the issue:
`unable to resolve host adoptopenjdkSol10: node name or service name not known`

**Comment by gdams** [comment]
The actual error seems to be caused by `sudo`:

```failed: [127.0.0.1] (item=nano) => {"ansible_loop_var": "item", "changed": false, "item": "nano", "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "sudo: unable to resolve host adoptopenjdkSol10: node name or service name not known\r\r\nsudo: error initializing audit plugin sudoers_audit\r\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}```
