### ISSUE TITLE
Ansible request for CentOS6 to be able to run playbooks under Vagrant

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2351]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [x] Bug in ansible playbook
- [ ] Request for new playbook addition

Details: The fix to the OpenSSL issues on our CentOS6 images works ok, but the runs in VagrantPlaybookCheck do not. This may be due to the presence of OpenSSL 32-bit (`i686`) packages in the vagrant boxes causing some problems. This needs to be replicated to see if we can understand the failure with the new playbook role (as added in https://github.com/adoptium/infrastructure/pull/2344) and see if we can work around it (either by removing any problematic packages, or also creating a 32-bit version of the updated packages from CentOS7)

@Haroon-Khel Can you take a look at this please?

**Comment by Willsparker** [comment]
Considering I've had 3 VPC runs where this has worked perfectly fine, I'm closing this issue
