### ISSUE TITLE
test-docker-alpine314-x64-1 got `make: pwd: Operation not permitted`

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2354]
All Aqa-test jenkins jobs on test-docker-alpine314-x64-1 got `make: pwd: Operation not permitted`

```
08:56:09  make: pwd: Operation not permitted
08:56:09  rm -f -r /../TKG/output_compilation; \
08:56:09  mkdir -p /../TKG/output_compilation; \
08:56:09  (ant -f ./scripts/build_tools.xml -DTEST_JDK_HOME=/home/jenkins/workspace/Test_openjdk17_hs_extended.functional_x86-64_alpine-linux/openjdkbinary/j2sdk-image/bin/../ -DTEST_ROOT=/.. 2>&1; echo $? ) | tee "/../TKG/output_compilation/compilation.log"; \
08:56:09  if [ -z "$(tail -1 /../TKG/output_compilation/compilation.log | grep 0)" ]; then perl scripts/moveDmp.pl --compileLogPath="/../TKG/output_compilation/compilation.log" --testRoot="/.."; false; else rm -f -r "/../TKG/output_compilation"; fi
08:56:09  make: /bin/sh: Operation not permitted
08:56:09  make: *** [makefile:94: compileTools] Error 127
```
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.functional_x86-64_alpine-linux/69/console
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.functional_x86-64_alpine-linux/68/console

test-docker-alpine311-x64-1 works fine
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.functional_x86-64_alpine-linux/70/

**Comment by sxa** [comment]
@Haroon-Khel What's the status of this - the machine still seems to be offline so I assume the problem has not been resolved yet?

**Comment by Haroon-Khel** [comment]
This issue is resolved

**Comment by smlambert** [comment]
Would be good to note what actions occurred in order to close this.  From comments, it sounds like the original containers were perhaps disposed of, and new ones created.  Was that ultimately how this was resolved?
