### ISSUE TITLE
openjdk net related tests failed on test-skytap-ubuntu2004-ppc64le-1

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2355]
75 openjdk tests failed on test-skytap-ubuntu2004-ppc64le-1. All tests are related with net connections: remote, net, connection, socket related. Tests running on this machine also takes triple times. Though it might be the failures make the running time longer than normal.
 
The whole set is:
jdk/jfr/jmx/TestGetRecordings.java.TestGetRecordings
javax/management/remote/mandatory/connection/RMIConnectionIdTest.java.RMIConnectionIdTest
javax/management/remote/mandatory/notif/RMINotifTest.java.RMINotifTest
javax/management/remote/mandatory/passwordAuthenticator/RMIAltAuthTest.java.RMIAltAuthTest
javax/management/remote/mandatory/passwordAuthenticator/RMIPasswdAuthTest.java.RMIPasswdAuthTest
javax/management/remote/mandatory/socketFactories/RMISocketFactoriesTest.java.RMISocketFactoriesTest
javax/management/remote/mandatory/subjectDelegation/SubjectDelegation1Test.java.SubjectDelegation1Test
javax/management/remote/mandatory/util/MapNullValuesTest.java.MapNullValuesTest
sun/management/jmxremote/bootstrap/CustomLauncherTest.java.CustomLauncherTest
sun/management/jmxremote/bootstrap/JMXInterfaceBindingTest.java.JMXInterfaceBindingTest
sun/management/jmxremote/bootstrap/JvmstatCountersTest.java.JvmstatCountersTest
sun/management/jmxremote/bootstrap/LocalManagementTest.java.LocalManagementTest
java/net/CookieHandler/CookieManagerTest.java.CookieManagerTest
java/net/DatagramPacket/ReuseBuf.java.ReuseBuf
java/net/DatagramSocket/GetLocalAddress.java.GetLocalAddress
java/net/DatagramSocket/PortUnreachable.java.PortUnreachable
java/net/DatagramSocket/ReuseAddressTest.java.ReuseAddressTest
java/net/DatagramSocket/Send12k.java.Send12k
java/net/DatagramSocket/SendReceiveMaxSize.java.SendReceiveMaxSize
java/net/DatagramSocket/SendSize.java.SendSize
java/net/DatagramSocket/SetDatagramSocketImplFactory/ADatagramSocket.java.ADatagramSocket
java/net/MulticastSocket/B6427403.java.B6427403
java/net/MulticastSocket/IPMulticastIF.java.IPMulticastIF
java/net/ServerSocket/TestLocalAddress.java.TestLocalAddress
java/net/Socket/CloseAvailable.java.CloseAvailable
java/net/Socket/GetLocalAddress.java.GetLocalAddress
java/net/Socket/InheritTimeout.java.InheritTimeout
java/net/Socket/ProxyCons.java.ProxyCons
java/net/Socket/ReadTimeout.java.ReadTimeout
java/net/Socket/SetSoLinger.java.SetSoLinger
java/net/Socket/SoTimeout.java.SoTimeout
java/net/Socket/asyncClose/AsyncClose.java.AsyncClose
java/net/Socket/asyncClose/BrokenPipe.java.BrokenPipe
java/net/Socket/setReuseAddress/Basic.java.Basic
java/net/Socket/setReuseAddress/Restart.java.Restart
java/net/SocketInputStream/SocketTimeout.java.SocketTimeout
java/net/Socks/BadProxySelector.java.BadProxySelector
java/net/Socks/SocksProxyVersion.java.SocksProxyVersion
jdk/net/ExtendedSocketOption/AsynchronousSocketChannelNAPITest.java.AsynchronousSocketChannelNAPITest
jdk/net/ExtendedSocketOption/DatagramChannelNAPITest.java.DatagramChannelNAPITest
jdk/net/ExtendedSocketOption/DatagramSocketNAPITest.java.DatagramSocketNAPITest
jdk/net/ExtendedSocketOption/SocketChannelNAPITest.java.SocketChannelNAPITest
jdk/net/ExtendedSocketOption/SocketNAPITest.java.SocketNAPITest
sun/net/www/http/HttpClient/B8025710.java.B8025710
sun/net/www/http/KeepAliveCache/B5045306.java.B5045306
sun/net/www/protocol/http/B6299712.java.B6299712
sun/net/www/protocol/http/HttpOnly.java.HttpOnly
sun/net/www/protocol/http/NoCache.java.NoCache
sun/net/www/protocol/http/RelativeRedirect.java.RelativeRedirect
sun/net/www/protocol/http/SetChunkedStreamingMode.java.SetChunkedStreamingMode
sun/net/www/protocol/https/HttpsURLConnection/B6226610.java.B6226610
sun/net/www/protocol/https/HttpsURLConnection/ImpactOnSNI.java.ImpactOnSNI
sun/net/www/protocol/https/HttpsURLConnection/PostThruProxyWithAuth.java.PostThruProxyWithAuth
java/nio/channels/DatagramChannel/AdaptorBasic.java.AdaptorBasic
java/nio/channels/DatagramChannel/EmptyBuffer.java.EmptyBuffer
java/nio/channels/DatagramChannel/IsBound.java.IsBound
java/nio/channels/DatagramChannel/IsConnected.java.IsConnected
java/nio/channels/DatagramChannel/Sender.java.Sender
java/nio/channels/Selector/Alias.java.Alias
java/nio/channels/Selector/BasicConnect.java.BasicConnect
java/nio/channels/Selector/Connect.java.Connect
java/nio/channels/Selector/ConnectWrite.java.ConnectWrite
java/nio/channels/Selector/KeysReady.java.KeysReady
java/nio/channels/Selector/SelectorLimit.java.SelectorLimit
java/nio/channels/ServerSocketChannel/Basic.java.Basic
java/nio/channels/ServerSocketChannel/NonBlockingAccept.java.NonBlockingAccept
java/nio/channels/SocketChannel/AdaptSocket.java.AdaptSocket
java/nio/channels/SocketChannel/Basic.java.Basic
java/nio/channels/SocketChannel/Connect.java.Connect
java/nio/channels/SocketChannel/ConnectState.java.ConnectState
java/nio/channels/SocketChannel/FinishConnect.java.FinishConnect
java/nio/channels/SocketChannel/Hangup.java.Hangup
java/nio/channels/SocketChannel/LingerOnClose.java.LingerOnClose
java/nio/channels/SocketChannel/LocalAddress.java.LocalAddress
java/nio/channels/SocketChannel/VectorParams.java.VectorParams

Rerun one test on different machine test-osuosl-centos74-ppc64le-1 looks good:
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/351/
rerun on test-skytap-ubuntu2004-ppc64le-1 failed
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/350/

**Comment by Haroon-Khel** [comment]
I think changing the inet on the `ibmveth3` interface to the public ipv4 will resolve the issues, but I have done something like this in the past before (on a different machine) and it immediately booted me out of the machine since I was connected remotely. I'll try to find another way

**Comment by Haroon-Khel** [comment]
More net related tests are failing on this machine https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1838/testReport/
jdk_nio_1,jdk_net_1,jdk_management_1,jdk_jfr_0,jdk_jmx_1 part of the hotspot extended openjdk test suite

**Comment by smlambert** [comment]
+1 to take this one offline (or remove ci.role.test label) to make it clearer for triaging during release.

**Comment by sxa** [comment]
Since we have now completed the release on this platform we should re-enable this and try and get a solution.

**Comment by Haroon-Khel** [comment]
ref https://github.com/adoptium/infrastructure/issues/2358#issuecomment-970196985
I've added `10.0.0.1` to the machine's /etc/hosts file
Rerunning an extended openjdk grinder https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2551/console

**Comment by Haroon-Khel** [comment]
```
jdk_other_0
jdk_other_1
jdk_other_2
jdk_net_0
jdk_net_1
jdk_security1_0
jdk_security1_1
jdk_security2_0
jdk_security2_1
jdk_security4_0
jdk_security4_1
jdk_jdi_0
jdk_jdi_1
```
all failed in the above extended openjdk grinder

I've run them again in https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2552/console after tweaking the /etc/hosts file again and now only 

```
java/net/httpclient/websocket/WebSocketServerDriver.java.WebSocketServerDriver
java/net/httpclient/websocket/WebSocketServerDriver.java.WebSocketServerDriver
```
from `jdk_net_0`, `jdk_net_1`

**Comment by Haroon-Khel** [comment]
The failing tests now pass. https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2553/console

Ive reenabled the machine for testing

**Comment by sophia-guo** [comment]
jdk_other com/sun/jndi/ldap/LdapPoolTimeoutTest.java failed on test-skytap-ubuntu2004-ppc64le-1 passed on others https://trss.adoptium.net/deepHistory?testId=62b783ac250c3c428c3aaebc

**Comment by sxa** [comment]
> jdk_other com/sun/jndi/ldap/LdapPoolTimeoutTest.java failed on test-skytap-ubuntu2004-ppc64le-1 passed on others https://trss.adoptium.net/deepHistory?testId=62b783ac250c3c428c3aaebc

Closing this out as I've created a separate issue for it: https://github.com/adoptium/infrastructure/issues/2924
