### ISSUE TITLE
Lots of openjdk tests failed on test-aws-rhel8-x64-1, passed on other machines

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2360]
Quite a few tests on test-aws-rhel8-x64-1.

[**Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0/14/) ❌ FAILURE ❌
jvm_compiler_1 => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6163635bc6182d02176be20f) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61636275c6182d02176bda6b&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0&testId=6163635bc6182d02176be20f&testName=jvm_compiler_1) 
jdk_jmx_0 => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6163635bc6182d02176be21c) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61636275c6182d02176bda6b&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0&testId=6163635bc6182d02176be21c&testName=jdk_jmx_0) 
jdk_net_0 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=6163635bc6182d02176be215) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61636275c6182d02176bda6b&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0&testId=6163635bc6182d02176be215&testName=jdk_net_0) 
jdk_tools_0 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=6163635bc6182d02176be219) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61636275c6182d02176bda6b&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0&testId=6163635bc6182d02176be219&testName=jdk_tools_0) 
Post Test => [deep history 2/3 passed](https://trss.adoptium.net/deepHistory?testId=6163635bc6182d02176be21b) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61636275c6182d02176bda6b&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0&testId=6163635bc6182d02176be21b&testName=Post%20Test) 
jdk_jfr_1 => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6163635bc6182d02176be218) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61636275c6182d02176bda6b&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0&testId=6163635bc6182d02176be218&testName=jdk_jfr_1) 
To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

Rerun jdk_jfr on same machine got the same failure.
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/359/
Rerun tests on different machines and passed.
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/361/

Rerun other tests on other machine and passed:
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/360/
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/358/

two others wait for the results:
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/362/
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/355/

**Comment by sxa** [comment]
Running full extended.openjdk in Grinder on [x64](https://ci.adoptopenjdk.net/job/Grinder/6550/) and [s390x](https://ci.adoptopenjdk.net/job/Grinder/6551/) RHEL8 systems for comparison

**Comment by sxa** [comment]
AWS RHEL7 stopped after 10h ([Re-running with TIME_LIMIT=100](https://ci.adoptopenjdk.net/job/Grinder/6585/))
AWS RHEL8 completed in 8h44
Marist RHEL8 completed in 9h05

**Comment by sxa** [comment]
Full extended.openjdk AWS RHEL7 run completed in 10h20m so just over the 10h limit and not too much slower than the other two machines

**Comment by sxa** [comment]
For the two RHEL8 jobs, both failed as per #2900 and [sun/security/tools/keytool/NssTest.java.NssTest](https://ci.adoptium.net/job/Grinder/6550/testReport/sun_security_tools_keytool_NssTest/java/NssTest/) and [sun/security/tools/keytool/NssTest.java.NssTest](https://ci.adoptium.net/job/Grinder/6550/testReport/sun_security_tools_keytool_NssTest/java/NssTest_2/)

In addition the Marist machine failed the following:
- [javax/imageio/plugins/shared/ImageWriterCompressionTest.java.ImageWriterCompressionTest](https://ci.adoptium.net/job/Grinder/6551/testReport/javax_imageio_plugins_shared_ImageWriterCompressionTest/java/ImageWriterCompressionTest/)
- [javax/imageio/plugins/shared/ImageWriterCompressionTest.java.ImageWriterCompressionTest](https://ci.adoptium.net/job/Grinder/6551/testReport/javax_imageio_plugins_shared_ImageWriterCompressionTest/java/ImageWriterCompressionTest_2/)
- [tools/jlink/JLinkReproducibleTest.java.JLinkReproducibleTest](https://ci.adoptium.net/job/Grinder/6551/testReport/tools_jlink_JLinkReproducibleTest/java/JLinkReproducibleTest/)
- [tools/jlink/JLinkReproducibleTest.java.JLinkReproducibleTest](https://ci.adoptium.net/job/Grinder/6551/testReport/tools_jlink_JLinkReproducibleTest/java/JLinkReproducibleTest_2/)

Compression tests from `jdk_imageio_0` are a file length issue so potentially a different algorithm being used. we've seen differences on zLinux compression tests in the past on certain distributions I believe.
The failure in the jlink tests from `jdk_tools_0` is not immediaately obvious and would require further analysis

**Comment by sxa** [comment]
On the above tests it looks like only the three suites `jdk_security3`, `jdk_imageio` and `jdk_tools` have failed suggesting the others have been resolved or disabled

**Comment by Haroon-Khel** [comment]
Rerunning https://ci.adoptium.net/job/Grinder/8748/console

Only 2 tests fail

java/net/HttpURLConnection/HttpURLConnectionExpectContinueTest.java.HttpURLConnectionExpectContinueTest

compiler/loopopts/superword/TestMovingLoadBeforeStore.java.TestMovingLoadBeforeStore

Rerunning both tests for 10 iterations

**Comment by Haroon-Khel** [comment]
Rerunning compiler/loopopts/superword/TestMovingLoadBeforeStore.java on other x64 linux nodes

https://ci.adoptium.net/job/Grinder/8787/console [test-ibmcloud-rhel7-x64-1](https://ci.adoptium.net/computer/test%2Dibmcloud%2Drhel7%2Dx64%2D1/)
https://ci.adoptium.net/job/Grinder/8788/console [test-docker-debian12-x64-1](https://ci.adoptium.net/computer/test%2Ddocker%2Ddebian12%2Dx64%2D1/)
https://ci.adoptium.net/job/Grinder/8789/console [test-equinix_esxi-ubuntu2204-x64-1](https://ci.adoptium.net/computer/test%2Dequinix%5Fesxi%2Dubuntu2204%2Dx64%2D1/)
https://ci.adoptium.net/job/Grinder/8790/console [test-docker-ubi8-x64-2](https://ci.adoptium.net/computer/test%2Ddocker%2Dubi8%2Dx64%2D2/)
https://ci.adoptium.net/job/Grinder/8791/console [test-docker-ubuntu2204-x64-4](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2204%2Dx64%2D4/)
https://ci.adoptium.net/job/Grinder/8792/console [test-ibmcloud-rhel6-x64-1](https://ci.adoptium.net/computer/test%2Dibmcloud%2Drhel6%2Dx64%2D1/)

**Comment by Haroon-Khel** [comment]
Taking a bit of a closer look to what the test is actually doing, https://github.com/adoptium/jdk17u/blob/master/test/hotspot/jtreg/compiler/loopopts/superword/TestMovingLoadBeforeStore.java, 

```
            byte[] a_ref = a.clone();
            byte[] a_res = a.clone();

    static void verify(String name, byte[] ref, byte[] res, byte[] orig) {
        boolean fail = false;
        for (int j = 0; j < ref.length; j++) {
            if (ref[j] != res[j]) {
                System.out.println("Wrong: " + j + ":" + ref[j] + " vs " + res[j] + " from " + orig[j]);
                fail = true;
            }
        }
        if (fail) {
            throw new RuntimeException("wrong result for array " + name);
        }
    }
```
One array is created, then cloned twice using `clone()`. The test then goes through all 3 arrays and and checks if each element is the same. If not, the test will fail

Failed test outputs look like this

```
Wrong: 116:-57 vs -58 from -59
Wrong: 117:-20 vs -21 from -22
Wrong: 118:79 vs 78 from 77
```

The elements in each array are off by 1

**Comment by Haroon-Khel** [comment]
>             ref1(a_ref, a_ref, i % 2);
            test1(a_res, a_res, i % 2);

Removing these two functions allows the test to pass. This means the clone() function is running fine. The error lies with these functions

**Comment by Haroon-Khel** [comment]
The `test1` and `ref1` functions look like they do the same thing (the code is exactly the same). If I replace the test1 execution with another ref1, so it looks like this
```
ref1(a_ref, a_ref, i % 2);
ref1(a_res, a_res, i % 2);
```
The test passes.

But if I replace the ref1 execution with a test1, 
```
test1(a_ref, a_ref, i % 2);
test1(a_res, a_res, i % 2);
```
The test fails: (the numbers surrounding the `vs` should be equal, ie -65 vs -65 or -82 vs -82)
```
Wrong: 44:-65 vs -66 from -67
Wrong: 45:-82 vs -83 from -84
Wrong: 46:-77 vs -78 from -79
```

**Comment by Haroon-Khel** [comment]
Continuing this test failure in https://github.com/adoptium/infrastructure/issues/3377 since this test failure affects more than just test-aws-rhel8-x64-1

**Comment by Haroon-Khel** [comment]
Since we are out of a release period I am adding test-aws-rhel8-x64-1 nack into the test pool
