### ISSUE TITLE
New Machine requirement: AIX 7.1TL05 for OpenJ9 builds and test

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2364]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): AIX
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): ppc64
- Provider (leave blank if it does not matter): OSUOSL
- Desired usage: Replacement for IBM Garage system which runs the OpenJ9 builds at Adopt
- Any unusual specification/setup required: Normal playbook setup :-)
- How many of them are required: 1 for now

Please explain what this machine is needed for: Replacing IBM Garage systems, as discussed with @aixtools 

Suggested name: build-osuosl-aix715-ppc64-1.

**Comment by aixtools** [comment]
System is ready at hostname: p8-java1-aix01-adopt.osuosl.org, 140.211.9.168

**Comment by sxa** [comment]
@Haroon-Khel Can we get these machines set up in jenkins and verify they can run the OpenJ9 builds without problems, with a view to decomissioning the `-ibm-` AIX machines that the OpenJ9 builds currently run on.

**Comment by Haroon-Khel** [comment]
140.211.9.168 is up and in jenkins https://ci.adoptopenjdk.net/computer/test-osuosl-aix715-ppc64-3/

@aixtools 140.211.9.169 does not have enough space in /opt and /tmp, and rootvg does not have enough free space to allocate to these filesystems. Could you please add more space to rootvg so that I can extend /tmp and /opt accordingly
```
Filesystem    GB blocks      Free %Used    Iused %Iused Mounted on
/dev/hd3           0.19      0.18    3%       68     1% /tmp
/dev/hd10opt       0.94      0.04   97%    16934    63% /opt
```
`FREE PPs:       14 (896 megabytes)`

**Comment by Haroon-Khel** [comment]
I ran a jdk11 openj9 build on 140.211.9.168 but it failed when it couldn't find Freetype (despite it being installed) https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/1082/console

I've made the symlink /usr/lib/libfreetype.a -> /opt/freeware/lib/libfreetype.a and re run the job https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/1083/console

**Comment by Haroon-Khel** [comment]
Rebuilding https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/1084/console
Made some more links
```
/usr/include/freetype2 -> /opt/freeware/include/freetype2
/usr/bin/freetype-config -> /opt/freeware/bin/freetype-config
```

**Comment by Haroon-Khel** [comment]
```
13:03:01  checking for fontconfig/fontconfig.h... yes
13:03:01  checking for FREETYPE... no
13:03:01  configure: Found freetype include files at /usr/include/freetype2 using well-known location
13:03:01  configure: Could not find /usr/lib/libfreetype.so. Ignoring location.
13:03:01  configure: Found freetype include files at /usr/include/freetype2 using well-known location
13:03:01  configure: Could not find /usr/lib/ppc64-aix-default/libfreetype.so. Ignoring location.
13:03:01  configure: Found freetype include files at /usr/include/freetype2 using well-known location
13:03:01  configure: Could not find /usr/lib/powerpc64-aix-default/libfreetype.so. Ignoring location.
13:03:01  configure: Found freetype include files at /usr/include/freetype2 using well-known location
13:03:01  configure: Could not find /usr/lib/ppc64-linux-gnu/libfreetype.so. Ignoring location.
13:03:01  configure: Found freetype include files at /usr/include/freetype2 using well-known location
13:03:01  configure: Could not find /usr/lib64/libfreetype.so. Ignoring location.
13:03:01  configure: error: Could not find freetype! You might be able to fix this by running 'sudo yum install freetype-devel'. 
```

**Comment by Haroon-Khel** [comment]
Reinstalled freetype to version 2.8-1 as this is the version on other machines
Rebuilding https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/1085/console

**Comment by Haroon-Khel** [comment]
It found `freetype`

```
13:37:24  checking for FREETYPE... yes
13:37:24  checking for freetype... yes (using pkg-config)
13:37:24  Using freetype: system
```

**Comment by aixtools** [comment]
I had been doing independent testing on what is now 'adopt08', that is why there where some non-rpm based opensource tools.

While I am not sure about how the difference in the disk-setup occurred, if it works for adopt07, then it will work for adopt08. However, I'll reinstall it so you can set it up normally.

```
root@p8-java1-adopt07:[/root]/usr/bin/df -g
Filesystem    GB blocks      Free %Used    Iused %Iused Mounted on
/dev/hd4           4.25      3.16   26%     3491     1% /
/dev/hd2           6.12      1.81   71%    48670    11% /usr
/dev/hd9var        4.56      3.89   15%     4948     1% /var
/dev/hd3           4.19      3.60   15%      358     1% /tmp
/dev/hd1          30.06     24.96   17%   172998     3% /home
/dev/hd11admin      0.12      0.12    1%        7     1% /admin
/proc                 -         -    -        -      - /proc
/dev/hd10opt       4.44      2.49   44%    44096     7% /opt
/dev/livedump      0.25      0.25    1%        4     1% /var/adm/ras/livedump

root@p8-java1-adopt08:[/root]df -g
Filesystem    GB blocks      Free %Used    Iused %Iused Mounted on
/dev/hd4           5.25      5.20    1%     3473     1% /
/dev/hd2          10.12      7.93   22%    41667     3% /usr
/dev/hd9var        5.56      5.43    3%      723     1% /var
/dev/hd3           0.19      0.18    3%       70     1% /tmp
/dev/hd11admin      0.12      0.12    1%        7     1% /admin
/proc                 -         -    -        -      - /proc
/dev/hd10opt       0.94      0.04   97%    16934    63% /opt
/dev/livedump      0.25      0.25    1%        4     1% /var/adm/ras/livedump
/dev/hd1          36.00     34.05    6%    58582     1% /home
```

**Comment by aixtools** [comment]
adopt08 is renewed to 7100-05-06-2028

**Comment by Haroon-Khel** [comment]
Setting up adopt08 now

Jdk11 openj9 build succeeded. Running a jdk17 openj9 build on adopt07.
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-openj9/33/console

**Comment by aixtools** [comment]
Need to check that adopt07 is also showing itself as 7100-05-06-2028. There are some tiny differences in the files the lpp_source was installing by default. I took the time yesterday to clean all those up.

So, once I hear adopt08 is also working I'll do an update_all, as needed on adopt07, better install the adoptium_bundle (was ojdk installp bundle) to ensure both X11 and bos.loc.* are at the correct levels.

**Comment by Haroon-Khel** [comment]
adopt08 is in jenkins. Running a jdk11 openj9 build on the machine
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/1087/console

**Comment by Haroon-Khel** [comment]
Running a jdk17 openj9 build job on adopt08 https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-openj9/35/console

The same failed on adopt07 https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-openj9/33/console
```
12:42:08  In file included from crypto/asn1/a_sign.c:22:
12:42:08  In file included from include/crypto/evp.h:11:
12:42:08  include/internal/refcount.h:21:12: fatal error: 'stdatomic.h' file not found
12:42:08  #  include <stdatomic.h>
12:42:08             ^~~~~~~~~~~~~
12:42:08  1 error generated.
12:42:08  Error while processing crypto/asn1/a_sign.c.
12:42:08  gmake[5]: *** [Makefile:841: crypto/asn1/a_sign.o] Error 1
12:42:08  gmake[5]: *** Waiting for unfinished jobs....
12:42:08  gmake[4]: *** [Makefile:174: all] Error 2
12:42:08  gmake[3]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-openj9/workspace/build/src/closed/openssl.gmk:43: build_openssl] Error 2
12:42:08  gmake[2]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-openj9/workspace/build/src/closed/custom/Main.gmk:49: j9vm-build] Error 2
12:42:08  gmake[2]: *** Waiting for unfinished jobs....
```
I think there might be an issue with the XLC16 compiler installed on the machine

**Comment by Haroon-Khel** [comment]
According to https://www.ibm.com/support/pages/apar/IV49949, `stdatomic.h` used to belong to the fileset bos.adt.include which is installed on the two boxes. @aixtools Would you know anything about this?

**Comment by Haroon-Khel** [comment]
On adopt08, i've tried building jdk17 openj9 using the system's openssl, but build process is upable to find it 

```
checking if ccache is enabled... disabled, default
checking if build directory is on local disk... no
checking for OPENSSL... checking for OPENSSL... no
configure: error: Unable to find openssl 1.0.2(and above) installed on System. Please use other options for '--with-openssl'
configure exiting with result code 1
Error: No configurations found for /home/jenkins/temurin-build/workspace/build/src.
Please run 'bash configure' to create a configuration.
```
Despite 
```
jenkins@adopt08:[/home/jenkins/temurin-build]openssl version
OpenSSL 1.0.2t  10 Sep 2019
```

**Comment by aixtools** [comment]
This is what I see on AIX - adopt07 -
```
root@p8-java1-adopt07:[/root]lslpp -L | grep opens
  openssh.base.client   7.5.102.1801    C     F    Open Secure Shell Commands
  openssh.base.server   7.5.102.1801    C     F    Open Secure Shell Server
  openssl.base            1.0.2.2002    C     F    Open Secure Socket Layer
  openssl.license         1.0.2.2002    C     F    Open Secure Socket License
  openssl.man.en_US       1.0.2.2002    C     F    Open Secure Socket Layer
```
And on adopt08
```
root@adopt08:[/root]lslpp -L | grep opens
  openssh.base.client   7.5.102.1801    C     F    Open Secure Shell Commands
  openssh.base.server   7.5.102.1801    C     F    Open Secure Shell Server
  openssl.base            1.0.2.2002    C     F    Open Secure Socket Layer
  openssl.license         1.0.2.2002    C     F    Open Secure Socket License
  openssl.man.en_US       1.0.2.2002    C     F    Open Secure Socket Layer
```

So, while the listing is a different order, OpenSSH and OpenSSL are the same at AIX BOS level (installp)

**Comment by aixtools** [comment]
That was open, but not posted - I have been trying the command from your history (@Haroon-Khel ).

- login as root
- su - jenkins
- cd term*build
- NOTE: I am not switching to bash as shell!
- ./makejdk-any-platform.sh --clean-git-repo --jdk-boot-dir /usr/java16_64 --configure-args '--disable-warnings-as-errors --with-cups-include=/opt/freeware/include --disable-warnings-as-errors --with-memory-size=7000' --target-file-name OpenJDK17U-jdk_ppc64_aix_openj9_2021-12-03-12-27.tar.gz --skip-freetype --use-jep319-certs --create-debug-image --build-variant openj9 jdk17u

- first error I got was memory related, which I fixed, as root with `chuser data=-1 jenkins`
- exit, and `su - jenkins` to get the updated limits.

now the error is:
```
checking if static build is enabled... disabled, default
configure: error: xlclang++ version output check failed, output: /home/jenkins/temurin-build/workspace/build/src/build/.configure-support/generated-configure.sh: line 75636: xlclang++: command not found
configure exiting with result code 1
Error: No configurations found for /home/jenkins/temurin-build/workspace/build/src.
Please run 'bash configure' to create a configuration.

/home/jenkins/temurin-build/workspace/build/src/make/Init.gmk:124: *** Cannot continue.  Stop.
OpenJDK make failed, archiving make failed logs
Archiving the build OpenJDK image and compressing with gzip
gzip: warning: GZIP environment variable is deprecated; use an alias or script
```

Note: this occurs on both systems. Investigating further.

**Comment by aixtools** [comment]
Currently, it seems the issue is that the build process is not able to find the **CMAKE** compiler, and that will ALSO need to be set using environment variables.

Will update with exported values - once I get, at least, to the openssl error. Nicer will be a successful build.

**Comment by aixtools** [comment]
I have updated the slack #aix channel discussion with details.

Summary: when using the approach of `git clone  https://github.com/adoptium/temurin-build.git` and running the script `makejdk-any-platform.sh` neither the existing systems (IBM garage hosted) nor new systems (OSUOSL hosted) are able to complete. Further, they stop at different points.

As such, I have no means to figure out which setup is actually better. There is a claim that the IBM hosted systems currently work - but that is apparantly different from the process used by `makejdk-any-platform.sh`.

**Comment by sxa** [comment]
The invocation of makejdk-any-platform.sh was set with a boot JDK definition in `/usr/java16_64` which did not exist on that particular machine - I believe it has now been installed. The jenkins process will automatically download a boot JDK if one does not already exist on machine, so that's explains the difference between the "claim" and what you had seen. The claim was based on the jenkins job that successfully builds on the machine: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-openj9/

**Comment by sxa** [comment]
As an update, the `stdatomic.h` is being included as a result of the build of openssl having the `-std=gnu11` option passed to the options when invoking `xlclang`, so we need to identify why that default is different between the two systems.

**Comment by aixtools** [comment]
At a different level - using the following URL for a openj9 test (not with j17 involved):
https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=ppc64_aix&TARGET=testList%20TESTLIST=testDDRExt_General_0,testDDRExt_Class_0,testDDRExt_Callsites_0,testDDRExt_JITExt_0,testDDRExt_SharedClasses_0,testDDRExtJunit_CollisionResilientHashtable_0,testDDRExtJunit_StackMap_0,testDDRExtJunit_MonitorsAndDeadlock1_0,testDDRExtJunit_MonitorsAndDeadlock1_1,testDDRExtJunit_MonitorsAndDeadlock2_0,testDDRExtJunit_MonitorsAndDeadlock2_1,testDDRExtJunit_MonitorsAndDeadlock3_0,testDDRExtJunit_MonitorsAndDeadlock3_1,testDDRExtJunit_MonitorsAndDeadlock4_0,testDDRExtJunit_MonitorsAndDeadlock4_1,testDDRExtJunit_MonitorsAndDeadlock5_0,testDDRExtJunit_MonitorsAndDeadlock5_1,testDDRExtJunit_MonitorsAndDeadlock6_0,testDDRExtJunit_MonitorsAndDeadlock6_1,testDDRExtJunit_FindExtThread_0,testOpenJ9DiagnosticsMXBean_0,TestJcmd_0,TestFileLocking_SE80_0,VmArgumentTests_0,testRASAPI_0,xlpCodeCacheTests_1,xlpCodeCacheTests_3,cmdLineTester_classesdbgddrext_0,cmdLineTester_classesdbgddrext_1,cmdLineTester_classesdbgddrext_aix_0,cmdLineTester_classesdbgddrext_aix_1,cmdLineTester_jvmtitests_hcr_OSRG_nongold_SE80_0,cmdLineTester_jvmtitests_hcr_OSRG_nongold_SE80_1,cmdLineTester_jvmtitests_hcr_OSRG_nongold_SE80_2,cmdLineTester_jvmtitests_hcr_OSRG_nongold_SE80_3,cmdLineTester_jvmtitests_hcr_OSRG_nongold_SE80_4,testSCCMLTests2_0,testSCCMLTests2_1,testSCCMLTests4_0,testSCCMLTests4_1,cmdLineTester_shrcdbgddrext_0,cmdLineTester_shrcdbgddrext_1,cmdLineTester_xlogTests_0

- test-ibm-aix71-ppc64-2 : reports 4 failures: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2808/#showFailuresLink
- test-osuosl-aix715-ppc64-4: reports 11 failures: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2809/#showFailuresLink
-  test-osuosl-aix72-ppc64-1: reports 11 failures: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2810/#showFailuresLink

- At this point - it is clear the GARAGE systems have something different, but it is not yet known what that is. The OSU systems seem to be consistent - at least with regard to this test.
- As such, the ticket to provide a new system MIGHT be considered complete as it is comparesable with what is already available with other OSU systems.
- A new ticket - focusing on the figuring out the delta between the IBM systems and OSUOSL systems may be prudent.
- In any case, I strongly recommend getting a `mksysb` image of the current IBM garage hosted systems and use that on an OSU virtual machine to study the difference before the garage system go offline.

**Comment by sxa** [comment]
OK So looking at the additional failures on the osuosl machines such as [this one](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2809/testReport/org.openj9.test.java.lang.management/TestOpenJ9DiagnosticsMXBean/testRemote_triggerDumpToFile/) - they all appear to be related to core file settings:

# Error Message
```
cannot find core file: "No such file or directory".check "ulimit -Hc" is set high enough not found expected [true] but found [false]
```

# Stacktrace
```
      java.lang.AssertionError: cannot find core file: "No such file or directory". check "ulimit -Hc" is set high enough not found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)</pre>
```

**Comment by Haroon-Khel** [comment]
I have downgraded autoconf on adopt08 to 2.69-1. A jdk17 openj9 build still failed but it made it passed the configure stage https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-openj9/44/console

```
23:32:34  Error while processing /home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-openj9/workspace/build/src/openj9/runtime/tests/jsig/main.c.
23:32:34  [ 12%] Linking CXX shared library ../../libbcvrelationships.so
23:32:34  gmake[6]: *** [runtime/tests/jsig/CMakeFiles/jsigjnitest.dir/build.make:63: runtime/tests/jsig/CMakeFiles/jsigjnitest.dir/main.c.o] Error 1
23:32:34  gmake[5]: *** [CMakeFiles/Makefile2:11540: runtime/tests/jsig/CMakeFiles/jsigjnitest.dir/all] Error 2
23:32:34  gmake[5]: *** Waiting for unfinished jobs....
23:32:34  [ 12%] Building C object runtime/tests/jniarg/CMakeFiles/jniargtests.dir/args_02.c.o
23:32:34  Scanning dependencies of target jvmti_test_src
...
23:32:48  [ 16%] Building C object runtime/tests/jvmtitests/src/CMakeFiles/jvmti_test_src.dir/com/ibm/jvmti/tests/eventVMStart/vmstart001.c.o
23:32:49  [ 16%] Linking C static library ../../../lib/libjvmti_test_src.a
23:32:50  [ 16%] Built target jvmti_test_src
23:32:50  gmake[4]: *** [Makefile:130: all] Error 2
23:32:50  gmake[3]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-openj9/workspace/build/src/closed/OpenJ9.gmk:505: build-j9] Error 2
23:32:50  gmake[2]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-openj9/workspace/build/src/closed/custom/Main.gmk:50: j9vm-build] Error 2
23:32:50  
23:32:50  ERROR: Build failed for targets 'product-images test-image debug-image' in configuration 'aix-ppc64-server-release' (exit code 2) 
```

**Comment by sxa** [comment]
So what's the difference between the run in your previous comment - number [44](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-openj9/44/console) - and the one that worked - number [42](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-openj9/42/console). They're both 7.1.5 right?

**Comment by Haroon-Khel** [comment]
```
root@p8-java1-adopt07:[/root]oslevel -s
7100-04-01-1543
root@adopt08:[/root]oslevel -s
7100-05-06-2028
```

If the 5 in 7.1.5 refers to TL, then only adopt08 is TL5

**Comment by sxa** [comment]
That's inconsistent with the names that we have in the inventory and jenkins then ... https://github.com/adoptium/infrastructure/commit/3bfcc1701169e1b53a46179aef126264983543a7

**Comment by Haroon-Khel** [comment]
I was going to suggest a reinstall of adopt07 to get it upto TL5, but the build passes only on adopt07 currently

**Comment by sxa** [comment]
So we actually have no working build machines at OSUOSL to replace the IBM Garage ones for building OpenJ9 on AIX 7.1.5 just now :'(

**Comment by Haroon-Khel** [comment]
I don't think the reason for the failure on adopt08 is to do with the fact that it is TL5, as the two test-ibm machines on which the builds pass are both TL5
```
bash-5.0# oslevel -s
7100-05-06-2016
```

**Comment by Haroon-Khel** [comment]
Package versions are exactly the same between adopt07 and adopt08

**Comment by aixtools** [comment]
adopt07 is actually also TL05, there is just a fileset that is downlevel:

```
root@p8-java1-adopt07:[/root]oslevel -s -q | head -3
Known Service Packs
-------------------
7100-05-06-2028
7100-05-06-2016
7100-05-06-2015
```
Again, the so-called vendor files downgrade the earlier installs:

```
root@p8-java1-adopt07:[/root]oslevel -s -l 7100-05-06-2028
Fileset                                 Actual Level       Service Pack Level
-----------------------------------------------------------------------------
X11.apps.aixterm                        7.1.4.0            7.1.5.31
X11.apps.rte                            7.1.4.0            7.1.5.31
X11.base.rte                            7.1.4.0            7.1.5.32
X11.compat.lib.X11R6                    7.1.4.0            7.1.5.31
X11.compat.lib.X11R6_motif              7.1.3.0            7.1.5.31
X11.motif.lib                           7.1.3.0            7.1.5.31
X11.motif.mwm                           7.1.1.0            7.1.5.31
X11.samples.apps.clients                7.1.4.0            7.1.5.31
```

I'll update_all on adopt07 to get the correct number to show.

**Comment by aixtools** [comment]
FYI: either the jobs "42" and "44" are removed, or my perms are being blocked AGAIN!

**Comment by aixtools** [comment]
> According to https://www.ibm.com/support/pages/apar/IV49949, `stdatomic.h` used to belong to the fileset bos.adt.include which is installed on the two boxes. @aixtools Would you know anything about this?

I followed the link. That was back in
```Modified date:
22 November 2013 ```

I do not see that as having any relevance - especially since autoconf back at 2.69 seems to have fixed it.

**Comment by aixtools** [comment]
> I have downgraded autoconf on adopt08 to 2.69-1. A jdk17 openj9 build still failed but it made it passed the configure stage https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-openj9/44/console
> 
> ```
> 23:32:33  [ 12%] Building C object runtime/tests/jniarg/CMakeFiles/jniargtests.dir/args_01.c.o
> 23:32:34  /home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-openj9/workspace/build/src/openj9/runtime/tests/jsig/main.c:61:8: error: duplicate 'volatile' declaration specifier [-Werror,-Wduplicate-decl-specifier]
> 23:32:34  static volatile sig_atomic_t handlerCalled = 0;
> 23:32:34         ^
> 23:32:34  1 error generated.
> 23:32:34  Error while processing /home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-aix-ppc64-openj9/workspace/build/src/openj9/runtime/tests/jsig/main.c.
> 23:32:34  [ 12%] Linking CXX shared library ../../libbcvrelationships.so
> ...

- This looks to be a coding issue (asin xlclang++ is more critical re: this statement than other compilers). 
- Further, I am somewhat concerned by the way the error is specified. I am sure the formats change, but I recall -Werror,... as more of a GNU (ie gcc) statement.

- Seems this is a result of the definition in the AIX include files:
```
/usr/include/sys/signal.h:typedef volatile int sig_atomic_t; /* accessable as an atomic entity (ANSI) */
```
So, imho, this needs a code change (for AIX)

**Comment by aixtools** [comment]
IMHO: Fixed by https://github.com/eclipse-openj9/openj9/pull/14184, and we just have to wait for the merge.

**Comment by aixtools** [comment]
The PR above, and it's cherrypick to v0.30.0-release are merged, and tests are passing. IMHO: time to close this.

**Comment by sxa** [comment]
Now that they're both machines seem to be working as expected, I agree :-)
