### ISSUE TITLE
Access request for leonarda to (docker-packet-ubuntu2004-amd-1)

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2367]
Access level:

- [ x] Non-privileged
- [ ] jenkins user
- [ ] root/Administrative
- [ ] other (Please specify):

System for which access is needed: docker-packet-ubuntu2004-amd-1

Please explain why you need this access including whether it is a temporary or permanent request:
For testing reproducible builds

**Comment by sxa** [comment]
Closing as this machine has now been decommissioned as part of #2666
