### ISSUE TITLE
Request configure permission of job build-scripts/release/refactor_openjdk_release_tool

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2371]
For linux installer publish to releases repo I will need access the job build-scripts/release/refactor_openjdk_release_tool, which currently I can't even see it. The following jobs are visible but can't see the configurations. Would be helpful if I could get the visibility of the configurations to have a big picture of the release.

job/build-scripts/job/release/job/sign_build/
/job/build-scripts/job/release/job/sign_installer/
/job/build-scripts/job/release/job/create_installer_mac/
job/build-scripts/job/release/job/create_installer_windows/

Thanks @sxa

**Comment by sxa** [comment]
@sophia-guo I think you have the permission you need now? Can this be closed?

**Comment by sophia-guo** [comment]
yep, close it as I do have the permission now. Thanks @sxa
