### ISSUE TITLE
New Machine requirement - static docker container for Ubuntu 21.10

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2395]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Ubuntu Linux
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): x64 and aarch64
- Provider (leave blank if it does not matter): Will be on an existing docker host
- Desired usage: cross-distribution linux test machines
- Any unusual specification/setup required: Needs to be a docker container :-)
- How many of them are required: 1 on each architecture, potentially replacing 21.04

Please explain what this machine is needed for: Keeping up to date with testing on the latest version of Ubuntu

**Comment by Haroon-Khel** [comment]
Ive added the new nodes under [test-docker-ubuntu2110-x64-1](https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2110-x64-1/) and [test-docker-ubuntu2110-armv7l-1](https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2110-armv7l-1/), which are running on dockerhost-equinix-ubuntu2004-x64-2 and -ubuntu2004-armv8-1 respectively.

Like https://github.com/adoptium/infrastructure/issues/2396#issuecomment-1005015689, test-docker-ubuntu2110-armv7l-1 seems to be complaining about not being able to find /usr/lib/jvm/jdk8/bin/java on the container, but again that path definitely on the container

```
root@test-equinix-ubuntu2004-armv8l-02:~# docker exec -it U2110_2235 bash
root@a071756351ed:/# ls -la /usr/lib/jvm/jdk8/bin/java
-rwxr-xr-x 1 root root 8640 Oct 19 20:56 /usr/lib/jvm/jdk8/bin/java
```

**Comment by Haroon-Khel** [comment]
Fixed see https://github.com/adoptium/infrastructure/issues/2396#issuecomment-1005655677

**Comment by Haroon-Khel** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2957/console x86
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2959/console aarch64

Jdk11 sanity tests passed on both containers. Like https://github.com/adoptium/infrastructure/issues/2396#issuecomment-1007487772, I'll add documentation regarding the setting up of these containers before closing this issue
