### ISSUE TITLE
New Machine requirement: Static docker container for Fedora 35

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2396]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Fedora Linux
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): x64 and aarch64
- Provider (leave blank if it does not matter): Will be on an existing docker host
- Desired usage: cross-distribution linux test machines
- Any unusual specification/setup required: Needs to be a docker container :-)
- How many of them are required: At least 1 on each architecture, probably replacing at least one of the Fedora33 containers on each host system

Please explain what this machine is needed for: Keeping up to date with testing on the latest version of Fedora. This will require updates to the `DockerStatic` role.

**Comment by Haroon-Khel** [comment]
Ive added the new nodes under [test-docker-fedora35-x64-1](https://ci.adoptopenjdk.net/computer/test-docker-fedora35-x64-1/) and [test-docker-fedora35-armv8l-1](https://ci.adoptopenjdk.net/computer/test-docker-fedora35-armv8l-1/), which are running on dockerhost-equinix-ubuntu2004-x64-2 and -ubuntu2004-armv8-1 respectively.

However test-docker-fedora35-armv8l-1's agent is complaining about not being able to find `/usr/lib/jvm/jdk8/bin/java` on the container, but that path does exist on the container

**Comment by sxa** [comment]
> Fixed it. I noticed that the dockerfile I used to make the container downloads an xlinux jdk8 binary, used an aarch64 binary instead

Is this now complete then? I would suggest that doing "something" (docs, whatever) to ensure that we don't install the "wrong" JVM architecture is something that should be added to, and defined, under #2070

**Comment by Haroon-Khel** [comment]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2956/console x86
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2958/console aarch64

jdk11 sanity tests passed on both new containers. Will add the documentation before closing this issue

**Comment by Haroon-Khel** [comment]
Can close now as https://github.com/adoptium/infrastructure/pull/2427 has been merged
