### ISSUE TITLE
Missing JDK 17 packages from deb/rpm repos.

### ISSUE THREAD

**Issue by PhonicUK** [adoptium/infrastructure#2399]
Some while ago the Adoptium (then AdoptOpenJDK) team published official DEB/RPM repos:

https://medium.com/adoptopenjdk/adoptopenjdk-rpm-and-deb-files-7003ba38144e

These work fine up to 16, but there are no packages for 17.

**Comment by karianna** [comment]
This is being worked on see installers repo issue 330
