### ISSUE TITLE
test-docker-fedora33-x64-2 can not run system tests due to no JAVA_HOME installed

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2412]
[systemtest.getDependency job](https://ci.adoptopenjdk.net/view/all/job/systemtest.getDependency/) requires java to be installed, when this job gets sent to test-docker-fedora33-x64-2 it fails with:

```
+ git clone https://github.com/adoptium/STF
Cloning into 'STF'...
[Pipeline] sh
+ ant -f ./aqa-systemtest/openjdk.build/build.xml -Djava.home=/home/jenkins/workspace/systemtest.getDependency/j2sdk-image/jre -Dprereqs_root=/home/jenkins/workspace/systemtest.getDependency/systemtest_prereqs configure
Error: JAVA_HOME is not defined correctly.
  We cannot execute java
```

Not sure if this is true of all the static docker nodes, but this particular one has different configuration from the bare metal nodes so should be assessed and corrected.  

I will create a separate aqa-tests issue to document the labeling schema and how one can/should expand it and suggest that we have a label (over and above the host name indication) for when we are on static docker nodes.

**Comment by sxa** [comment]
Many of the machines have `JAVA_HOME` defined in jenkins so the simple fix if this is happening is to add a JAVA_HOME variable to the jenkins agent definition then restart the agent. Has it just not been noticed on this node before or is it a new failure?

**Comment by sxa** [comment]
Hmmm a quick scan through the jenkins config files suggest most of them do NOT have that defined at the jenkins level so I'm now curious as to why this is only showing up now ... Odd

**Comment by sophia-guo** [comment]
It happened to five different docker machines according to history. So probably to all test-docker*. The job has been failed since this March or May.

**Comment by sxa** [comment]
Looking at this, most of the machines do not have `JAVA_HOME` set - I don't believe that's ever been a hard requirement.

The reason this is failing on certain machines is that for the machines where we ONLY have the adoptopenjdk or Temurin java installed, the symlinks into `/usr/bin` are not created (On many machines we have the Linux distribution's openjdk installed as a package, which will set themselves up with `/usr/bin/java` etc. symlinks)

So the outstanding questions:
1. With the aforementioned https://github.com/adoptium/aqa-tests/pull/3183 being merged now, is this still a problem?
2. If there is a specific requirement for `JAVA_HOME` to be set we should call it out (But I'd probably prefer to avoid that unless really necessary)
3. Should we ensure that a `java` (and `javac`?) is available in the PATH on all systems?

I would probably also want some convincing that adding a label specifically for docker machines was required - I don't think we have any specific outstanding problems which are definitely unresolvable other than by running on a non-dockerised machine, so I'm not sure what the value / use of that would be.

**Comment by sophia-guo** [comment]
Another failure with test-docker-fedora33-x64-2:

```
Building remotely on test-docker-fedora33-x64-2 (ci.role.test sw.os.linux hw.arch.x86) in workspace /home/jenkins/workspace/Test_Job_Auto_Gen
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to test-docker-fedora33-x64-2
```

https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/277/console

**Comment by sxa** [comment]
@smlambert Ref the last comment, is this still an issue or can I close it now?

**Comment by sophia-guo** [comment]
I don't think this is resolved. The job use ant, which requires java installed. The job runs weekly and takes one minutes. Alternatively if there is  a label defined to java installed, we could assign the job to that category.

**Comment by smlambert** [comment]
The presumption is that there is something defined in JAVA_HOME for system tests.  I do not believe we came to a satisfying conclusion to this: https://github.com/adoptium/aqa-tests/issues/2387 (related PR: https://github.com/adoptium/aqa-systemtest/pull/426), so it is expected that machines would have a JDK installed (all other test machines seem to have, presumably the idea is to have the static docker machines configured in the same way?).

**Comment by sxa** [comment]
> it is expected that machines would have a JDK installed

That statement is guaranteed to be correct as it's a prerequisite of being able to run a jenkins agent, however it's not always in the PATH or in a location defined in `JAVA_HOME`. I would have expected to see more failures here if the system tests had it as a hard requirement to be defined before things start. It sounded from earlier comments as though `getDependency` was the job that required it and it can now be tied to a specific job. We should probably thrash this one out in a discussion at some point :-)

**Comment by sxa** [comment]
Based on https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk11_hs_sanity.system_x86-64_linux/634/ progressing well I'm going to close this. It can be reopened if seen elsewhere.
