### ISSUE TITLE
New Machine requirement

### ISSUE THREAD

**Issue by Nexuscompute** [adoptium/infrastructure#2417]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix):
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc):
- Provider (leave blank if it does not matter):
- Desired usage:
- Any unusual specification/setup required:
- How many of them are required: 1

Please explain what this machine is needed for:

**Comment by Willsparker** [comment]
Spam
