### ISSUE TITLE
System unavailable: test-sxa-armv7l-ubuntu2004-odroid-1 & 2

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2418]
Both systems are down: https://ci.adoptopenjdk.net/label/sw.os.linux&&hw.arch.aarch32&&ci.role.perf

I've added ci.role.perf to node https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2004-armv7l-3/
as a temporary measure to stop hung builds.

**Comment by sxa** [comment]
Back online after power outage. These machines start up automatically but do not automatically restart the jenkins agent at the moment. I've removed the `ci.role.perf` tag from the test-docker machine as that will mess up the comparative performance results for that platform. In the future it would generally be preferable to leave them queued up until the correct machines come back, or abort them in the meantime.
