### ISSUE TITLE
System unavailable: test-packet-win2012r2-x64-1

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2431]
Less that 5G available on the machine https://ci.adoptopenjdk.net/computer/test-packet-win2012r2-x64-1/

**Comment by sxa** [comment]
This machine is a bit unhappy and I will have to go through a recovery process with Equinix in order to see if it can be brought online, otherwise it will have to be reinstalled.

**Comment by sxa** [comment]
Machine will be replaced at Equinix. Will not be fixed.
