### ISSUE TITLE
 test-docker-ubuntu2110-armv8l-1 : 13:28:02  ./get.sh: line 595: /home/jenkins/workspace/Test_openjdk8_hs_extended.functional_arm_linux/openjdkbinary/j2sdk-image/bin/java: No such file or directory

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2435]
Test build failed at the setup stage. It only happened to this machine. test-docker-ubuntu2110-armv8l-1: 

```
13:28:02  ./get.sh: line 595: /home/jenkins/workspace/Test_openjdk8_hs_extended.functional_arm_linux/openjdkbinary/j2sdk-image/bin/java: No such file or directory/home/jenkins/workspace/Test_openjdk8_hs_extended.functional_arm_linux/openjdkbinary/j2sdk-image/bin/java: No such file or directory
```
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.functional_arm_linux/131/console
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_special.functional_arm_linux/35/
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_arm_linux_testList_1/25/
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_arm_linux_testList_0/25/

**Comment by smlambert** [comment]
Think we may have already corrected this problem... this machine was mislabelled with hw.arch.aarch32 but is a 64-bit [machine](https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2110-armv8l-1/), label now been changed to hw.arch.aarch64 so should not receive arm_linux jobs anymore.

**Comment by sxa** [comment]
Agreed - my fix last week should have resolved this. I'll close this, but if it shows again (unlikely!) we can re-open.
