### ISSUE TITLE
Ansible request for aixPB, yum tag

### ISSUE THREAD

**Issue by aixtools** [adoptium/infrastructure#2436]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [ ] Bug in ansible playbook
- [ ] Request for new playbook addition
- [x] Bug in OSS support

Details:
Recently IBM (AIXToolbox) has updated their OSS information, and this has broken the current playbook, better, role `yum`.
- dependencies are not not found (e.g., says /bin/sh not found)
- some packages are not showing as available using `yum install package-x.y` (e.g., autoconf-2.69, or even autoconf).

Consequences:
- some manual work required to complete the `yum` role
- add ignore_errors: True - to get past certain packages not installing

Additionally:
- review all packages currently installed - to re-certify their need.
- whenever possible, remove `noise` packages

**Comment by sxa** [comment]
Do you have a list of the packages you've seen which are failing? There shouldn't be any `noise` packages, but we should definitely look at any that might come into that category.

**Comment by aixtools** [comment]
Been doing research.

I have resolved the immediate issues and will be posting a new (perhaps a few) PR as I work through the details.

**Comment by aixtools** [comment]
What I was working on in January has been merged or fixed elsewhere.

Closing this as no longer relevant.
