### ISSUE TITLE
AIX virtual machine(s) configured for QA-like testing

### ISSUE THREAD

**Issue by aixtools** [adoptium/infrastructure#2437]
I wish to request a new machine with only a 'test' role:

- New machine operating system (aix):
- New machine architecture (ppc64):
- Provider (leave blank if it does not matter): OSUOSL
- Desired usage: test-only
- Any unusual specification/setup required: as close as possible to customer environment, ie, only base AIX, plus tools needed to support `jenkins` ci
- How many of them are required: 1

Please explain what this machine is needed for:
The current setup of AIX systems introduces many additional libraries via OSS, some with the same name as AIX provided libraries. A system that lacks all these tools needed to build `hotspot` and/or `openj9` is needed to verify that what is built can run (ie, successfully complete) test suites without development tools active.

* As there are two more systems planned (adopt09 and adopt10) I request that at least one of these are configured as `customer-like` test systems to strengthen "QA" aka "(pre-)PROD" like testing, versus "DEV" like testing.

**Comment by smlambert** [comment]
Adding some notes to help inform about our test strategy and based on reading the Slack discussion and what I understand the intent is.

Noting that some of the test material needs to be compiled also.  For native test material, we expect to find some of the same tools needed to build Temurin.  We do not precompile test natives and push them to the machines.  

Of the 5 categories of tests we run on the public server, [openjdk, functional, system, perf, external], the first 3 of that set of categories do have a native test component and the last one is typically run in Docker containers so is excluded from platforms where we can not run Docker (currently not run on AIX).   

In terms of a [test 'pyramid'](https://martinfowler.com/articles/practical-test-pyramid.html), DEV-like testing forms the base of the pyramid (which includes the unit/regression/functional testing in openjdk and functional categories), is the first filter source code needs to run through, and finds many development defects, are fast and inexpensive to run.  As you go up the pyramid, prePROD like integration testing, system and perf tests (which include load/stress/contract tests) simulate more complex scenarios, closer to what a customer workload would be.  Moving up the test pyramid, the 'cost' of testing and triage becomes more expensive and it typically takes longer to setup/run the tests.  Finally to mimic what a large set of our consumer base does, we take and run many of the large Java frameworks and applications in the external category.  We do this in containers, to ease the burden from the infra team, to test how our binaries behave underneath the apps and in containers, and also as a mechanism to verify what we push to hub.docker.  

One supposes that you can do an exercise where you install all of the prereqs required by each of the external 3rd party applications that we have in the external category of tests, but that is 'involved' and not part of our automated testing story. 
 
We as a project would have to look at whether the benefits of such an effort would outweigh the cost (where costs include not only time and resources to run the tests, but also to maintain infrastructure and triage failures, etc).

**Comment by aixtools** [comment]
- Thx for the added info.
- re: up the pyramid - primary issue I would like to see addressed - are their hidden dependencies? Likely, this is covered by the docker based testing environments.
- I agree - more complex customer environments could be cost prohibitive, but I hope that would not discourage getting something started for AIX that approaches the testing done via docker (or `hub.docker`, new term for me).
- "external 3rd party applications" ... "external category of tests" was not something I was thinking of
- more simply perhaps - I hope to achieve a better level of assurance that the (AIX) install images, whether they be tar-ball, rpm, or installp - work without a customer needing to add anything for "the base". In particular, for tar-balls as they have no way to inform the `customer` that a pre-req is missing.

**Comment by aixtools** [comment]
@sxa - I know it is release_week this week - so I'll not bother you `this` week -- OR -- if not you, please point me at someone who can help with the correct parameters for a manual (or better jenkins) run of the basic tests. I'll contact them/she/he later.

**Comment by sxa** [comment]
If you look at any of the buid pipelines e.g. https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-hotspot/ you can see the list of test jobs that are kicked off e.g. `sanity.openjdk`, `extended.system` etc. - Those are all names that can be set as the `TARGET` parameter in grinder to run the same suites.

**Comment by sxa** [comment]
As shelley says, the five categories all have `sanity and `extended` subsets, and some have `special` too although they're not as important at this stage, and the `external` ones don't apply to AIX at present.

**Comment by aixtools** [comment]
I'll do some study before contacting anyone - IF - I remain stuck.

**Comment by aixtools** [comment]
will get back to this after the AIX 7.1 systems get refit into something else.

**Comment by aixtools** [comment]
withdrawing the request.
