### ISSUE TITLE
ProcessCheck job not working properly on Solaris

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2442]
The SXA-processCheck job is not correctly detecting java processes from the test suites, so stuck jobs can build up over time without it being noticed, leading to failures such as https://github.com/adoptium/temurin-build/issues/2829

This may be due to the `ps -fu jenkins` command output being truncated at 130 characters with the default terminal settings.

**Comment by steelhead31** [comment]
This is a suitable alternative command for processes owned and run by the jenkins user

/usr/ucb/ps -uxww| egrep -v "remoting.jar|agent.jar|grep" | egrep "java|X.*vfb|revokeall"

**Comment by steelhead31** [comment]
@sxa, can this be closed now? it does appear to be working ok.

**Comment by sxa** [comment]
Yep - thanks
