### ISSUE TITLE
test build failed to grab the jdk on test-osuosl-aix72-ppc64-2 and test-osuosl-aix71-ppc64-1

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2455]
test builds consistently failed to grab the jdk on test-osuosl-aix72-ppc64-2 and test-osuosl-aix71-ppc64-1. No issue with build-osuosl-aix71-ppc64-2

```
14:41:02  _ENCODE_FILE_NEW=UNTAGGED curl -OLJSks --user ****:**** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/284/artifact/target/aix/ppc64/hotspot/OpenJDK17U-jdk_ppc64_aix_hotspot_17.0.2_8.tar.gz
14:41:59  curl: (18) transfer closed with 128208394 bytes remaining to read
14:41:59  curl error code: 18
14:41:59  Failed to retrieve https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/284/artifact/target/aix/ppc64/hotspot/OpenJDK17U-jdk_ppc64_aix_hotspot_17.0.2_8.tar.gz, exiting. This is what we received of the file and MD5 sum:
14:41:59  ls_64: cannot access 'https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/284/artifact/target/aix/ppc64/hotspot/OpenJDK17U-jdk_ppc64_aix_hotspot_17.0.2_8.tar.gz': No such file or directory
14:41:59  md5sum_64: 'https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/284/artifact/target/aix/ppc64/hotspot/OpenJDK17U-jdk_ppc64_aix_hotspot_17.0.2_8.tar.gz': No such file or 
```

**Comment by sophia-guo** [comment]
https://github.com/adoptium/adoptium/issues/114

**Comment by aixtools** [comment]
- Since I do not have anything I am sure of o satisfy --user ****:**** I cannot test locally.
- Looking at the ulimits of jenkin of build--2 (adopt02) and test--aix72--2 I do not see any differences in settings.
- All 8 systems at OSU have about 30G freespace in /home (build--1 has 23G in /home and a 10G /scratch, the rest do not have /scratch - as that is a historical setting not yet removed from build--1).

**Comment by smlambert** [comment]
error code 18: transfer closed with outstanding read data remaining

https://stackoverflow.com/questions/1759956/curl-error-18-transfer-closed-with-outstanding-read-data-remaining

**Comment by aixtools** [comment]
- Well, that gives an idea of what to look for.
- check the levels of curl installed on the respective systems
- and, need a userid:password pair so I (or someone) can try and replicate on client CLI

- curl-levels installed: - there are differences!
```
adopt01:
curl-7.74.0-1.ppc
python-pycurl-7.43.0-1.ppc
==============
adopt02:
curl-7.74.0-1.ppc
python-pycurl-7.43.0-1.ppc
==============
adopt03:
curl-7.76.1-1.ppc
python-pycurl-7.43.0-1.ppc
==============
adopt04:
curl-7.74.0-1.ppc
python-pycurl-7.43.0-1.ppc
==============
adopt05:
curl-7.74.0-1.ppc
python-pycurl-7.43.0-1.ppc
==============
adopt06:
curl-7.74.0-1.ppc
python-pycurl-7.43.0-1.ppc
==============
adopt07:
curl-7.79.1-1.ppc
python-pycurl-7.43.0-1.ppc
==============
adopt08:
curl-7.79.1-1.ppc
python-pycurl-7.43.0-1.ppc
==============
```

**Comment by sxa** [comment]
May not be related, but [one of the builds](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-hotspot/66/consoleFull) seemed to get stuck, or hit a network communication issue that resulted in a timeout, this morning on [build-osuosl-aix71-ppc64-1](https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-1/).

**Comment by sxa** [comment]
> * Since I do not have anything I am sure of o satisfy --user ****:**** I cannot test locally.

I would suggest just trying to download the JDK tarball from https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-hotspot/lastSuccessfulBuild/artifact/workspace/target/ to try and replicate this since that does not require authentication.

**Comment by sxa** [comment]
@sophia-guo Can you provide a link to a failing job please?

**Comment by Haroon-Khel** [comment]
Failed again https://ci.adoptopenjdk.net/job/Grinder/3278/console on test-osuosl-aix72-ppc64-1

**Comment by sophia-guo** [comment]
https://ci.adoptopenjdk.net/job/Grinder/3287/console on  test-osuosl-aix715-ppc64-4

**Comment by sophia-guo** [comment]
Looks only build-osuosl-aix71-ppc64-2 doesn't have this issue.

**Comment by sophia-guo** [comment]
Also some tests failed on test aix machine and passed on build-osuosl-aix71-ppc64-2 https://github.com/adoptium/aqa-tests/issues/3073

**Comment by aixtools** [comment]
OK - I went back to #3973 and extracted these four tests from the grinder jobs listed.

```
java/beans/XMLEncoder/Test4903007.java
java/beans/XMLEncoder/Test4631471.java
java/beans/PropertyChangeSupport/Test4682386.java
javax/imageio/plugins/shared/ImageWriterCompressionTest.java
```

As the jobs used a customized JAVA (17) - I am trying to generate a single job:
```
jdk_custom
TESTLIST=java/beans/XMLEncoder/Test4903007.java,java/beans/XMLEncoder/Test4631471.java,java/beans/PropertyChangeSupport/Test4682386.java,javax/imageio/plugins/shared/ImageWriterCompressionTest.java
```

- See how this proceeds (and if I get an working job, I'll update with the re-run/re-build URL)

**Comment by aixtools** [comment]
a) tried to CLI curl from URL list that @sxa recommended. - this worked (as I expected). -- on jenkins@build-1
b) the real issue is perhaps the (piped) command syntax. Don't have that ready atm - and working in another area atm. Should someone have the complete command (including pipes) I can try replicating that.

**Comment by sxa** [comment]
> the real issue is perhaps the (piped) command syntax

What piped command syntax are you referring too? That curl command should just doing a straight download, not piping the output anywhere

**Comment by sxa** [comment]
I'm currnetly getting this repeatedly on test-osuosl-aix72-ppc64-2:
- Running `/opt/freeware/bin/curl -OLJSksv  https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-hotspot/lastSuccessfulBuild/artifact/workspace/target/OpenJDK17U-jdk_ppc64_aix_hotspot_2022-01-25-23-30.tar.gz` I get:
```
# t/lastSuccessfulBuild/artifact/workspace/target/OpenJDK17U-jdk_ppc64_aix_hotspot_2022-01-25-23-30.tar.gz                                                                                                      <
*   Trying 78.47.239.97:443...
* Connected to ci.adoptopenjdk.net (78.47.239.97) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*  CAfile: none
*  CApath: /var/ssl/certs/
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [109 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4030 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=ci.adoptopenjdk.net
*  start date: Jan  9 04:47:47 2022 GMT
*  expire date: Apr  9 04:47:46 2022 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify result: certificate has expired (10), continuing anyway.
} [5 bytes data]
> GET /job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-hotspot/lastSuccessfulBuild/artifact/workspace/target/OpenJDK17U-jdk_ppc64_aix_hotspot_2022-01-25-23-30.tar.gz HTTP/1.1
> Host: ci.adoptopenjdk.net
> User-Agent: curl/7.74.0
> Accept: */*
> 
{ [5 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.10.3 (Ubuntu)
< Date: Thu, 27 Jan 2022 10:50:08 GMT
< Content-Type: application/x-gtar
< Content-Length: 182368284
< Connection: keep-alive
< X-Content-Type-Options: nosniff
< Content-Security-Policy: sandbox; default-src 'none'; img-src 'self'; style-src 'self';
< X-WebKit-CSP: sandbox; default-src 'none'; img-src 'self'; style-src 'self';
< X-Content-Security-Policy: sandbox; default-src 'none'; img-src 'self'; style-src 'self';
< Last-Modified: Wed, 26 Jan 2022 00:15:47 GMT
< Expires: Wed, 26 Jan 2022 00:15:47 GMT
< Accept-Ranges: bytes
< Strict-Transport-Security: max-age=15768000
< 
{ [3547 bytes data]
* TLSv1.2 (IN), TLS alert, close notify (256):
{ [2 bytes data]
* transfer closed with 135479700 bytes remaining to read
* Closing connection 0
} [5 bytes data]
* TLSv1.2 (OUT), TLS alert, close notify (256):
} [2 bytes data]
curl: (18) transfer closed with 135479700 bytes remaining to read
#                                                                                                         
# 
```
It's repeatable at the moment (Different "bytes remaining" on the last line though) and this is visible whether in `/` or `/tmp`

**Comment by aixtools** [comment]
This happened to me yesterday on build-2, but a re-run went immediately:

- failed: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3308/
- ran: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3309/

So, it does not seem to be anything with the nodes per se. Most likely, something outside of the frame.

**Comment by aixtools** [comment]
recommend closing. Does not seem to be occurring. Can be reopened if the issue returns.

**Comment by sxa** [comment]
@sophia-guo Have you seen any more occurrences of this recently?

**Comment by sophia-guo** [comment]
@sxa Believe no otherwise I will leave a comment. Close it and can be reopened if it returned.
