### ISSUE TITLE
JDK17 jdk_beans_1 failure on PPC64 AIX test machine

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2457]
The following tests in jdk_beans_1 from the extended openjdk test suite fail on aix

```
java/beans/XMLEncoder/Test4903007.java
java/beans/XMLEncoder/Test4631471.java
java/beans/PropertyChangeSupport/Test4682386.java
```

`Execution failed: main' threw exception: java.lang.Error: Probable fatal error: No physical fonts found.`

```
[2021-10-20T19:35:47.583Z] java.lang.Error: Probable fatal error: No physical fonts found.
[2021-10-20T19:35:47.583Z] 	at java.desktop/sun.font.SunFontManager.lambda$getDefaultPhysicalFont$0(SunFontManager.java:1056)
[2021-10-20T19:35:47.583Z] 	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[2021-10-20T19:35:47.583Z] 	at java.desktop/sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1056)
[2021-10-20T19:35:47.583Z] 	at java.desktop/sun.font.CompositeFont.doDeferredInitialisation(CompositeFont.java:291)
[2021-10-20T19:35:47.583Z] 	at java.desktop/sun.font.CompositeFont.getSlotFont(CompositeFont.java:376)
```

https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_1/10/

trss link https://trss.adoptium.net/output/test?id=6170bee0c6182d02179274e8

**Comment by aixtools** [comment]
- Known difference between build-2 and test-3 and test-4 is the level of the OS. AIX 71-TL4 versus AIX71-TL5.
- Something else may be the libraries, especially if OSS libraries are involved - the base java (hotspot) is, afaik, built on the build-1 and build-2 systems (base OS AIX 7.1 TL4).
- The uncertainty here is why I propose action in the following areas: a) #2453 b) #2437 and c) #1886

**Comment by aixtools** [comment]
Confused: is this issue open, or closed - considering the recent addition by @sophia-guo - moved, then closed??

**Comment by sxa** [comment]
@sophia-guo I'm going to re-open this because I believe this should NOT have been closed? I'm not sure what the current test policy is - I thought it was to open a new infrastructure if the problem was identified to be elsewhere, but this one seems to have been moved (which I'm also ok with, but if it's closed too it obviously is less likely to be addressed).

**Comment by sxa** [comment]
> [2021-10-20T19:35:47.583Z] java.lang.Error: Probable fatal error: No physical fonts found.

@aixtools Based on this can you check for potentially missing AIX font packages on the 715 systems? I don't feel at the moment there is evidence to suggest this being an OSS/AIX package conflict.

**Comment by aixtools** [comment]
will do.

**Comment by sxa** [comment]
> * Not applying anything yet - release week.

Not quite sure what that output is telling me, and I was suggesting intiaily checking for font packages rather than any remidiation.

It looks like the build machine which passes has:
```
lslpp -l | grep -i font
  X11.fnt.coreX              7.1.0.0  COMMITTED  AIXwindows X Consortium Fonts 
  X11.fnt.defaultFonts       7.1.0.0  COMMITTED  AIXwindows Default Fonts 
  X11.fnt.iso1               7.1.0.0  COMMITTED  AIXwindows Latin 1 Fonts 
  X11.fnt.iso_T1             7.1.0.0  COMMITTED  AIXwindows Latin Type1 Fonts 
                                                 AIX Code Sets/Fonts 
```
and the failing one has:
```
lslpp -l | grep -i font
sxa@140.211.9.169's password: 

lslpp -l | grep -i font
  X11.fnt.defaultFonts       7.1.0.0  COMMITTED  AIXwindows Default Fonts 
                                                 AIX Code Sets/Fonts
```
Which could explain the difference and the failure on the new OSUOS 7.1.5 machines

**Comment by aixtools** [comment]
- Suggest closing this - as it appears to have been _fixed_.

```
adopt01:
  X11.fnt.coreX              7.1.0.0    C     F    AIXwindows X Consortium Fonts
  X11.fnt.defaultFonts       7.1.0.0    C     F    AIXwindows Default Fonts
  X11.fnt.iso1               7.1.0.0    C     F    AIXwindows Latin 1 Fonts
  X11.fnt.iso_T1             7.1.0.0    C     F    AIXwindows Latin Type1 Fonts
                                                   AIX Code Sets/Fonts
  fontconfig               2.11.95-4    C     R    Font configuration and
  fontconfig-devel         2.11.95-4    C     R    Font configuration and
  freetype2                    2.8-1    C     R    A free and portable font
==============
adopt02:
  X11.fnt.coreX              7.1.0.0    C     F    AIXwindows X Consortium Fonts
  X11.fnt.defaultFonts       7.1.0.0    C     F    AIXwindows Default Fonts
  X11.fnt.iso1               7.1.0.0    C     F    AIXwindows Latin 1 Fonts
  X11.fnt.iso_T1             7.1.0.0    C     F    AIXwindows Latin Type1 Fonts
                                                   AIX Code Sets/Fonts
  fontconfig               2.11.95-4    C     R    Font configuration and
  fontconfig-devel         2.11.95-4    C     R    Font configuration and
  freetype2                    2.8-1    C     R    A free and portable font
==============
adopt03:
  X11.fnt.coreX              7.2.0.0    C     F    AIXwindows X Consortium Fonts
  X11.fnt.defaultFonts       7.2.0.0    C     F    AIXwindows Default Fonts
  X11.fnt.iso1               7.2.0.0    C     F    AIXwindows Latin 1 Fonts
  X11.fnt.iso_T1             7.2.0.0    C     F    AIXwindows Latin Type1 Fonts
                                                   AIX Code Sets/Fonts
  fontconfig               2.11.95-4    C     R    Font configuration and
  fontconfig-devel         2.11.95-4    C     R    Font configuration and
  freetype2                 2.10.4-1    C     R    A free and portable font
==============
adopt04:
  X11.fnt.coreX              7.2.0.0    C     F    AIXwindows X Consortium Fonts
  X11.fnt.defaultFonts       7.2.0.0    C     F    AIXwindows Default Fonts
  X11.fnt.iso1               7.2.0.0    C     F    AIXwindows Latin 1 Fonts
  X11.fnt.iso_T1             7.2.0.0    C     F    AIXwindows Latin Type1 Fonts
                                                   AIX Code Sets/Fonts
  fontconfig               2.11.95-4    C     R    Font configuration and
  fontconfig-devel         2.11.95-4    C     R    Font configuration and
  freetype2                    2.8-1    C     R    A free and portable font
==============
adopt05:
  X11.fnt.coreX              7.1.0.0    C     F    AIXwindows X Consortium Fonts
  X11.fnt.defaultFonts       7.1.0.0    C     F    AIXwindows Default Fonts
  X11.fnt.iso1               7.1.0.0    C     F    AIXwindows Latin 1 Fonts
  X11.fnt.iso_T1             7.1.0.0    C     F    AIXwindows Latin Type1 Fonts
                                                   AIX Code Sets/Fonts
  fontconfig               2.11.95-4    C     R    Font configuration and
  fontconfig-devel         2.11.95-4    C     R    Font configuration and
  freetype2                    2.8-1    C     R    A free and portable font
==============
adopt06:
  X11.fnt.coreX              7.1.0.0    C     F    AIXwindows X Consortium Fonts
  X11.fnt.defaultFonts       7.1.0.0    C     F    AIXwindows Default Fonts
  X11.fnt.iso1               7.1.0.0    C     F    AIXwindows Latin 1 Fonts
  X11.fnt.iso_T1             7.1.0.0    C     F    AIXwindows Latin Type1 Fonts
                                                   AIX Code Sets/Fonts
  fontconfig               2.11.95-4    C     R    Font configuration and
  fontconfig-devel         2.11.95-4    C     R    Font configuration and
  freetype2                    2.8-1    C     R    A free and portable font
==============
adopt07:
  X11.fnt.coreX              7.1.0.0    C     F    AIXwindows X Consortium Fonts
  X11.fnt.defaultFonts       7.1.0.0    C     F    AIXwindows Default Fonts
  X11.fnt.iso1               7.1.0.0    C     F    AIXwindows Latin 1 Fonts
  X11.fnt.iso_T1             7.1.0.0    C     F    AIXwindows Latin Type1 Fonts
                                                   AIX Code Sets/Fonts
  fontconfig               2.11.95-4    C     R    Font configuration and
  fontconfig-devel         2.11.95-4    C     R    Font configuration and
  freetype2                    2.8-1    C     R    A free and portable font
==============
adopt08:
  X11.fnt.coreX              7.1.0.0    C     F    AIXwindows X Consortium Fonts
  X11.fnt.defaultFonts       7.1.0.0    C     F    AIXwindows Default Fonts
  X11.fnt.iso1               7.1.0.0    C     F    AIXwindows Latin 1 Fonts
  X11.fnt.iso_T1             7.1.0.0    C     F    AIXwindows Latin Type1 Fonts
                                                   AIX Code Sets/Fonts
  fontconfig               2.11.95-4    C     R    Font configuration and
  fontconfig-devel         2.11.95-4    C     R    Font configuration and
  freetype2                    2.8-1    C     R    A free and portable font
==============
adopt10:
  X11.fnt.coreX              7.2.0.0    C     F    AIXwindows X Consortium Fonts
  X11.fnt.defaultFonts       7.2.0.0    C     F    AIXwindows Default Fonts
  X11.fnt.iso1               7.2.0.0    C     F    AIXwindows Latin 1 Fonts
  X11.fnt.iso_T1             7.2.0.0    C     F    AIXwindows Latin Type1 Fonts
                                                   AIX Code Sets/Fonts
  fontconfig               2.11.95-4    C     R    Font configuration and
  fontconfig-devel         2.11.95-4    C     R    Font configuration and
  freetype2                    2.8-1    C     R    A free and portable font
```

**Comment by aixtools** [comment]
can it be closed? Or is there something I missed?

**Comment by aixtools** [comment]
Can this be closed?

**Comment by karianna** [comment]
@sophia-guo to make a final call.

**Comment by aixtools** [comment]
build-2 is no more, and the test-aix715 systems are going soon. I still recommend close - ALSO - because the version of java being tested is likely no longer current (ie, the level it failed on).

**Comment by sxa** [comment]
ping @sophia-guo - has this been seen recently? As @aixtools says we are decomissioning the AIX 7.1 systems soon so if the problem has only been seen on those then we can close this.

**Comment by aixtools** [comment]
maybe it needs a milestone to get them to close it? :)

**Comment by aixtools** [comment]
And, is this an issue with the current systems? Cleanup time!!

**Comment by aixtools** [comment]
> maybe it needs a milestone to get them to close it? :)

Nope - not working. imho: ripe for closing. I don't see any possibility for action on the original issue.

**Comment by Haroon-Khel** [comment]
These tests still fail on all machines
```
TEST: java/beans/PropertyChangeSupport/Test4682386.java
TEST: java/beans/PropertyEditor/TestFontClassJava.java
TEST: java/beans/PropertyEditor/TestFontClassValue.java
TEST: java/beans/XMLEncoder/Test4631471.java
TEST: java/beans/XMLEncoder/Test4903007.java
```

Execution failed: `main' threw exception: java.lang.UnsatisfiedLinkError: /home/jenkins/workspace/Grinder/jdkbinary/j2sdk-image/lib/libfontmanager.so: /home/jenkins/workspace/Grinder/jdkbinary/j2sdk-image/lib/libfontmanager.so, LIBPATH=/home/jenkins/workspace/Grinder/jdkbinary/j2sdk-image/lib/server:/home/jenkins/workspace/Grinder/jdkbinary/j2sdk-image/lib:/home/jenkins/workspace/Grinder/jdkbinary/j2sdk-image/../lib, LD_LIBRARY_PATH= : rtld: 0712-001 Symbol _ZNK2OT10postV2Tail6subsetEP19hb_subset_context_t was referenced from module /home/jenkins/workspace/Grinder/jdkbinary/j2sdk-image/lib/libfontmanager.so(), but a runtime definition of the symbol was not found.    
```

**Comment by Haroon-Khel** [comment]
[test-osuosl-aix73-ppc64-1](https://ci.adoptium.net/computer/test%2Dosuosl%2Daix73%2Dppc64%2D1/)
https://ci.adoptium.net/job/Grinder/11616/console

[test-osuosl-aix72-ppc64-2](https://ci.adoptium.net/computer/test%2Dosuosl%2Daix72%2Dppc64%2D2/)
https://ci.adoptium.net/job/Grinder/11617/console

[test-osuosl-aix72-ppc64-4](https://ci.adoptium.net/computer/test%2Dosuosl%2Daix72%2Dppc64%2D4/)
https://ci.adoptium.net/job/Grinder/11618/console

[test-osuosl-aix72-ppc64-3](https://ci.adoptium.net/computer/test%2Dosuosl%2Daix72%2Dppc64%2D3/)
https://ci.adoptium.net/job/Grinder/11619/console

[test-osuosl-aix72-ppc64-1](https://ci.adoptium.net/computer/test%2Dosuosl%2Daix72%2Dppc64%2D1/)
https://ci.adoptium.net/job/Grinder/11620/console

[build-osuosl-aix72-ppc64-3](https://ci.adoptium.net/computer/build%2Dosuosl%2Daix72%2Dppc64%2D3/)
https://ci.adoptium.net/job/Grinder/11621/console

[test-osuosl-aix72-ppc64-5](https://ci.adoptium.net/computer/test%2Dosuosl%2Daix72%2Dppc64%2D5/)
https://ci.adoptium.net/job/Grinder/11622/console

[test-osuosl-aix72-ppc64-6](https://ci.adoptium.net/computer/test%2Dosuosl%2Daix72%2Dppc64%2D6/)
https://ci.adoptium.net/job/Grinder/11623/console

**Comment by sxa** [comment]
All of the above 

> These tests still fail on all machines, https://ci.adoptium.net/job/Grinder/8481/testReport/ (and grinders 8482 to 8487)
> 
> ```
> TEST: java/beans/PropertyChangeSupport/Test4682386.java
> TEST: java/beans/PropertyEditor/TestFontClassJava.java
> TEST: java/beans/PropertyEditor/TestFontClassValue.java
> TEST: java/beans/XMLEncoder/Test4631471.java
> TEST: java/beans/XMLEncoder/Test4903007.java
> ```


None of these are failing in the runs from the previous comment (I wonder if the Harfbuzz fix from earlier in the year cleared them?). The only failure currently showing is in [DefaultMethodBeanPropertyTest](https://ci.adoptium.net/job/Grinder/11616/testReport/java_beans_Introspector_DefaultMethodBeanPropertyTest/java/DefaultMethodBeanPropertyTest/)

```
 java.lang.Error: could not find property 'value' in class DefaultMethodBeanPropertyTest$D1
	at BeanUtils.getPropertyDescriptor(BeanUtils.java:149)
	at DefaultMethodBeanPropertyTest.lambda$verifyProperties$0(DefaultMethodBeanPropertyTest.java:180)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1728)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at DefaultMethodBeanPropertyTest.verifyProperties(DefaultMethodBeanPropertyTest.java:181)
	at DefaultMethodBeanPropertyTest.testScenario1(DefaultMethodBeanPropertyTest.java:81)
	at DefaultMethodBeanPropertyTest.main(DefaultMethodBeanPropertyTest.java:207)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:840)

JavaTest Message: Test threw exception: java.lang.Error: could not find property 'value' in class DefaultMethodBeanPropertyTest$D1
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.Error: could not find property 'value' in class DefaultMethodBeanPropertyTest$D1
```

**Comment by sxa** [comment]
Interestingly https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix/167/tapTestReport/ doesn't show a failure in jdk_beans_1.
And specifically, the `DefaultMethodBeanPropertyTest` has run and passes: https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix/167/testReport/java_beans_Introspector_DefaultMethodBeanPropertyTest/java/

Further testing shows that it failed against the last GA build (`SDK_RESOURCE=releases`) but passes in the last EA, so this is now resolved. Closing.
