### ISSUE TITLE
Ansible request for FAQ,md and Teams URLs, descriptions

### ISSUE THREAD

**Issue by aixtools** [adoptium/infrastructure#2458]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [x] Bug in infrastructure documentation
- [ ] Request for new playbook addition

Details:
- Looking at the FAQ.md - there are two sections re: AdoptOpenJDK teams.
- besides the (expected) switch from _AdoptOpenJDK_ to `adoptium` there appears to be some changes in the teams names.
- compare AdoptOpenJDK teams (names) via: https://github.com/orgs/AdoptOpenJDK/teams (30 teams) and the names in the FAQ.
```
- [adoptopenjdk-infrastructure](https://github.com/orgs/AdoptOpenJDK/teams/adoptopenjdk-infrastructure) - write access to the repository which lets you be an official approver of PRs (
triage doesn't)
- [infrastructure](https://github.com/orgs/AdoptOpenJDK/teams/infrastructure) - higher level of access for system administrators only
- [admin_infrastructure](https://github.com/orgs/AdoptOpenJDK/teams/admin_infrastructure) - The Admin team - can force through changes without approval etc.
```
and
```
## Jenkins access

The AdoptOpenJDK Jenkins server at [https://ci.adoptopenjdk.net](https://ci.adoptopenjdk.net) is used for all the
builds and testing automation. Since we're as open as possible, general read
access is enabled. For others, access is controlled via github teams (via
the Jenkins `Github Authentication Plugin` as follows. (Links here won't work for
most people as the teams are restricted access)

- [release](https://github.com/orgs/AdoptOpenJDK/teams/jenkins-admins/members) can run and configure jobs and views
- [build](https://github.com/orgs/AdoptOpenJDK/teams/build/members) has the access for `release` plus the ability to create new jobs
- [testing](https://github.com/orgs/AdoptOpenJDK/teams/testing/members) has the same access as `build`
- [infrastructure](https://github.com/orgs/AdoptOpenJDK/teams/infrastructure/members) has the same as `build`/`testing` plus can manage agent machines
- [jenkins-admins](https://github.com/orgs/AdoptOpenJDK/teams/jenkins-admins/members) as you might expect has access to Administer anything
```
- **NOTE**: https://github.com/adoptium (No TEAMS URL, i.e., 0 teams (it seems, only 3 people).

**Comment by aixtools** [comment]
A _closely_ related .md file that needs URL updating is:
- https://github.com/adoptium/ci-jenkins-pipelines#readme
- Likely - all the readme's of all the repositories (boring :p)

**Comment by sxa** [comment]
The teams were all revised as part of https://github.com/adoptium/infrastructure/issues/1084#issuecomment-688443553 and what's in there is pretty much the current state, although you're right that the full set of doc updates didn't get done at the time by the look of it. I'll get the FAQ updates done today.
