### ISSUE TITLE
Ansible request for AIX - bootjdk tasks

### ISSUE THREAD

**Issue by aixtools** [adoptium/infrastructure#2460]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [ ] Bug in ansible playbook
- [ ] Request for new playbook addition
- [x] Request for additional info re: URL needed

Details:
- While reviewing the URL used to download (transfer and extract) the AIX GA and EA JDK versions the value for "{{ bootjdk }}" is openj9, which works with the api.adoptopenjdk.net URL, but it does not seem to work with the api.adoptium.net API interface.
- The SWAGGER UI : https://api.adoptium.net/q/swagger-ui/#/Binary/getBinary only shows 'hotspot' as a version available, e.g., https://api.adoptium.net/v3/binary/latest/11/ga/aix/ppc64/jdk/hotspot/normal/eclipse?project=jdk
- Manually changing to **openj9** https://api.adoptium.net/v3/binary/latest/11/ga/aix/ppc64/jdk/openj9/normal/eclipse?project=jdk does not fetch a file.

**Comment by aixtools** [comment]
needs os:aix tag

**Comment by sxa** [comment]
Not necessarily specific to AIX. Adoptium does not, and will not, provide OpenJ9 downloads.

**Comment by aixtools** [comment]
Well, is as much specific to AIX - for the playbooks that now have bootjdk defined as "openj9" in the global vars file.

**Comment by aixtools** [comment]
So, will need to test if everything will still work with hotspot as the global variable. ??

**Comment by sxa** [comment]
I think this needs to be a case of changing the default from `openj9` to `hotspot`. I don't think we can reasonably justify continuing to use `openj9`/`semeru` as the boot JDK when it's not supported at Adoptium.

IMHO we should test this on one machine and ensure that there are no problems with the builds of OpenJ9 when performed using a Temurin HotSpot boot JDK.

**Comment by aixtools** [comment]
> I think this needs to be a case of changing the default from `openj9` to `hotspot`. I don't think we can reasonably justify continuing to use `openj9`/`semeru` as the boot JDK when it's not supported at Adoptium.
> 
> IMHO we should test this on one machine and ensure that there are no problems with the builds of OpenJ9 when performed using a Temurin HotSpot boot JDK.

- Just one of the reasons I brought this up.
- I'll work on a PR with the global variable changed (that should make the URL work) - and then try a manual build of both hotspot and openj9.
- What also might need to be done is replace all current 'boot' images installed - I am guessing that they are all openj9 based atm

**Comment by sxa** [comment]
> What also might need to be done is replace all current 'boot' images installed - I am guessing that they are all openj9 based atm

Yeah, and that will probably be best done as a one-off manual activity on the machines (or a manual deletion followed by a playbook execution to re-install the hotspot one!)

**Comment by aixtools** [comment]
Actually, I was thinking about a 'tag' of rr_bootjdk (remove_replace_bootjdk) - which would only count for the images 8 and higher.
rr_bootjdk would only remove_replace the images currently installed.
And, I have pre and post task envisioned, and looking for the _on_error_ syntax to trap to either post tasks, or some kind of handler - to clean up the 'pre_tasks' when something unexpected happens.

**Comment by aixtools** [comment]
- Down the road - I'll look into what can be down with the API to see what version is available and compare it with what is installed.
- during testing for #2483, and with some help from you (@sxa) came to realize that for AIX we need to continue using the API URL because not all of the JDK versions that AIX is still working on are supported on the new one.
- regardless of URL used, `openjdk` as a jdk_implentation is no longer supported.

**Comment by aixtools** [comment]
Will re-visit soon.

**Comment by aixtools** [comment]
Lacking a system to test/develop this on - and/or maybe it has already been changed from what it was a year ago. In any case, the recent re-runs of the playbook on the newly cloned systems indicates that what is there is working.

Under the mom: **leave well enough alone!** - closing.
