### ISSUE TITLE
System unavailable: test-packet-ubuntu2004-x64-2

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2464]
Ping @sxa https://ci.adoptopenjdk.net/computer/test-packet-ubuntu2004-x64-2/ appears to be down. Needs a restart via the console

Lost contact mid grinder https://ci.adoptopenjdk.net/job/Grinder/3579/console

```
13:43:44  ====== als (apache-spark), iteration 6 completed (10499.616 ms) ======
13:43:44  ====== als (apache-spark), iteration 7 started ======
13:43:55  ====== als (apache-spark), iteration 7 completed (10616.616 ms) ======
13:43:55  ====== als (apache-spark), iteration 8 started ======
13:44:23  Cannot contact test-packet-ubuntu2004-x64-2: java.lang.InterruptedException
```

**Comment by sxa** [comment]
Console is dead ... Forcing a reboot of the server

**Comment by sxa** [comment]
It's back :-)

**Comment by Haroon-Khel** [comment]
@sxa Seems to be down again

**Comment by sxa** [comment]
It's back up again but I've left it offline in jenkins to see if it stays up. Do you know if anything got scheduled on it after it was recovered the first time?

**Comment by sxa** [comment]
(Doesn't look like it as there's nothing new in the jenkins workspace from the last 3½ hours)

**Comment by Haroon-Khel** [comment]
Seems to be stable (for now) https://ci.adoptopenjdk.net/computer/test-packet-ubuntu2004-x64-2/

**Comment by Haroon-Khel** [comment]
Commands that I ran:

`systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target`
and then for good measure

`root@test-packet-ubuntu2004-x64-2:~# gsettings set org.gnome.desktop.screensaver lock-enabled false`
`root@test-packet-ubuntu2004-x64-2:~# gsettings set org.gnome.desktop.lockdown disable-lock-screen true`
`root@test-packet-ubuntu2004-x64-2:~# gsettings set org.gnome.settings-daemon.plugins.power idle-dim false`
