### ISSUE TITLE
System unavailable: Several mac machines

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2467]
- Please put the system name in the title of this issue.
 - Anything not showing as online at https://ci.adoptopenjdk.net/label/mac/

- Please describe the issue:

Given the costs associated with the mac servers we should ensure that they are available, decommissioned or reassigned as appropriate. There are currently machines at macstadium, macincloud and nine which are offline. The Nine ones are a [known issue where they periodically lose their network address](https://github.com/adoptium/infrastructure/issues/2050), but the others are currently unknown. Suggest doing an audit to ensure that the machines are still available to us, and if so ensure they are live in jenkins.

Related: https://github.com/adoptium/infrastructure/issues/2378

**Comment by sxa** [comment]
Hmmm 

> test-macstadium-macos1014-x64-2 - Down in jenkins (launch fails), can ssh into, pingable

```
test-macstadium-macos1014-x64-2:~ administrator$ sudo su - jenkins
-bash: fork: Resource temporarily unavailable
```

**Comment by Haroon-Khel** [comment]
I was getting `permission denied` when trying to `ls` the jenkins home directories as `administrator`
Try switching from root to jenkins, rather than administrator to jenkins

**Comment by sxa** [comment]
> I was getting `permission denied` when trying to `ls` the jenkins home directories as `administrator` which I found odd. Try switching from root to jenkins, rather than administrator to jenkins

Looks ok to me:
```
test-macstadium-macos1014-x64-2:~ administrator$ ls /Users/jenkins
Desktop			freemarker.jar		kcpass
Documents		javasharedresources	kcpassdecode
Downloads		jdk-11.0.13+8		remoting
Library			jdk11u			remoting.jar
caches			jtreg			workspace
test-macstadium-macos1014-x64-2:~ administrator$ 
```

**Comment by sxa** [comment]
Hmmm it looks like several of the online ones aren't marked as build or test systems. @smlambert are you aware of any issue preventing us from adding the tags onto those machines?

We have https://github.com/adoptium/infrastructure/issues/1085 and https://github.com/adoptium/infrastructure/issues/1922 relating to two of the macincloud systems but we should start working towards enabling these machines (and decomissioning any we don't need!)

**Comment by sxa** [comment]
Hmmm we seem to have three macos/x64 build machines. Given the cost of these we should considker reducing that by converting at least one to be a test machine, and possibly two, keeping one of them as a "backup" build machine too if required.

https://ci.adoptopenjdk.net/label/mac&&!ci.role.test/

**Comment by smlambert** [comment]
re: https://github.com/adoptium/infrastructure/issues/2467#issuecomment-1041542350 +1 to that, especially given we are at a ratio of "for every hour of build time, we typically need 17 hrs of test time".

**Comment by sxa** [comment]
Added `ci.role.test hw.arch.x86 sw.os.osx` and removed `build` from [build-macstadium-macos1014-x64-3](https://ci.adoptopenjdk.net/computer/build-macstadium-macos1014-x64-3) to alleviate this backlog:

![image](https://user-images.githubusercontent.com/6487691/154448502-c46d1eb8-17d6-4060-acd8-ea905cc6838f.png)

**Comment by sxa** [comment]
MacStadium machines now back up, Nine machines back online after [restarting the RA service for the [TEST] group](https://github.com/adoptium/infrastructure/issues/2094).
