### ISSUE TITLE
Ensure power management features are disabled on our systems

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2468]
ref https://github.com/adoptium/infrastructure/issues/2464

test-packet-ubuntu2004-x64-2 recently had power management features enabled (sleep/hibernate) which caused the machine to suspend unexpectedly. We need to ensure power management features are disabled for our other machines

- [ ] Check to see if power management is enabled on existing systems
- [ ] Add playbook feature to ensure it is disabled 

Related commands

```
systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target
gsettings set org.gnome.desktop.screensaver lock-enabled false
gsettings set org.gnome.desktop.lockdown disable-lock-screen true
gsettings set org.gnome.settings-daemon.plugins.power idle-dim false
```

**Comment by sxa** [comment]
Looking at the last three of those - which of our servers have the GUI desktop enabled? That's likely just chewing up resources so it would be preferable to disable the desktop starting completely if it's present.

**Comment by Haroon-Khel** [comment]
For ubuntu, I found that `systemctl set-default multi-user` followed by a reboot turns off the gui. I've tested this on a ubuntu virtual box vm whose gui I could visually see.

On test-packet-ubuntu2004-x64-2: 

Before systemctl set-default multi-user
root@test-packet-ubuntu2004-x64-2:~# systemctl status gdm3
```
● gdm.service - GNOME Display Manager
     Loaded: loaded (/lib/systemd/system/gdm.service; static; vendor preset: enabled)
     Active: active (running) since Thu 2022-02-10 17:12:01 UTC; 5 days ago
   Main PID: 1489 (gdm3)
      Tasks: 3 (limit: 9425)
     Memory: 7.0M
     CGroup: /system.slice/gdm.service
             └─1489 /usr/sbin/gdm3

```
After
```
● gdm.service - GNOME Display Manager
     Loaded: loaded (/lib/systemd/system/gdm.service; static; vendor preset: enabled)
     Active: inactive (dead)
```

**Comment by Haroon-Khel** [comment]
Other distributions should have similar commands. I'll try to find them

**Comment by Haroon-Khel** [comment]
Closing since https://github.com/adoptium/infrastructure/pull/2481 is merged
