### ISSUE TITLE
Access request for andrew_m_leonard to docker-packet-ubuntu2004-intel-1 and docker-packet-ubuntu2004-amd-1

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2474]
Access level:

- [ ] Non-privileged
- [X] jenkins user
- [ ] root/Administrative
- [ ] other (Please specify):

System for which access is needed: docker-packet-ubuntu2004-intel-1 and docker-packet-ubuntu2004-amd-1

Please explain why you need this access including whether it is a temporary or permanent request:
I have a reproducible build issue where debug symbol table entries are different for identical compiled source on Intel vs AMD machines. I would like to access the build output directly to determine the problem.

**Comment by sxa** [comment]
Granted to user `aleonard@147.75.79.143` and `aleonard@139.178.85.251`. Any problems, shoot my a DM.

**Comment by sxa** [comment]
Both machines have been decomissioned as part of #2666 - if this is needed again a new issue can be raised for those.
