### ISSUE TITLE
Create CentOS stream DockerStatic images

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2478]
The [official repository for CentOS stream](https://wiki.centos.org/FAQ/CentOSStream#What_artifacts_are_built.3F) is at docker pull [quay.io/centos/centos](https://quay.io/repository/centos/centos?tab=tags):stream8. We should be able to create and use docker images based off this for testing, which can be used in preference to the now unsupported CentOS8. There is also an image for CentOS Stream 9 but we may not wish to use that yet ...

**Comment by sxa** [comment]
Related https://github.com/adoptium/infrastructure/issues/2487 (Supporting CentOS8 stream in the playbooks)

**Comment by Willsparker** [comment]
Yeah, sorry, forgot to unassign myself

**Comment by sxa** [comment]
Superceded for now by https://github.com/adoptium/infrastructure/issues/2532

**Comment by sxa** [comment]
Related: #3276
