### ISSUE TITLE
Ansible request for playbooks to support CentOS stream

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2487]
The following do not exist in the CentOS stream8 repositories so cannot be installed out of the box in `Common/vars/CentOS.yml`:
- libdwarf-devel (`Build_Tool_Packages`)
- perl-GD (`Build_Tool_Packages`)
- ccache (`Additional_Build_Tools_CentOS8`)
- fakeroot (`Additional_Build_Tools_NOT_Centos8`)
Also, the crontab tool isn't available so `crontab` tag needs to be skipped too without additional changes

**Comment by steelhead31** [comment]
I'll pick this up, could you assign it to me please @sxa ?.

**Comment by steelhead31** [comment]
libdwarf-devel equivalent can be installed with ```sudo dnf install libdwarf.x86_64```

**Comment by sxa** [comment]
Added in https://github.com/adoptium/infrastructure/pull/2577 - closing
