### ISSUE TITLE
System unavailable: Low space on ubuntu2004-intel-1

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2491]
Disk space is low on [docker-packet-ubuntu2004-intel-1](https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu2004-intel-1/)

For example the following directories are taking about 5Gb each on the `U2110_2235`/[test-docker-ubuntu2110-x64-1](https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2110-x64-1/) image (although several others have similar amounts)
```
drwxrwxr-x 6 jenkins jenkins 4096 Feb 19 16:51 Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_2
drwxrwxr-x 6 jenkins jenkins 4096 Feb 17 17:52 Test_openjdk11_hs_sanity.openjdk_x86-64_linux
drwxrwxr-x 6 jenkins jenkins 4096 Feb 12 22:24 Test_openjdk11_hs_sanity.system_x86-64_linux
drwxrwxr-x 6 jenkins jenkins 4096 Feb 13 11:40 Test_openjdk17_hs_sanity.system_x86-64_linux
drwxrwxr-x 6 jenkins jenkins 4096 Feb 15 23:07 Test_openjdk17_j9_extended.system_x86-64_linux
```
```
2362500	Test_openjdk17_j9_extended.system_x86-64_linux
3063132	Test_openjdk17_hs_sanity.system_x86-64_linux
4164208	Test_openjdk11_hs_sanity.system_x86-64_linux
5115072	Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_2
5381432	Test_openjdk11_hs_sanity.openjdk_x86-64_linux
```

**Comment by Haroon-Khel** [comment]
Freed up 20G by stopping/deleting unused containers and images

**Comment by smlambert** [comment]
What containers and/or images were cleaned up?  build ones? test ones? so we can ensure that the pipelines that produce them clean up after themselves properly.

No builds are happening when they land on this machine now, https://github.com/adoptium/aqa-tests/issues/3465#issuecomment-1067478037

```
19:30:54  java.nio.file.FileSystemException: /home/jenkins/workspace/build-scripts/jobs/jdk18/jdk18-linux-x64-temurin@tmp/durable-218c9348: No space left on device
```

**Comment by sxa** [comment]
This has been fixed as per https://github.com/adoptium/infrastructure/issues/2510#issuecomment-1097973435
