### ISSUE TITLE
System unavailable: Multiple windows machines currently offline

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2493]
- Please put the system name in the title of this issue. Anything in https://ci.adoptopenjdk.net/label/ci.role.test&&hw.arch.x86&&sw.os.windows/

- Link to any log file showing the problem: Same as above :-)

- Please describe the issue: Jenkins agent not started not started on several machines (May also affect some build ones too)

**Comment by sxa** [comment]
Still happening on these three systems:
```
   3109 JNLP4-connect connection from 13.68.134.204/13.68.134.204:000000] Refusing headers from remote: test-azure-win2012r2-x64-1 is already connected to this master. Rejecting this connection.
   3263 JNLP4-connect connection from 13.68.219.237/13.68.219.237:000000] Refusing headers from remote: test-azure-win2012r2-x64-3 is already connected to this master. Rejecting this connection.
   2835 JNLP4-connect connection from 20.185.182.137/20.185.182.137:000000] Refusing headers from remote: test-azure-win2019-x64-1 is already connected to this master. Rejecting this connection.
```

**Comment by Haroon-Khel** [comment]
For test-azure-win2012r2-x64-1, I have changed it's work directory to `D:\jenkins` as there is 32g of free space on the D drive (the machine was offline due to a lack of disk space in C:\Users\jenkins and I could not find anything significant to delete)
Running a sanity job on it to see if it lives
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4441/console

**Comment by Haroon-Khel** [comment]
test-azure-win2012r2-x64-3 is fine, but is low on disk space. I've changed it's Jenkins workspace to E:\jenkins which has 127g free.
Running a sanity grinder on it
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4442/console

**Comment by sxa** [comment]
> test-ibmcloud-win2012r2-x64-1
> build-ibmcloud-win2012r2-x64-2

@AdamBrousseau Are you able to initiate a restart of these two systems for us?

**Comment by sxa** [comment]
I've triggered a restart of test-equinix-win2012r2-x64-1

**Comment by AdamBrousseau** [comment]
rebooted, online.
>test-ibmcloud-win2012r2-x64-1
build-ibmcloud-win2012r2-x64-2

**Comment by sxa555** [comment]
Thanks Adam!

**Comment by Haroon-Khel** [comment]
test-ibmcloud-win2012r2-x64-1 is down again, and unpingable. build-ibmcloud-win2012r2-x64-2 is still up

**Comment by sxa** [comment]
FYI I'm no longer seeing the already connected messages so at least for now that seems to have been resolved by things that have changed in the last day.

**Comment by sxa** [comment]
@AdamBrousseau Can you see if test-ibmcloud-win2012r2-x64-1 can be recovered again please? We might need to keep an eye on that one - bring it up, look in the event look, then try a reboot and verify whether it comes back again. Ping me on slack when you want to do it so I can try and catch it in case it disappears of its own accod again.

**Comment by AdamBrousseau** [comment]
rebooted, online.
>test-ibmcloud-win2012r2-x64-1

**Comment by sxa** [comment]
[It's back](https://ci.adoptopenjdk.net/computer/test-ibmcloud-win2012r2-x64-1/) and has survived a subsequent reboot to apply security updates :+1:
It's running https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.perf_x86-64_windows/323/console just now

**Comment by sxa** [comment]
Although build-ibmcloud-win2012r2-x64-2 seems to have gone offline again :-( Have pinged Adam who will try and recover it again. We should take a close look at the event log when it's back to see if there's any obvious cause

**Comment by zdtsw** [comment]
both **build-azure-win2012r2-x64-1** and **build-ibmcloud-win2012r2-x64-1** went offline
maybe @AdamBrousseau can help restart the 2nd one?

**Comment by AdamBrousseau** [comment]
Took a few tries but it's back online.

Feel free to ping me on slack if I don't respond fast enough here.

**Comment by Haroon-Khel** [comment]
All but [test-equinix-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/test-equinix-win2012r2-x64-1/) are back online. The ibmcloud machines need to be restarted every now and then, thankfully we have @AdamBrousseau to do it, but it would be nice to understand why they are unstable and find a solution

**Comment by sxa** [comment]
@Haroon-Khel Can you see anything in the event log on the ibmcloud systems? Those machines have historically been stable enough for us.

**Comment by sxa** [comment]
Current offline systems:
- [test-azure-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/test%2Dazure%2Dwin2012r2%2Dx64%2D1/) (Low disk space on C:)
- [test-azure-win2012r2-x64-3](https://ci.adoptopenjdk.net/computer/test%2Dazure%2Dwin2012r2%2Dx64%2D3/) (Low disk space on C:)
- [test-azure-win2019-x64-1](https://ci.adoptopenjdk.net/computer/test%2Dazure%2Dwin2019%2Dx64%2D1/) (Low disk space on C:)
- [test-equinix-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/test%2Dequinix%2Dwin2012r2%2Dx64%2D1/) (Generally broken and likely to be decommissioned as part of #2666

**Comment by Haroon-Khel** [comment]
In [test-azure-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/test-azure-win2012r2-x64-1/), its C:\Users\jenkins.test-2012r2-1\AppData\Local\Temp directory contains some beefy files. @sxa Have you seen files like these before?
```
adoptopenjdk@test-2012r2-1 /cygdrive/c/Users/jenkins.test-2012r2-1/AppData/Local/Temp
$ du -sh * | grep G
2.1G    dst12191381147079577745.dat
2.1G    dst8808757851773313999.dat
2.1G    src10083073893585810729.dat
2.1G    src17662931351367789633.dat
2.1G    src17862466297894479515.dat
```

**Comment by Haroon-Khel** [comment]
They were not created recently
```
adoptopenjdk@test-2012r2-1 /cygdrive/c/Users/jenkins.test-2012r2-1/AppData/Local/Temp
$ ls -la *.dat
-rwx------+ 1 jenkins None 2147484671 Oct 10  2021 dst12191381147079577745.dat
-rwx------+ 1 jenkins None 2147484671 May  8 03:13 dst8808757851773313999.dat
-rwx------+ 1 jenkins None 2147484671 Oct 10  2021 src10083073893585810729.dat
-rwx------+ 1 jenkins None          0 Jun 19 01:10 src12523888732483928706.dat
-rwx------+ 1 jenkins None          0 Jun 26 01:35 src14450829699699143094.dat
-rwx------+ 1 jenkins None          0 Jul  3 02:00 src16185337324852676813.dat
-rwx------+ 1 jenkins None          0 Jul 10 22:30 src17095945012730825308.dat
-rwx------+ 1 jenkins None 2147484671 May  8 03:13 src17662931351367789633.dat
-rwx------+ 1 jenkins None 2147484671 May  8 04:37 src17862466297894479515.dat
-rwx------+ 1 jenkins None          0 Jul 10 02:01 src17894327494747906074.dat
-rwx------+ 1 jenkins None          0 Jun 26 05:03 src5264114818175128872.dat
-rwx------+ 1 jenkins None          0 Jul 10 04:11 src7319034148243782179.dat
```

**Comment by Haroon-Khel** [comment]
Same on [test-azure-win2012r2-x64-3](https://ci.adoptopenjdk.net/computer/test-azure-win2012r2-x64-3/). Some of these files are more recent than the others

```
AdoptopenJDK@test-2012r2-3 /cygdrive/c/Users/jenkins/AppData/Local/Temp
$ ls -la *.dat
-rwx------+ 1 jenkins None 2147484671 Jul  3 18:26 dst10525283875402494967.dat
-rwx------+ 1 jenkins None 2147484671 Jan  9  2022 dst1090982662380210025.dat
-rwx------+ 1 jenkins None 2147484671 Jan  9  2022 dst14090557438999081470.dat
-rwx------+ 1 jenkins None 2147484671 Oct 17  2021 dst15451742831967023501.dat
-rwx------+ 1 jenkins None 2147484671 May  8 02:44 dst16767680786618213670.dat
-rwx------+ 1 jenkins None 2147484671 Jul  3 00:59 dst5560256765629115735.dat
-rwx------+ 1 jenkins None 2147484671 Jul  4 00:14 src11220301557628620189.dat
-rwx------+ 1 jenkins None 2147484671 Jul  3 18:26 src12371769305297563754.dat
-rwx------+ 1 jenkins None 2147484671 Jul  3 00:59 src1798870126431615614.dat
-rwx------+ 1 jenkins None 2147484671 Jul 10 21:06 src5646674978054390026.dat
```

**Comment by Haroon-Khel** [comment]
And on [test-azure-win2019-x64-1](https://ci.adoptopenjdk.net/computer/test-azure-win2019-x64-1/)

adoptopenjdk@test-win2019-1 /cygdrive/c/Users/jenkins/AppData/Local/Temp
$ ls -la *.dat
-rwx------+ 1 jenkins None 5368709122 Feb  7 01:57 LargeGatheringWrite3322105129955012357.dat
-rwx------+ 1 jenkins None 5368709122 Feb 20 08:19 LargeGatheringWrite9933378702831300867.dat
-rwx------+ 1 jenkins None 2147484671 Mar 14 09:43 dst12651648640093188310.dat
-rwx------+ 1 jenkins None 2147484671 Feb  6 10:31 dst183570549372488362.dat
-rwx------+ 1 jenkins None 2147484671 Jun 19 21:07 dst4338419869657228497.dat
-rwx------+ 1 jenkins None 2147484671 Feb 20 08:22 dst5702335999286369047.dat
-rwx------+ 1 jenkins None 2147484671 Jun 19 05:08 dst7728209470019621345.dat
-rwx------+ 1 jenkins None 2147484671 Feb  7 02:00 dst9261951980099793202.dat
-rwx------+ 1 jenkins None 2147484671 Jun 19 21:06 src14810603928291401966.dat
-rwx------+ 1 jenkins None 2147484671 Jun 19 05:06 src2088681814118365386.dat

**Comment by sxa** [comment]
Almost certainly from test cases. There are definitely ones that create files of that sort of size outside the workspace (See https://github.com/adoptium/infrastructure/issues/2448 for an issue with that on AIX when `/tmp` was too small - the directory you're looking at is the equivalent of `/tmp` for windows.
