### ISSUE TITLE
Decomission some mac machines

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2496]
The two macos 10.10 machines are no longer running an operating system we support, and JDK17 will not run on them.
Also, since we do not get sponsorship from macstadium we should look at reducing our use of them in preference for the two replacement macos 12 (Monterey) machines that we now have.

I have marked the following machines offline, leaving us with one of each of macos 10.12, 10.13 and 10.14, plus the two Nine systems at 10.15 (Which still have an [issue with our RA service](https://github.com/adoptium/infrastructure/issues/2094) and will stay offline for a few days in order to check capacity). We can see if there are any capacity issues in the next week or so (Particularly with the weekend runs).

- https://ci.adoptopenjdk.net/computer/test-macincloud-macos1010-x64-1/
- https://ci.adoptopenjdk.net/computer/test-macincloud-macos1010-x64-2/
- https://ci.adoptopenjdk.net/computer/test-macstadium-macos1014-x64-2/
- https://ci.adoptopenjdk.net/computer/test-macstadium-macos1014-x64-3/
- https://ci.adoptopenjdk.net/computer/test-macstadium-macos1014-x64-4/

Completing this would remove 50% of the macstadium x64 test machines (we still have the [two build ones](https://ci.adoptopenjdk.net/label/build&&mac&&x64/), reduced from three as of https://github.com/adoptium/infrastructure/issues/2475. We should possibly look at whether we can set up one machine at macincloud as a build system to replace one of the macstadium ones.

**Comment by sxa** [comment]
NOTE: Based on https://github.com/adoptium/infrastructure/issues/1910#issuecomment-879800166 and the fact our [supported platforms page](https://adoptium.net/supported_platforms.html) says we only support 10.14 and later.

If we choose to do that then a revised policy would be to decomission the following set:

- https://ci.adoptopenjdk.net/computer/test-macincloud-macos1010-x64-1/
- https://ci.adoptopenjdk.net/computer/test-macincloud-macos1010-x64-2/
- https://ci.adoptopenjdk.net/computer/test-macstadium-macos1012-x64-1/
- https://ci.adoptopenjdk.net/computer/test-macstadium-macos1013-x64-1/
- https://ci.adoptopenjdk.net/computer/test-macstadium-macos1014-x64-4/

**Comment by sxa** [comment]
(Note: JDK11 and 17 still run ok on macos 10.13) as per https://github.com/adoptium/infrastructure/issues/1910#issuecomment-1059231378

**Comment by hendrikebbers** [comment]
Based on [wikipedia](https://en.wikipedia.org/wiki/OS_X_Yosemite#Release_history) Apple published the last security update for 10.10. in 2017. Based on this I would say that we can easily stop to build & test on 10.10

**Comment by sxa** [comment]
Agreed on PMC call - the ones prior to 10.14 can now be decomissioned as we don't claim to support them.
