### ISSUE TITLE
Investigate feasibility of providing systems for Alpine/aarch64

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2497]
This has been requested a couple of times, usually from owners of new Mac M1 systems who now find themselves unable to run the adoptium docker containers.
Sample request: https://github.com/adoptium/containers/issues/158

**Comment by zdtsw** [comment]
working on it now

**Comment by zdtsw** [comment]
took about 14 mins to finish `infrastructure$ docker build  -f ansible/docker/Dockerfile.Alpine3 .`

then when running `./build-farm/make-adopt-build-farm.sh` within the container, got error: 
`BOOT JDK: /tmp/source/temurin-build/build-farm/platform-specific-configurations/linux.sh: line 170: /usr/lib/jvm/zulu11/bin/java: No such file or directory`. even it does have /usr/lib/jvm/zulu11/bin/java
manually run got same error:
```
/usr/lib/jvm/zulu11/bin/java -version
/bin/sh: /usr/lib/jvm/zulu11/bin/java: not found
```

**Comment by sxa** [comment]
I haven't got the auto-detection for alpine working yet - can you set `TARGET_OS=alpine-linux` before running the make-adopt-build-farm.sh script. That should make it pick up the right stuff.

**Comment by sxa** [comment]
Also FYI while these look a bit odd they are correct:
```
JDK7_BOOT_DIR="/usr/lib/jvm/zulu8" \ 
JDK10_BOOT_DIR="/usr/lib/jvm/zulu11" \
```
When building any verison of the JDK it's typically the previous version that's used as the "boot JDK" during the process so we use a variable name reflecting that. However it is possible to use the 'current" version too i.e. we can boot 8 with 8, or 11 with 11. On some platforms (such as alpine) there is no JDK7 or JDK10 so we set those variables to be the location of 8 or 11 respectively instead. Removing those lines will break the builds.

**Comment by zdtsw** [comment]
> Also FYI while these look a bit odd they are correct:
> 
> ```
> JDK7_BOOT_DIR="/usr/lib/jvm/zulu8" \ 
> JDK10_BOOT_DIR="/usr/lib/jvm/zulu11" \
> ```
> 
> When building any verison of the JDK it's typically the previous version that's used as the "boot JDK" during the process so we use a variable name reflecting that. However it is possible to use the 'current" version too i.e. we can boot 8 with 8, or 11 with 11. On some platforms (such as alpine) there is no JDK7 or JDK10 so we set those variables to be the location of 8 or 11 respectively instead. Removing those lines will break the builds.

thanks, now i understand why it set to different value

**Comment by zdtsw** [comment]
btw, think https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml#L106 is skipped when i am testing build image.
probably a lot steps are skipped at the moment

**Comment by sxa** [comment]
Yes it makes sense for that not to run since we haven't built it yet. I would hope it could find a zulu one though.
On a quick look I'm guessing [roles/Common/tasks/Alpine.yml](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Alpine.yml) will need changing to be able to pull an aarch64 version as well as x64 one instead of aarch64 if there is one in the location it's looking during the build process.
I'm guessing there probably isn't one for JDK7 that can be downloaded from zulu though for the [zulu7 role](https://github.com/adoptium/infrastructure/tree/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/zulu7/tasks).

**Comment by zdtsw** [comment]
https://github.com/adoptium/infrastructure/blame/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml#L82 maybe this is the reason

**Comment by sxa** [comment]
No - that's absolutely reasonable since we haven't built a JDK for alpine/aarch64 so we can't install it.
Which is why we install zulu in the common role for alpine.

**Comment by zdtsw** [comment]
tested the built image with `make-adopt-build-farm.sh `
seems all good:
from log:
```
real	0m13.056s
user	0m12.768s
sys	0m0.512s
Your final archive was created at /tmp/build/temurin-build/workspace/build/src/build/linux-aarch64-server-release/images/OpenJDK.tar.gz
Moving the artifact to /tmp/build/temurin-build/workspace/target/
archive done.
build.sh : 17:04:16 : All done!
```
inside the container:

```
bash-5.1# ls -lat
total 186888
drwxr-xr-x    3 root     root          4096 Apr 19 17:04 .
-rw-r--r--    1 root     root     191357776 Apr 19 17:04 jdk18u-hotspot.tar.gz
drwxr-xr-x    2 root     root          4096 Apr 19 17:03 metadata
drwxr-xr-x    6 root     root          4096 Apr 19 16:50 ..
```

**Comment by sxa** [comment]
tarball looks around the right size so that looks great :-)

**Comment by zdtsw** [comment]
Hope this is the correct implementation in Jenkins cluster for how to pick up the new Alpine image by Jenkins agent :up:

**Comment by zdtsw** [comment]
build log from jenkins https://ci.adoptopenjdk.net/job/centos7_docker_image_updater/172/consoleFull
```
+ docker push index.docker.io/adoptopenjdk/alpine3_build_image:linux-aarch64

The push refers to repository [docker.io/adoptopenjdk/alpine3_build_image]

5d9e21750265: Preparing

620da8964d54: Preparing

e536492ffea6: Preparing

281abe237615: Preparing

4f4ce317c6bb: Preparing

denied: requested access to the resource is denied
```
Does it mean we need to make a change in dockerhub first to enable this new image in adoptopenjdk first? @sxa

**Comment by karianna** [comment]
> build log from jenkins https://ci.adoptopenjdk.net/job/centos7_docker_image_updater/172/consoleFull
> 
> ```
> + docker push index.docker.io/adoptopenjdk/alpine3_build_image:linux-aarch64
> 
> The push refers to repository [docker.io/adoptopenjdk/alpine3_build_image]
> 
> 5d9e21750265: Preparing
> 
> 620da8964d54: Preparing
> 
> e536492ffea6: Preparing
> 
> 281abe237615: Preparing
> 
> 4f4ce317c6bb: Preparing
> 
> denied: requested access to the resource is denied
> ```
> 
> Does it mean we need to make a change in dockerhub first to enable this new image in adoptopenjdk first? @sxa

Not sure - @gdams

**Comment by sxa** [comment]
Definitely not a temporary glitch - it's still failing today at https://ci.adoptopenjdk.net/job/centos7_docker_image_updater/
ping @gdams

**Comment by gdams** [comment]
Looks like the adoptopenjdk bot didn't have push access to that repo... I've just added it:
<img width="1159" alt="Screenshot 2022-05-16 at 11 01 54" src="https://user-images.githubusercontent.com/20224954/168568848-124534c7-02dd-4353-b357-c5216cf7f3f8.png">

@sxa please try again

**Comment by sxa** [comment]
LGTM - Alpine/aarch64 appears to have completed at https://ci.adoptopenjdk.net/job/centos7_docker_image_updater/
