### ISSUE TITLE
sanity.perf regularly fails to be able to run on test-sxa-armv7l-ubuntu2004-odroid-2

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2499]
Details:

Tests are not failing, as we do not get to the point where they can even be run.

- test suite/name? sanity.perf jobs often unable to setup and run (https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.perf_arm_linux/) 
- Is there an existing issue elsewhere covering this? Did not find an infra issue for this problem
- Which machine(s) does it work on? None, there are no other online nodes labelled to receive perf jobs https://ci.adoptopenjdk.net/label/sw.os.linux&&hw.arch.aarch32&&ci.role.perf/ 
- Which machine(s) does it fail on? test-sxa-armv7l-ubuntu2004-odroid-2
- Do you have a link to a Grinder re-run if the test with the failure?
[Grinder rerun link](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?TARGET=sanity.perf&SDK_RESOURCE=upstream&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&EXTRA_DOCKER_ARGS=&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&PLATFORM=arm_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&LABEL=test-sxa-armv7l-ubuntu2004-odroid-2&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&JDK_VERSION=11&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk11u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-arm-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=dev&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&TKG_SHA=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&NUM_MACHINES=&OPENJDK_SHA=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=perf&UPSTREAM_JOB_NUMBER=6&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)

Any other details:
Unable to setup and run tests, console output is:
```
Exception: java.io.IOException: Remote call on JNLP4-connect connection from [...] failed
[Pipeline] }
```

**Comment by sxa** [comment]
Restarted jenkins agent on both systems and the seem to be starting jobs without that error now:
- https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.perf_arm_linux/178/console
Although I've no idea why 177 is assigned to the executor on the other machine but is not progressing at the time I'm posting this.

**Comment by sxa** [comment]
Looking fairly reliable from the runs I've done on both systems, therefore closing.

One of the machines was running the jenkins agent with a Java17, which I think may not be reliable. More investigation potentially required since we generally run with JDK8, or on 11 on some systems.
