### ISSUE TITLE
SSDF PW6.1: Documentation of build servers, compilers, tools, build process

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2503]
```
PW.6.1: Use securely configured compilers and build tools
Adoptium will maintain process documentation detailing all build servers used, all compilers & tools and versions of each used for the offering and summarizing the build process for each.
```
ref https://github.com/adoptium/adoptium/issues/124

This issue will be used to discuss the documentation concerning our build servers, compilers, tools etc. (any current documentation and ideas/improvements to the documentation)

**Comment by sxa** [comment]
Current build environments:

JDK | Platform | Build env | compiler | Other info
--- | --- | --- | --- | ---
8,11 | Linux/x64 | CentOS6 | GCC [1] | glibc 2.1
20+ | Linux/x64 | CentOS7 | GCC [1] | glibc 2.17
All | Linux/arm32 | Ubuntu 1604 | GCC [1] | glibc 2.23
All | Linux (others) | CentOS7 | GCC [1] | glibc 2.17
8 | Windows/x86 | Server 2012 | VS2017 - CL  19.16.27038 |
11,17 | Windows/x86 | Server 2012 | VS2019 - CL 19.27.29111 |
20+ | Windows/x86 | Server 2022 | VS2019 - CL 19.29.30146 |
All | Macos/x64 | 10.14 (18.7.0) | clang-1001.0.46.4 |
All (No 8) | Macos/aarch64 | 11 (20.1.0) | clang-1200.0.32.29 |
All | Alpine/x64 | 3.15.6 | GCC 10.3.1 | Default compiler Alpine 10.3.1_git20211027
All | Alpine/aarch64 | 3.15.4 | GCC 10.3.1 | Default compiler Alpine 10.3.1_git20211027
8,11 | AIX | 7.2 (7200-02)| xlc 13.1.3 (13.01.0003.0007) |  
17+ | AIX | 7.2 (7200-02 | xlc 16.1.0 (16.01.0000.0011) |
8 | Solaris (Both) | 10 1/13 | Studio 12.3 (C 5.12) | 


[*] LInux gcc levels are 7.5 for JDK8 and 11, 10.3.0 for JDK17 and 11.2.0 for JDK20+

**Comment by sxa** [comment]
Note that https://github.com/adoptium/infrastructure/issues/1270#issuecomment-1632305063 covers trying to get windows machines windows set to a consistent compiler (which will likely mean bumping older versions up to Win2022 with the fixed compiler layout)

**Comment by sxa** [comment]
Similarly https://github.com/adoptium/temurin-build/issues/3354 covers trying to switch to building on a newer macos.

**Comment by sxa** [comment]
@andrew-m-leonard In terms of the information in the table above, do you think anything more needs to be captured in terms of giving people the information on our environment. The SBOMs will likely be a more detailed list of each build, but would you advocate adding any other important information to this as a "one page" summary?

**Comment by andrew-m-leonard** [comment]
@sxa I think it's enough, possibly we should expand the gcc [1] note as to the Trusted source of the gcc compiler?

**Comment by sxa** [comment]
Other items will be covered by the SBOM contents. Closing.
