### ISSUE TITLE
All system tests failing on mac machine(s)

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2508]
To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name? sanity.system and extended.system
- Is there an existing issue elsewhere covering this? seen during pre-release triage (https://github.com/adoptium/aqa-tests/issues/3465)
- Which machine(s) does it work on? N/A
- Which machine(s) does it fail on? [test-macincloud-macos1201-x64-1](https://ci.adoptopenjdk.net/computer/test-macincloud-macos1201-x64-1) - need to verify if they fail on other machines
- Do you have a link to a Grinder re-run if the test with the failure? [rerun link](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.system&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=18&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk18&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk18%2Fjdk18-mac-x64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=dev&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&TKG_SHA=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=19&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)

Any other details:
```
20:22:54  Unable to determine amount of free space for test results, terminating
20:22:54  Unable to parse df -k /Users/jenkins/workspace/Test_openjdk18_hs_sanity.system_x86-64_mac/aqa-tests/TKG/../TKG/output_16471309591232/TestJlmRemoteMemoryAuth_0 output:
20:22:54  df: getattrlist failed: Input/output error
```

**Comment by Haroon-Khel** [comment]
I ran some sanity system grinders when I looked at this issue last week. Seems to only affect  test-macincloud-macos1201-x64-1:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3848/console. I ran the same tests on two other machines, nothing failed:
test-macstadium-macos1014-x64-3 
(https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3847/console) and 
build-macstadium-macos1014-x64-1
(https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3846/console)

If I am not able to detect why the tests are failing on test-macincloud-macos1201-x64-1 in time for the release, I'll disable it for the release

**Comment by Haroon-Khel** [comment]
I think the error comes from the `df` command on test-macincloud-macos1201-x64-1:

```
test-macincloud-macos1201-x64-1:TKG jenkins$ df -k .
df: getattrlist failed: Input/output error
Filesystem   1024-blocks     Used Available Capacity iused     ifree %iused  Mounted on
/dev/disk1s1   125624280 64419200  43217540    60% 1238968 432175400    0%   /System/Volumes/Data
```
Other machines do not produce the line `df: getattrlist failed: Input/output error`, and I'm guessing the tests scripts do not expect it

**Comment by smlambert** [comment]
Does that mean the df command behaves differently on certain machines? (like its a different version that takes different arguments? ). 

Also seen on [test-macincloud-macos1201-x64-1](https://ci.adoptopenjdk.net/computer/test-macincloud-macos1201-x64-1) reported in https://github.com/adoptium/adoptium/issues/133#issuecomment-1077892278

**Comment by sxa** [comment]
> Does that mean the df command behaves differently on certain machines? (like its a different version that takes different arguments? ).

No - it's coming out with normal output but is also showing an error trying to retrieve some information. It's not giving a non-zero exit code and the message is being sent to `stderr` so shouldn't affect normal parsing of the main output.

I've just had a look in a few test repos but I can't see where the code is that's producing that error message - can someone point us at it?

**Comment by smlambert** [comment]
Believe its a [check_free_space function](https://github.com/adoptium/STF/blob/master/stf.core/scripts/stf.pl#L725) of the STF framework

```
07:26:35  STF 06:26:33.780 - =========================   S T F   =========================
07:26:35  systemtest-prereqs has been processed, and set to: /Users/jenkins/workspace/Test_openjdk18_hs_sanity.system_x86-64_mac/jvmtest/system/systemtest_prereqsRetrieving amount of free space on drive containing /Users/jenkins/workspace/Test_openjdk18_hs_sanity.system_x86-64_mac/aqa-tests/TKG/../TKG/output_16480347789815/TestJlmRemoteMemoryNoAuth_1
07:26:35  Unable to determine amount of free space for test results, terminating
07:26:35  Unable to parse df -k /Users/jenkins/workspace/Test_openjdk18_hs_sanity.system_x86-64_mac/aqa-tests/TKG/../TKG/output_16480347789815/TestJlmRemoteMemoryNoAuth_1 output:
07:26:35  df: getattrlist failed: Input/output error
07:26:35  Filesystem   1024-blocks     Used Available Capacity iused     ifree %iused  Mounted on
07:26:35  /dev/disk1s1   125624280 66122004  41514736    62% 1239867 415147360    0%   /System/Volumes/Data
07:26:35  
```
