### ISSUE TITLE
git/config.lock file blocking builds from running on build-marist-rhel77-s390x-1

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2509]
Builds are failing on [build-marist-rhel77-s390x-1](https://ci.adoptopenjdk.net/computer/build-marist-rhel77-s390x-1) with this error
```
01:27:03  Caused by: hudson.plugins.git.GitException: Command "/usr/local/bin/git config remote.origin.url https://github.com/adoptium/ci-jenkins-pipelines.git" returned status code 4:
01:27:03  stdout: 
01:27:03  stderr: error: failed to write new configuration file /home/jenkins/workspace/workspace/build-scripts/jobs/jdk18/jdk18-linux-s390x-temurin/.git/config.lock
01:27:03  
```

Seen as part of pre-release triage: https://github.com/adoptium/aqa-tests/issues/3465#issuecomment-1067477959

**Comment by sxa** [comment]
I don't believe this has been seen subsequently, and the jdk18 path referenced no longer exists, therefore closing.
