### ISSUE TITLE
JDK18 Alpine Linux jdk_net_0 failures

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2517]
ref https://github.com/adoptium/aqa-tests/issues/3487

The following tests from jdk_net in the extended openjdk suite fail on alpine linux due to the container environment 

```
com/sun/net/httpserver/simpleserver/CommandLinePositiveTest.java.CommandLinePositiveTest
com/sun/net/httpserver/simpleserver/jwebserver/CommandLinePositiveTest.java.CommandLinePositiveTest
java/net/InetAddress/HostsFileOrderingTest.java.HostsFileOrderingTest
java/net/InetAddress/InternalNameServiceTest.java.InternalNameServiceTest
java/net/InetAddress/InternalNameServiceWithHostsFileTest.java.InternalNameServiceWithHostsFileTest
```

ref https://github.com/adoptium/aqa-tests/issues/3487#issuecomment-1081033644
>these tests will become blocking once we want to publish this platform to the Adoptium marketplace, so we should raise an infrastructure issue to get the IPv6 configuration addressed for the static docker hosts.

**Comment by Haroon-Khel** [comment]
`com/sun/net/httpserver/simpleserver/CommandLinePositiveTest.java.CommandLinePositiveTest`
`com/sun/net/httpserver/simpleserver/jwebserver/CommandLinePositiveTest.java`


```
15:06:19  [simpleserver]:/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java -m jdk.httpserver -b ::0
15:06:19  [simpleserver] Error: server config failed: java.net.SocketException: Unsupported address type
15:06:19  	Thread[Signal Dispatcher,9,system] stack: (length = 0)
```

`java/net/InetAddress/HostsFileOrderingTest.java.HostsFileOrderingTest`

```
15:39:12  STDERR:
15:39:12  Expected addresses:
15:39:12  [2001:db8:85a3:0:0:8a2e:370:7334, 2001:85a3:db8:0:0:8a2e:7334:370, 2001:dead:beef:0:0:8a2e:1239:212, 192.168.239.11, 192.168.14.10, 192.168.129.16]
15:39:12  Resolved addresses:
15:39:12  [192.168.239.11, 192.168.14.10, 192.168.129.16]
15:39:12  java.lang.Exception: failures: 1
```

`java/net/InetAddress/InternalNameServiceTest.java.InternalNameServiceTest`

```
15:39:12  STDOUT:
15:39:12   TEST HOST TO  IP ADDRESS MAPPINGS 
15:39:12  UnknownHostException as expected for host host3.sample-domain
15:39:12  UnknownHostException as expected for host host4.sample-domain
15:39:12  UnknownHostException as expected for host host5.sample-domain
15:39:12  STDERR:
15:39:12  java.net.UnknownHostException: Unable to resolve host host-ipv6.sample-domain in hosts file TestHosts
15:39:12  	at java.base/java.net.InetAddress$HostsFileResolver.checkResultsList(InetAddress.java:1220)
15:39:12  	at java.base/java.net.InetAddress$HostsFileResolver.lookupByName(InetAddress.java:1193)
```

`java/net/InetAddress/InternalNameServiceWithHostsFileTest.java`

```
15:39:12  STDOUT:
15:39:12  ############################  InetAddress == testHost.testDomain/10.2.3.4
15:39:12  retrieved address == [10, 2, 3, 4] equal to expected address == [10, 2, 3, 4]
15:39:12  STDERR:
15:39:12  java.net.UnknownHostException: Unable to resolve host ip6-localhost in hosts file /home/jenkins/workspace/Grinder/aqa-tests/openjdk/openjdk-jdk/test/jdk/java/net/InetAddress/TestHosts-III
15:39:12  	at java.base/java.net.InetAddress$HostsFileResolver.checkResultsList(InetAddress.java:1220)
15:39:12  	at java.base/java.net.InetAddress$HostsFileResolver.lookupByName(InetAddress.java:1193)
```

**Comment by Haroon-Khel** [comment]
Added the following to /etc/docker/daemon.json
```
{
  "ipv6": true,
  "fixed-cidr-v6": "fd00::/80"
}
```
on the host and restarted docker with `systemctl`

So far both 

`com/sun/net/httpserver/simpleserver/CommandLinePositiveTest.java.CommandLinePositiveTest`
`com/sun/net/httpserver/simpleserver/jwebserver/CommandLinePositiveTest.java`

pass on test-docker-alpine314-x64-2

https://ci.adoptopenjdk.net/job/Grinder/4232/console
https://ci.adoptopenjdk.net/job/Grinder/4233/console

Rerunning jdk_net https://ci.adoptopenjdk.net/job/Grinder/4234/console on test-docker-alpine314-x64-2

**Comment by smlambert** [comment]
re: https://github.com/adoptium/infrastructure/issues/2517#issuecomment-1084815153 That's great news @Haroon-Khel !

**Comment by Haroon-Khel** [comment]
Im running jdk_net on another docker static container on the same host (non alpine) https://ci.adoptopenjdk.net/job/Grinder/4244/console. I expect these tests to pass now on any container on this host, https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu2004-intel-1/

**Comment by Haroon-Khel** [comment]
Closing since https://github.com/adoptium/infrastructure/pull/2520 is merged
