### ISSUE TITLE
Ansible request for native JDK11 on macos/aarch64

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2518]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [x] Missing install
- [ ] Bug in ansible playbook
- [ ] Request for new playbook addition

Details: For now I've put a "beta" Temurin into the jenkins home directory on the two build machines and set that location in the machine's confituration in jenkins as `JDK10_BOOT_DIR` but we should look at installing this properly once JDK 11.0.15 is released later this month if we make it a GA platform.

**Comment by sxa** [comment]
This has been released today so we can move forward with this now.

**Comment by Haroon-Khel** [comment]
It would be good to get https://github.com/adoptium/infrastructure/pull/2512 in for this issue

**Comment by sxa** [comment]
@Haroon-Khel Does 2572 cover this? So can this now be closed?

**Comment by Haroon-Khel** [comment]
This can be closed
