### ISSUE TITLE
Create UBI8 DockerStatic images

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2532]
Red Hat UBI is a minimal version of RHEL which is available as docker images. These form an ideal basis for cloud deployments, and are free to use, so it would make sense for us to test and support running on them, so we should include them in the `DockerStatic` image set. They can be pulled from https://hub.docker.com/u/redhat (or `docker pullregistry.access.redhat.com/ubi8/ubi`)
There is also a `ubi8-minimal` which we could try as well, but it will need to be tested to see if it's good enough for running tests on.

**Comment by steelhead31** [comment]
I shall investigate this.

**Comment by sxa** [comment]
Merged via https://github.com/adoptium/infrastructure/pull/2557
