### ISSUE TITLE
Some nodes with questionable shortage of disk space?

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2534]
The following nodes seem rather short on disk space:

- https://ci.adoptopenjdk.net/computer/test-azure-win2016-x64-1/
- https://ci.adoptopenjdk.net/computer/test-azure-win2019-x64-1/
- https://ci.adoptopenjdk.net/computer/test-ibmcloud-ubuntu1604-x64-1/
- https://ci.adoptopenjdk.net/computer/test-osuosl-ubuntu2004-ppc64le-1/

**Comment by andrew-m-leonard** [comment]
@Haroon-Khel could you take a peek at these please? thanks

**Comment by Haroon-Khel** [comment]
I've kept the 2 windows machines offline as I cannot find anything significant to delete from their respective workspaces. Looking into the other 2

**Comment by Haroon-Khel** [comment]
Cleared up lots of unused docker images on test-ibmcloud-ubuntu1604-x64-1, now has 50G free. Cleared up some space on test-osuosl-ubuntu2004-ppc64le-1, now has 27G free
