### ISSUE TITLE
New Machine requirement: Ubuntu 22.04 (Static Docker)

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2537]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Ubuntu Linux 22.04
- New machine architecture (e.g. x64/aarch64/arm32/ppc64/ppc64le/sparc): x64 and aarch64 for now)
- Provider (leave blank if it does not matter):
- Desired usage: Testing on latest Ubuntu LTS
- Any unusual specification/setup required:
- How many of them are required: 1 per architecture

Please explain what this machine is needed for: Testing on latst ubuntu LTS (released today)

**Comment by zdtsw** [comment]
working on this one
