### ISSUE TITLE
Update XLC16 to FP11 on AIX build machines

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2575]
We have tested the new FP11 of the XLC11 on two of the AIX machines (test-osuosl-aix715-ppc64-2 and build-osuosl-aix71-ppc64-1) and it successfully builds XLC11 now that the prereq of XLC16 has been put into openjdk.

We should therefore verify that the other builds using XLC16 are unaffected, and assuming they are still good, we should install it on the other machines. For now I have marked build-osuosl-aix71-ppc64-1 offline so that the builds will all run on the upgraded machine in order to verify it.

**Comment by sxa** [comment]
Builds on the upgraded system:
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/65/console
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/51/console
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-aix-ppc64-temurin/46/console
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-aix-ppc64-temurin/61/console

**Comment by sxa** [comment]
Those failed due to issues with files in /tmp. Re-running:
Builds on the upgraded system:
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/66/console
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-aix-ppc64-temurin/52/console
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-aix-ppc64-temurin/47/console
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-aix-ppc64-temurin/62/console

**Comment by sxa** [comment]
(NOTE: This is a subtask required to fully complete https://github.com/adoptium/temurin-build/issues/2882)

**Comment by aixtools** [comment]
FYI: All AIX systems have XLC-FP11 installed (last Thursday)

**Comment by sxa** [comment]
[LGTM](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/92/console) - re-enabled the `build` tags
