### ISSUE TITLE
Jenkins server unable to run test pipeline

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2578]
See Grinders https://ci.adoptopenjdk.net/job/Grinder/4821/ through https://ci.adoptopenjdk.net/job/Grinder/4826/ for examples...

```
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/adoptium/aqa-tests.git # timeout=10
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/adoptium/aqa-tests.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:1003)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1244)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1308)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:159)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:70)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:311)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Caused by: hudson.plugins.git.GitException: Command "git config remote.origin.url https://github.com/adoptium/aqa-tests.git" returned status code 4:
stdout: 
stderr: error: failed to write new configuration file /home/jenkins/.jenkins/workspace/Grinder@script/7d272c0688f17ab4e5b2f6ce77a7dc9cf4df33ff05c3a95eddd38682ef795b79/openjdk-tests/.git/config.lock

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2671)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2601)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2597)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1968)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1980)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.setRemoteUrl(CliGitAPIImpl.java:1594)
	at hudson.plugins.git.GitAPI.setRemoteUrl(GitAPI.java:161)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:991)
	... 8 more
ERROR: Error fetching remote repo 'origin'
ERROR: Maximum checkout retry attempts reached, aborting
Finished: FAILURE
```

**Comment by zdtsw** [comment]
This probably related to the permission when in the jenkins job's workspace.
Someone need to login to the Jenkins controller and manually remove these lock or change mod/owner of it

**Comment by zdtsw** [comment]
**I got error too, looks like the reason is out of diskspace, not permission**
```
hudson.plugins.git.GitException: Command "git checkout -f 5ef0745eea12d418844cef0d3f50d9cc690c2902" returned status code 128:
stdout: 
stderr: fatal: sha1 file '/home/jenkins/.jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-sparcv9-temurin/.git/index.lock' write error. Out of diskspace
```

**Comment by sxa** [comment]
The `workspace` directory on the controller (build in) node had run out of space. It is on a separate 1Tb file system so I'm a little surprised it's managed to fill all that up. I'll do a quick cleanup of some things on there and we can look separately about how to manage that disk. Everything on there should be relatively short lived so a prune of things that haven't been tuched in a while would seem prudent. I do have a monitor on the size of that file system over time so will investigate and see if we can identify what the big culprits were

**Comment by sxa** [comment]
It's up to 64Gb free now which should free it up for today while I look into it closer. Mostly clearing up directories with @x (the ones created when you run multiple versions of a job in parallel) - https://ci.adoptopenjdk.net/job/Grinder/4832/console seems to be runnign through successfully now.

I'll close this for now since the urgent problem is now resolved, but will likely add the results of investigation to it.

**Comment by sxa** [comment]
Jobs in `build-scripts` are in total using around 10% (100Gb) of the space, mostly because they're shuffling all the built artefacts around for each version.

Test jobs are using between 200-600Mb each and there are over 3000 of them, and it looks like it's the later ones that are using a lot more (Has `aqa-tests` balooned in size which could be a cause? The old OpenJ9 `xl` tests from 2021 are about 60Mb, the non-xl ones are now around 650Mb):

```
jenkins@jenkins-hetzner-ubuntu2004:~/workspace$ du -sk Test_openjdk8_j9_sanity.system_x86-64_linux*
654264  Test_openjdk8_j9_sanity.system_x86-64_linux@script
64032   Test_openjdk8_j9_sanity.system_x86-64_linux_xl@script
jenkins@jenkins-hetzner-ubuntu2004:~/workspace$
```

**Comment by sxa** [comment]
We still have openjdk15 and openjdk16 jobs in there, which can now be removed (I'll tarball them up for now) although those do show the differences.
The Test_openjdk15 jobs were using about 65Mb each, the openjdk16 ones seem to have some that are 200Mb and some 400M (seems like a platform variance - arm and alpine linux are smaller then e.g. normal x64_linux). It's also worth noting that the use of Dynamic Parallel testing has increased the amount of space being used, as each of those jobs has it's own directory in the jenkins controller workspace.

**Comment by sxa** [comment]
OK The ones that are 400Mb instead of 200Mb are becuase they have two copies of the source material - `openjdk-tests` and `aqa-tests` so I can clear up the old name without any problems.

**Comment by sxa** [comment]
Looking at one of the directories - openjdk-tests in January 2021 was at SHA 1cd5ad1ca10fd1b84e0982437d6d3009b73f0a39 and was 72Mb in size, aqa-tests today at SHA b1b6a4b5c3f2ad2d24465ccdbeda6600a4a23532 takes up 220Mb so multiplied up that is a significant increase in disk space requirements.

**Comment by sxa** [comment]
Removing the following from the `workspace` directory on the controller:
All OpenJ9 _xl directories (Total: 201, TBC Gb freed)
All `Test_openjdk15*` directories (Total: 136 - was 184 with j9xl, TBC Gb freed)
All `Test_openjdk16*` directories (Total: 205 - was 259 with j9xl, TBC Gb freed)
All `Test_openjdk*/openjdk-tests` directories (Total: 1508, TBC Gb freed)

**Comment by sxa** [comment]
Overall usage in the workspace directory has shot up this month. It was ~580GB at the start of the month, and ~9879GB this morning when it filled up so there has been a lot of extra use in recent weeks:

<details>
<summary>Daily breakdown of jenkins controller workspace file system usage by date/size in Kb</summary>

220501 581297092
220502 582885788
220503 583979296
220504 594188924
220505 587295032
220506 599505984
220507 595988996
220508 596591916
220509 597264640
220510 598059032
220511 595690000
220512 599717712
220513 618981680
220514 612054776
220515 611351792
220516 611370624
220517 659615144
220518 739348868
220519 739915760
220520 764883472
220521 780244996
220522 822996532
220523 846071564
220524 934743684
220525 947476260
220526 987979120
</details>

**Comment by sxa** [comment]
While many of these are `testlist` ones (so from dynamic parallel runs) if I look at an arbitrary day comparing between 220519 and 220520 there were 143 new directories created, 91 were testList jobs from presumnably new parallel runs, 13 were new ones for alpine/aarch64 and 38 were new `libs` suffixed directories, although those are generally under 1MB each.

**Comment by smlambert** [comment]
Yes, that usage is correct and expected. (related: https://github.com/adoptium/infrastructure/issues/2578)

**Comment by sxa** [comment]
Currently looking stable over the weekend with no significant change in usage - 711956616 Kb
