### ISSUE TITLE
Improve clean up of vagrant boxes

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2581]
Currently there are plenty of vagrant processes leftover on infra-ibmcloud-vagrant-x64-1 after vpc jobs run to completion

For example 

```
/usr/lib/virtualbox/VBoxNetDHCP --comment HostInterfaceNetworking-vboxnet11 --config /tmp/dhcp-config-6892l.xml
/usr/lib/virtualbox/VBoxNetDHCP --comment HostInterfaceNetworking-vboxnet72 --config /tmp/dhcp-config-9tk46.xml
/usr/lib/virtualbox/VBoxNetDHCP --comment HostInterfaceNetworking-vboxnet54 --config /tmp/dhcp-config-9q0tt.xml
```

Some vagrant boxes remain running even after their job finishes

```
vagrant3@infra-ibmcloud-vagrant-x64:~$ vagrant global-status
id       name            provider   state   directory                                                                                                                 
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
1c8fa33  adoptopenjdkU20 virtualbox running /home/vagrant3/workspace/VagrantPlaybookCheck/OS/Ubuntu2004/label/vagrant/adoptopenjdkPBTests/AdoptOpenJDK-master/ansible 
```

I suspect these leftover processes are contributing to some of the timeout/unreachable errors we are seeing

**Comment by sxa** [comment]
Related: https://github.com/adoptium/infrastructure/issues/2314

**Comment by Haroon-Khel** [comment]
https://github.com/adoptium/infrastructure/issues/1287#issuecomment-649440760 suggests that the leftover `VBoxNetDHCP` can cause the vagrant boxes to have ip issues while the vpc jobs are running

**Comment by Haroon-Khel** [comment]
VPC jobs looking ok https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1434/ though I have only run the playbooks, not builds or tests

**Comment by sxa** [comment]
DId you do some clearups? It wasn't working well at all yesterday so curious as to what's changed

**Comment by Haroon-Khel** [comment]
Platforms look good (ish) after a process clean up
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/

**Comment by Haroon-Khel** [comment]
Got https://github.com/adoptium/infrastructure/pull/2595 in as a draft

**Comment by Haroon-Khel** [comment]
Clean up looks like it has improved.
For unstable and failed jobs, the vpc will still attempt to destroy the vm (unless the user has chosen to keep the vm)
https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1451/OS=Ubuntu1804,label=vagrant/console is an example; failed at the test stage yet still destroyed its vm

**Comment by Haroon-Khel** [comment]
Closing as https://github.com/adoptium/infrastructure/pull/2595 has been merged
