### ISSUE TITLE
Ansible request for non-Windows JNLP agents to start as a service

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2585]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

- [ ] Missing install
- [ ] Bug in ansible playbook
- [x] Request for new playbook addition

Details: We've got some systems which are starting the jenkins agents via JNLP instead of over ssh. For these we should ensure that the jenkins agent comes back when the machines are restarted. The best way to do this is likely to support an optional variable for the JNLP secret key and jenkins machine name and if that's set when running the playbooks a service will be set up to restart the agent that way. It will need the playbooks to download `agent.jar` into the jenkins' user home directory first.

This will be better than the startjenkins.sh script we're currently using on some systems.

**Comment by Haroon-Khel** [comment]
Aside from the windows machines, which other machines start up over jnlp?

**Comment by sxa** [comment]
Anything behind NAT, so the arm32 ones not hosted at equinix and most of the riscv64 systems

**Comment by sxa** [comment]
The following in `/lib/systemd/system/jenkins.service` should be adequate to allow `system jenkins start` to be usable. When the file is changed be sure to run `systemctl daemon-reload` to pick up the changes. The final line `ExecStart=` should be the command you get from the jenkins UI, and will typically include the location of the path to the `java` executable at the start.

```
[Unit]
Description=Jenkins Agent
Wants=network.target
After=network.target

[Install]
WantedBy=multi-user.target

[Service]
Type=simple
User=jenkins
Restart=always
RestartSec=300
StartLimitInterval=0
WorkingDirectory=/home/jenkins

Environment="USER=jenkins"
Environment="HOME=/home/jenkins"

ExecStart=/usr/lib/jvm/jdk-17/bin/java -jar agent.jar [...]
```

**Comment by sxa** [comment]
Note that for the RISC-V PLCTLab systems, there is an extra line to set the connection proxy to prevent git clone operations having problems:
`Environment="HTTPS_PROXY=http://10.8.8.41:8080"` (Was proviously on `10.8.8.2`)
