### ISSUE TITLE
Ansible request for JDK18 bootjdk

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2587]
JDK18 is needed to bootstrap JDK19. Currently our Unix, Windows and AIX playbooks install 17 as the latest bootstrap. So a role for 18 needs to be added to each playbook

**Comment by sxa** [comment]
Not technically true: https://github.com/adoptium/temurin-build/blob/dd97246b053d56db4dc0492c60ab04a29155926c/build-farm/make-adopt-build-farm.sh#L145 (introduced in https://github.com/adoptium/temurin-build/pull/2819)

**Comment by Haroon-Khel** [comment]
That's interesting. Then do we want jdk19 installed as a bootjdk on each machine?

**Comment by sxa** [comment]
I'm going to close this on the basis that the reproducible build changes are being backported to 17, but not 18, so there will be no requirement for this version.
