### ISSUE TITLE
System unavailable: Solaris X86_64 Nodes - Unavailable 

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2589]
The 2 solaris X86_64 nodes are both unusable

**build-packet_esxi-solaris10u11-x64-1 is out of memory ( log below )**

09:35:20  # There is insufficient memory for the Java Runtime Environment to continue.
09:35:20  # Native memory allocation (mmap) failed to map 243269632 bytes for committing reserved memory.
From [Grinder](https://ci.adoptopenjdk.net/job/Grinder/4905/consoleFull)

**build-packet_esxi-solaris10u11-x64-2 is offline**

**Comment by sxa** [comment]
There are 26836 `defunct` processes on the `-1` machine. 1351 of those under the jenkins ID. I'll reboot it.

**Comment by sxa** [comment]
Jenkins process listing (excluding the defunct ones):  [build-packet_esxi-solaris10u11-x64.1.leftovers.txt.gz](https://github.com/adoptium/infrastructure/files/8813384/build-packet_esxi-solaris10u11-x64.1.leftovers.txt.gz)

There are quite a lot from old jobs which is likely exhausting the resources. See also: #2442 which would potentially have caught many of these
I've triggered a reboot

**Comment by sxa** [comment]
`-1` is back and currently showing a load everage of, erm, `8388608.00`.
Which I assume is fake news as it seems pretty responsive and the jenkins agent has been launched successfully on it

**Comment by steelhead31** [comment]
Once I've got access, I'll have a look at fixing #2442

**Comment by sxa** [comment]
Solaris x64 machines were all rebuilt as part of #2792 #2666 and I'm not aware of any such issues on the new ones, therefore closing.
