### ISSUE TITLE
Add trss-node to Jenkins

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2598]
Request to finish adding trss-node to Jenkins, see https://ci.adoptopenjdk.net/computer/trss-node/

Details:
Would like to complete the setup (and someone with visibility of which would be the appropriate credentials to use).

We will add a Jenkins job that will allow us to update the trss server via the --watch option (rather than depend on the small set of people to log on to the machine to manually update).

**Comment by sxa** [comment]
If this isn't running as the jenkins user I believe we'll have to create a duplicate credential with the trss username

**Comment by sxa** [comment]
> If this isn't running as the jenkins user I believe we'll have to create a duplicate credential with the trss username

Looks like it is running as a jenkins user so I have enabled it (the IP address on that agent definition was also incorrect) and made a suitable java available to run the jenkins agent.

**Comment by smlambert** [comment]
thanks @sxa !
