### ISSUE TITLE
refactor_openjdk_release_tool fails on C3Jenkins : JAVA_HOME is set to an invalid directory

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2604]
https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/release/job/refactor_openjdk_release_tool/
```
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-8-openjdk-amd64
```

I've modified the refactor_openjdk_release_tool job configuration to run on masterX until this is fixed

**Comment by sxa** [comment]
Set to `/usr/lib/jvm/java-17-openjdk-amd64`

**Comment by sxa** [comment]
Still not picking it up - have installed a JDK in the place it's looking for it and jobs seem to be ok now.
