### ISSUE TITLE
New Machine request for Deep AQAtik GSoC work

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2605]
New machine request:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): linux
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): x64
- Provider (leave blank if it does not matter): 
- Desired usage: for machine learning prototype
- Any unusual specification/setup required: no
- How many of them are required: 1

Please explain what this machine is needed for:
Mentioned previously, but had not yet created a request for a separate machine where we can run and develop the Deep AQAtik prototype (partially described [here](https://github.com/adoptium/aqa-test-tools/wiki/Outreachy-TRSS-Machine-Learning-Project:-Deep-AQAtik)).  We had been running this ML prototype on the same machine as TRSS, but that is not required or desired, as we will be making many changes and do not want to destabilize the TRSS machine.

**Comment by sxa** [comment]
Keys for @llxia @LongyuZhang and Giannis have been added to the `aqatik` user

**Comment by sxa** [comment]
@llxia @LongyuZhang @ichristod @smlambert Is this machien working ok? I haven't got it in the system inventory file at the moment so I'll get it added if it's up, running, and working as desired to close this off :-)

**Comment by LongyuZhang** [comment]
Thanks @sxa for the help. The machine is working well. We will work with a university professor to implement new ml architecture on this machine in the coming weeks. I think we can close this issue for now. Thanks.

**Comment by smlambert** [comment]
Closing as completed.
