### ISSUE TITLE
containerd.io error on one of the ppc64le build machines

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2610]
Works on `-2` but not on `-1`
```
TASK [Docker : Install docker based on OS (Ubuntu, RHEL7, CentOS7, Debian)] ****
skipping: [build-osuosl-centos74-ppc64le-2]
fatal: [build-osuosl-centos74-ppc64le-1]: FAILED! => {"changed": false, "msg": "No package matching 'containerd.io' found available, installed or updated", "rc": 126, "results": ["All packages providing docker-ce are up to date", "No package matching 'containerd.io' found available, installed or updated"]}
```

**Comment by sxa** [comment]
NOTE: Neither `docker-ce-cli` nor `containerd.io` are in the repositories on RHEL installations but `docker-ce` is. Unclear why there is no failure on the other ppc64le RHEL7 machine though, as it doesn't have them installed either.

**Comment by sxa** [comment]
@zdtsw It looks like you added these packages [during a refactor](https://github.com/adoptium/infrastructure/pull/2545) - why were these additional ones added?

**Comment by zdtsw** [comment]
> @zdtsw It looks like you added these packages [during a refactor](https://github.com/adoptium/infrastructure/pull/2545) - why were these additional ones added?

according to https://developer.ibm.com/tutorials/install-docker-on-linux-on-power/
`Run the following command to install containerd:
sudo yum --enablerepo="epel" install containerd`
Could that be one of the machines does not have epel enabled?

**Comment by sxa** [comment]
> > @zdtsw It looks like you added these packages [during a refactor](https://github.com/adoptium/infrastructure/pull/2545) - why were these additional ones added?
> 
> according to https://developer.ibm.com/tutorials/install-docker-on-linux-on-power/ `Run the following command to install containerd: sudo yum --enablerepo="epel" install containerd` Could that be one of the machines does not have epel enabled?

It's enabled on both, but why are we trying to install additional packages that were not previously required? I don't believe there are any issues with being able to run docker on the systems as they are which already have just `docker-ce` installed.

**Comment by zdtsw** [comment]
> > > @zdtsw It looks like you added these packages [during a refactor](https://github.com/adoptium/infrastructure/pull/2545) - why were these additional ones added?
> > 
> > 
> > according to https://developer.ibm.com/tutorials/install-docker-on-linux-on-power/ `Run the following command to install containerd: sudo yum --enablerepo="epel" install containerd` Could that be one of the machines does not have epel enabled?
> 
> It's enabled on both, but why are we trying to install additional packages that were not previously required? I don't believe there are any issues with being able to run docker on the systems as they are which already have just `docker-ce` installed.

in the old version of docker(v17 docker/docker-engine), it should work with only install docker,
then in 18.03.* and 18.06.*, it changed to docker-ce, still it only require docker-ce
18.09.03+  when they changed to use OCI which need dependencies to have container.d and docker-ce-cli along with docker-ce  https://docs.docker.com/engine/install/centos/ that's the reason I put all these three there. 
we can only have docker-ce in our code, but it still does auto install the other two packages. 
unless we dedice to fix on a version of docker, which docker-ce should work. otherwise we need other packages.

**Comment by sxa** [comment]
> we can only have docker-ce in our code, but it still does auto install the other two packages.

Since it'll automatically pulling those dependencies we cover both situations if we just install docker-ce, so I would suggest removing the other two from being listed explicitly. From what you've said there is no disadvantage to doing that.

**Comment by zdtsw** [comment]
> > we can only have docker-ce in our code, but it still does auto install the other two packages.
> 
> Since it'll automatically pulling those dependencies we cover both situations if we just install docker-ce, so I would suggest removing the other two from being listed explicitly. From what you've said there is no disadvantage to doing that.

sure I can remove these two

**Comment by sxa** [comment]
> sure I can remove these two

Thanks :-)

**Comment by zdtsw** [comment]
implemented by https://github.com/adoptium/infrastructure/pull/2618
