### ISSUE TITLE
jdk8: sun/security/tools/jarsigner/emptymanifest.sh failed on some aarch64

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2623]
jdk8: sun/security/tools/jarsigner/emptymanifest.sh failed on some aarch64. For example: failed on [test-docker-ubuntu1604-armv8l-2](https://ci.adoptopenjdk.net/computer/test-docker-ubuntu1604-armv8l-2,  [test-docker-ubuntu2004-armv8l-2](https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2004-armv8l-2)), passed on test-alibaba-ubuntu1804-armv8-2. 

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name: sun/security/tools/jarsigner/emptymanifest.sh
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on?  test-alibaba-ubuntu1804-armv8-2
- Which machine(s) does it fail on? test-docker-ubuntu2004-armv8l-2
- Do you have a link to a Grinder re-run if the test with the failure? https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=nightly&TARGET=jdk_custom&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=test-docker-ubuntu2004-armv8l-2&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk8u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-aarch64-temurin&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=sun%2Fsecurity%2Ftools%2Fjarsigner%2Femptymanifest.sh&VENDOR_TEST_SHAS=&JDK_BRANCH=dev&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=92&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None

Any other details:
Some aarch64 installs zip and some not, which causes different behaviour.

Error message: ` zip: not found`. Test requires zip. `zip $JFILE META-INF${FS}MANIFEST.MF A B`.

**Comment by sophia-guo** [comment]
Same issue with some linux64.
Affected jdk8 tests:
sun/security/tools/jarsigner/diffend.sh
sun/security/tools/jarsigner/emptymanifest.sh

One of tests is excluded for linux-aarch64 by wrong format. 

```
sun/security/tools/jarsigner/diffend.sh	https://github.com/adoptium/aqa-tests/issues/21233	linux-aarch64
sun/security/tools/jarsigner/emptymanifest.sh	https://github.com/adoptium/aqa-tests/issues/21233	linux-aarch6
```
To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

test suite/name: 
Is there an existing issue elsewhere covering this?
Which machine(s) does it work on? [test-docker-fedora35-x64-1](https://ci.adoptopenjdk.net/computer/test-docker-fedora35-x64-1)
Which machine(s) does it fail on? [test-docker-ubuntu2004-x64-1](https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2004-x64-1) test-docker-ubuntu2110-x64-1, probably more
Do you have a link to a Grinder re-run if the test with the failure? 
Any other details:

Grinder with test-docker-fedora35-x64-1 passed: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5018/
Grinder with test-docker-ubuntu2004-x64-1 failed : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5019/

Some linux64 with zip installed and some not, which causes different behaviour.

Error message: zip: not found. `zip $JFILE META-INF${FS}MANIFEST.MF A B` or `zip diffend.jar META-INF/MANIFEST.MF 1`

**Comment by Haroon-Khel** [comment]
Rerunning on failed nodes

aarch64

Failed nodes:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5082/console
test-docker-ubuntu1604-armv8l-2

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5083/console
test-docker-ubuntu2004-armv8l-2

Other aarch64 nodes:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5084/console
test-docker-ubuntu2110-armv8l-1

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5085/console
test-docker-ubuntu2010-armv8l-2

**Comment by Haroon-Khel** [comment]
x64

Installed `zip` on test-docker-ubuntu2004-x64-1. Rerunning
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5086/console

**Comment by Haroon-Khel** [comment]
After installing zip on the aarch64 nodes
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5087/console
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5088/console
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5089/console
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5090/console

**Comment by sxa** [comment]
@sophia-guo You've marked this one as critical but based on Haroon's updates the machines have now been updated - have you seen any occurrences of this in the last week?

**Comment by Haroon-Khel** [comment]
And in regards to the 2 failing grinders linked above, 5087 and 5089, that machine has been upgraded to a Ubuntu 2204 machine on which this test has passed

**Comment by sophia-guo** [comment]
No, I didn't see this issue during the recent run. As we do know the quick fix it should not be critical. Close it and can reopen if happens again.
