### ISSUE TITLE
Process unavailable: Alpine/x64 docker build image generation 

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2627]
The `adoptopenjdk/alpine3_build_image` has not been updated recently which is preventing the correct boot JDKs from being available in the image for JDK8 and JDK11.

https://github.com/adoptium/infrastructure/runs/6981021248?check_suite_focus=true is showing as running green but does not appear to contain the latest changes that I get when running locally (e.g. the absence of `jdk8` and `jdk-11` in `/var/lib/jvm`)

Unclear if this is related to #2626

**Comment by sxa** [comment]
@gdams Can you take a look at this please? The image seems to build correctly when I build it locally, and it's showing green in the actions, but `adoptopenjdk/Alpine3_build_image` does not have /usr/lib/jvm/jdk8 etc. present

**Comment by gdams** [comment]
It's not being updated because the centos 7 job keeps failing to push which then in turn prevents the manifest job from running. Hopefully my update should have fixed the problem
