### ISSUE TITLE
jdk8 java/nio/file/Files/probeContentType/Basic.java failed on test-docker-fedora34-x64-1

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2631]
jdk8 java/nio/file/Files/probeContentType/Basic.java failed on test-docker-fedora34-x64-1

- test suite/name?  jdk8 java/nio/file/Files/probeContentType/Basic.java
- Is there an existing issue elsewhere covering this? 
- Which machine(s) does it work on?  [test-ibmcloud-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/test-ibmcloud-ubuntu1604-x64-1)
- Which machine(s) does it fail on? test-docker-fedora34-x64-1
- Do you have a link to a Grinder re-run if the test with the failure?

Any other details:
[test-ibmcloud-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/test-ibmcloud-ubuntu1604-x64-1) : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5027/

test-docker-fedora34-x64-1: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5026/
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_linux_testList_2/45/

History show https://trss.adoptium.net/deepHistory?testId=62ae0eb4250c3c428c287b29

```
Stacktrace
Execution failed: `main' threw exception: java.lang.RuntimeException: Test failed!    
Standard Output
probe /tmp/foo7555592115402834250.html...
/home/jenkins/.mime.types does not exist
/etc/mime.types does not exist
probe /tmp/red2631690209915529139.grape...
    
Standard Error
Expected "text/html" but obtained "application/x-zerosize"
java.lang.RuntimeException: Test failed!
	at Basic.main(Basic.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:750)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Test failed!
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Test failed!
```

**Comment by sophia-guo** [comment]
Same issue for jdk8 tests:
[java/net/Inet6Address/B6206527.java.B6206527](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_linux_testList_2/45/testReport/junit/java_net_Inet6Address_B6206527/java/B6206527/)
[java/net/ipv6tests/B6521014.java.B6521014](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_linux_testList_2/45/testReport/junit/java_net_ipv6tests_B6521014/java/B6521014/)

Grinder on [test-ibmcloud-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/test-ibmcloud-ubuntu1604-x64-1) passed:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5029/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5030/
Grinder on test-docker-fedora34-x64-1 failed:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5031/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5032/

**Comment by Haroon-Khel** [comment]
Initial suspicion is that this test will fail on docker containers

**Comment by Haroon-Khel** [comment]
java/nio/file/Files/probeContentType/Basic.java

test-docker-fedora34-x64-1 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5114/console

test-docker-ubuntu2204-x64-1 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5115/console

test-docker-ubuntu1804-x64-1 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5116/console

test-docker-ubuntu2004-x64-2 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5117/console

test-docker-ubuntu2010-x64-2 
https://ci.adoptopenjdk. test-docker-ubuntu2010-x64-2/view/Test_grinder/job/Grinder/5118/console

**Comment by Haroon-Khel** [comment]
java/net/Inet6Address/B6206527.java.B6206527

test-docker-fedora34-x64-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5120/console

test-docker-ubuntu2204-x64-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5121/console

test-docker-ubuntu1804-x64-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5122/console

test-docker-ubuntu2004-x64-2
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5123/console

test-docker-ubuntu2010-x64-2
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5124/console

test-docker-fedora35-x64-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5125/console

**Comment by Haroon-Khel** [comment]
java/net/ipv6tests/B6521014.java

test-docker-fedora34-x64-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5126/console

test-docker-ubuntu2204-x64-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5127/console

test-docker-ubuntu1804-x64-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5128/console

test-docker-ubuntu2004-x64-2
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5129/console

test-docker-ubuntu2010-x64-2
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5130/console

test-docker-fedora35-x64-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5131/console

**Comment by Haroon-Khel** [comment]
The ipv6 issues are interesting. This is related, https://github.com/adoptium/infrastructure/issues/1105, but I dont think the solution to that issue helps here. The dockerstatic containers do have ipv6 enabled; I added this to the /etc/docker/daemon.json file a while ago:

`{ "ipv6": true, "fixed-cidr-v6": "fd00::/80" }`

I will try creating another fedora container and see if the tests still fail on that one

**Comment by Haroon-Khel** [comment]
Created a new fedora34 container [est-docker-fedora34-x64-2](https://ci.adoptopenjdk.net/computer/test-docker-fedora34-x64-2/)

java/nio/file/Files/probeContentType/Basic.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5133/console

java/net/Inet6Address/B6206527.java.B6206527
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5135/console

java/net/ipv6tests/B6521014.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5136/console

**Comment by Haroon-Khel** [comment]
Rerunning the tests on our other fedora boxes:

[test-docker-fedora35-x64-1](https://ci.adoptopenjdk.net/computer/test-docker-fedora35-x64-1/) :

java/nio/file/Files/probeContentType/Basic.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5201/console

java/net/Inet6Address/B6206527.java.B6206527
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5202/console

java/net/ipv6tests/B6521014.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5203/console

[test-docker-fedora35-armv8l-1](https://ci.adoptopenjdk.net/computer/test-docker-fedora35-armv8l-1/) :

java/nio/file/Files/probeContentType/Basic.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5204/console

java/net/Inet6Address/B6206527.java.B6206527
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5205/console

java/net/ipv6tests/B6521014.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5206/console

**Comment by Haroon-Khel** [comment]
Newly created https://ci.adoptopenjdk.net/computer/test-docker-fedora36-x64-1/

java/nio/file/Files/probeContentType/Basic.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5207/console

java/net/Inet6Address/B6206527.java.B6206527
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5208/console

java/net/ipv6tests/B6521014.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5209/console

**Comment by Haroon-Khel** [comment]
The ipv6 tests pass on the f35 containers but fail on the f36 one. This may be due to the dockerhost of the f36 container, https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu2004-amd-1/ while the former containers are on https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu2004-intel-1/. I'm going to build an f36 container on the latter dockerhost to test

**Comment by Haroon-Khel** [comment]
Created another f36 container https://ci.adoptopenjdk.net/computer/test-docker-fedora36-x64-2/, on https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu2004-intel-1/

Rerunning tests, I expect Basic to still fail. Ive installed `mailcap` which creates the /etc/mime.types file which the test needs but I dont think this allows the test to pass:

java/nio/file/Files/probeContentType/Basic.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5212/console

java/net/Inet6Address/B6206527.java.B6206527
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5213/console

java/net/ipv6tests/B6521014.java
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5214/console

**Comment by Haroon-Khel** [comment]
Ipv6 test pass when the docker container is on https://ci.adoptopenjdk.net/computer/docker-packet-ubuntu2004-intel-1/, so theres a difference in docker ipv6 config between the two dockerhost machines

**Comment by Haroon-Khel** [comment]
On the failing fedora machines, the failure lies here:

https://github.com/adoptium/jdk8u/blob/a18e9043fa2a0a14098e1ec25d32577aaac6c023/jdk/test/java/nio/file/Files/probeContentType/Basic.java#L45 creates a html file, but when its 'type' is tested here https://github.com/adoptium/jdk8u/blob/a18e9043fa2a0a14098e1ec25d32577aaac6c023/jdk/test/java/nio/file/Files/probeContentType/Basic.java#L118, instead of return `html` it returns `application/x-zerosize`

**Comment by Haroon-Khel** [comment]
Cannot seem to get the Basic test to pass on Fedora. The following is a basic java file which zones in on what is causing this error, where foo.html is an html file.

```
import java.io.*;
import java.nio.file.*;

class Filetype {
  public static void main(String[] args) {
    try {
        System.out.println(Files.probeContentType(Paths.get("/home/jenkins/foo.html")));
    }
    catch(Exception e) {
      e.getStackTrace();
    }
  }
}
```
On fedora it returns `application/x-zerosize`. I tested it with a basic plain text file and it still returned `application/x-zerosize`. However on the same Fedora machine, if I use `file` to detect filetypes it returns:
```
[jenkins@24154f331d28 bin]$ file -b --mime-type /home/jenkins/foo.html 
text/html
```
Which is correct.

On a working machine, the above java file will return `text/html`

**Comment by Haroon-Khel** [comment]
I think installing `shared-mime-info` seemed to do the trick, rerunning on https://ci.adoptopenjdk.net/computer/test-docker-fedora36-x64-2/

**Comment by Haroon-Khel** [comment]
Installing `shared-mime-info` allows the Basic test to pass
