### ISSUE TITLE
System unavailable: docker&&linux&&x86_64 not available docker-aws-ubuntu1604-x64-0/-2

### ISSUE THREAD

**Issue by zdtsw** [adoptium/infrastructure#2632]
- Please put the system name in the title of this issue.
[docker-aws-ubuntu1604-x64-0](https://ci.adoptopenjdk.net/computer/docker-aws-ubuntu1604-x64-0/) [docker-aws-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/docker-aws-ubuntu1604-x64-1/) [docker-aws-ubuntu1604-x64-2](https://ci.adoptopenjdk.net/computer/docker-aws-ubuntu1604-x64-2/)
- Link to any log file showing the problem:

- Please describe the issue:
when using label 'docker&&linux&&x86_64'  found no jenkins agent available. 
by looking at all 3 nodes, [one](docker-aws-ubuntu1604-x64-1) is offline intentionally , but other two seems have issue to start jenkins process

**Comment by zdtsw** [comment]
I am testing the installer job,
the debian build stage cannot find agent.

**Comment by sxa** [comment]
> I am testing the installer job, the debian build stage cannot find agent.

Same question - which job is this affecting? The Linux installer generator job [adoptium-packages-linux-pipeline](https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline) is not being held up because of this issue as far as I can tell.

**Comment by zdtsw** [comment]
this is the test job  https://ci.adoptopenjdk.net/view/work-in-progress/job/Sophia-adoptium-packages-linux-pipeline/
not using the official "installer" job

**Comment by sxa** [comment]
> this is the test job https://ci.adoptopenjdk.net/view/work-in-progress/job/Sophia-adoptium-packages-linux-pipeline/ not using the official "installer" job

I don't know why that's targetting different machines. I don't particularly want to recover machines running those out of support OSs. If they're not causing a problem with any critical jobs I'm just going to decomission those systems (as per the comment you've seen on one of them)

**Comment by zdtsw** [comment]
> > this is the test job https://ci.adoptopenjdk.net/view/work-in-progress/job/Sophia-adoptium-packages-linux-pipeline/ not using the official "installer" job
> 
> I don't know why that's targetting different machines. I don't particularly want to recover machines running those out of support OSs. If they're not causing a problem with any critical jobs I'm just going to decomission those systems (as per the comment you've seen on one of them)

sure. if agents are not needed/supposed to be there, we either remove them or put message as description  to not cause confusion.

**Comment by sxa** [comment]
Adding extras will be covered as part of https://github.com/adoptium/infrastructure/issues/3482
