### ISSUE TITLE
aqa test jobs failed on test-docker-alpine313-aarch64-1

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2636]
It's not testcase failure. It's test job failure before test running. The reason is running testing jdk pointed by environment variable TEST_JDK_HOME will end up with using java defined `_=/usr/lib/jvm/jdk-17.0.4+3/bin/java`. This only happened to test-docker-alpine313-aarch64-1. Other machines are configured as `_=/usr/bin/java` and do not have this issue.

- test suite/name?
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on? test-docker-alpine311-aarch64-1
- Which machine(s) does it fail on? test-docker-alpine313-aarch64-1
- Do you have a link to a Grinder re-run if the test with the failure? https://ci.adoptopenjdk.net/job/Grinder/5038/

Any other details:
grinder https://ci.adoptopenjdk.net/job/Grinder/5038/
rerun on test-docker-alpine311-aarch64-1 : [est-docker-alpine311-aarch64-1](https://ci.adoptopenjdk.net/job/Grinder/5039/)

**Comment by Haroon-Khel** [comment]
Ive switched its java path to /usr/bin/jdk8/bin/java. Theres a nightly test running on it currently,, https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_aarch64_alpine-linux/16/console. I've also kicked off https://ci.adoptopenjdk.net/job/Grinder/5138/console

**Comment by Haroon-Khel** [comment]
The grinder is failing due to `cp: can't preserve ownership of './prog': Operation not permitted` but this is a known issue https://bugs.openjdk.org/browse/JDK-8245748

**Comment by sophia-guo** [comment]
Thanks @Haroon-Khel!
