### ISSUE TITLE
New Machine requirement: Add docker in perf machines

### ISSUE THREAD

**Issue by joeyleeeeeee97** [adoptium/infrastructure#2642]
I need to request a new machine that support` ci.role.perf and sw.tool.docker`, currently only have [these](https://ci.adoptopenjdk.net/label/sw.tool.docker&&ci.role.perf/)
Please explain what this machine is needed for:
as in this [test](https://github.com/adoptium/aqa-tests/pull/3746), we need to cover a wider range of platforms.

**Comment by sxa** [comment]
Which Linux architectures are you looking for specifically?

**Comment by sxa** [comment]
Added to the following, which will give ppc64le and armv7l (arm32) coverage. Please re-open if you require more.
- https://ci.adoptopenjdk.net/computer/test-osuosl-centos74-ppc64le-1
- https://ci.adoptopenjdk.net/computer/test-osuosl-centos74-ppc64le-2
- https://ci.adoptopenjdk.net/computer/test-sxa-armv7l-ubuntu2004-odroid-1
- https://ci.adoptopenjdk.net/computer/test-sxa-armv7l-ubuntu2004-odroid-2
