### ISSUE TITLE
jdk11 javax/net/ssl/SSLSocket/Tls13PacketSize.java failed on test windows machines test-**-win**

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2645]
jdk11 javax/net/ssl/SSLSocket/Tls13PacketSize.java failed on test windows machines and passed on test build machines 
https://trss.adoptium.net/deepHistory?testId=62b7b987250c3c428c3c323b

with error message:

```
Server input bytes: 16366
Client died: java.net.SocketException: Software caused connection abort: recv failed
java.net.SocketException: Software caused connection abort: recv failed
```

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name?
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on? https://ci.adoptopenjdk.net/label/sw.os.windows&&ci.role.test&&build/
- Which machine(s) does it fail on? https://ci.adoptopenjdk.net/label/sw.os.windows&&ci.role.test/ without label 'build'
- Do you have a link to a Grinder re-run if the test with the failure?

Any other details:
Grinder rerun on passed machines https://ci.adoptopenjdk.net/job/Grinder/5046/
on failed machines https://ci.adoptopenjdk.net/job/Grinder/5045/

**Comment by sophia-guo** [comment]
java/nio/file/Files/probeContentType/Basic.java failed with different error message

https://github.com/adoptium/aqa-tests/issues/3594#issuecomment-1103848392

**Comment by Haroon-Khel** [comment]
Rerunning:

test-azure-win2012r2-x64-1 
https://ci.adoptopenjdk.net/job/Grinder/5064/console

test-azure-win2012r2-x64-3
https://ci.adoptopenjdk.net/job/Grinder/5065/console

test-azure-win2016-x64-1
https://ci.adoptopenjdk.net/job/Grinder/5066/console

test-azure-win2019-x64-1
https://ci.adoptopenjdk.net/job/Grinder/5067/console

test-ibmcloud-win2012r2-x64-1
https://ci.adoptopenjdk.net/job/Grinder/5068/console

test-ibmcloud-win2012r2-x64-2
https://ci.adoptopenjdk.net/job/Grinder/5069/console

build-alibaba-win2012r2-x64-2
https://ci.adoptopenjdk.net/job/Grinder/5070/console

build-azure-win2012r2-x64-2
https://ci.adoptopenjdk.net/job/Grinder/5071/console

build-ibmcloud-win2012r2-x64-2
https://ci.adoptopenjdk.net/job/Grinder/5072/console

**Comment by Haroon-Khel** [comment]
Failed on test-azure-win2012r2-x64-3 and test-azure-win2019-x64-1. Passed on the rest. Looks to be machine specific

**Comment by Haroon-Khel** [comment]
Theres still some intermittent behaviour; on test-azure-win2012r2-x64-3 the test passed twice while failed three times. On test-azure-win2019-x64-1 the test failed four times and passed once

**Comment by sxa** [comment]
Need to verify if this is a problem on the win2022 machines
