### ISSUE TITLE
System unavailable:  test-docker-alpine311-aarch64-1 and test-docker-alpine312-aarch64-1

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2652]
https://ci.adoptopenjdk.net/label/ci.role.test&&hw.arch.aarch64&&sw.os.alpine-linux/

**Comment by sxa** [comment]
@andrew-m-leonard In order to assess the urgency, what is the current impact of this outage?

**Comment by sxa** [comment]
Closing this as we now have five machines online and the hardware that was hosting the two referenced in the title had gone faulty and has now been decommissioned as per https://github.com/adoptium/infrastructure/issues/2666.
