### ISSUE TITLE
ERROR: Cannot delete workspace on https://ci.adoptopenjdk.net/computer/build-azure-win2012r2-x64-2/

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2654]
Jenkins jobs failed on build-azure-win2012r2-x64-2 with

```
ERROR: Cannot delete workspace :Unable to delete 'J:\jenkins\workspace\Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2\openjdkbinary\j2sdk-image\bin\client\jvm.dll'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```

https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2/47/console

Please set the title to indicate the test name and machine name where known.

- test suite/name? Not a test failure. jenkins job failed.
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on?
- Which machine(s) does it fail on?
- Do you have a link to a Grinder re-run if the test with the failure?

Any other details:

**Comment by Haroon-Khel** [comment]
The .dll file seems to be in use by another process

```
$ rm jvm.dll
rm: cannot remove 'jvm.dll': Device or resource busy
```

**Comment by Haroon-Khel** [comment]
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/34969545/176477294-7699b4d1-decf-48bb-80c3-938be981ca9f.png">
@sophia-guo Do you know what the process `jhsdb.exe` is used for?

**Comment by sophia-guo** [comment]
I did a search. jhsdb is used by some jdk_tools tests.
