### ISSUE TITLE
Git version 2.11.4 needs to be install as a minimum for tests

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2658]
As of https://github.com/adoptium/aqa-tests/pull/3789/files, machines need git version 2.11.4 installed as a minimum, else they will run into this error

```
16:18:51       [exec] git clone --depth 1 -q --reference-if-able /home/jenkins/openjdk_cache -b dev https://github.com/adoptium/jdk8u.git openjdk-jdk
16:18:51       [exec] error: unknown option `reference-if-able'error code: 129. Sleep 300 secs, then retry 1...
```
from https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5087/console (updated)

Out of support OSs, like Ubuntu 16, may not be able to install this version of git from its repos, the max Ubuntu16 can install is 2.7 for example. So it will need to be discussed whether we are going to replace such machines in favour of supported OSs, or compile and build git 2.11.4 on such machines. I am in favour of the former. @sxa thoughts?

**Comment by Haroon-Khel** [comment]
Wrong link, https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5087/console. 
The docker static containers do not have the playbook run on them. Only the test prereqs are installed. 

Posting the wrong link threw me off, I think it may just be [test-docker-ubuntu1604-armv8l-2](https://ci.adoptopenjdk.net/search/?q=test-docker-ubuntu1604-armv8l-2) that has an outdated version of git installed. I'll look into upgrading to a newer Ubuntu OS.

I'll see why the ubunutu2004 system has an outdated OS, should be an easy fix

**Comment by sxa** [comment]
Related: There is follow-on work occurring to fix this for Solaris: https://github.com/adoptium/infrastructure/pull/2665
