### ISSUE TITLE
[jdk8 - windows64]: some java_util tests failed with `insufficient memory`

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2663]
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/#showFailuresLink

[java/util/stream/test/org/openjdk/tests/java/lang/invoke/SerializedLambdaTest.java.SerializedLambdaTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_lang_invoke_SerializedLambdaTest/java/SerializedLambdaTest/)
[java/util/stream/test/org/openjdk/tests/java/util/FillableStringTest.java.FillableStringTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_FillableStringTest/java/FillableStringTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/ConcatOpTest.java.ConcatOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_ConcatOpTest/java/ConcatOpTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/DistinctOpTest.java.DistinctOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_DistinctOpTest/java/DistinctOpTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/DoublePrimitiveOpsTests.java.DoublePrimitiveOpsTests](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_DoublePrimitiveOpsTests/java/DoublePrimitiveOpsTests/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/FindAnyOpTest.java.FindAnyOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_FindAnyOpTest/java/FindAnyOpTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/FlatMapOpTest.java.FlatMapOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_FlatMapOpTest/java/FlatMapOpTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/FlatMapOpTest.java.FlatMapOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_FlatMapOpTest/java/FlatMapOpTest_2/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/InfiniteStreamWithLimitOpTest.java.InfiniteStreamWithLimitOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_InfiniteStreamWithLimitOpTest/java/InfiniteStreamWithLimitOpTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/InfiniteStreamWithLimitOpTest.java.InfiniteStreamWithLimitOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_InfiniteStreamWithLimitOpTest/java/InfiniteStreamWithLimitOpTest_2/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/MapOpTest.java.MapOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_MapOpTest/java/MapOpTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/SequentialOpTest.java.SequentialOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_SequentialOpTest/java/SequentialOpTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/SliceOpTest.java.SliceOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_SliceOpTest/java/SliceOpTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/SliceOpTest.java.SliceOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_SliceOpTest/java/SliceOpTest_2/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/SortedOpTest.java.SortedOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_SortedOpTest/java/SortedOpTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/SpliteratorTest.java.SpliteratorTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_SpliteratorTest/java/SpliteratorTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/StreamBuilderTest.java.StreamBuilderTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_StreamBuilderTest/java/StreamBuilderTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/StreamSpliteratorTest.java.StreamSpliteratorTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_StreamSpliteratorTest/java/StreamSpliteratorTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/StreamSpliteratorTest.java.StreamSpliteratorTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_StreamSpliteratorTest/java/StreamSpliteratorTest_2/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/TabulatorsTest.java.TabulatorsTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_TabulatorsTest/java/TabulatorsTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/TabulatorsTest.java.TabulatorsTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_TabulatorsTest/java/TabulatorsTest_2/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/TeeOpTest.java.TeeOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_TeeOpTest/java/TeeOpTest/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/TeeOpTest.java.TeeOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_TeeOpTest/java/TeeOpTest_2/)
[java/util/stream/test/org/openjdk/tests/java/util/stream/ToArrayOpTest.java.ToArrayOpTest](https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_windows/648/testReport/junit/java_util_stream_test_org_openjdk_tests_java_util_stream_ToArrayOpTest/java/ToArrayOpTest/)

```
09:03:34  STDOUT:
09:03:34  #
09:03:34  # There is insufficient memory for the Java Runtime Environment to continue.
09:03:34  # Native memory allocation (malloc) failed to allocate 1048576 bytes for AllocateHeap
09:03:34  # An error report file with more information is saved as:
09:03:34  # E:\workspace\Test_openjdk8_hs_sanity.openjdk_x86-64_windows\aqa-tests\TKG\output_16567659847658\jdk_util_1\work\java\util\stream\test\org\openjdk\tests\java\util\stream\TabulatorsTest\hs_err_pid19676.log
```

Failed on test-azure-win2012r2-x64-3 test-ibmcloud-win2012r2-x64-1.

**Comment by Haroon-Khel** [comment]
Util tests look good. The insufficient memory error seems intermittent. The lang test did not run with the above grinders, i'll re run that one now

**Comment by Haroon-Khel** [comment]
java/util/stream/test/org/openjdk/tests/java/lang/invoke/SerializedLambdaTest.java

Problem machines:
test-azure-win2012r2-x64-3
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5153/console

test-ibmcloud-win2012r2-x64-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5154/console

Other machines:
test-ibmcloud-win2012r2-x64-2
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5145/console

test-azure-win2012r2-x64-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5155/console

build-ibmcloud-win2012r2-x64-2
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5156/console

test-azure-win2016-x64-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5157/console

test-azure-win2019-x64-1
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5158/console

build-azure-win2012r2-x64-2
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5159/console

build-alibaba-win2012r2-x64-2
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5160/console

**Comment by Haroon-Khel** [comment]
Lang tests also look good. More evidence towards this being an intermittent error

**Comment by sxa** [comment]
Have they failed at all in your recent runs? May be worth trying again on the machines it's failed on but running with 50 iterations or something like that and see if any of them fail :-)

**Comment by sxa** [comment]
@sophia-guo @Haroon-Khel Has this been seen recently?

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/7120/console jdk_util on test-azure-win2012r2-x64-3
https://ci.adoptium.net/view/Test_grinder/job/Grinder/7121/console java/util/stream/test/org/openjdk/tests/java/lang/invoke/SerializedLambdaTest.java on test-azure-win2012r2-x64-3

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/computer/test-ibmcloud-win2012r2-x64-1/ is not able to connect to jenkins. I can rdp into the machine. From there it looks like its having trouble accessing the internet, for example it cant connect to ci.adoptium.net in a web browser. @AdamBrousseau Are you able to see if test-ibmcloud-win2012r2-x64-1 is having network issues?

**Comment by sxa** [comment]
> https://ci.adoptium.net/computer/test-ibmcloud-win2012r2-x64-1/ is not able to connect to jenkins. I can rdp into the machine. From there it looks like its having trouble accessing the internet, for example it cant connect to ci.adoptium.net in a web browser. @AdamBrousseau Are you able to see if test-ibmcloud-win2012r2-x64-1 is having network issues?

Can it do anything e.g. ssh out? Download something via curl/wget? What errors are we getting on the machine?

**Comment by Haroon-Khel** [comment]
curl and wget did not work as it looks like it cannot resolve hostnames, website were not loading in a browser

<img width="566" alt="image" src="https://user-images.githubusercontent.com/34969545/231512230-5d54f0cf-0df1-4752-9dd2-f1883a3645c4.png">

<img width="578" alt="image" src="https://user-images.githubusercontent.com/34969545/231512405-7414ca2f-5660-447c-90ac-c5f12a05d031.png">

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/computer/test-ibmcloud-win2012r2-x64-1/ is back online after manually giving it a dns server (8.8.8.8)

**Comment by Haroon-Khel** [comment]
jdk_util on test-ibmcloud-1 https://ci.adoptium.net/view/Test_grinder/job/Grinder/7136/console
No need for a separate java/util/stream/test/org/openjdk/tests/java/lang/invoke/SerializedLambdaTest.java grinder as it runs in jdk_util

**Comment by Haroon-Khel** [comment]
Out of the 10 iterations in the grinder, these tests were the common failures. Others were intermittent

```
Failed test cases: 
TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/StreamLinkTest.java
TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/StreamSpliteratorTest.java
TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/TeeOpTest.java
TEST: java/util/stream/test/org/openjdk/tests/java/util/stream/ToArrayOpTest.java
TEST: java/util/stream/test/org/openjdk/tests/java/util/FillableStringTest.java
TEST: java/util/stream/test/org/openjdk/tests/java/util/MapTest.java
TEST: java/util/stream/test/org/openjdk/tests/java/util/NullArgsTestCase.java
TEST: java/util/stream/test/org/openjdk/tests/java/util/SplittableRandomTest.java
Test results: passed: 662; failed: 8
```

**Comment by Haroon-Khel** [comment]
rebuilds

jdk11 https://ci.adoptium.net/view/Test_grinder/job/Grinder/7138/console
jdk 17 https://ci.adoptium.net/view/Test_grinder/job/Grinder/7139/console
jdk 20 https://ci.adoptium.net/view/Test_grinder/job/Grinder/7140/console

**Comment by Haroon-Khel** [comment]
Tests pass for jdk 11 17 and 20

**Comment by adamfarley** [comment]
Heya Haroon. Do you think [this](https://github.com/adoptium/aqa-tests/issues/4583) could be related?

**Comment by Haroon-Khel** [comment]
Needs to be rerun on newer machines, alot (if not all) of the original machines are out of commission

**Comment by sxa** [comment]
Are you suggesting that it would only fail now on win2012 machines or are you using another definition of "newer" there?

**Comment by sxa** [comment]
Need to verify on win2022 systems

**Comment by Haroon-Khel** [comment]
Rerunning on win22 machines

build-azure-win2022-x64-2
https://ci.adoptium.net/job/Grinder/11422/console

build-azure-win2022-x64-3
https://ci.adoptium.net/job/Grinder/11423/console

test-azure-win2022-x64-1
https://ci.adoptium.net/job/Grinder/11424/console

test-azure-win2022-x64-2
https://ci.adoptium.net/job/Grinder/11425/console

test-azure-win2022-x64-3
https://ci.adoptium.net/job/Grinder/11426/console
