### ISSUE TITLE
C3Jenkins github identity not set for SkaraMirror job commits

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2664]
Mirror job commits are identified with "Jenkins master agent replacement"
https://github.com/adoptium/jdk/commits/dev

The previous master node used "adoptopenjdk-github-bot"

**Comment by sxa** [comment]
Should be fixed now - the git didn't have a `user.name` property set (Didn't seem to make much difference what it was set to since the commit messge is back to normal and doesn't match what `user.name` currently is...)
