### ISSUE TITLE
Move Marist machines to the self-service provisioning

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2673]
To avoid having to go through support for any requests on our Marist systems, they have been trialling a self-service interface for their machines and it is ready to be used as the primary method for provisioning our machines. #2267 has machines which have been provisioned through the new interface and we should start migrating our existing systems across to this too.

The first step will be to ensure we have capacity in the system (At the moment the account I'm using only has 4 machine slots available) and then start duplicating the existing machines in it, followed by decomissioning the existing ones. We will likely look at having at least one `dockerhost` system in order to have a wider range of distributions tested for Linux/s390x (Subject to availability...)

Systems ready for installation:
- dockerhost (8 core, 32GB RAM): 148.100.74.237
- build (RHEL7.9, 4 core, 16GB): 148.100.74.54
- test (SLES12, 2 core, 4GB): 148.100.74.193
- Others listed in https://github.com/adoptium/infrastructure/pull/2690

**Comment by sxa** [comment]
I'm going to use this as a conclusive verification of a number of other infrastructure PRs that we have in flight just now, so I won't run the playbooks until after they are merged:
- https://github.com/adoptium/infrastructure/pull/2691
- https://github.com/adoptium/infrastructure/pull/2394

**Comment by Haroon-Khel** [comment]
For future reference before syncing inventories in awx you have to update the project source first in order for awx to have the latest inventory file. I assumed the syncing inventory process automatically pulled the latest inventory file.

Running https://awx2.adoptopenjdk.net/#/jobs/playbook/137?job_search=page_size:20;order_by:-finished;not__launch_type:sync on test-marist-rhel8-s390x-2 as a prelim playbook run

**Comment by Haroon-Khel** [comment]
Failed at the installation of `systemtap-sdt-devel`

I've created a new job in awx which I can use for debugging/testing. It deploys my own branch, https://github.com/Haroon-Khel/openjdk-infrastructure/tree/awx.debug, which so far the only change is `systemtap-sdt-devel` commented out

https://awx2.adoptopenjdk.net/#/jobs/playbook/143?job_search=page_size:20;order_by:-finished;not__launch_type:sync

**Comment by Haroon-Khel** [comment]
test-marist-rhel8-s390x-2 is actually a SLES15 machine

```
test-marist-rhel8-s390x-2:~ # cat /etc/os-release
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"
```

And test-marist-sles15-s390x-2 is Rhel 8
```
[root@testrhel8 ~]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
```

**Comment by Haroon-Khel** [comment]
Failed at downloading Ant

```
TASK [ant : Download Apache Ant binaries] **************************************
fatal: [test-marist-rhel8-s390x-2]: FAILED! => {"changed": false, "dest": "/tmp/", "elapsed": 0, "gid": 0, "group": "root", "mode": "01777", "msg": "Request failed: <urlopen error unknown url type: https>", "owner": "root", "size": 255, "state": "directory", "uid": 0, "url": "https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.zip"}
```

**Comment by sxa** [comment]
> Failed at the installation of `systemtap-sdt-devel`

Presumnably that's only on a subset of the OSs?

**Comment by sxa** [comment]
Tried [deploying to just the RHEL79 build machines](https://awx2.adoptopenjdk.net/#/jobs/playbook/151) - hit https://github.com/adoptium/infrastructure/issues/2700
Tried [deploying to test-marist-ubuntu2204](https://awx2.adoptopenjdk.net/#/jobs/playbook/153) system - failed because [gcc7 PR](https://github.com/adoptium/infrastructure/pulls) has not yet been merged
Tried [deploying to the RHEL79 build machines](https://awx2.adoptopenjdk.net/#/jobs/playbook/155) skipping the `docker` tag

**Comment by sxa** [comment]
> Failed at the installation of `systemtap-sdt-devel`

This is specific to SLES15. It is installed on the `-1` sles15 machine so it's not entirely clear why this message is appearing on the other machines, unless it was bypassed . `libc.so.6` is on the machine:

```
test-marist-sles15-s390x-2:~ # ls -l /lib64/libc.so.6
lrwxrwxrwx 1 root root 12 Nov  5  2021 /lib64/libc.so.6 -> libc-2.26.so
test-marist-sles15-s390x-2:~ # zypper install systemtap-sdt-devel
Refreshing service 'SMT-http_lxslsmt'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'libc.so.6(GLIBC_2.27)(64bit)' needed by the to be installed systemtap-4.6-151.d_t.3.s390x
 Solution 1: do not install systemtap-sdt-devel-4.6-151.d_t.3.s390x
 Solution 2: break systemtap-4.6-151.d_t.3.s390x by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): c
test-marist-sles15-s390x-2:~ # 
```

**Comment by sxa** [comment]
`test-marist-ubuntu-1804-s390x-` systems `1` and `2` had these entries in `/etc/hosts`:
```
91.189.95.85 ppa.launchpad.net
91.189.88.142 ports.ubuntu.com
```
This was preventing them from updating themselves - presumably implemented to bypass a temporary problem at some point - the date stamp on the file was:
```
-rw-r--r-- 1 root root 487 Apr 22  2021 /etc/hosts
```
I've commented those lines out of both machines now which should avoid this problem:
```
root@test-marist-ubuntu1804-s390x-2:~# apt-get update
Err:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
  Could not connect to ports.ubuntu.com:80 (91.189.88.142), connection timed out
Err:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
  Unable to connect to ports.ubuntu.com:http:
Err:3 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
  Unable to connect to ports.ubuntu.com:http:
Err:4 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
  Unable to connect to ports.ubuntu.com:http:
Reading package lists... Done                      
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic/InRelease  Could not connect to ports.ubuntu.com:80 (91.189.88.142), connection timed out
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic-updates/InRelease  Unable to connect to ports.ubuntu.com:http:
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic-backports/InRelease  Unable to connect to ports.ubuntu.com:http:
W: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/bionic-security/InRelease  Unable to connect to ports.ubuntu.com:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by sxa** [comment]
`sles12-2` was missing the AWX ssh key - now fixed so that should work now.
RHEL8 looks to be trying to install some of the 31-bit (`s390`) packages which we probably don't need.

**Comment by steelhead31** [comment]
@sxa want me to pick up the systemtap-sdt-devel on test-marist-ubuntu-1804-s390x-1 ?

**Comment by sxa** [comment]
Sure - please co-ordinate with Haroon in slack.

**Comment by Haroon-Khel** [comment]
That would be helpful @steelhead31 Thanks

**Comment by sxa** [comment]
[Ubuntu 22.04 looking happier](https://awx2.adoptopenjdk.net/#/jobs/playbook/237) now that https://github.com/adoptium/infrastructure/pull/2691 is merged.

**Comment by steelhead31** [comment]
The sles15 playbooks run better using python 3 as the ansible\_python\_interpreter ( which can be specified in the inventory ), and also an issue with the ipv6 configuration on test-marist-sles15-s390x-2 has been resolved by disabling ipv6 as shown below.

```
1. Edit the file sysctl.conf by executing the command sudo vi /etc/sysctl.conf
2. Add the below 2 lines to the file
  net.ipv6.conf.all.disable_ipv6 = 1
  net.ipv6.conf.default.disable_ipv6 = 1
3. Save and execute the command "sudo sysctl -p" . This would re-load the settings and disables ipv6 address.
4. Execute the command ip a | grep inet - this should only show ipv4 addresses
```

**Comment by sxa** [comment]
From Marist: _"Let me know when fully migrated and I can remove the old servers as we are targeting end of September to power off the old storage servers."_

**Comment by sxa** [comment]
@Haroon-Khel Looks like there may be some problems that need addressing: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_s390x_linux/651

Certainly a subset of them are in the compression code (we've seen issues there elsewhere - at least on Ubuntu 20.04 - that run was on 22.04) and if all the failures are related to that it will be good to confirm which distributions and versions it happens on, as there will be implications elsewhere.

**Comment by Haroon-Khel** [comment]
Nagios should be working on all of the new marist machines expect for test-marist-rhel8-s390x-2 due to 
`No package nagios-plugins-all available`. Should have a quick solution

**Comment by sxa** [comment]
Added `docker` tag onto [test-marist-ubuntu2204-s390x-1](https://ci.adoptopenjdk.net/computer/test%2Dmarist%2Dubuntu2204%2Ds390x%2D1/) as [openjdk_build_docker_multiarch](https://ci.adoptopenjdk.net/job/openjdk_build_docker_multiarch) builds were getting stuck due to lack of [suitable labels](https://ci.adoptopenjdk.net/label/docker&&s390x/). The [dockerhost-marist machine](https://ci.adoptopenjdk.net/computer/dockerhost%2Dmarist%2Dubuntu2204%2Ds390x%2D1/) is currently unsuitable as despite being in jenkins it appears that it cannot run docker as the jenkins user (See [this log](https://ci.adoptopenjdk.net/job/openjdk_build_docker_multiarch/805/execution/node/109/log/) from when I tried to add the tag to that machine)

**Comment by sxa** [comment]
Request for Eclipse to set up two machines for Temurin Compliance: 

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1917

**Comment by sxa** [comment]
NOTE: I've brought docker-marist-ubuntu1604-s390x-1 back online in jenkins for now since that one (why not others?) was causing 'temporarily offline in jenkins' messages to appear in the bot channel, but I've switched the `docker` label to `dockerX`

**Comment by sxa** [comment]
@Haroon-Khel @steelhead31 Can we remove the old machines from Nagios, Jenkins and the inventory files please as they have now been deprovisioned. Full list as follows (Some of these were temporary systems so if you can't find them, that's not a problem):

- 148.100.113.46
- 148.100.113.30
- 148.100.113.58
- 148.100.113.25
- 148.100.113.20
- 148.100.86.102
- 148.100.245.197
- 148.100.84.144
Older early adopter Self-service account:
- 148.100.84.26
- 148.100.84.159
- 148.100.84.52
- 148.100.84.144

**Comment by steelhead31** [comment]
Will do, has the ansible inventory been updated with the new ip's / hostnames ?, Im starting work on fixing the discrepancies between nagios and ansible today.

**Comment by sxa** [comment]
> Will do, has the ansible inventory been updated with the new ip's / hostnames ?

Yep the new ones have been live for a few weeks: https://github.com/adoptium/infrastructure/pull/2690/files

In theory removing the ones listed above should only leave the s390x ones added in that PR.

**Comment by steelhead31** [comment]
All have now been removed from nagios.

**Comment by sxa** [comment]
That'll clear up the slack channel a bit then ;-)

**Comment by sxa** [comment]
The old machines have all been relieved or their duties and returned to Marist.

There is still some more work required to fix some issues that have shown up during this release cycle under #2807 but those can be covered under that issue. The old TCK machines will be decomissioned this week too.

**Comment by Haroon-Khel** [comment]
Removing the following machines from jenkins as they've been decommissioned 

    * https://ci.adoptopenjdk.net/computer/test-marist-sles15-s390x-1/
    * https://ci.adoptopenjdk.net/computer/build-marist-rhel77-s390x-1/
    * https://ci.adoptopenjdk.net/computer/build-marist-rhel77-s390x-2/
    * https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1604-s390x-1/
    * https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1804-s390x-1/
    * https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1804-s390x-2/
    * https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1804-s390x-3/
    * https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1804-s390x-4/
    * https://ci.adoptopenjdk.net/computer/docker-marist-ubuntu1604-s390x-1/
