### ISSUE TITLE
Need a Windows 2012r2 machine for Reproducible build testing

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2675]
To test full reproducible jdk-20 Winx64 builds, I need to do an equivalent 3rd party reproducible build comparison, so need a test machine I can setup to do a build please...

**Comment by andrew-m-leonard** [comment]
@sxa has provided me a machine, thanks!

**Comment by sxa** [comment]
Machine is a `B4s` spec called `andrew-repro-test` in the Azure portal and Andrew has been provided with the credentials for his exclusive use.

**Comment by sxa** [comment]
Second machine created for the new version of the layout - setup guidelines at https://github.com/adoptium/temurin-build/issues/2978#issuecomment-1259993010

TL;DR:

`.\vs_community.exe --noweb --add Microsoft.VisualStudio.Workload.NativeDesktop;includeRecommended;includeOptional --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.Tools.ARM64 --add Microsoft.VisualStudio.Component.VC.ATL.ARM64 --add Microsoft.VisualStudio.Component.VC.MFC.ARM64 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64`

**Comment by sxa** [comment]
Machine https://ci.adoptopenjdk.net/computer/build%2Dazure%2Dwin2012r2%2Dx64%2D3%2Dsxa/ now online with the new VS2019 layout.

**Comment by sxa** [comment]
Note: Keeping this open until the machine is decommissioned so we don't forget about it :-)

**Comment by sxa** [comment]
Now decomissioned
