### ISSUE TITLE
jdk8 jdk_jfr 313 tests failed on test-docker-ubuntu2004-armv7l-3

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#2684]
jdk8 jdk_jfr_2 313 tests failed with crash on test-docker-ubuntu2004-armv7l-3 

https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_arm_linux_testList_1/47/#showFailuresLink
Grinder: https://ci.adoptopenjdk.net/job/Grinder/5324/#showFailuresLink 

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? jdk_jfr_2
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure
- **Hyperlink** to re-run: 
[Rerun link](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=hotspot_jre_2&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk8_hs_extended.openjdk_arm_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=arm_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=test-docker-ubuntu2004-armv7l-3&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fci.adoptopenjdk.net%2Fjob%2Fbuild-scripts%2Fjob%2Fopenjdk8-pipeline%2F2203%2Fartifact%2Ftarget%2Flinux%2Farm%2Ftemurin%2FOpenJDK8U-jdk_arm_linux_hotspot_8u342b07.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v0.9.3-release&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk8u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-linux-arm-temurin&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=53&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=true&UPSTREAM_JOB_NUMBER=112&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)
- Is there an existing issue elsewhere covering this? No
- Which machine(s) does it work on? [test-sxa-armv7l-ubuntu2004-odroid-2](https://ci.adoptopenjdk.net/label/test-sxa-armv7l-ubuntu2004-odroid-2). grinder https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5323/
- Which machine(s) does it fail on?  test-docker-ubuntu2004-armv7l-3, might same to  test-docker-ubuntu2004-armv7l-1,  test-docker-ubuntu2004-armv7l-2.  

Any other details:

**Comment by sophia-guo** [comment]
Crash

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0xf617d440, pid=3350750, tid=0xe0a5f460
#
# JRE version: OpenJDK Runtime Environment (8.0_342-b07) (build 1.8.0_342-b07)
# Java VM: OpenJDK Client VM (25.342-b07 mixed mode linux-aarch32 )
# Problematic frame:
# V  [libjvm.so+0x335440]  write_checkpoint_header(unsigned char*, long long, long long, bool, unsigned int)+0xe8
#
# Core dump written. Default location: /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_arm_linux_testList_1/aqa-tests/TKG/output_16584865593451/jdk_jfr_2/work/scratch/1/core or core.3350750
#
# An error report file with more information is saved as:
# /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_arm_linux_testList_1/aqa-tests/TKG/output_16584865593451/jdk_jfr_2/work/scratch/1/hs_err_pid3350750.log
[thread -530189216 also had an error]
[thread -521472928 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
    
```

**Comment by smlambert** [comment]
Same issue seen in Jan 2024 release (details at: https://github.com/adoptium/aqa-tests/issues/4984#issuecomment-1897527288), example of crashing in [Grinder/8657](https://ci.adoptium.net/job/Grinder/8657)

**Comment by roberttoyonaga** [comment]
Please see my explanation of the problem here: https://github.com/adoptium/aqa-tests/issues/3115#issuecomment-2256561374

**Comment by roberttoyonaga** [comment]
https://github.com/adoptium/aqa-tests/pull/5469#event-13780240293 has been merged. Is it safe to close this issue now?

**Comment by sxa** [comment]
If it's been excluded then yes I'm fine with closing it - thanks for diagnosing this one! :-)
