### ISSUE TITLE
"Ansible Playbook / macOS" github check failing for all PRs

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2693]
Ref: https://github.com/adoptium/infrastructure/runs/7750861675?check_suite_focus=true
```
TASK [Common : Install Build Tool Casks] ***************************************
failed: [localhost] (item=adoptopenjdk10) => {"ansible_loop_var": "item", "changed": false, "item": "adoptopenjdk10", "msg": "Error: Calling Cask::DSL::Version#before_colon is disabled! Use Cask::DSL::Version#csv instead.\nPlease report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:\n  /usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk10.rb:14"}
changed: [localhost] => (item=packages)
```

**Comment by zdtsw** [comment]
slack thread relate to this issue: https://adoptium.slack.com/archives/C53GHCXL4/p1655203667404569

**Comment by zdtsw** [comment]
tested in draft run https://github.com/adoptium/infrastructure/runs/8031345539?check_suite_focus=true
job failed in a different step which related to: https://github.com/adoptium/infrastructure/runs/8031345539?check_suite_focus=true
install adoptopenjdk10 works
![Screenshot from 2022-08-26 09-17-45](https://user-images.githubusercontent.com/915053/186845173-3be64f06-1bcf-42b1-9404-a0532a4fe745.png)
