### ISSUE TITLE
find missing option on Solaris machine build-siteox-solaris10u11-sparcv9-1

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2695]
[build-siteox-solaris10u11-sparcv9-1](https://ci.adoptopenjdk.net/computer/build-siteox-solaris10u11-sparcv9-1)

find -path option on solaris is missing

```
find: bad option -path
09:45:30  find: [-H | -L] path-list predicate-list
```

Details:
See https://ci.adoptopenjdk.net/job/Grinder/5391/

Will add more details shortly (rerun link was not posted as the job fails before it gets created).

**Comment by sxa** [comment]
This would be better fixed by using standard POSIX commands. I'll prep a PR for get.sh

**Comment by sxa** [comment]
Related PR now closed
