### ISSUE TITLE
VPC - Upgrade Ubuntu2104 to Ubuntu2204

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2697]
The VPC for ubuntu 2104 keeps failing https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Ubuntu2104,label=vagrant/1500/console

```
12:52:44 TASK [Common : Install gnupg2 for aarch64] *************************************
12:52:44 skipping: [127.0.0.1]
12:52:44 
12:52:44 TASK [Common : Add the openjdk repository to apt] ******************************
12:53:10 fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "apt cache update failed"}
12:53:10 
12:53:10 PLAY RECAP *********************************************************************
12:53:10 127.0.0.1                  : ok=8    changed=1    unreachable=0    failed=1    skipped=23   rescued=0    ignored=0   
```

We should look at upgrading this box to Ubuntu 22.04 LTS

**Comment by sxa** [comment]
Steps completed:

- Under the vagrant1-vagrant4 users I have run: `vagrant box add generic/ubuntu2204`
- On vagrant5 to see if this is a more sensible way of copying them across I have run: `cd .vagrant.d/boxes && tar cf - -C /home/vagrant1/.vagrant.d/boxes/ubuntu-VAGRANTSLASH-ubuntu2204 | tar xpvf -` as this seems to be the only change to the file system on the other users.
- Updated the VPC job configuration to have a `Ubuntu2204` option in the `OS` parameter (Note - this won't work until I've got a PR in place, so I don't recommend using it!)
- PR to add support to the automation for the new version and also create the new Vagrantfile

It's currently giving me `adoptopenjdkU22: Warning: Authentication failure. Retrying...` messages - @Willsparker is there any magic needed on a new box to make the login work ok? I couldn't identify any existing doc on that.

**Comment by sxa** [comment]
ping @Willsparker - any idea if there's some "secret sauce" needed on a new Ubuntu? If the answer is "No" that's fine too but I'm trying to take the easy option of seeing if we do know of a solution first before digging :-)
