### ISSUE TITLE
Ansible request for RHEL7 docker install

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2700]
- Bug in ansible playbook

Details: The docker role does not work on RHEL7. The following failure was from an s390x system - unclear if it is across architectures:
```
fatal: [build-marist-rhel79-s390x-2]: FAILED! => {
   "changed": false,
   "msg": "https://download.docker.com/linux/rhel/docker-ce.repo/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
               Trying other mirror.
               To address this issue please refer to the below knowledge base article
               https://access.redhat.com/articles/1320623
               If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.
               One of the configured repositories failed (docker YUM repo s390x),
               and yum doesn't have enough cached data to continue. At this point the only
                safe thing yum can do is fail. There are a few ways to work \"fix\" this:
                    1. Contact the upstream for the repository and get them to fix the problem.
                    2. Reconfigure the baseurl/etc. for the repository, to point to a working upstream.
                    This is most often useful if you are using a newer
                    distribution release than is supported by the repository (and the
                    packages for the previous distribution…
```
Note tgat in the error message `https://download.docker.com/linux/rhel/docker-ce.repo` is a file, not a directory, so it is likely that it is simply being referenced wrongly for some reason.

**Comment by Haroon-Khel** [comment]
I think changing the repo url to `https://download.docker.com/linux/rhel/7/stable/` looks like it might work

**Comment by Haroon-Khel** [comment]
Running on build-marist-rhel79-s390x-2 (no docker installed)
https://awx2.adoptopenjdk.net/#/jobs/playbook/199?job_search=page_size:20;order_by:-finished;not__launch_type:sync

**Comment by sxa** [comment]
> Running on build-marist-rhel79-s390x-2 (no docker installed) https://awx2.adoptopenjdk.net/#/jobs/playbook/202?job_search=page_size:20;order_by:-finished;not__launch_type:sync

LGTM assuming it's done what it claims to have!

**Comment by Haroon-Khel** [comment]
Pr is in https://github.com/adoptium/infrastructure/pull/2707

**Comment by Haroon-Khel** [comment]
Can be closed as the pr is merged
