### ISSUE TITLE
System unavailable: no hw.arch.aarch32&&ci.role.perf nodes available

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2716]
Need at least 1 of the 2 https://ci.adoptopenjdk.net/label/sw.os.linux&&hw.arch.aarch32&&ci.role.perf/ nodes to be brought online.

Test jobs sent to https://ci.adoptopenjdk.net/computer/test-sxa-armv7l-ubuntu2004-odroid-2/ are hitting no space left on device issues, marking it offline so we can get through the jdk18u respin

- Link to any log file showing the problem:

https://ci.adoptopenjdk.net/job/Grinder/5502/console

(or see aborted jobs from https://github.com/adoptium/aqa-tests/issues/3940#issuecomment-1228372065)

- Please describe the issue:
```
java.nio.file.FileSystemException: /ssd/jenkins/workspace/Grinder/aqa-tests: No space left on device
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
```

**Comment by sxa** [comment]
Cleared up some space that was in use of the `-2` machine - will do a proper cleanup next week as there are some macos backups on there too.

**Comment by sxa** [comment]
I think `-1` may have a problem with it's SSD that's causing it to crash - will keep an closer eye on it ... It's back for now though.
