### ISSUE TITLE
Verify current GH workflow works on macos-11+ with vagrant

### ISSUE THREAD

**Issue by zdtsw** [adoptium/infrastructure#2717]
Since GH runner wont support macos-10.15 after Dec 2022, we need to test and verify if "build_vagrant.yml" works with macos-11/macos-latest.

From a test run looks like job cannot find vagrant in line `vagrant up` 
some work might be needed before we can do the last part upgrade to get rid of macos-10.15 in GA totally. 

Ref: https://github.com/adoptium/infrastructure/issues/2715

**Comment by zdtsw** [comment]
any reason we chose mac-os as runner for this [part](https://github.com/adoptium/infrastructure/blob/master/.github/workflows/build_vagrant.yml#L14)? it is just easier to install virtualbox by brew than ubuntu, or ? 
@gdams

**Comment by gdams** [comment]
>any reason we chose mac-os as runner for this [part](https://github.com/adoptium/infrastructure/blob/master/.github/workflows/build_vagrant.yml#L14)? it is just easier to install virtualbox by brew than ubuntu, or ?
@gdams 

the macos VMs are the only ones to support virtualization

**Comment by zdtsw** [comment]
ok I see, on ubuntu need to enable libvrt and that cannot be done from GH action.
so if we still want solaris to be run in GH, we need to make it work on macos-11 
currently we have https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/OS=Solaris10,label=vagrant/ also running for solaris10 on jdk8
