### ISSUE TITLE
Permission request for https://ci.adoptopenjdk.net/

### ISSUE THREAD

**Issue by zdtsw** [adoptium/infrastructure#2722]
I would like to get permission in https://ci.adoptopenjdk.net/
- start job: I  have permission to start some jobs like pipeline, downstream job (rebuild previous one or start a new run) but not the ones under https://ci.adoptopenjdk.net/job/build-scripts/job/release/
- abort job: I think I have aborted certain jobs but not e.g https://ci.adoptopenjdk.net/job/Grinder nor https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk19/job/jdk19-alpine-linux-aarch64-temurin_SmokeTests so I am not sure what other job I might miss permission
- config job: I do not think i have permission to view or update any job in this jenkins instance
- create job: I do not have permission to create any test job for myself.
- access folder:  https://ci.adoptopenjdk.net/job/build-scripts/job/release/ I cannot access this URL even I login to the Jenkins.

**Comment by sxa** [comment]
Access granted to `AdoptOpenJDK*build` group which should give you access to most of those tha are required. The release jobs can be dealt with separately, but I'll leave this open for now.

**Comment by zdtsw** [comment]
verified: abort, create new, check config these all work for me now

**Comment by zdtsw** [comment]
I found out I still miss permission to run VPC
```
19:44:31 ?zdtsw? lacks permission to run on ?infra-ibmcloud-vagrant-x64-1.2?
19:44:31 ?zdtsw? lacks permission to run on ?infra-ibmcloud-vagrant-x64-1.3?
19:44:31 ?zdtsw? lacks permission to run on ?infra-ibmcloud-vagrant-x64-1.5?
```
from https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1535/consoleFull
Could this be granted?

**Comment by sxa** [comment]
Try now - that should not have been restricted :-)

**Comment by zdtsw** [comment]
> Try now - that should not have been restricted :-)

rerun the same build, but still hanging there https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1537/ 
```
07:52:16 ?zdtsw? lacks permission to run on ?infra-ibmcloud-vagrant-x64-1.1?
07:52:16 ?zdtsw? lacks permission to run on ?infra-ibmcloud-vagrant-x64-1.2?
07:52:16 ?zdtsw? lacks permission to run on ?infra-ibmcloud-vagrant-x64-1.3?
07:52:16 ?zdtsw? lacks permission to run on ?infra-ibmcloud-vagrant-x64-1.4?
07:52:16 ?zdtsw? lacks permission to run on ?infra-ibmcloud-vagrant-x64-1.5?
```

it is not urgent, can check later when you are back :D

**Comment by zdtsw** [comment]
Any procedure need to follow to get permission for  https://ci.adoptopenjdk.net/job/build-scripts/job/release/ ? I will be the champion for Oct CPU release.

**Comment by karianna** [comment]
@sxa Will this require a request to the EF?

**Comment by sxa** [comment]
@karianna No as it's still controlled via the AdoptOpenJDK github org.

**Comment by sxa** [comment]
> rerun the same build, but still hanging there https://ci.adoptopenjdk.net/job/VagrantPlaybookCheck/1537/

OK I have no idea why that's happening. I've tried a few things to no avail. It doesn't seem to be working with groups. Have opened https://github.com/adoptium/infrastructure/issues/2778 to investigate.

**Comment by zdtsw** [comment]
> @karianna No as it's still controlled via the AdoptOpenJDK github org.

Any way can proceed with this permission?

**Comment by karianna** [comment]
@zdtsw Which permissions are still required?

**Comment by sxa** [comment]
@karianna It'll be adding to `AdoptOpenJDK*release`.

**Comment by karianna** [comment]
That team doesn't seem to exist?

**Comment by karianna** [comment]
Invited to the relevant groups - may need to check your inbox or GitHub homepage to accept the invites

**Comment by zdtsw** [comment]
awesome! :+1:  got the mails + did a logout then login to the jenkins 
 can access https://ci.adoptopenjdk.net/job/build-scripts/job/release/ now

**Comment by sxa** [comment]
I'll close this now (As mentioned the VPC access will need to be dealt with separately as it's being weird). If anything else shows up during the release cycle please reopen this.
