### ISSUE TITLE
32bit packages causing failure in playbook s390x RHEL

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2725]
The following packages found [here](https://github.com/adoptium/infrastructure/blob/7c29bb812d58c4df12cfa2dad1779f9f2c724fe8/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/RedHat.yml#L78) are causing playbook failures on rhel s390x
```
Additional_Build_Tools_RHEL_s390x:
  - glibc.s390                    # a dependency required for executing a 32-bit C binary
  - glibc-devel.s390              # a dependency required for executing a 32-bit C binary
  - libstdc++.s390                # a dependency required for executing a 32-bit C binary
```

```
TASK [Common : Install additional build tools for RHEL on s390x] ***************
failed: [test-marist-rhel8-s390x-2] (item=glibc.s390) => {"ansible_loop_var": "item", "changed": false, "failures": ["No package glibc.s390 available."], "item": "glibc.s390", "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
failed: [test-marist-rhel8-s390x-2] (item=glibc-devel.s390) => {"ansible_loop_var": "item", "changed": false, "failures": ["No package glibc-devel.s390 available."], "item": "glibc-devel.s390", "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
failed: [test-marist-rhel8-s390x-2] (item=libstdc++.s390) => {"ansible_loop_var": "item", "changed": false, "failures": ["No package libstdc++.s390 available."], "item": "libstdc++.s390", "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
```

**Comment by sxa** [comment]
@AdamBrousseau Do you still have a requirement for 31-bit packages to be installed via the playbooks?

**Comment by AdamBrousseau** [comment]
If we do, it would be for IBM Java 8 compiles. Do we know why they're failing? Is this something we could make optional? If not maybe we can move them to our internal fork.

**Comment by AdamBrousseau** [comment]
31bit libs aren't available on rhel8. Can we fix the PBs to not run them on 8+?

**Comment by sxa** [comment]
> 31bit libs aren't available on rhel8. Can we fix the PBs to not run them on 8+?

Yep that's the best option in the absence of any objections (The only 32-bit Linux that adoptium builds is ARM) so we don't need them on RHEL.
