### ISSUE TITLE
Nagios server is unstable

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2727]
- Please describe the issue:

The nagios server has gone offline at least twice in recent weeks. When it goes, the machine cannot be contacted over ssh but is responsive on the Hetzner console. The machine has been upgraded to Ubuntu 22.04 (The other main Hetzner machine we have is on Ubuntu 20.04) so it's possible there is an issue with 22.04 on their systems. We can track instances of outages in this issue.

**Comment by sxa** [comment]
Offline again - does not have an IPv4 address
![image](https://user-images.githubusercontent.com/6487691/188477717-3878df7a-5b56-405f-9775-59d87deac920.png)

**Comment by sxa** [comment]
Output should be what it is immediately after a reboot:
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:a2:01:e2:d1 brd ff:ff:ff:ff:ff:ff
    inet 172.31.1.100/24 brd 172.31.1.255 scope global dynamic eth0
       valid_lft 86358sec preferred_lft 86358sec
    inet6 fe80::5054:a2ff:fe01:e2d1/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by sxa** [comment]
This is happening almost precisely 24 hours after the machine was last restarted which is a bit suspicious:
```
Sep  2 12:12:28 nagios kernel: [    0.000000] Linux version 5.15.0-40-generic (buildd@lcy02-amd64-047) [...]
```

**Comment by sxa** [comment]
I have stopped the nagios service and will see if it stops again at 17:04 (16:24 UK time) tomorrow.

**Comment by sxa** [comment]
As a temporary hack I've put in a cron entry to reboot the server each morning. Not ideal at all - it looks like `dhclient eth0` will also recover it, but since that's freezing at this point:
```
+ . /usr/share/sendmail/dynamic
/sbin/dhclient-script: 28: .: cannot open /usr/share/sendmail/dynamic: No such file
```
and looping round and never exiting I'm reluctant to put that in the cron job. More investigation most definitely required ...
FYI @steelhead31

**Comment by sxa** [comment]
I have moved `/etc/dhcp/dhclient-exit-hooks.d/sendmail` to `/root/sendmail` which is allowing `dhclient` to function correctly. On that basis I have adjusted the crontab to run that instead of rebooting the server.

It is unclear whether the same 24 hour limit will apply to the dhclient operation. It's also possible that the "fix" to the sendmail script will cause the problem not to occur, but since I will be absent for the next week I will leave the cron entry as-is so we reduce the risk of instability.

**Comment by steelhead31** [comment]
Following the Ubuntu upgrade, I believe sendmail needs to be reinstalled, as the O/S upgraded causes issues. I've reinstalled sendmail and will see if the issues persist.

**Comment by steelhead31** [comment]
Nagios server has had no issues with stability for 3 days now.

**Comment by sxa** [comment]
LGTM - closing
