### ISSUE TITLE
Linter in GH action is throwing errors

### ISSUE THREAD

**Issue by zdtsw** [adoptium/infrastructure#2730]
Related GH action runs from:
https://github.com/adoptium/infrastructure/pull/2721

e.g 
https://github.com/adoptium/infrastructure/runs/8096269351?check_suite_focus=true

**Comment by sxa** [comment]
@zdtsw Please ensure when raising issues that the important error messages are included in the desciption as well as any link to the logs, so the errors can be searched for in GitHub. I'll add them here - there seems to be three primary things that the linter is currently objecting to:

`Error: name All plays should be named.`
`Error: name All names should start with an uppercase letter.`
`Error: no-handler Tasks that run when changed should likely be handlers.`
