### ISSUE TITLE
azurebuildagent055fe0 has issue to resolve fedora repo

### ISSUE THREAD

**Issue by zdtsw** [adoptium/infrastructure#2739]
From running installer job, seems this machine has issue to do `dnf upgrade`
Since I cannot find this machine from inventory not sure how it is setup. 
The label I used for running this job is "dockerBuild&&linux&&x64" 
```
---> Running in 878826834b03
Fedora 36 - x86_64                              0.0  B/s |   0  B     00:00    
[91mErrors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-36&arch=x86_64 [getaddrinfo() thread failed to start]
[0m[91mError: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-36&arch=x86_64 [getaddrinfo() thread failed to start]
```
see link:
https://ci.adoptopenjdk.net/view/work-in-progress/job/Sophia-adoptium-packages-linux-pipeline/157/console
and
https://ci.adoptopenjdk.net/view/work-in-progress/job/Sophia-adoptium-packages-linux-pipeline/152/console

Ref: https://github.com/adoptium/installer/pull/472

**Comment by sxa** [comment]
This is a dynamically created machine and therefore non-trivial to diagnose problems on. The problem does not appear to occur when I try to run a `dnf update` in a `fedora:36` container on another x64 system

On a separate node, what functionality is still left in [Sophia-adoptium-packages-linux-pipeline](https://ci.adoptopenjdk.net/view/work-in-progress/job/Sophia-adoptium-packages-linux-pipeline) that isn't in the main installer job? @sophia-guo

**Comment by zdtsw** [comment]
if other machines with these labels work, we can drop this issue.

code has been merged , we should use [ adoptium-packages-linux-pipeline job](https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline/) for installer.
[Sophia-adoptium-packages-linux-pipeline](https://ci.adoptopenjdk.net/view/work-in-progress/job/Sophia-adoptium-packages-linux-pipeline) will only be used for test purpose

**Comment by sxa** [comment]
> if other machines with these labels work, we can drop this issue.

But does it fail with all of the dynamic machines (those with an azure prefix). If so we're going to get random failures depending on which machine the job lands on.

**Comment by zdtsw** [comment]
[Sophia-adoptium-packages-linux-pipeline](https://ci.adoptopenjdk.net/view/work-in-progress/job/Sophia-adoptium-packages-linux-pipeline) was created for me (at that time I did not have permission to create job) to test the change in installer. It was not used for any release. the code behind this job was on my branch, it got merged to master 2 weeks ago.  
So, they should be identical now.

**Comment by sxa** [comment]
Closing as @steelhead31 is going to be reworking the installers as part of https://github.com/adoptium/installer/issues/1005 and will either hit it and fix it or it won't be a problem any more.
