### ISSUE TITLE
Access request for scfryer

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2755]
Required access level (Delete as appropriate). Note that you should only
request the minimum level that is required to solve your problem

- [X] root/Administrative

System for which access is needed:
(test-scaleway-ubuntu1604-x64-1) - 51.15.76.107

Require root access to fix several issues identified by nagios ( apt updates, root partition space, ntpd )

**Comment by sxa** [comment]
This was nothing personal to you and is now fixed. Machine did not have the current key installed so Bastillion was not able to update it.
The scaleway machines have this note, so I have added the correct admin key to `instance_keys` as directed:
```
#  WARNING: Automatically generated file
# This file will be erased at every boot
# This file was generated with '/usr/local/sbin/scw-fetch-ssh-keys'
#
# To add a new key, you can:
#   -- Add keys on your Scaleway account https://cloud.scaleway.com/#/credentials
#   -- Add keys using server tags - https://cloud.scaleway.com/#/servers/c65ca930-bf4f-4e58-91d6-1d5b4525b093
#        - i.e: "AUTHORIZED_KEY=ssh-rsa_XXXXXXXXXXX AUTHORIZED_KEY=ssh-rsa_YYYYYYYYYYYYYYY"
#        - Be sure to replace all spaces with underscores
#        - $> sed 's/ /_/g' ~./ssh/id_rsa.pub
#   -- Add the keys to '/root/.ssh/instance_keys' which will be imported
#
# And recreate your 'authorized_keys' file with the new keys:
#   -- Run 'scw-fetch-ssh-keys --upgrade'
```
