### ISSUE TITLE
Some test-docker armv7 containers have jdk11 in their jdk8 directory

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2762]
For the following machines, their jdk8 path points to a jdk11 binary

test-docker-ubuntu2004-armv7l-1
test-docker-ubuntu2004-armv7l-2
test-docker-ubuntu2004-armv7l-3
```
root@412c7c344fe5:/# /usr/lib/jvm/jdk8/bin/java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

Their dockerfiles install jdk 8 https://github.com/adoptium/infrastructure/blob/d0da68208c7eff255ddcda85ff5e080968b8a296/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/Dockerfiles/Dockerfile.u2004#L6 (the architecture is changed to arm during build)

I'll look at upgrading their, and other docker container's, default jdk to 17

**Comment by zdtsw** [comment]
i am bit confused, either it download jdk8 or did a yum/apt install openjdk8, how could it ended with a jdk11 ?

**Comment by Haroon-Khel** [comment]
Yeah I don't know how this happened, im guessing manual intervention. I've upgraded the jdks to 17 now anyway so im closing this issue
