### ISSUE TITLE
Install Nagios client side bits on all AIX machines so they can be monitored

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2764]
During a call today it was discovered that not all of the AIX machines that we use have the appropriate ssh keys and client code required for the Nagios server to be able to interact with them. Only the AIX7.1 build machines have the required setup.

This issue will cover ensuring that the other AIX machines are set up in a suitable way, and get them integrated into the Nagios server

**Comment by steelhead31** [comment]
The AIX playbooks now install the required elements. All AIX build machines are monitored.
