### ISSUE TITLE
Nagios - Add Additional Jenkins Check Label Job To Nagios Server Group For ubuntu & fpm labels

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2765]
Currently the nagios server has check_label jobs for various jenkins options such as

Check Label- arm/ci.role.test
Check Label- build/linux/s390x
Check Label- macos10.14/build/mac/x64
Check Label- wix 

A further check is required to be added for the machines with the build, windows & x64 labels

Please update the readme.md file in the ansible/playbooks/nagios/README.md with a new section detailing how to add an additional version of these checks.

**Comment by lumuchris256** [comment]
Hi @steelhead31 @smlambert  i would like to take up this issue

**Comment by smlambert** [comment]
great @lumuchris256 - I will let @steelhead31 provide more details on how to get started on this one!
