### ISSUE TITLE
Nagios - Add Additional Disk Space Check For /tmp on AIX hosts

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2766]
For the AIX hosts, add an additional monitoring command to monitor the disk space under the /tmp path.

**Comment by julian55455** [comment]
HI @smlambert can I work on this?

**Comment by Nigale-Djomo** [comment]
Hello, 

Hope you are doing good on this day.
My name is Nigale and i am an outreachy applicant. 
Can this task be assigned to me

Best

**Comment by Nigale-Djomo** [comment]
Hello 

Hope you are doing good on this day.
My name is Nigale and i am an outreachy applicant.
Can this task be assigned to me

Best
