### ISSUE TITLE
Nagios - Add Additional Disk Space Check For /home/jenkins on AIX hosts

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2767]
For the AIX hosts, add an additional monitoring command to monitor the disk space under the /home/jenkins path.

**Comment by Sarahligbe** [comment]
Hi, I'm Sarah. I'm an outreachy applicant. Can this be assigned to me

**Comment by smlambert** [comment]
For sure @Sarahligbe - and I will leave it to @steelhead31 to provide more details on how you can get started on this!

**Comment by Sarahligbe** [comment]
Thanks. I'll be waiting for more details from@steelhead31

**Comment by aixtools** [comment]
- I have been looking at the PR #2789 - and I do not understand how this adds anything. It is just some comments in README.md.

- What am I missing?

**Comment by Sarahligbe** [comment]
I worked on it on my local VM. @steelhead31 asked me to add it to the README.md so he'll use the documentation to make the changes to the production nagios server. He already did that and it's working

**Comment by aixtools** [comment]
:) How could I know? Thx for assistance.
