### ISSUE TITLE
Upgrade jenkins agent's JDK to 11 or newer

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2771]
Jenkins latest LTS requires a jdk version of 11 or newer to be used as the jenkins agent when connecting a machine to jenkins. 

https://www.jenkins.io/blog/2022/06/28/require-java-11/

So at some point we will need to check and upgrade the java version used by each machine to connect to jenkins.

https://adoptium.net/support/, since java 17 has the longest EOL, I would be happy with that

This will require:

- Check if the machine has jdk17 installed (install if needed)
- Change the JavaPath variable in the machine's jenkins config to java 17
- Disconnect and Reconnect the machine for changes to take effect
- Run a grinder on the machine to ensure everythings working

**Comment by sxa** [comment]
Dup of https://github.com/adoptium/infrastructure/issues/2763?

**Comment by Haroon-Khel** [comment]
Yep didn't see yours
