### ISSUE TITLE
test-equinix-ubuntu1604-x64-1 appears to have an issue running git commands

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2773]
test-equinix-ubuntu1604-x64-1 - as per the console output of this job: 
https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_dev.system_x86-64_linux_testList_2/1/console

[test-equinix-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/test-equinix-ubuntu1604-x64-1/) appears to have an issue running git commands

```
10:05:29  The recommended git tool is: git
10:05:33  No credentials specified
10:05:33  Cloning the remote Git repository
10:05:33  ERROR: Error cloning remote repo 'origin'
10:05:33  hudson.plugins.git.GitException: Command "git fetch --tags --progress -- https://github.com/adoptium/aqa-tests.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
10:05:33  stdout: 
10:05:33  stderr: /usr/local/libexec/git-core/git-remote-https: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/local/libexec/git-core/git-remote-https)
10:05:33  
10:05:33  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2675)
10:05:33  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2099)
```

I have taken this machine offline (with a reference to this issue) until it can be resolved.

To reproduce, run any test job with LABEL parameter set to test-equinix-ubuntu1604-x64-1, or rebuild https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_dev.system_x86-64_linux_testList_2/1/.

**Comment by sxa** [comment]
This machine is due to be decomissioned as part of https://ci.adoptopenjdk.net/computer/test-equinix-ubuntu1604-x64-1/ so we may not being it back, but I'll keep this open in case we find an easy fix.
