### ISSUE TITLE
System unavailable: test-azure-win11-aarch64-1

### ISSUE THREAD

**Issue by zdtsw** [adoptium/infrastructure#2783]
- Please put the system name in the title of this issue.
test-azure-win11-aarch64-1

- Link to any log file showing the problem:
https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/cross-compiled-version-out/492/console

- Please describe the issue:
We only have one node assigned with label "windows&&riscv64" which is test-azure-win11-aarch64-1
and it is offline, so the jenkins job https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/cross-compiled-version-out/ if running for windows is not working and this blocks openjdkX-pipeline to finish.

**Comment by gdams** [comment]
The system appeared to have restarted itself. I've resolved this now
