### ISSUE TITLE
Low disk space: https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-1/

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#2784]
https://ci.adoptopenjdk.net/computer/build-osuosl-aix71-ppc64-1/ is offline, only has 7Gb free

**Comment by sxa** [comment]
Fixed - I had a tarball kicking around which was wasting space and have cleared some other junk in jenkins' home dir

Related (Nagios won't currently pick up on this for AIX): https://github.com/adoptium/infrastructure/issues/2767

FYI @backwaterred do you still need the `jdk11u-dev` in your home dir on this machine? That would clearu up a furtehr 2.3Gb. The OSUOSL AIX machines are quite frugal in terms of disk capacity. particularly

**Comment by backwaterred** [comment]
As it turns out, I don't need need that folder any more. Thanks for reminding me about it.
