### ISSUE TITLE
Access request for luhenry

### ISSUE THREAD

**Issue by luhenry** [adoptium/infrastructure#2786]
Required access level (Delete as appropriate). Note that you should only
request the minimum level that is required to solve your problem

- [x] Non-privileged
- [ ] jenkins user

System for which access is needed:

Any RISC-V board.

Please explain why you need this access including whether it is a temporary or permanent request:

I'm focusing on the development of the RISC-V adoptium CI. It would be very helpful to have access to a RISC-V board which is closest to Adoptium CI.

**Comment by sxa** [comment]
Access added to the jumpbox which will let you into the riscv64 machines once I sort out that access (separately).
`ssh luhenry@lab.rvperf.org uptime` should work for you just now

**Comment by sxa** [comment]
Access to machine "043" now granted to `luhenry` user via the jumpbox. Details sent to user.

**Comment by sxa** [comment]
043 is no longer available. Access can be granted to others as required.
