### ISSUE TITLE
Nagios: Create Scripts To Manage Existing Host Checks

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2787]
Part of epic : #2445 

Create a script to perform the following tasks on the nagios configuration files :

1.  Add an existing defined check to an existing host.
2.  Remove a defined check from an existing host.

The script should behave roughly as described below, and accept parameters so that it can be used as part of the ongoing automation effort and can be checked into the following path ansible/playbooks/nagios/roles/Nagios\_Server/scripts :

Script Example:

./nagios\_check --add --check \<\<check\_name>> --host \<\<host\_name>> --config\_path = \<\<path\_to\_config>>  
e.g  
./nagios\_check --add --check  "Disk Space For Jenkins" --host [build-osuosl-aix71-ppc64-1](https://nagios.adoptopenjdk.net/nagios/cgi-bin/extinfo.cgi?type=1&host=build-osuosl-aix71-ppc64-1)  --config\_path /usr/local/nagios/etc 

The --add should be switched for --remove to have that check removed from the configuration files.

**Comment by Sarahligbe** [comment]
@smlambert I'll love to be assigned this issue. @steelhead31 assigned it to me as a follow on the other issue I was assigned #2767

**Comment by steelhead31** [comment]
@Sarahligbe I've managed to assign it now you've commented!

**Comment by steelhead31** [comment]
Closing as functionality replaced with nagios-config-server role, and templating process.
