### ISSUE TITLE
ESXi server at Equinix

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2792]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): ESXi
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): x64
- Provider (leave blank if it does not matter): Equinix
- Desired usage: Replacement for the existing ESXi server due to machine migration, and to use for relpacement of some of the smaller xLinux machines we currently have hosted at Equinix
- Any unusual specification/setup required: ESXi :-)
- How many of them are required: 2 (One to begin with, but should be duplicated with the same set of systems across both for redundancy - ideally with both in different data centres.

Please explain what this machine is needed for:
- Part of https://github.com/adoptium/infrastructure/issues/2666 - existing servers will be decommissioned and we need to ensure the replacements are operational before then.
To be consistent with the existing naming convention these should have a provider name of `equinix_esxi` in the hostname:

Guest VMs required are as follows. Specs listed are of the existing systems
- [x] Solaris/x64 build machine (8 core, 16GB, 250Gb) (Probably don' need this much disk ...)
- [x] Solaris/x64 test (AQA) machine (n/a - no current system separate from build)
- [x] Solaris/x64 TCK machine (4 core, 8Gb, 500Gb) (Probably doesn't need this much disk...)
- [x] Linux/x64 performance machine (4 core, 8Gb, 140Gb)
- [x] Linux/x64 TCK machine (8 core, 8Gb, 140Gb) (Also used as dockerhost, so may benefit from more RAM)

I'll create tick boxes for the second instance too:
- [ ] Solaris/x64 build machine
- [ ] Solaris/x64 test (AQA) machine
- [ ] Solaris/x64 TCK machine
- [ ] Linux/x64 performance machine
- [ ] Linux/x64 TCK machine

**Comment by Haroon-Khel** [comment]
New solaris test machine https://ci.adoptopenjdk.net/computer/test-equinix_esxi-solaris10-x64-1-NEW/
Running a sanity test on it https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6138/console

**Comment by Haroon-Khel** [comment]
@sxa The original issue https://github.com/adoptium/infrastructure/issues/2666#issue-1301005042, there are 3 ubuntu16 machines which needed to be virtualised, im guessing theyre to be used for perf testing. Ive virtualised one https://ci.adoptopenjdk.net/computer/test-equinix_esxi-ubuntu1604-x64-1-NEW/, do we still need 2 more?

**Comment by sxa** [comment]
We should have two. I would also suggest that since we're switching to new hardware (where the perf characteristics will be different anyway) that we bump them up to ubuntu 22.04 instead of 16.04 which is now unsupported. I'd suggest one more - and possibly on the same machine purely because if we split it across AMD vs Intel with differnet characteristics the results won't be consistent.

**Comment by Haroon-Khel** [comment]
I've upgraded the ubuntu16 perf machine I made earlier to 2204, https://ci.adoptopenjdk.net/computer/test-equinix_esxi-ubuntu2204-x64-1-NEW/, and created a second u2204 perf machine https://ci.adoptopenjdk.net/computer/test-equinix_esxi-ubuntu2204-x64-1
2-NEW/. Both are on the intel esxi server. I'll create an AMD replica after I finish these machines

**Comment by Haroon-Khel** [comment]
A second ESXi server has been created as the first one ran out of assignable IP addresses. On this second server, we have the 2 tck machines, solaris and ubuntu. EF are currently setting them up with an ETA of before the end of the month
