### ISSUE TITLE
Access request for scfryer

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2793]
Required access level (Delete as appropriate). Note that you should only
request the minimum level that is required to solve your problem

- [X] root/Administrative

System for which access is needed: build-equinix-centos8-armv8-1

Need temporary root access, to install nagios, I'm also unable to do this via awx.

**Comment by sxa** [comment]
Machine will get replaced/reinstalled as part of https://github.com/adoptium/infrastructure/issues/2479 but I've put your key on it for now until that happens :-)
