### ISSUE TITLE
Nagios: Enhancement: Document Process For Adding Windows Hosts To A Nagios Server

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2802]
Part Of Epic #2445 

Please investigate the process, tasks and steps involved in adding Nagios monitoring checks to a windows host.

Please create a new document in the /ansible/playbooks/nagios folder called something like How\_To\_Add\_Nagios\_To\_Windows.MD , with detailed steps about the tasks etc on both the Nagios Server & the Windows Host, so that we can try this in production at a later date. I'd recommend using nagios etc to create a nagios server, and a windows VM, so that you have an isolated development environment.

**Comment by lumuchris256** [comment]
hi @steelhead31 i would want to take this up
