### ISSUE TITLE
System planned downtime: Equinix aarch64 systems

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2808]
Equinix are migrating systems in their data centers starting on the 14th of November. This will take up to four days to complete. We have been asked to shut the machines down by end of day on the 13th.

No backups will be performed, but the expectation is that the machines will come back as-is, although potentially with a different IP address.

FYI @Haroon-Khel

**Comment by Haroon-Khel** [comment]
Setup here

https://ci.adoptopenjdk.net/computer/build-osuosl-ubuntu2204-aarch64-1/
https://ci.adoptopenjdk.net/computer/dockerhost-osuosl-ubuntu2204-aarch64-1/

Dockerstatic machines (cant get them to connect yet)
https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2204-armv8l-3/ on the build machine
https://ci.adoptopenjdk.net/computer/test-docker-centos8-armv8l-1/ on the docker host machine

**Comment by Haroon-Khel** [comment]
build-osuosl-ubuntu2204-aarch64-1 fails to build a jdk11 aarch64 binary https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-temurin/142/console

**Comment by Haroon-Khel** [comment]
I cant get the dockerstatic machines to connect to jenkins. The correct public key is on the container, iptables looks fine (cant see any reason the packets are getting dropped when comparing it to a working dockerhost machine).

On dockerhost-osuosl-ubuntu2204-aarch64-1 
```
CONTAINER ID   IMAGE       COMMAND               CREATED             STATUS             PORTS                                   NAMES
ee6bf41532c6   aqa_cent8   "/usr/sbin/sshd -D"   About an hour ago   Up About an hour   0.0.0.0:2224->22/tcp, :::2224->22/tcp   cent8.2224
```
From my workstation
```
hkhel@hkhel-mac ~ % nc -zv 140.211.167.67 2224
nc: connectx to 140.211.167.67 port 2224 (tcp) failed: Operation timed out
```
Same goes for the build-osuosl machine

**Comment by Haroon-Khel** [comment]
The build-osuosl machine can run tests thankfully https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6116/console

**Comment by Haroon-Khel** [comment]
>Dockerstatic machines (cant get them to connect yet)
https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2204-armv8l-3/ on the build machine
https://ci.adoptopenjdk.net/computer/test-docker-centos8-armv8l-1/ on the docker host machine

I've configured them so that they connect to jenkins, as opposed to jenkins connecting to the machines. Should work until I can resolve the connectivity issues

**Comment by sxa** [comment]
Equinix systems are now back online again (Same IPs so no extra work needed on our part)

**Comment by sxa** [comment]
I'm going to close this but it sounds like we'll need some remedial work on the OSUOSL systems which can be covered elsewhere.
