### ISSUE TITLE
Audit all ACLs on the jenkins server

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2814]
As  per https://github.com/adoptium/infrastructure/issues/2108 we should perform an audit of the individual access controls on every job in our jenkins server and determine what the correct controls for each job or set of jobs are. We should aim to remove individuals from all jobs and rely on the teams defined either as temurin committers overall or the groups as defined in https://github.com/adoptium/infrastructure/issues/2108#issuecomment-1308661897

The outcome from this will be a documented set of what each group controls in jenkins that can be included in [the top level Adoptium SSDF issue](https://github.com/adoptium/adoptium/issues/120#issuecomment-1308661158)

**Comment by zdtsw** [comment]
Should this include non-human access controls? e.g bot, credential token.

**Comment by sxa** [comment]
This is now mostly done. Partially as a result of the work for https://github.com/adoptium/ci-jenkins-pipelines/pull/656 we have very few jobs using anything other than a group or special permissions for the two bot users `eclipse-temurin-bot` and `eclipse-temurin-compliance-bot`.

Some notable exceptions are:
- `luhenry` with permissions for some RISC-V jobs (He should be added to `build*triage` instead
- `adambrousseau` for some of the jobs he has visibility of (Likewise - suggest adding to build*triage*)
- `bethgriggs` with access to create_release_notes (new job, will plan to revoke once we've got a couple of releases out of the way)
- `calderast` on [jdk8-alpine-linux-x64-hotspot](https://ci.adoptium.net/job/jdk8-alpine-linux-x64-hotspot/) (presumably for debugging, although not run in over a year)
- `scottfryer` on [release-build-pipeline-generator](https://ci.adoptium.net/job/build-scripts/job/utils/job/release-build-pipeline-generator/) and [build-pipeline-generator](https://ci.adoptium.net/job/build-scripts/job/utils/job/build-pipeline-generator/) (TBC which they should be replaced with)

Ping @andrew-m-leonard for any particular thoughts on the above.

**Comment by sxa** [comment]
For reference this will generate the list of specific user overrides, excluding the two bots and the pr-tester jobs which have not been regenerated recently: `find jobs -name config.xml -print | xargs grep -w permission | grep -v pr-tester | grep -w USER | egrep -v 'eclipse-temurin-bot|eclipse-temurin-compliance-bot'`

**Comment by sxa** [comment]
Ping @andrew-m-leonard sine we're now out of the release cycle we should move this forward. Are you ok with Ludovic and Adam being added to `build*triage` so they can get access to the jobs instead of being named individuals? And do you have any view on what group Scott should be added to (or specifically, what access controls we should use on the generation jobs)

**Comment by andrew-m-leonard** [comment]
@sxa Yes, please add Adam and Ludovic to build*triage
Re.Scott, I suspect we need a role one step above build, something like ReleaseEngineer, i'm not sure of the complete set of roles we currently have?

**Comment by sxa** [comment]
> @sxa Yes, please add Adam and Ludovic to build*triage Re.Scott, I suspect we need a role one step above build, something like ReleaseEngineer, i'm not sure of the complete set of roles we currently have?

https://github.com/adoptium/infrastructure/pull/2977/files :-) We do have a `build-release` role.

**Comment by sxa** [comment]
With the exception of beth on the release notes job and one anonymous entry on the build pipeline generator this is now complete. The audit has been done and all cases understood, therefore closing.

**Comment by jiekang** [comment]
@sxa Is "a documented set of what each group controls in jenkins that can be included in https://github.com/adoptium/adoptium/issues/120#issuecomment-1308661158" no longer in plan? Or maybe tracked elsewhere?
