### ISSUE TITLE
Create a process for verifying a node is ready to be added to Jenkins with label ci.role.test

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2815]
In order to verify that a newly added machine is ready to be added to Jenkins as a test node (with the label ci.role.test), we should outline a process by which the machine is verified to have the appropriate configuration.  This will help stabilize the machine layer and reduce surprises when doing daily/weekly/release triage.

One suggestion is to modify the [AQA_Test_Pipeline](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/) job to take a LABEL parameter (set to the hostname of the new machine) to run the 9 test areas that are expected to be run and pass as part of AQAvit verification of JDK binaries.  These are the groups of tests that need to run and pass as part of a release.

This would also show us the expected execution times for all of those 9 top-level targets on the new machines.

This is a discussion issue, other ideas and input welcome.

**Comment by llxia** [comment]
Thanks @smlambert . 
LABEL is already supported in AQA_Test_Pipeline script. I updated the job configuration to add the LABEL parameter.

**Comment by smlambert** [comment]
Action to add a section to the [FAQ](https://github.com/adoptium/infrastructure/blob/master/FAQ.md) doc to describe running the AQA_Test_Pipeline.
