### ISSUE TITLE
WindowsPB - Nvidia Cuda 9.0 Toolkit No Longer Available From NVIDIA

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2818]
Whilst running the Windows Playbook, the Nvidia_Cuda_Toolkit task fails, as the download of the Nvidia Cuda 9.0 toolkit is no longer available.

https://developer.nvidia.com/compute/cuda/9.0/Prod/network_installers/cuda_9.0.176_windows_network-exe

I believe this is only required for openJ9, @AdamBrousseau  have you encountered this, or do you have any workaround etc?

**Comment by AdamBrousseau** [comment]
Looks like those links went dead recently. We ran them not long ago without issue. We could probably find a download link somewhere else? We have a copy of it locally but I'm not sure if we'd want to host it. Might be legal implications of redistribution as well.
It seems v11.8 is the current release.
@keithc-ca what is the feasibility of moving OpenJ9 up to Cuda v11?

**Comment by keithc-ca** [comment]
CUDA 9.0 is still available at https://developer.nvidia.com/cuda-90-download-archive.
It seems the name of that specific download is now
* https://developer.nvidia.com/compute/cuda/9.0/Prod/network_installers/cuda_9.0.176_win10_network-exe

**Comment by AdamBrousseau** [comment]
Seems the other releases are there. Only the 9.0 is not from what I've seen so far. Perhaps we need to contact nvidia. They have a forum.
https://forums.developer.nvidia.com/c/development-tools/cuda-developer-tools/285

**Comment by AdamBrousseau** [comment]
https://forums.developer.nvidia.com/t/broken-download-links-for-cuda-toolkit-9-0-windows/234422

**Comment by steelhead31** [comment]
Thanks @AdamBrousseau ,  I'll keep an eye on that thread, in the short term, I do have a copy of the full Cuda 9 installer (1.4Gb), @sxa, what do you think about hosting this in the Vendor\_Files, until a more permanent solution is found ?

**Comment by steelhead31** [comment]
@keithc-ca / @AdamBrousseau  would switching to one of the CUDA v9 services packs ( 9.1 or 9.2 ) be an option both of those are still available.

**Comment by keithc-ca** [comment]
Using 9.1 instead of 9.0 would only drop support for 9.0, but hopefully, removal of 9.0 downloads was just an error that Nvidia will correct.

**Comment by steelhead31** [comment]
@sxa for the official nvidia download for the full exe install, thats no longer available, the checksum is listed as   
  
48d85427ddb4c0eae8ee46aea9d3126e cuda\_9.0.176\_windows.exe ( from [https://developer.download.nvidia.com/compute/cuda/9.0/Prod/docs/sidebar/md5sum-4.txt](https://developer.download.nvidia.com/compute/cuda/9.0/Prod/docs/sidebar/md5sum-4.txt) )  
  
my download is exactly the same (at least md5 checksum identical...)  
  
\[scfryer@scfryer Downloads\]$ md5sum cuda\_9.0.176\_windows.exe  
48d85427ddb4c0eae8ee46aea9d3126e  cuda\_9.0.176\_windows.exe  
\[scfryer@scfryer Downloads\]$

**Comment by sxa** [comment]
I had a chat with @AdamBrousseau and @keithc-ca today - let's bump to 9.1. We can revert if we need to later. OpenJ9 are using machine snapshots in IBM Cloud that already have the version they need so they still have 9.0 but would be affected if they had to rebuild an image.

@steelhead31 Can you handle bumping it to 9.1 please?

I think we should probably keep a copy of the original installer around just in case though ...

**Comment by keithc-ca** [comment]
Just to confirm: the plan is to stay with version 9.0, but use a working URL; it shouldn't matter which version Windows it was intended for, the build only needs a small subset of the header files (which should be the same, even on Linux).

**Comment by steelhead31** [comment]
I've tested the windows 10 version of the 9.0 cuda installer on windows server 2012, it throws this error..  
  
 

![](https://user-images.githubusercontent.com/60462088/207378622-0b8914c7-f581-4e58-984b-47360f82c54b.png)

**Comment by keithc-ca** [comment]
Did you try using the installer like in the playbook (where it doesn't try to install the driver)?
> network-exe.exe -s compiler_9.0 nvml_dev_9.0

Actually, we don't even need the compiler, that argument could be replaced by `cudart_9.0`:
> network-exe.exe -s cudart_9.0 nvml_dev_9.0

**Comment by keithc-ca** [comment]
Also, as noted https://github.com/eclipse-openj9/openj9/issues/16463#issuecomment-1348880691, if the only problem is on Windows 2012, we should be able to safely drop support for that environment.

**Comment by steelhead31** [comment]
I've tried passing the compiler parameters and the cudart parameters with no success, I've also tried to override the pre-requisite operating system check with no success.

**Comment by keithc-ca** [comment]
If https://github.com/eclipse/omr/pull/7088 is accepted, the version of CUDA used at build time will have no relevance for the versions that are supported at runtime. For example, building with 9.1 will still allow use on a system where 9.0 (or even older) is present.

**Comment by sxa** [comment]
> Also, as noted [eclipse-openj9/openj9#16463 (comment)](https://github.com/eclipse-openj9/openj9/issues/16463#issuecomment-1348880691), if the only problem is on Windows 2012, we should be able to safely drop support for that environment.

@keithc-ca Related to this, we've started shifting the Temurin builds over to Windows Server 2022 - is that ok for all versions of OpenJ9 too?

**Comment by keithc-ca** [comment]
We discovered a minor problem on Windows 11 (fixed via https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/630).

Windows Server 2022 should be fine, but we'll want to fix any issues building there, so do let us know if you encounter any problems.
