### ISSUE TITLE
System unavailable: https://packages.adoptium.net/

### ISSUE THREAD

**Issue by mikhailkoliada** [adoptium/infrastructure#2819]
- Please put the system name in the title of this issue.

- Link to any log file showing the problem: self-explicable

- Please describe the issue: also self-explicable, we use adoptium for `actions/runner-images` and can't download a gpg key

**Comment by karianna** [comment]
This is being worked on with JFrog.

**Comment by gdams** [comment]
Issue has now been resolved. Closing
