### ISSUE TITLE
Equinix Altra upgrade to Ubuntu 22.04

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2820]
Ubuntu 22.04 has now been added as a valid option for the `x.large.arm` servers at Equinix (Thanks @vielmetti!) so we should be able to bump this up now.

_Originally posted by @sxa in https://github.com/adoptium/infrastructure/issues/2479#issuecomment-1316805138_

Since this system is not yet live in jenkins we should be able to reinstall it from scratch with 22.04 and continue the verification of the docker containers:

Ref:
- https://github.com/adoptium/infrastructure/issues/2479#issuecomment-1307658249 (extended.openjdk runs on the different containers)
- https://github.com/adoptium/infrastructure/issues/2815 (Machine setup test process)
- [equinix-altra1-dockerhost.tar.gz](https://github.com/adoptium/infrastructure/files/10020949/equinix-altra1-dockerhost.tar.gz) (Extra dockerstatic files, and the start command I'd used on the machine when I set it up with Ubuntu 20.04)

**Comment by sxa** [comment]
System reinstall with Ubuntu 22.04 attempted but may be hanging ...

**Comment by sxa** [comment]
Note: There is a second 1Tb disk on this machine which could be formatted as `btrfs` and mounted on `/var/lib/docker` in order to try and take advantage of some of Docker's [btrfs support](https://docs.docker.com/storage/storagedriver/btrfs-driver/).

**Comment by sxa** [comment]
Just got very confused because I'd put this table in [the wrong issue](https://github.com/adoptium/infrastructure/issues/2807#issuecomment-1315497753), but this was some Grinder runs from the Docker images I had created on the (now reinstalled) Ubuntu 20.04 host:

Node | Grinder link | Result
--- | --- | ---
ubuntu1804-1 | [6145](https://ci.adoptopenjdk.net/job/Grinder/6145/) | 24 failures, 6h
ubuntu2004-1 | [6146](https://ci.adoptopenjdk.net/job/Grinder/6146/) | 25 failures, 10h
alma8 | [6147](https://ci.adoptopenjdk.net/job/Grinder/6147/) | 30 failures, 6h20
rocky9 | [6148](https://ci.adoptopenjdk.net/job/Grinder/6148/) | 30 failures, 6h22
ubi9 | [6149](https://ci.adoptopenjdk.net/job/Grinder/6149/) | 32 failures, 6h20
Fedora35 | [6150](https://ci.adoptopenjdk.net/job/Grinder/6150/) | 24 failures, 9h42
Fedora36 | [6151](https://ci.adoptopenjdk.net/job/Grinder/6151/) | 24 failures, 9h30
Alpine315 | [6157](https://ci.adoptopenjdk.net/job/Grinder/6157/) | 88 failures
Alpine316 | [6156](https://ci.adoptopenjdk.net/job/Grinder/6156/) | 88 failures
Alpine314 | [6158](https://ci.adoptopenjdk.net/job/Grinder/6158/) | 89 failures

**Comment by steelhead31** [comment]
Machine currently has the following containers running

docker container ls --format "table {{.ID}}\\t{{.Image}}\\t{{.Names}}\\t{{.Ports}}"

<table><tbody><tr><td>09a7b7456ad5</td><td><strong>aqa_ubi8</strong></td><td>ubi8.2247</td><td>0.0.0.0:2247-&gt;22/tcp</td></tr><tr><td>02a5d797ea43</td><td>aqa_deb11</td><td>deb11.2211</td><td>0.0.0.0:2211-&gt;22/tcp</td></tr><tr><td>d20973988a10</td><td>aqa_cent8</td><td>cent8.2228</td><td>0.0.0.0:2228-&gt;22/tcp</td></tr><tr><td>0f8444d60b98</td><td>aqa_alp317</td><td>alp317.2217</td><td>0.0.0.0:2217-&gt;22/tcp</td></tr><tr><td>03f1b11b122c</td><td>aqa_alp316</td><td>alp316.2216</td><td>0.0.0.0:2216-&gt;22/tcp</td></tr><tr><td>205ad558b32e</td><td>aqa_alp315</td><td>alp315.2215</td><td>0.0.0.0:2215-&gt;22/tcp</td></tr><tr><td>cf211e0f4b96</td><td>aqa_alp314</td><td>alp314.2214</td><td>0.0.0.0:2214-&gt;22/tcp</td></tr><tr><td>e2bafc50fb5c</td><td>aqa_alma8</td><td>alma8.2248</td><td>0.0.0.0:2248-&gt;22/tcp</td></tr><tr><td>43fda62e5766</td><td>aqa_f37</td><td>f37.2237</td><td>0.0.0.0:2237-&gt;22/tcp</td></tr><tr><td>08c153be3d76</td><td>aqa_f36</td><td>f36.2236</td><td>0.0.0.0:2236-&gt;22/tcp</td></tr><tr><td>863e5de7ecdf</td><td>aqa_f35</td><td>f35.2235</td><td>0.0.0.0:2235-&gt;22/tcp</td></tr><tr><td>946a4a9d9b86</td><td>aqa_u2204</td><td>U2204_2226</td><td>0.0.0.0:2226-&gt;22/tcp</td></tr><tr><td>a60f9e4d1b24</td><td>aqa_u2004</td><td>U2004_2224</td><td>0.0.0.0:2224</td></tr></tbody></table>

These now require adding to jenkins.

**Comment by steelhead31** [comment]
@sxa, I think this new host can now be considered complete.
