### ISSUE TITLE
Enhancement: WindowsPB : Include Installation Of NSClient++ Software For Nagios Monitoring

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2825]
- Request for new playbook addition

Install NSClient++ as part of the windows playbook/installation

Details:

In order to use nagios monitoring on windows machines, some software to provide the equivalent functionality to the nagios plugins used on linux/unix systems is required.  [NSClient++](https://www.nsclient.org/) is the most common piece of opensource windows software used to provide this functionality ( to report things such as disk space usage, cpu usage etc ). It may be possible to manually write scripts and plugins to achieve the same results, or identify individual plugins from the nagios plugin exchange, but having done some investigation, I believe this is a quicker solution to implement.

Implements Element 7.2 of Nagios Monitoring Epic #2445

**Comment by steelhead31** [comment]
@sxa I've added some details, but in a nutshell, this is by far the simplest/quickest solution for windows, it does require a different set of plugins to those on \*nix systems. NSClient has the bonus of being opensource though :)

**Comment by sxa** [comment]
NOTE: Azure machines are configured restrictively by default and require a networking rule on the Azure console to be able to allow this connection through. Settings which have been defined on the machines are as follows (Shame this came up after I recorded the [Azure deployment video](https://www.youtube.com/watch?v=CC_gOFl3unY) but c'est la vie :-)

![image](https://user-images.githubusercontent.com/6487691/205303034-da356c7c-4b32-4c18-8d16-8053637c52a5.png)
