### ISSUE TITLE
No space left on device on test-sxa-armv7l-ubuntu2004-odroid-1

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2829]
No space left on device on test-sxa-armv7l-ubuntu2004-odroid-1

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? All test jobs hitting this machine are failing to run
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure, https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.functional_arm_linux/253
- **Hyperlink** to re-run in Grinder:  There is no rerun link, as the Test job can not set up to run.  Send any job to this machine as a test.
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on? test-docker-ubuntu2004-armv7l-1
- Which machine(s) does it fail on? test-sxa-armv7l-ubuntu2004-odroid-1

<img width="381" alt="Screen Shot 2022-11-21 at 9 25 01 AM" src="https://user-images.githubusercontent.com/2836948/203079154-e827f0b8-83a7-4c93-ac77-3d60a8d7e1c0.png">

Any other details:
```
07:38:58  ERROR: Execution failed
07:38:58  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from cpc145836-warw19-2-0-cust71.3-2.cable.virginm.net/80.2.248.72:34214
07:38:58  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
07:38:58  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
07:38:58  		at hudson.remoting.Channel.call(Channel.java:1000)
07:38:58  		at hudson.FilePath.act(FilePath.java:1194)
07:38:58  		at hudson.FilePath.act(FilePath.java:1183)
07:38:58  		at hudson.FilePath.mkdirs(FilePath.java:1374)
07:38:58  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:97)
07:38:58  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
07:38:58  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
07:38:58  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
07:38:58  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
07:38:58  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
07:38:58  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
07:38:58  		at java.base/java.lang.Thread.run(Thread.java:833)
07:38:58  java.nio.file.FileSystemException: /ssd/jenkins/workspace/Test_openjdk8_hs_extended.functional_arm_linux: No space left on device
```

**Comment by sxa** [comment]
@smlambert It looks like this is `-2` rather than `-1`. Can you confirm this isn't a problem on `-1`?

**Comment by sophia-guo** [comment]
I got the issue with -2 https://github.com/adoptium/infrastructure/issues/2251#issuecomment-1315755371

**Comment by sxa** [comment]
Interesting - jenkins is showing `N/A` for the disk space on that system - I would normally have expected it to detect that it was out of space and bring it offline. I wonder why that hasn't happened this time. `odroid-1` is correctly showing 134Gb free

**Comment by smlambert** [comment]
Both seem to have a problem:

https://ci.adoptopenjdk.net/computer/test-sxa-armv7l-ubuntu2004-odroid-2/ - 
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-arm-temurin_SmokeTests/98

https://ci.adoptopenjdk.net/computer/test-sxa-armv7l-ubuntu2004-odroid-1/ - 
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.functional_arm_linux/253

**Comment by sxa** [comment]
I suspect that problem on `-1` was a "random glitch" of some sort. The machine has also been restarted over the weekend (when it was idle - so that's not the cause of the failure in that log) - I've kicked off https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.functional_arm_linux/254/console to retest.

**Comment by sxa** [comment]
Job on `-1` passed.
`-2` now has 20Gb free and I'm clearing up about 24Gb now so this can now be closed.
