### ISSUE TITLE
 jdk8 s390x Temurin test jobs fail on test-marist-ubuntu2004-s390x-1 and test-marist-ubuntu2204-s390x-1

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2830]
**What are you trying to do?**
Run smoke tests and sanity.openjdk tests against jdk8 s390x Temurin build (even though we do not release this version as it does not have a JIT).

**Expected behaviour:**
That we would be able to run smoke tests and sanity.openjdk tests.

**Observed behaviour:**
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-temurin_SmokeTests/99 (on [test-marist-ubuntu2004-s390x-1](https://ci.adoptopenjdk.net/computer/test-marist-ubuntu2004-s390x-1))
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_s390x_linux/725 on [test-marist-ubuntu2204-s390x-1](https://ci.adoptopenjdk.net/computer/test-marist-ubuntu2204-s390x-1)

Fail with 
```
07:40:22  + ./get.sh -s /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_s390x_linux/aqa-tests/.. -p s390x_linux -r upstream -j 8 -i hotspot --openj9_repo https://github.com/eclipse-openj9/openj9.git --openj9_branch master --tkg_repo https://github.com/adoptium/TKG.git --tkg_branch master
07:40:22  TESTDIR: /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_s390x_linux/aqa-tests
07:40:22  get jdk binary...
07:40:22  --sdkdir is set to upstream. Therefore, skip download jdk binary
07:40:22  Uncompressing file: OpenJDK8U-jdk_s390x_linux_hotspot_2022-11-19-12-05.tar.gz ...
07:40:22  Uncompressing file: OpenJDK8U-jre_s390x_linux_hotspot_2022-11-19-12-05.tar.gz ...
07:40:22  Uncompressing OpenJDK8U-debugimage_s390x_linux_hotspot_2022-11-19-12-05.tar.gz over ./j2sdk-image/jre...
07:40:22  tar (GNU tar) 1.34
07:40:22  License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
07:40:22  Run /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_s390x_linux/openjdkbinary/j2sdk-image/bin/java -version
07:40:22  =JAVA VERSION OUTPUT BEGIN=
07:40:22  Error: dl failure on line 898
07:40:22  Error: failed /home/jenkins/workspace/Test_openjdk8_hs_sanity.openjdk_s390x_linux/openjdkbinary/j2sdk-image/jre/lib/s390x/server/libjvm.so, because libffi.so.6: cannot open shared object file: No such file or directory
```

**Any other comments:**
Successful run from 17 days ago
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_s390x_linux/716/ on [test-marist-rhel8-s390x-2](https://ci.adoptopenjdk.net/computer/test-marist-rhel8-s390x-2)

Successful run from 3 days ago
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-temurin_SmokeTests/98/
on [test-marist-rhel7-s390x-2](https://ci.adoptopenjdk.net/computer/test-marist-rhel7-s390x-2)

**Comment by steelhead31** [comment]
@smlambert , I've done some investigating, and this appears to have been caused by an o/s update, upgrading some versions of the libffi libraries to version 7 on ubuntu 20.04 and version 8 on ubuntu 22.04 .. Im investigating solutions to this.

**Comment by steelhead31** [comment]
@smlambert  Reinstalling the missing packages fixes the problem.  would you mind re-checking, whilst I look into the necessary updates in the ansible playbooks

**Comment by sxa** [comment]
`libffi` again 😡 
In the past we have created a symlink from the installed version to the one that it's expecting, but that's clearly not ideal ;-)

**Comment by smlambert** [comment]
Verify on test-marist-ubuntu2004-s390x-1 in [Grinder/6218](https://ci.adoptopenjdk.net/job/Grinder/6218)
Verify on test-marist-ubuntu2204-s390x-1 in [Grinder/6219](https://ci.adoptopenjdk.net/job/Grinder/6219)

**Comment by sxa** [comment]
> Verify on test-marist-ubuntu2004-s390x-1 in [Grinder/6218](https://ci.adoptopenjdk.net/job/Grinder/6218)
> Verify on test-marist-ubuntu2204-s390x-1 in [Grinder/6219](https://ci.adoptopenjdk.net/job/Grinder/6219)

Much better!

**Comment by sxa** [comment]
Related: https://github.com/adoptium/infrastructure/issues/2815
