### ISSUE TITLE
Some Jenkins nodes with sw.tool.docker label seem to be docker containers 

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2832]
Ensure we use the [sw.tool.docker](https://ci.adoptopenjdk.net/label/sw.tool.docker/) label for machines with Docker installed, not for nodes that are themselves containers.  This label is used by tests that require docker or podman and typically will not run inside a container (docker in docker).

3 nodes in question are 
[docker-osuosl-ubuntu2004-ppc64le-1](https://ci.adoptopenjdk.net/computer/docker-osuosl-ubuntu2004-ppc64le-1/) 
[docker-skytap-ubuntu2004-ppc64le-1](https://ci.adoptopenjdk.net/computer/docker-skytap-ubuntu2004-ppc64le-1/) 
[dockerhost-osuosl-ubuntu2204-aarch64-1](https://ci.adoptopenjdk.net/computer/dockerhost-osuosl-ubuntu2204-aarch64-1/)

Related to https://github.com/adoptium/infrastructure/issues/93

**Comment by sxa** [comment]
I've just logged into all three of those systems  and been able to start up a docker container on each of them so I'm not clear on what the problem is on those systems - have you seen something to indicate the labels on those three machines are not accurate, or had a failure to run as expected on those hosts?

**Comment by smlambert** [comment]
I assumed given the naming that those hosts were themselves docker containers, and there is a note regarding the containers tests being added by @jerboaa that they may not run well container in container (related: https://github.com/adoptium/aqa-tests/issues/4143#issuecomment-1311938497).  So, while I have not tried those tests on these machines, I raised the issue in case it's a real concern.
