### ISSUE TITLE
Please add me to this organisation/team so that we (Loongson) can start contributing

### ISSUE THREAD

**Issue by Panxuefeng-loongson** [adoptium/infrastructure#2836]
I'm a member of the Loongson platform jdk team, and would like to contribute to Adoptium/infrastructure. We want to add LoongArch machines to the infrastructure to support the Loongson platform jdk build. 

Thanks

**Comment by tellison** [comment]
Hi @Panxuefeng-loongson 

Thank you for the offer, consider yourself part of "the team"! I understand that you wish to add LoongArch support and you are equally welcome to contribute to any of the infrastructure tasks.

Just a reminder that rights such as committer are earned after demonstrating a good understanding of the infrastructure codebase including implications of changes, and working on tasks that benefit the project.

I'm looking forward to the PRs for adding LoongArch support to the infra code.

**Comment by Panxuefeng-loongson** [comment]
Hi @tellison 

Thank you for your suggestions. I will abide by the community norms and contribute to the project.

**Comment by sxa** [comment]
This likely does not require further discussions - contributions can be accepted via PRs and issues without any special access :-)
