### ISSUE TITLE
System unavailable: arm&&ci.role.test

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2840]
Nagios reporting only 9% of systems online.
https://ci.adoptopenjdk.net/label/arm&&ci.role.test/ shows that all of the arm32 docker containers are currently offline.
It appears that jenkins is unable to connect to it. I've checked one of them and there is no obvious reason for it - the jenkins key is in place, but the container does not seem to be allowing it for authentication.

**Comment by sxa** [comment]
```
root@test-equinix-ubuntu2004-armv8l-02:~# docker exec -it 412c7c344fe5 bash
root@412c7c344fe5:/# su - jenkins
su: warning: cannot change directory to /home/jenkins: Permission denied
su: failed to execute /bin/sh: Permission denied
root@412c7c344fe5:/# ls -ld /home/jenkins
drwxr-xr-x 1 jenkins jenkins 4096 Dec  5 18:20 /home/jenkins
root@412c7c344fe5:/# ls -ldn /home/jenkins
drwxr-xr-x 1 1000 1000 4096 Dec  5 18:20 /home/jenkins
root@412c7c344fe5:/# id jenkins
uid=1000(jenkins) gid=1000(jenkins) groups=1000(jenkins)
root@412c7c344fe5:/# 
```

**Comment by steelhead31** [comment]
First issue was with permissions on / , /lib and /bin ( these were 777, Id expect them to be 755 ) I've changed them ( not recursively ) and the su - jenkins within the container works ok... jenkins still doesnt launch for some reason though, so I'll keep looking.

**Comment by steelhead31** [comment]
The machines have now been returned to service.
