### ISSUE TITLE
Jenkins unable to connect to ESXi Solaris machines

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2842]
Jenkins is not able to connect to 2 of our Solaris machines hosted on our Esxi server 
https://ci.adoptopenjdk.net/computer/test-equinix_esxi-solaris10-x64-1-NEW/
https://ci.adoptopenjdk.net/computer/build-equinix_esxi-solaris10-x64-1-NEW/

Currently their node configs are set to `Launch agent by connecting it to controller`

Jenkins fails to connect if set to `Lauch agents via ssh`

**Comment by sxa** [comment]
@Haroon-Khel I had a quick play this morning. Based on the error it look like it was related to the host key verification so I adjusted the configuration of a new definition https://ci.adoptopenjdk.net/computer/build%2Dequinix%5Fesxi%2Dsolaris10%2Dx64%2D1%2DSSH to have a host key verification strategy of Manually Provided and then put the key from `/etc/opt/csw/ssh/ssh_host_rsa_key.pub` into the box. That allowed it to connect, then it seems you can switch it back to `Known hosts file Verification Strategy` without any problems.

Feel free to switch over to using the `-SSH` one. They're both live at the moment (ssh one is runnig with a root dir of /export/home/jenkins/sshagent` to avoid conflicts. It's also set to use zulu 11 (Which requires `LD_PRELOAD_64` in the start options in the jenkins agent config).

**Comment by Haroon-Khel** [comment]
Excellent find. I've done the same thing to https://ci.adoptopenjdk.net/computer/test-equinix_esxi-solaris10-x64-1-NEW/
