### ISSUE TITLE
New Solaris/x64 machine is not building reliably

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2847]
See https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-temurin/

Each recent build which occurred on [build-equinix_esxi-solaris10-x64-1-NEW](https://ci.adoptopenjdk.net/computer/build-equinix_esxi-solaris10-x64-1-NEW/) appears to have failed while checking out from the pipelines repository:

```
22:36:11  [CHECKOUT] Checking out Adopt Pipelines https://github.com/adoptium/ci-jenkins-pipelines.git : master
[Pipeline] checkout
22:36:11  The recommended git tool is: git
22:36:11  No credentials specified
22:36:11  Cloning the remote Git repository
22:36:12  ERROR: Error cloning remote repo 'origin'
22:36:12  hudson.plugins.git.GitException: Could not init /export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-temurin
```

**Comment by Haroon-Khel** [comment]
Running the git clone on the machine itself

```
bash-3.2$ git clone https://github.com/adoptium/ci-jenkins-pipelines.git
Cloning into 'ci-jenkins-pipelines'...
git: 'remote-https' is not a git command. See 'git --help'.
bash-3.2$ git version
git version 2.31.0
```

I believe we have a fix for this in the playbooks somewhere. Looking...

**Comment by sxa** [comment]
That's a PATH issue - it can't find `git-remote-https`.

**Comment by Haroon-Khel** [comment]
The machine is not missing git-remote-https

```
bash-3.2$ ls -la /usr/local/bin/git-remote-https
-rwxrwxr-x   1 root     root     1664400 Mar  5  2015 /usr/local/bin/git-remote-https
```
Once `/usr/local/bin` is added to the PATH, it has no problem git cloning

```
bash-3.2$ export PATH=/usr/local/bin/:$PATH
bash-3.2$ git clone https://github.com/adoptium/ci-jenkins-pipelines.git
Cloning into 'ci-jenkins-pipelines'...
remote: Enumerating objects: 12814, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 12814 (delta 8), reused 13 (delta 7), pack-reused 12795
Receiving objects: 100% (12814/12814), 4.80 MiB | 2.37 MiB/s, done.
Resolving deltas: 100% (8674/8674), done.
bash-3.2$ 
```

**Comment by Haroon-Khel** [comment]
Yep, ive kicked off a pending build https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-temurin/

**Comment by Haroon-Khel** [comment]
The machine is having troubling picking up the new $PATH variable despite me disconnecting and reconnecting it multiple times

**Comment by Haroon-Khel** [comment]
![image](https://user-images.githubusercontent.com/34969545/206702522-bc7be1b4-def7-4481-8cc8-18b64bffb709.png)

**Comment by Haroon-Khel** [comment]
Its picked up the new PATH variable 
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-temurin/214/console

Adding the git location may have helped
![image](https://user-images.githubusercontent.com/34969545/206703747-26303d12-82ab-491a-a72f-985c343b6fd5.png)

**Comment by sxa** [comment]
Still did not work without having `/usr/local/bin` added to the start of the path before starting the jenkins agent (Jenkins agent on this system is not running over ssh. I've added the path setting along with `LD_PRELOAD_64` to the invocation of the jenkins agent on the machine which is running under Zulu 11 as per https://github.com/adoptium/infrastructure/issues/2763#issuecomment-1344207247. The build jobs appear to be working ok under this environment, although the agent that was running previously under java 8 appears to have shut itself down at some point. Reason unclear - we'll see if it stays up with Zulu 11 this time..

**Comment by Haroon-Khel** [comment]
The connection still drops.

https://issues.jenkins.io/browse/JENKINS-43979?focusedCommentId=298057&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-298057 suggests a solution

```
Hi, could you try https://github.com/jenkinsci/trilead-ssh2/pull/20 please.

You git clone https://github.com/mc1arke/trilead-ssh2.git

then git checkout jenkins-43979-sha512-issues

you then mvn install -Dmaven.test.skip=true

you then git clone https://github.com/jenkinsci/jenkins

then you edit file core/pom.xml

find this

https://github.com/jenkinsci/jenkins/blob/c33e7dc42094568a7d37aaa59f2bf5ab8332dc9a/core/pom.xml#L118 line

change it from build217-jenkins-9 to build217-jenkins-10-SNAPSHOT

then 

mvn install -Dmaven.test.skip=true

then you will find the war under war/target/ (will be jenkins.war in there) copy that to where ever jenkins runs the war on your os. On debian it's /usr/share/jenkins/
```
Though that is a bug for ubuntu 12, I was redirected there from the same bug on solaris 10. 

This would have to be tried out on the jenkins server.

That same thread suggests updating the openssh solaris box, https://issues.jenkins.io/browse/JENKINS-43979?focusedCommentId=298141&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-298141

but its the same version as https://ci.adoptopenjdk.net/computer/build-packet_esxi-solaris10u11-x64-1 which is a machine to which jenkins can connect to

(from the problem solaris box)
```
bash-4.3# which ssh
/opt/csw/bin/ssh
bash-4.3# ssh -V
OpenSSH_6.6p1, OpenSSL 1.0.2u  20 Dec 2019
```

**Comment by Haroon-Khel** [comment]
With the jenkins key, the jenkins server can ssh into the solaris box with no problem

**Comment by Haroon-Khel** [comment]
Found this in the jenkins log about the drop in connection, from the solaris box to jenkins

```
2022-12-14 11:31:50.605+0000 [id=5242642]       INFO    hudson.slaves.ChannelPinger$1#onDead: Ping failed. Terminating the channel JNLP4-connect connection from 145.40.115.43/145.40.115.43:47713.
java.util.concurrent.TimeoutException: Ping started at 1671017270603 hasn't completed by 1671017510604
        at hudson.remoting.PingThread.ping(PingThread.java:132)
        at hudson.remoting.PingThread.run(PingThread.java:88)
2022-12-14 11:31:50.611+0000 [id=5254107]       SEVERE  h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (Workspace clean-up thread/5254107) died unexpectedly due 
to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.nio.channels.ClosedChannelException
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 145.40.115.43/145.40.115.43:47713
```

**Comment by sxa** [comment]
As @Haroon-Khel found, `/usr/csw/bin` needs to be earlier in the `PATH` than `/usr/bin` otherwise a version of perl is used that does have the SHA module installed.

```
16:09:54  getDependentLibs:
16:09:54       [exec] Can't locate Digest/SHA.pm in @INC (@INC contains: /usr/perl5/5.8.4/lib/i86pc-solaris-64int /usr/perl5/5.8.4/lib /usr/perl5/site_perl/5.8.4/i86pc-solaris-64int /usr/perl5/site_perl/5.8.4 /usr/perl5/site_perl /usr/perl5/vendor_perl/5.8.4/i86pc-solaris-64int /usr/perl5/vendor_perl/5.8.4 /usr/perl5/vendor_perl .) at /export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-temurin_SmokeTests/aqa-tests/TKG/../TKG/scripts/getDependencies.pl line 19.
16:09:54       [exec] BEGIN failed--compilation aborted at /export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-temurin_SmokeTests/aqa-tests/TKG/../TKG/scripts/getDependencies.pl line 19.
16:09:54  
16:09:54  BUILD FAILED
```

The current system appears to be working well for build and test jobs with the following configuration:

Options | Value
---|---
Host key verification strategy | One-off with manually added key from `/etc/opt/csw/ssh/ssh_host_rsa_key.pub`
JavaPath | /usr/lib/jvm/zulu11.60.19-ca-jdk11.0.17-solaris/bin/java
Prefix Start Agent Command | export PATH=/usr/local/bin:$PATH && export LD_PRELOAD_64=/usr/lib/jvm/fallocate-preload.so &&
Env.Var: `GIT` | `/usr/local/bin/git`
Env.Var: `GIT_SSH` | `/opt/csw/bin/ssh`
Env.Var: `PATH` | `/opt/csw/bin:/usr/local/bin:/usr/bin:/bin`
Tool locations: `(Git)` | `/usr/local/bin/git

Some of these may not be required, but at least that's a record of a set up that appears to be working. Note there was a rogue java 11 process (likely a defunct agent) running that was chewing up CPU earlier and likely affecting the machine. [Build](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-temurin/240/console) and [smoke tests](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-temurin_SmokeTests/127/console) are working with the above configuration.

On the basis of this I'm going to close this issue, although perhaps some more investigation would be good to see if we can reduce the number of special options from the table above.
