### ISSUE TITLE
No available aarch64_alpine-linux test machines

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2858]
Most nightly/weekly pipelines failing consistently with
`Could not find any nodes with 'ci.role.test&&hw.arch.aarch64&&sw.os.alpine-linux' label` (and therefore abort and not run).

<img width="373" alt="Screen Shot 2022-12-19 at 8 20 01 AM" src="https://user-images.githubusercontent.com/2836948/208440252-6b9075ad-d94a-48f9-8ac4-829d01889249.png">
<img width="853" alt="Screen Shot 2022-12-19 at 8 21 36 AM" src="https://user-images.githubusercontent.com/2836948/208440270-4b0440c4-c446-43b4-af12-6f04e727b10c.png">

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? all tests
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.functional_aarch64_alpine-linux/85
- **Hyperlink** to re-run in Grinder:  [rerun link](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=nightly&TARGET=extended.functional&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_alpine-linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk17u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=dev&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=true&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&OPENJDK_SHA=&NUM_MACHINES=&TRSS_URL=&BUILD_LIST=functional&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)
- Is there an existing issue elsewhere covering this? no, but #2652 perhaps related
- Which machine(s) does it work on? n/a
- Which machine(s) does it fail on?  n/a

Any other details:
Some machines seem to be online today for a manual run:
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.functional_aarch64_alpine-linux/76/ so perhaps this is now already resolved.

**Comment by steelhead31** [comment]
Currently there are 5 machines available, out of 10 listed in jenkins ( I suspect some of these are old ones, that have been replaced and need removing from jenkins. )

I've added a nagios host check to check for these labels..
ci.role.test&&hw.arch.aarch64&&sw.os.alpine-linux

**Comment by sxa** [comment]
Closing.
