### ISSUE TITLE
Sparcv9_solaris builds broken 

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2859]
Sparcv9_solaris builds appear to be broken since Dec 7th with the following errors:

When it fails quickly:
```
07:21:09  Execution error: hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected termination of the channel
[Pipeline] echo
07:21:09  hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected termination of the channel
07:21:09  	at hudson.remoting.Request.abort(Request.java:345)
07:21:09  	at hudson.remoting.Channel.terminate(Channel.java:1080)
07:21:09  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:90)
07:21:09  	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to build-siteox-solaris10u11-sparcv9-1
```

When it builds for hours, then fails differently:
```
19:39:55  Execution error: org.eclipse.jgit.errors.InvalidObjectIdException: Invalid id: b8f651cfbf403edfdf136c1587b4d9bf1d681084
19:39:55  Process leaked file descriptors. See https://www.jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
[Pipeline] echo
19:39:55  org.eclipse.jgit.errors.InvalidObjectIdException: Invalid id: b8f651cfbf403edfdf136c1587b4d9bf1d681084
19:39:55  Process leaked file descriptors. See https://www.jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
19:39:55  	at org.eclipse.jgit.lib.ObjectId.fromString(ObjectId.java:203)
```

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure: Any recent build https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-temurin/
- **Hyperlink** to re-run in Grinder: 
- Is there an existing issue elsewhere covering this? No
- Which machine(s) does it work on? there is only one build machine
- Which machine(s) does it fail on? [build-siteox-solaris10u11-sparcv9-1](https://ci.adoptopenjdk.net/computer/build-siteox-solaris10u11-sparcv9-1/)

Any other details:
<img width="617" alt="Screen Shot 2022-12-19 at 9 50 22 AM" src="https://user-images.githubusercontent.com/2836948/208453257-4506e1c0-5f2c-4385-b8ba-57bac8fcee5d.png">

**Comment by sxa** [comment]
That timing may be coincident with trying to use a Zulu 11 JDK for the jenkins agent. Although [the most recent build](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-temurin/223/) appears to have been ok

**Comment by sxa** [comment]
I've kicked off another at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-temurin/224 (I've also switched the test system over to Zulu11 to see if that shows any problems after the switch)

@steelhead31 if you're able to keep an eye on this for me since I'm not 100% today that would be appreciated.

**Comment by steelhead31** [comment]
A quick SAR shows the system is at 99% usage..  
bash-3.2# sar 1 10

SunOS build-siteox-solaris10u11-sparcv9-1 5.10 Generic\_147147-26 sun4v    12/21/2022

00:18:28    %usr    %sys    %wio   %idle  
00:18:31       3      97       0       0  
00:18:34       2      98       0       0  
00:18:36       1      99       0       0  
00:18:39       2      98       0       0

**Comment by sxa** [comment]
Of the list at https://ci.adoptopenjdk.net/label/solaris||sw.os.sunos/ all active ones are using Liberica 11, although https://ci.adoptopenjdk.net/computer/test%2Dequinix%5Fesxi%2Dsolaris10%2Dx64%2D1%2DNEW has it in `/usr/lib/jvm/jdk-11.0.17` instead of `/usr/lib/jvm/bell-jdk-11.0.17` like the others - I have now corrected that for clarity and consistency so this can "now mission" for this issue can now be considered complete.
