### ISSUE TITLE
Nagios : Amend Nagios/Ansible Config Role To Create Host Groups Config File

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2864]
Part of epic : [#2445](https://github.com/adoptium/infrastructure/issues/2445) ( Task 6.2 )

Update the Nagios\_Config playbook to create the hostgroups.cfg file

The script should parse the ansible inventory ( similar to issue #2629 )

And create a config file which contains a hostgroup entry for each of the providers in the inventory, ie the second stanza for the build, test & dockerhost level 1 stanzas.  
  
define hostgroup{  
       hostgroup\_name  Ibmcloud  
       alias           Ibmcloud  
       members         ,test-ibmcloud-rhel7-x64-1,test-ibmcloud-rhel6-x64-1,test-ibmcloud-ubuntu1604-x64-1,build-ibmcloud-win2012r2-x64-1,build-ibmcloud-win2012r2-x64-2,test-ibmcloud-win2012r2-x64-1,test-ibmcloud-win2012r2-x64-2  
       }

The playbook should then add the relevant machines to the members list as shown in the example above.

**Comment by lumuchris256** [comment]
this is a task next in line,  could you assign me ?
