### ISSUE TITLE
Nagios : Amend Nagios/Ansible Config Role To Create Service Groups Config File

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2865]
Part of epic : [#2445](https://github.com/adoptium/infrastructure/issues/2445) ( Task 6.3 )

Update the Nagios\_Config playbook to create the servicegroups.cfg file

The script should parse the ansible inventory ( similar to issue [#2629](https://github.com/adoptium/infrastructure/issues/2629) )

And create a config file which contains a service group entry for each of the group types in the inventory, ie the first stanza for each of the build, test & dockerhost level 1 stanzas.

The format of the servicegroups.cfg file should be as below.. ( please keep the default servicegroup Web\_Sites as it is required for Nagios )

define servicegroup{  
       servicegroup\_name       Web\_Sites  
       alias                   Web Sites  
       }

define servicegroup{  
       servicegroup\_name       Docker\_Hosts  
       alias                   Docker Hosts  
       }

**Comment by lumuchris256** [comment]
this is a task next in line ,could you assign me ?
