### ISSUE TITLE
Vagrant agents do not auto-start

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2878]
- Please put the system name in the title of this issue.

- Link to any log file showing the problem:

- Please describe the issue:
Spotted during last jenkins restart. At the moment the [five jenkins agents](https://ci.adoptopenjdk.net/label/vagrant/) for running the [VPC jobs](https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/) are started via the `startjenkins.sh` script via nohup but are not configured to automatically restart. These should be switched over to [using services](https://github.com/adoptium/infrastructure/issues/2585) to ensure that they are all restarted when required.

I've restarted them manually for now.

**Comment by sxa** [comment]
Deferred to March pending resolution of instability in VPC job.

**Comment by sxa** [comment]
Tried with vagrant1 and vagrant2 using `jenkins1` and `jenkins2` services but neither are starting up properly at present.

**Comment by sxa** [comment]
@steelhead31 Have the jenkins agents on the [replacement vagrant machine](https://github.com/adoptium/infrastructure/issues/3729) been set up to restart automatically?

**Comment by steelhead31** [comment]
No, Its top of my to do list for today :)

**Comment by steelhead31** [comment]
Services created for vagrant1 -> vagrant4 inclusive, set to run on restart.
