### ISSUE TITLE
jdk_net and jdk_tools FAILED on test-docker-ubi8-x64-2 and test-docker-fedora35-x64-1

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2882]
2 test cases in jdk_net target fail on a couple of static docker nodes with `Cannot run program "hostname"` and
Several test cases in jdk_tools target fail with  `diff: command not found`

Console output:
```
[2023-01-14T00:13:03.085Z] Command line: [hostname]
[2023-01-14T00:13:03.085Z] executeProcess() failed: java.io.IOException: Cannot run program "hostname": error=2, No such file or directory
[2023-01-14T00:13:03.085Z] --- ProcessLog ---
[2023-01-14T00:13:03.085Z] cmd: hostname
[2023-01-14T00:13:03.085Z] exitvalue: null
[2023-01-14T00:13:03.085Z] stderr: null
[2023-01-14T00:13:03.085Z] stdout: null
[2023-01-14T00:13:03.085Z] 
[2023-01-14T00:13:03.085Z] Client side failed: Get hostname failed.
[2023-01-14T00:13:03.085Z] STDERR:
[2023-01-14T00:13:03.085Z] java.lang.RuntimeException: Get hostname failed.

...

20:06:31  STDERR:
20:06:31  /home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_x86-64_linux_testList_1/aqa-tests/openjdk/openjdk-jdk/jdk/test/sun/tools/jrunscript/jrunscript-fTest.sh: line 48: diff: command not found
```

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? BUILD_LIST=openjdk, TARGET=jdk_net
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_linux_testList_1/78
- **Hyperlink** to re-run in Grinder: [Rerun in Grinder](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_net_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_hs_extended.openjdk_x86-64_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.6-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk8u&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk8u%2Fjdk8u-release-linux-x64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk8u362-b06_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=112&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=3&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

- Is there an existing issue elsewhere covering this? No
- Which machine(s) does it work on? test-equinix_esxi-ubuntu2204-x64-2, test-docker-ubuntu2204-x64-2 and test-ibmcloud-rhel7-x64-1
- Which machine(s) does it fail on? test-docker-ubi8-x64-2 and test-docker-fedora35-x64-1 and 
test-docker-ubi8-armv8-1 
test-marist-rhel7-s390x-2 - no route to host (in https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.system_s390x_linux/247/)

---

**Test Info**
Test Name: jdk_net_1
Test Duration: 16 min 1 sec
Machine: test-docker-ubi8-x64-2
TRSS link for the test output: https://trss.adoptium.net/output/test?id=63c21271ed0b30773ba34529

**Build Info**
Build Name: Test_openjdk8_hs_extended.openjdk_x86-64_linux_testList_1
Jenkins Build start time: Jan 13 2023, 06:19 pm
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_linux_testList_1/78/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=63c21190ed0b30773ba3410b

**Java Version**
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b06, mixed mode)

**This test has been failed 2 times since Jan 11 2023, 12:15 pm**
**Java Version when the issue first seen**
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b06, mixed mode)
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_linux_testList_1/76/

The test failed on machine test-docker-ubi8-x64-2 1 times 
The test failed on machine test-docker-fedora35-x64-1 1 times 

---

<img width="790" alt="Screen Shot 2023-01-13 at 9 53 35 PM" src="https://user-images.githubusercontent.com/2836948/212447806-318eccf4-2ac6-483e-b989-150de49fdb78.png">

**Comment by smlambert** [comment]
Are test-docker-ubi8-x64-2 and test-docker-fedora35-x64-1 new machines?  Seems the process to bring machines online was not followed for these 2.

**Comment by smlambert** [comment]
Also seen on test-docker-sles15-s390x-1 in https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_1/73/

**Comment by smlambert** [comment]
jdk_management target also fails on test-docker-ubi8-x64-2 with  

```
[2023-01-15T21:38:32.190Z] TEST FAILED: TestSystemLoadAvg test failed 5 runs
[2023-01-15T21:38:32.190Z] STDERR:
[2023-01-15T21:38:32.190Z] Exception in thread "main" java.io.IOException: Cannot run program "/usr/bin/uptime": error=2, No such file or directory
[2023-01-15T21:38:32.190Z] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
[2023-01-15T21:38:32.190Z] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
[2023-01-15T21:38:32.190Z] 	at GetSystemLoadAverage.checkLoadAvg(GetSystemLoadAverage.java:90)
[2023-01-15T21:38:32.190Z] 	at GetSystemLoadAverage.main(GetSystemLoadAverage.java:64)
```

**Comment by smlambert** [comment]
I have disabled https://ci.adoptopenjdk.net/computer/test-docker-ubi8-x64-2/ since sanity.openjdk and extended.openjdk will fail on it (jdk_net, jdk_tools, jdk_management).

**Comment by sxa** [comment]
Is this an attempt to duplicate the pinned issue https://github.com/temurin-compliance/temurin-compliance/issues/226 ?

**Comment by Haroon-Khel** [comment]
Got the failures down to the following two

java/security/cert/CertPathBuilder/targetConstraints/BuildEEBasicConstraints.java.BuildEEBasicConstraint
java/security/cert/pkix/policyChanges/TestPolicy.java.TestPolicy

I'll keep the two machines offline for now to keep triage work easier

**Comment by Haroon-Khel** [comment]
The two failing java/security tests now pass on all 6 machines

* java/security/cert/CertPathBuilder/targetConstraints/BuildEEBasicConstraints.java
    * test-docker-fedora35-x64-1 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6696/console
    * test-docker-fedora35-x64-2 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6697/console 
    * test-docker-fedora37-x64-1 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6698/console 
    * test-docker-fedora37-x64-2 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6699/console 
    * test-docker-ubi8-x64-1 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6700/console 
    * test-docker-ubi8-x64-2 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6701/console 
* java/security/cert/pkix/policyChanges/TestPolicy.java
    * test-docker-fedora35-x64-1 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6702/console 
    * test-docker-fedora35-x64-2 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6703/console 
    * test-docker-fedora37-x64-1 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6705/console 
    * test-docker-fedora37-x64-2 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6704/console 
    * test-docker-ubi8-x64-1 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6706/console 
    * test-docker-ubi8-x64-2 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6707/console

**Comment by Haroon-Khel** [comment]
Issue is resolved
