### ISSUE TITLE
ipv6 tests in jdk_net FAILED on test-docker-ubuntu2204-ppc64le-1 and test-docker-debian11-ppc64le-1

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2883]
java/net/Inet6Address/B6206527.java and java/net/ipv6tests/B6521014.java fail on test-docker-ubuntu2204-ppc64le-1 and test-docker-debian11-ppc64le-1 with `No such device (Bind failed)` and `java.net.ConnectException: Network is unreachable (connect failed)`

Console output:
```
10:28:14          B6206527
10:28:14  STDOUT:
10:28:14  trying LL addr: /fe80:0:0:0:42:acff:fe11:2%eth0
10:28:14  trying LL addr: /fe80:0:0:0:42:acff:fe11:2
10:28:14  STDERR:
10:28:14  java.net.SocketException: No such device (Bind failed)
10:28:14  	at java.net.PlainSocketImpl.socketBind(Native Method)
10:28:14  	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
10:28:14  	at java.net.ServerSocket.bind(ServerSocket.java:390)
10:28:14  	at java.net.ServerSocket.bind(ServerSocket.java:344)
10:28:14  	at B6206527.main(B6206527.java:57)
10:28:14  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:28:14  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:28:14  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:28:14  	at java.lang.reflect.Method.invoke(Method.java:498)
10:28:14  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
10:28:14  	at java.lang.Thread.run(Thread.java:750)
```
and
```
10:28:14          B6521014
10:28:14  STDERR:
10:28:14  java.net.ConnectException: Network is unreachable (connect failed)
10:28:14  	at java.net.PlainSocketImpl.socketConnect(Native Method)
10:28:14  	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
10:28:14  	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
10:28:14  	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
10:28:14  	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
10:28:14  	at java.net.Socket.connect(Socket.java:607)
10:28:14  	at B6521014.test1(B6521014.java:77)
10:28:14  	at B6521014.main(B6521014.java:106)
10:28:14  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:28:14  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:28:14  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:28:14  	at java.lang.reflect.Method.invoke(Method.java:498)
10:28:14  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
10:28:14  	at java.lang.Thread.run(Thread.java:750)
```

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? BUILD_LIST=openjdk, TARGET=jdk_net
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/85/
- **Hyperlink** to re-run in Grinder: [Rerun in Grinder](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_net_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_hs_extended.openjdk_ppc64le_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.6-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk8u&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk8u%2Fjdk8u-release-linux-ppc64le-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk8u362-b06_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=107&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=4&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)
- Is there an existing issue elsewhere covering this? No
- Which machine(s) does it work on? test-osuosl-ubuntu1604-ppc64le-1, test-osuosl-ubuntu1604-ppc64le-2, test-osuosl-ubuntu1804-ppc64le-1
- Which machine(s) does it fail on? test-docker-ubuntu2204-ppc64le-1 and test-docker-debian11-ppc64le-1

---

**Test Info**
Test Name: jdk_net_1
Test Duration: 8 min 37 sec
Machine: test-docker-ubuntu2204-ppc64le-1
TRSS link for the test output: https://trss.adoptium.net/output/test?id=63c21fffed0b30773ba35f46

**Build Info**
Build Name: Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1
Jenkins Build start time: Jan 13 2023, 06:19 pm
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/86/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=63c21f23ed0b30773ba35d15

**Java Version**
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b06, mixed mode)

**This test has been failed 2 times since Jan 12 2023, 09:56 am**
**Java Version when the issue first seen**
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b06, mixed mode)
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/85/

The test failed on machine test-docker-ubuntu2204-ppc64le-1 1 times 
The test failed on machine test-docker-debian11-ppc64le-1 1 times

**Comment by Haroon-Khel** [comment]
Rerunning on the problem machines, and other that I suspect will have the same error
https://ci.adoptopenjdk.net/job/Grinder/6338/console test-docker-debian11-ppc64le-3
https://ci.adoptopenjdk.net/job/Grinder/6339/console test-docker-debian11-ppc64le-1
https://ci.adoptopenjdk.net/job/Grinder/6340/console test-docker-debian11-ppc64le-1
https://ci.adoptopenjdk.net/job/Grinder/6341/console test-docker-ubuntu2204-ppc64le-1
 https://ci.adoptopenjdk.net/job/Grinder/6342/console test-docker-ubuntu2204-ppc64le-2

**Comment by Haroon-Khel** [comment]
Rerunning the two failing ipv6 tests

* java/net/Inet6Address/B6206527.java
    * test-docker-ubuntu2204-ppc64le-1 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6711/console
    * test-docker-ubuntu2204-ppc64le-2 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6712/console 
    * test-docker-debian11-ppc64le-1 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6713/console 
    * test-docker-debian11-ppc64le-2 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6714/console 
    * test-docker-debian11-ppc64le-3 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6715/console 
* java/net/ipv6tests/B6521014.java
    * test-docker-ubuntu2204-ppc64le-1 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6716/console 
    * test-docker-ubuntu2204-ppc64le-2 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6717/console 
    * test-docker-debian11-ppc64le-1 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6718/console 
    * test-docker-debian11-ppc64le-2 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6719/console 
    * test-docker-debian11-ppc64le-3 https://ci.adoptium.net/view/Test_grinder/job/Grinder/6720/console

**Comment by Haroon-Khel** [comment]
Both tests continue to fail on test-docker-ubuntu2204-ppc64le-1. Strange since the tests pass on -2 which is hosted on the same dockerhost machine. 

I've set up a temporary -3, on which both tests failed
https://ci.adoptium.net/view/Test_grinder/job/Grinder/6724/console
https://ci.adoptium.net/view/Test_grinder/job/Grinder/6723/console

I will take -1 offline and replace it with another linux container. 

Investigation into the difference in ipv6 networking setup between the working and non working containers can continue in another infra issue. This one can be closed
