### ISSUE TITLE
jcmd test cases in jdk_tools FAILED on test-docker-ubuntu2204-ppc64le-1 and test-docker-debian11-ppc64le-1

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2884]
Appears to be an extra character on the end of the jcmd options when running some jcmd tests from jdk_tools target on test-docker-ubuntu2204-ppc64le-1 and test-docker-debian11-ppc64le-1.

sun/tools/jcmd/TestJcmdDefaults.java
```
[/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image/bin/jcmd -J-XX:+UsePerfData -h]
Usage: jcmd <pid | main class> <command ...|PerfCounter.print|-f file>
   or: jcmd -l                                                    
   or: jcmd -h          
```
and 

sun/tools/jcmd/TestJcmdSanity.java
```
[/home/jenkins/workspace/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/openjdkbinary/j2sdk-image/bin/jcmd -J-XX:+UsePerfData 294202 help]
294202:
The following commands are available:
VM.unlock_commercial_features
JFR.configure
JFR.stop
JFR.start
JFR.dump
JFR.check
...
```

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/86
- **Hyperlink** to re-run in Grinder: [Rerun in Grinder](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_tools_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk8_hs_extended.openjdk_ppc64le_linux&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64le_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.6-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk8u&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk8u%2Fjdk8u-release-linux-ppc64le-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk8u362-b06_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=107&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=4&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)
- Is there an existing issue elsewhere covering this? No
- Which machine(s) does it work on? test-osuosl-ubuntu1604-ppc64le-1, test-osuosl-ubuntu1604-ppc64le-2, test-osuosl-ubuntu1804-ppc64le-2
- Which machine(s) does it fail on? test-docker-ubuntu2204-ppc64le-1 and test-docker-debian11-ppc64le-1
---

**Test Info**
Test Name: jdk_tools_0
Test Duration: 16 min 43 sec
Machine: test-docker-ubuntu2204-ppc64le-1
TRSS link for the test output: https://trss.adoptium.net/output/test?id=63c21fffed0b30773ba35f54

**Build Info**
Build Name: Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1
Jenkins Build start time: Jan 13 2023, 06:19 pm
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/86/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=63c21f23ed0b30773ba35d15

**Java Version**
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b06, mixed mode)

**This test has been failed 2 times since Jan 12 2023, 09:56 am**
**Java Version when the issue first seen**
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b06, mixed mode)
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_1/85/

The test failed on machine test-docker-ubuntu2204-ppc64le-1 1 times 
The test failed on machine test-docker-debian11-ppc64le-1 1 times

**Comment by Haroon-Khel** [comment]
Multiple failures on all but debian11-3. A bit confusing as they were set up at the same time and are all on the same dockerhost machine

```
com/sun/tools/attach/BasicTests.java.BasicTests
com/sun/tools/attach/TempDirTest.java.TempDirTest
sun/jvmstat/monitor/MonitoredVm/CR6672135.java.CR6672135
sun/jvmstat/monitor/MonitoredVm/MonitorVmStartTerminate.java.MonitorVmStartTerminate
sun/tools/jcmd/TestJcmdDefaults.java.TestJcmdDefaults
sun/tools/jcmd/TestJcmdSanity.java.TestJcmdSanity
sun/tools/jps/TestJpsClass.java.TestJpsClass
sun/tools/jps/TestJpsJar.java.TestJpsJar
```
I'll keep the problem machines offline. Theres plenty of other ppc64le linux test machines

**Comment by Haroon-Khel** [comment]
Created a new debian ppc64le node on the same dockerhost of the problem machines (with the same docker image of that of the problem machines), https://ci.adoptium.net/computer/test-docker-debian11-ppc64le-4/
The jdk_tools suite passes fine on this new node

**Comment by Haroon-Khel** [comment]
I am closing this as I have replaced the problem container with a working one. The failing container is offline in jenkins
