### ISSUE TITLE
Xvfb failed to start on test-docker-fedora35-armv8l-1

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2887]
Please set the title to indicate the test name and machine name where known.
Xvfb failed to start on 
[test-docker-fedora35-armv8l-1](https://ci.adoptopenjdk.net/computer/test-docker-fedora35-armv8l-1)

```
04:58:44  $ Xvfb -displayfd 2 -screen 0 1024x768x24 -fbdir /home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_aarch64_linux/.xvfb-94-..fbdir5706743967630555806
04:58:55  Xvfb starting_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
04:58:55  _XSERVTransMakeAllCOTSServerListeners: server already running
04:58:55  _XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
04:58:55  1
04:58:55  
04:58:55  ERROR: Xvfb failed to start, consult the lines above for errors
```

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux/94/
- **Hyperlink** to re-run in Grinder: 
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on? have not seen this issue elsewhere
- Which machine(s) does it fail on? test-docker-fedora35-armv8l-1

**Comment by smlambert** [comment]
Marking machine offline to avoid hitting it during release runs.

**Comment by steelhead31** [comment]
This is a ( hopefully the final! ) fallout of the duplicate docker container/jenkins issues, I've amended this nodes configuration to reflect reality ( and ensure isolation ), and am currently running tests here.. https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux/100/console

**Comment by steelhead31** [comment]
This test run has been successful, so this node is returned to service, issues with Xvfb do not recur.
