### ISSUE TITLE
Subset of openjdk tests can not complete on certain machines within 10hrs

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2893]
Please set the title to indicate the test name and machine name where known.
<img width="900" alt="Screen Shot 2023-01-23 at 9 52 39 AM" src="https://user-images.githubusercontent.com/2836948/214070326-a810e317-5a48-48b3-9a5a-84587cce6401.png">

3/7 of the last runs of a subset of extended.openjdk tests timeout and are aborted when run on certain machines ([test-marist-sles12-s390x-2](https://ci.adoptopenjdk.net/computer/test-marist-sles12-s390x-2), [test-marist-rhel7-s390x-2](https://ci.adoptopenjdk.net/computer/test-marist-rhel7-s390x-2), [test-marist-sles15-s390x-2](https://ci.adoptopenjdk.net/computer/test-marist-sles15-s390x-2)) 

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure
  - https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_1/70/
  - https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_1/75/
  - https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_1/76/
  - https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_aarch64_linux/
- **Hyperlink** to re-run in Grinder: 
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on? [test-docker-sles15-s390x-1](https://ci.adoptopenjdk.net/computer/test-docker-sles15-s390x-1), [test-marist-ubuntu2204-s390x-1](https://ci.adoptopenjdk.net/computer/test-marist-ubuntu2204-s390x-1)
- Which machine(s) does it fail on? ([test-marist-sles12-s390x-2](https://ci.adoptopenjdk.net/computer/test-marist-sles12-s390x-2), [test-marist-rhel7-s390x-2](https://ci.adoptopenjdk.net/computer/test-marist-rhel7-s390x-2), [test-marist-sles15-s390x-2](https://ci.adoptopenjdk.net/computer/test-marist-sles15-s390x-2)), test-docker-debian11-armv8-1

**Comment by sxa** [comment]
@smlambert Are we getting test case failures on those systems (timeouts etc. on some tests) which would explain this as opposed to the machines being slow?

**Comment by smlambert** [comment]
See https://github.com/adoptium/aqa-tests/issues/4258#issuecomment-1398963195 for sparcv9 solaris example.

Also noting the performance degradation between run from September 10th to present day, what changed (new machine config? tests starting to fail, so hitting timeouts? needs investigation):

<img width="794" alt="Screen Shot 2023-01-23 at 8 58 11 PM" src="https://user-images.githubusercontent.com/2836948/214197931-2b029226-af76-4206-9aaa-9c77a3981a65.png">

**Comment by sxa** [comment]
I'd treat the solaris/sparcv9 systems separately from everything else since they're a bit less under our control as to how they might be virtualised at the provider and that is consistent with what we've seen elsewhere where those systems are used. We're a little limited in options there unfortunately.

**Comment by sxa** [comment]
The Marist machines were all replaced a few months ago as part of [a migration project](https://github.com/adoptium/infrastructure/issues/2673) and the two SLES ones were brought online after our older SLES ones were not being regularly used.

FYI @steelhead31 @Haroon-Khel

**Comment by smlambert** [comment]
On test-marist-sles12-s390x-2:
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_0/70/
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_0/77/

**Comment by sxa** [comment]
Probably related: #2923

**Comment by sxa** [comment]
Seen by Andrew this week too ([slack thread](https://adoptium.slack.com/archives/C09NW3L2J/p1678705276894389?thread_ts=1678699823.862989&cid=C09NW3L2J))

**Comment by Haroon-Khel** [comment]
Ref linux aarch64 containers, theyre spread over 2 dockerhost machines
```
dockerhost-equinix-ubuntu2004-armv8-1, max cpu clock speed 3000.0000 MHz, MemTotal: 525926796 kB (500G)
dockerhost-equinix-ubuntu2204-armv8-1, max cpu clock speed 2800.0000 MHz, MemTotal: 525918844 kB (500G)
```
So theres a slight difference in max clock speed (but not significant). 

In addition, if you look at https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml, we limit the cpu and memory of each of the containers; 2 cpus and 6g memory for most containers with the exception of some of the ubuntu ones which have a 4cpu limit

**Comment by Haroon-Khel** [comment]
Another platform for which the extended openjdk job aborts due to timeout is windows x64. These jobs appeared during the march release

https://ci.adoptium.net/job/Test_openjdk20_hs_extended.openjdk_x86-64_windows_testList_2/29/ on [test-azure-win2019-x64-1](https://ci.adoptium.net/computer/test-azure-win2019-x64-1)
https://ci.adoptium.net/job/Test_openjdk20_hs_extended.openjdk_x86-64_windows_testList_0/27/ on [test-azure-win2012r2-x64-3](https://ci.adoptium.net/computer/test-azure-win2012r2-x64-3)
https://ci.adoptium.net/job/Test_openjdk20_hs_extended.openjdk_x86-64_windows_testList_0/28/ again on [test-azure-win2012r2-x64-3](https://ci.adoptium.net/computer/test-azure-win2012r2-x64-3)

**Comment by Haroon-Khel** [comment]
Skimming through https://ci.adoptium.net/job/Test_openjdk20_hs_extended.openjdk_x86-64_windows_testList_0/28/consoleFull to see how long it takes for test suites to pass I notice that the jvm_compiler tests take the most time:

```
18:59:26  Running test jvm_compiler_0 ...
22:38:54  jvm_compiler_0_PASSED
```
3h38m

```
22:38:54  Running test jvm_compiler_1 ...
02:49:19  jvm_compiler_1_PASSED
```
under 4hrs

jvm_compiler_2 is skipped

It would be interesting to see the run time of these tests on other platforms

**Comment by Haroon-Khel** [comment]
On https://ci.adoptium.net/job/Test_openjdk20_hs_extended.openjdk_x86-64_windows_testList_2/29/consoleFull

```
06:19:29  Running test jdk_beans_1 ...
07:19:13  jdk_beans_1_PASSED
```
1hr
```
07:30:19  Running test jdk_net_0 ...
09:47:47  jdk_net_0_PASSED
```
over 2hrs
```
11:02:46  Running test jdk_security3_0 ...
15:12:19  jdk_security3_0_PASSED
```
over 4hrs

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_1/80/consoleFull on [test-marist-sles12-s390x-2](https://ci.adoptium.net/computer/test-marist-sles12-s390x-2/) is interesting. There isnt a test suite that hangs

**Comment by Haroon-Khel** [comment]
Sparcv9 extended openjdk

https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/72/consoleFull on [build-siteox-solaris10u11-sparcv9-1](https://ci.adoptium.net/computer/build-siteox-solaris10u11-sparcv9-1/)

```
01:40:16  Running test hotspot_jre_0 ...
05:47:15  hotspot_jre_0_FAILED
```
4hrs

```
05:47:15  Running test jdk_other_0 ...
08:06:12  jdk_other_0_PASSED
```
over 2hrs

```
09:43:39  Running test jdk_security4_0 ...
11:06:14  Cancelling nested steps due to timeout
```
over 1hr

https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/71/consoleFull on [test-siteox-solaris10u11-sparcv9-1](https://ci.adoptium.net/computer/test-siteox-solaris10u11-sparcv9-1/)

```
01:16:05  Running test hotspot_jre_0 ...
05:18:45  hotspot_jre_0_FAILED
```
4hrs again

```
05:18:46  Running test jdk_other_0 ...
07:55:45  jdk_other_0_PASSED
```
over 2hrs again

jdk_security4_0, jdk_nio_0 took 1hr

https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/68/consoleFull on [test-siteox-solaris10u11-sparcv9-1](https://ci.adoptium.net/computer/test-siteox-solaris10u11-sparcv9-1/)

```
05:03:35  Running test hotspot_jre_0 ..
08:58:16  hotspot_jre_0_FAILED
```
close to 4hrs

```
08:58:16  Running test jdk_other_0 ...
11:15:58  jdk_other_0_PASSED
```
over 2hrs

jdk_security4_0, jdk_nio_0 about 1hr

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/job/Grinder/6986/console was a grinder from the march release. I increased the timeout from its default 10 to 20. 13:22:06 to 00:35:47, so around 11hrs. I assume the 10 refers to 10 hours. I propose that until we can figure out why tests are hanging, the default timeout should be set to 15 (if 15 does in fact means 15hrs)

@smlambert What do you think?

**Comment by smlambert** [comment]
It is measured in hours and we can certainly adjust the TIME_LIMIT (across the board or for specific platforms).

**Comment by Haroon-Khel** [comment]
I would prefer across the board. Aside from changing the job config of every extended openjdk, is there a quicker way to adjust the default TIME_LIMIT parameter?

If I change it [here](https://github.com/adoptium/aqa-tests/blob/f49810a3cd3616a62cbde9a78525622dc1d2353d/buildenv/jenkins/aqaTestPipeline.groovy#L11), [here](https://github.com/adoptium/aqa-tests/blob/548fd4a3da6fbeb5c847d69eec4aed47d275a159/buildenv/jenkins/JenkinsfileBase#L853) and [here](https://github.com/adoptium/aqa-tests/blob/5e33f1c01f9610d6bb6b369ee07bfb8ab8f0b0ff/buildenv/jenkins/testJobTemplate#L34), do you know if it update it for the existing jenkins jobs?

**Comment by smlambert** [comment]
Changing it in those places only matters if the setting in the jobs is left blank, which we typically never do.  So, I suggest we regenerate the extended.openjdk test jobs with the desired value across all platforms and versions.

regen JDK8 extended.openjdk - [Test_Job_Auto_Gen/986](https://ci.adoptium.net/view/Test_grinder/job/Test_Job_Auto_Gen/986/)
regen JDK11,17 extended.openjdk - [Test_Job_Auto_Gen/987](https://ci.adoptium.net/view/Test_grinder/job/Test_Job_Auto_Gen/987/)
regen JDK20 extended.openjdk - [Test_Job_Auto_Gen/988](https://ci.adoptium.net/view/Test_grinder/job/Test_Job_Auto_Gen/988/)

**Comment by sxa** [comment]
I'm going to copy the comment from https://github.com/adoptium/infrastructure/issues/2923#issuecomment-1460405723 into here as another data point, and close the other issue as a duplicate:

ubuntu2110 took 9h30
ubuntu2204 took 6h30
Both passed all13,931 tests
Both were started at pretty much the same time (to within a minute) but one of them just seemed to get though everything a bit more slowly:
[times.2583.gz](https://github.com/adoptium/infrastructure/files/10922472/times.2583.gz)
[times.6583.gz](https://github.com/adoptium/infrastructure/files/10922473/times.6583.gz)

**Comment by adamfarley** [comment]
JDK8 extended.openjdk testing on Solaris SparcV9 appears to be timing out regularly, especially the target jdk_security3_0.

At one point it was suggested that AsyncSSLSocketClose.java may be responsible, but I ran it on its own [here](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_0/85/console) and it seems to run and pass without a problem.

So to identify the slow runner/s in security3, I've run another job [here]() with an extended timeout. If it hasn't finished by this time tomorrow, I'll explore other options. Regular javacore generation could be useful (once every few minutes kinda), or perhaps something that announces each time a unit test starts and finishes, complete with test name and timestamp.

**Comment by adamfarley** [comment]
I reran with a new exclusion file [here](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris/91/console), and the two testList subjobs ran for 10 hours (ish) each.

@Haroon-Khel - I propose we merge this PR and increase the SparcV9 time limit to prevent the "ish" from pushing us a hair over the default 10 hours. What do you think?

**Comment by adamfarley** [comment]
Thia changeset as a PR, I meant to say. The changeset excludes a bunch of the longer running tests, which I tested in the links above. I've created the PR now. [Here's a link.](https://github.com/adoptium/aqa-tests/pull/4631/files)

**Comment by adamfarley** [comment]
Without that PR, we'll need to increase the timeout to more than 15 hours (per each of the two testlists), or we'll need to run these tests in more than 2 testlists, which would require:
- Making a testlist job able to wait for over 10 hours for a machine to free up.
- Making sure we can run with concurrency able to be set to more than the number of machines.
- Coming to terms with the idea that individual unit tests can run for over 2 hours.

Seemed a simpler idea to just exclude the biggest offenders for the overrun, and lengthening the timeout.

**Comment by smlambert** [comment]
Noting that queue time is not part of the overall TIME_LIMIT value, so you would not hit the 10 hr default time limit if you waited for 10 hrs for a machine to become free.  The time limit starts the countdown at the setup stage.
