### ISSUE TITLE
IPv6 not available on some arm_linux and alpine-linux machines

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2894]
Please set the title to indicate the test name and machine name where known.
As seen in https://github.com/adoptium/aqa-tests/issues/4257#issuecomment-1396445666, 
```
Execution failed: `main' threw exception: java.lang.UnsupportedOperationException: IPv6 not available
``` 

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure
  - https://ci.adoptopenjdk.net/job/Test_openjdk19_hs_extended.openjdk_arm_linux_testList_2/33/(rerun in [Grinder/6424](https://ci.adoptopenjdk.net/job/Grinder/6424))
  - https://ci.adoptopenjdk.net/job/Test_openjdk19_hs_extended.openjdk_x86-64_alpine-linux_testList_2/34/ 
- **Hyperlink** to re-run in Grinder: [rerun link](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST=jdk_net_2&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk19_hs_extended.openjdk_arm_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=arm_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v0.9.6-release&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=19&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk19u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk19u%2Fjdk19u-release-linux-arm-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-19.0.2%2B7_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=39&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=2&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on? test-docker-ubuntu2204-armv8-2 
- Which machine(s) does it fail on? [test-docker-ubuntu2004-armv7l-1](https://ci.adoptopenjdk.net/computer/test-docker-ubuntu2004-armv7l-1), [test-docker-alpine314-x64-1](https://ci.adoptopenjdk.net/computer/test-docker-alpine314-x64-1)

Any other details:

**Comment by Haroon-Khel** [comment]
On dockerhost-equinix-ubuntu2004-armv8-1, the host of test-docker-ubuntu2004-armv7l-1, I added `{ "ipv6": true, "fixed-cidr-v6": "fd00::/80" }` to /etc/docker/daemon.json and restarted docker. 

The failing tests (jdk_net_2) pass https://ci.adoptium.net/view/Test_grinder/job/Grinder/6755/console

Going to do the same for [test-docker-alpine314-x64-1](https://ci.adoptopenjdk.net/computer/test-docker-alpine314-x64-1)

**Comment by Haroon-Khel** [comment]
jdk_net passes on [test-docker-alpine314-x64-1](https://ci.adoptopenjdk.net/computer/test-docker-alpine314-x64-1) https://ci.adoptium.net/view/Test_grinder/job/Grinder/6758/console. Will check other nodes before closing

**Comment by sxa** [comment]
Let's not close this just yet and lose this setup info. A couple of questions:
- Is there anything preventing this from be added into the dockerhost playbook? If not, let's make sure we do that
- Was it affecting all containers on each host or just a subset, and if a subset do we know what was special about the ones it worked on? (Were different distributions all behaving the same for example?)
- Is the fix required on all dockerhosts?

**Comment by Haroon-Khel** [comment]
It is already in the playbooks https://github.com/adoptium/infrastructure/blob/052bdf48d697b290ff7cd333abee7ba029a2c901/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml#L6
But I do not know why the fix wasnt present on the dockerhost

**Comment by Haroon-Khel** [comment]
Some ipv6 tests still fail on the following machines despite the above fix

https://ci.adoptium.net/job/Grinder/6831/ [test-docker-ubuntu2204-x64-2](https://ci.adoptium.net/computer/test-docker-ubuntu2204-x64-2)

 com/sun/net/httpserver/simpleserver/CommandLinePositiveTest.java.CommandLinePositiveTest
 com/sun/net/httpserver/simpleserver/jwebserver/CommandLinePositiveTest.java.CommandLinePositiveTest
java/net/InetAddress/HostsFileOrderingTest.java.HostsFileOrderingTest
 java/net/InetAddress/InternalNameServiceTest.java.InternalNameServiceTest
 java/net/InetAddress/InternalNameServiceWithHostsFileTest.java.InternalNameServiceWithHostsFileTest
 jdk/net/ExtendedSocketOption/DontFragmentTest.java.DontFragmentTest

In the below  java/net/httpclient/ManyRequestsLegacy.java.ManyRequestsLegacy fails

https://ci.adoptium.net/job/Grinder/6840/ [test-docker-ubi8-x64-1](https://ci.adoptium.net/computer/test-docker-ubi8-x64-1)
https://ci.adoptium.net/job/Grinder/6843/ [test-docker-fedora35-x64-1](https://ci.adoptium.net/computer/test-docker-fedora35-x64-1)
https://ci.adoptium.net/job/Grinder/6850/ [test-docker-ubuntu2110-armv8l-1](https://ci.adoptium.net/computer/test-docker-ubuntu2110-armv8l-1)
https://ci.adoptium.net/job/Grinder/6851/ [test-docker-fedora35-armv8l-1](https://ci.adoptium.net/computer/test-docker-fedora35-armv8l-1)

I've labelled those machines offline for now

**Comment by Haroon-Khel** [comment]
The ipv6 tests passed on [test-docker-ubuntu2204-x64-1](https://ci.adoptium.net/computer/test-docker-ubuntu2204-x64-1) https://ci.adoptium.net/view/Test_grinder/job/Grinder/6836/, which is hosted on dockerhost-equinix-ubuntu2004-x64-1, while test-docker-ubuntu2204-x64-2 is hosted on test-docker-ubuntu2004-x64-1. I'll create another ubuntu 2204 container on the passing dockerhost machine

**Comment by Haroon-Khel** [comment]
Closing this issue since the ipv6 tests pass. There are some problematic containers on dockerhost-equinix-ubuntu2004-x64-1, for which I have opened https://github.com/adoptium/infrastructure/issues/3010
