### ISSUE TITLE
NagiosPB: Populate Nagios Server Config Files From j2.templates For Windows Machines

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2899]
NagiosPB: Populate Nagios Server Config Files From j2.templates

Task 6.4.1 Of The Epic ( #2445 )

In an earlier part of the automation of nagios configuration, files with names similar to these

test-azure-win2012r2-x64-1.cfg  
build-ibmcloud-win2012r2-x64-2.cfg

were created as a place holder to be used for populating the config files appropriately

Starting off with Windows on this issue, write ansible code and any supporting scripts to populate the content of these files appropriately. This can be done using jinja2 templates , such as the example ones provided

test-windows-template.j2  
build-windows-template.j2

The logic should run along the lines of, if a host is a test & windows machine, its configuration should use the test-windows-template.j2 to populate its configuration file.

Thought should be given to how this mapping between service types, and machine description should be performed, in order to simplify the expansion. As this task will expand to cover all other service and host types.

**Comment by lumuchris256** [comment]
Next issue in line , can you assign me ?

**Comment by steelhead31** [comment]
@lumuchris256 done!

**Comment by steelhead31** [comment]
Main PR is now merged
