### ISSUE TITLE
Nagios: - Add docker-xxxxx host to monitoring

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2903]
Currently the docker-xxxxxx ( dynamic docker hosts are not monitored ), these should be.

1.  Define monitoring template(s) as necessary for the docker-xxxxx hosts.
2.  Check the nagios tasks from the ansible playbooks have been run. ( Nagios user exists, key in place, and plugins installed )
3.  Create the Nagios configuration files for these hosts.

**Comment by steelhead31** [comment]
First docker machine has been added to Nagios

docker-skytap-ubuntu2004-ppc64le-1

**Comment by sxa** [comment]
> Can either of you confirm that... docker-equinix-ubuntu2004-armv8-1: (139.178.82.146) was replaced with  dockerhost-equinix-ubuntu2004-armv8-1: (147.75.35.203) ?

Short answer: "Not directly"
Long answer: The 82.146 machine was a type of machine (eMag) which equinix were decommissioning. Ours went faulty and has been offline for a while and it wasn't likely to come back. Now that we have https://ci.adoptopenjdk.net/computer/dockerhost%2Dequinix%2Dubuntu2204%2Darmv8%2D1/ (The one you set up for me @steelhead31) that would effectively be the replacement. the 35.203 machine has been used for ages and was alongside the eMag.

**Comment by steelhead31** [comment]
Unless there are any objections, I'll remove .82.146 from both the ansible inventory, and jenkins?

**Comment by steelhead31** [comment]
I'll also remove docker-aws-ubuntu1604-x64-1: {ip: 34.253.28.27} as that is no longer in use ?

**Comment by Haroon-Khel** [comment]
I have no objections

**Comment by steelhead31** [comment]
All done, on e remaining docker- host and all dockerhost- machines are aligned with nagios.
