### ISSUE TITLE
Nagios: - Add TRSS host to monitoring

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2904]
Currently the TRSS host server is not monitored and should be.

1.  Define monitoring template(s) as necessary for the trss host.
2.  Check the nagios tasks from the ansible playbooks have been run. ( Nagios user exists, key in place, and plugins installed )
3.  Create the Nagios configuration files for this host.

**Comment by sxa** [comment]
The important file system on the TRSS server is `/data` - that's where the mysql database is stored, and also jenkins' home directory `/home/jenkins` is symlinked across to `/data/jenkinshome`   which is where the TRSS application is stored and updated.

(At some point we should really just edit jenkins homedir to be `/data/jenkinshome` and do away with the symlink but that's a separate concern :-) )

**Comment by steelhead31** [comment]
Nagios user, ssh key and home dir in place... due to lack of compilers/make tools etc, installing the nagios plugins will need to be done manually.

**Comment by steelhead31** [comment]
TRSS is now being monitored by nagios..  
  
 

![](https://user-images.githubusercontent.com/60462088/216357493-41b36f04-20a8-4ad6-8407-16a271926e2a.png)
