### ISSUE TITLE
Nagios: - Add public jenkins host to monitoring.

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2905]
Currently the jenkins host server is not monitored and should be.

1.  Define monitoring template(s) as necessary for the jenkins host.
2.  Check the nagios tasks from the ansible playbooks have been run. ( Nagios user exists, key in place, and plugins installed )
3.  Create the Nagios configuration files for this host.

**Comment by sxa** [comment]
NOTE: The CI server already has a `nagios` user which is available for use for this purpose.

**Comment by steelhead31** [comment]
Current changes made:

apt-get update

apt-get install nagios-plugins
