### ISSUE TITLE
Access request for scottfryer

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2911]
Required access level (Delete as appropriate). Note that you should only
request the minimum level that is required to solve your problem

- [ ] Non-privileged
- [ ] jenkins user
- [X] root/Administrative
- [ ] other (Please specify):

System for which access is needed: docker-aws-ubuntu1604-x64-1(ip: 34.253.28.27)

Please explain why you need this access including whether it is a temporary or permanent request:

I need temporary root access to install the nagios plugins / predependent packages ( basically the nagios_plugins ) role from the unix playbook.

**Comment by sxa** [comment]
I've just deprovisioned this machine - it's been offline for nearly four months with no side effects so is not required, so no need to add to nagios :-)
