### ISSUE TITLE
All test jobs fail during setup on test-ibmcloud-win2012r2-x64-2 with Could not resolve host: github.com 

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2917]
Please set the title to indicate the test name and machine name where known.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? all tests, during setup when trying to git clone test material
- a link into recent `Test_` job on https://ci.adoptopenjdk.net which showed the failure
  - https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.perf_x86-32_windows/357/
  - https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.perf_x86-32_windows/356/
  - https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.system_x86-32_windows/365/
  - https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.functional_x86-32_windows/319/
  - https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.functional_x86-32_windows/318/
- Is there an existing issue elsewhere covering this? No
- Which machine(s) does it work on? build-alibaba-win2012r2-x64-2
- Which machine(s) does it fail on? test-ibmcloud-win2012r2-x64-2

Any other details:
```
14:40:20  stderr: fatal: unable to access 'https://github.com/adoptium/aqa-tests.git/': Could not resolve host: github.com
14:40:20  
14:40:20  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2675)

```

That machine appeared to be fine up until recently, see a test job running on it on Jan 18th with no issues:
https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.perf_x86-32_windows/355/

Fresh rerun to check if this is a transient connectivity issue (though it appears to be present in both Jan 28 and Jan 31 runs):
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6537

Taking that machine offline, until this is resolved.

**Comment by steelhead31** [comment]
This appears to be an issue with name server resolution, temporarily adding dns lookup entries to the machines hosts file appears to work as a workaround, but this machine needs a proper fix

**Comment by steelhead31** [comment]
Also needs work to fix jenkins agent to run as service currently agent.jar launched manually with jdk11 environment..

**Comment by steelhead31** [comment]
Temporarily configured DNS for IPv4 & IPv6 to use google public DNS servers

**Comment by steelhead31** [comment]
Grinder now successful with public DNS added..

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6673/

**Comment by steelhead31** [comment]
Succesful sanity perf run : https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.perf_x86-32_windows/363/

**Comment by steelhead31** [comment]
The issues with this host not being able to resolve DNS names has now been resolved. The machine is working normally.
