### ISSUE TITLE
Migrate ci.adoptopenjdk.net to ci.adoptium.net

### ISSUE THREAD

**Issue by gdams** [adoptium/infrastructure#2932]
I want to kick off the process of migrating the Jenkins server to the Adoptium DNS space. I've listed a few things that will likely need to be changed:

- [x] 1. Create ci.adoptium.net A record pointing to `78.47.239.97`
- [x] 2. Create ci.adoptium.net AAAA record pointing to `2a01:4f8:c0c:1804::2`
- [x] 3. Update let's encrypt config file on Jenkins to use new DNS
- [x] Update GitHub authentication callback URL (https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2696)
- [x] 4. Update any hosts that don't connect via SSH.
- [x] 5. Update Jenkins URL at https://ci.adoptopenjdk.net/configure
- [x] 6. Update Jenkins logo to use Adoptium logo
- [x] 7. Update any references to ci.adoptopenjdk.net in Adoptium repos
- [x] 8. Ensure that ci.adoptopenjdk.net still redirects to prevent breaking existing bookmarks

**Comment by gdams** [comment]
Request for DNS records to be created https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2670

**Comment by karianna** [comment]
I suspect we will have a long tail of internal and external scripts referencing the old URL.  Probably need to add a few tasks for that.

**Comment by zdtsw** [comment]
do we have issue to update https://trss.adoptopenjdk.net to something similar?

**Comment by gdams** [comment]
@zdtsw I think TRSS is already running at https://trss.adoptium.net. There seems to be a redirect for me at least.

**Comment by zdtsw** [comment]
> @zdtsw I think TRSS is already running at https://trss.adoptium.net. There seems to be a redirect for me at least.

ok, nice! probably just need to update our job config

**Comment by gdams** [comment]
> ok, nice! probably just need to update our job config

Which job are you referring to @zdtsw?

**Comment by smlambert** [comment]
I presume we will still redirect from ci.adoptopenjdk.net to ci.adoptium.net ... otherwise, I will also need to update which pipelines we monitor in TRSS.

**Comment by zdtsw** [comment]
> > ok, nice! probably just need to update our job config
> 
> Which job are you referring to @zdtsw?

it is https://ci.adoptium.net/job/nightlyBuildAndTestStats_temurin/, we have job not created by scripts. i've updated the config for both URl:s in this job.

**Comment by gdams** [comment]
Things seem good here, no issues observed so I'm going to mark this as closed.
