### ISSUE TITLE
Access request for RadekCap

### ISSUE THREAD

**Issue by RadekCap** [adoptium/infrastructure#2944]
Required access level (Delete as appropriate). Note that you should only
request the minimum level that is required to solve your problem

- [ ] Non-privileged

System for which access is needed: Nagios

Please explain why you need this access including whether it is a temporary or permanent request: I would like to understand more about infrastructure and I'm interested in about monitoring generally.

**Comment by sxa** [comment]
@steelhead31 Can you create the account for Radek please?

**Comment by steelhead31** [comment]
@sxa / @RadekCap Account for nagios has been created, and details emailed.

**Comment by RadekCap** [comment]
And it's working, thank you.

**Comment by sxa** [comment]
@RadekCap If you want a quite overview of the Nagios UI I've just uploaded a ten minute video that @steelhead31 has produced for us to https://youtu.be/Dr8ymWV-pow :-)
