### ISSUE TITLE
Verify fakeroot is available on all arm_linux machines

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#2954]
Not unlike the [5 closed infrastructure issues](https://github.com/adoptium/infrastructure/issues?q=is%3Aissue+fakeroot+is%3Aclosed) related to fakeroot missing on other platforms, need to verify that all arm_linux machines are also capable of running the jdk_tools target from the extended.openjdk top-level target (see https://github.com/adoptium/aqa-tests/issues/4257#issuecomment-1396445666 for details).

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? BUILD_LIST=openjdk TARGET=jdk_tools
- a link into recent `Test_` job on https://ci.adoptium.net which showed the failure
https://ci.adoptium.net/job/Test_openjdk19_hs_extended.openjdk_arm_linux_testList_0/34/
- **Hyperlink** to re-run in Grinder:  [rerun link](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk19_hs_extended.openjdk_arm_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=arm_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v0.9.6-release&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=19&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk19u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk19u%2Fjdk19u-release-linux-arm-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-19.0.2%2B7_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=39&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=2&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)
- Is there an existing issue elsewhere covering this? No, but 5 similar closed issues linked above
- Which machine(s) does it work on? test-docker-ubuntu2004-armv7l-2
- Which machine(s) does it fail on? test-docker-ubuntu2204-armv8-2

Any other details:
```
[15:18:20.405] Running fakeroot
[15:18:20.412] jdk.jpackage.internal.ConfigException: Can not find fakeroot. Reason: Cannot run program "fakeroot": error=2, No such file or directory
	at jdk.jpackage/jdk.jpackage.internal.ToolValidator.validate(ToolValidator.java:122)
	at jdk.jpackage/jdk.jpackage.internal.LinuxPackageBundler.validate(LinuxPackageBundler.java:76)
	at jdk.jpackage/jdk.jpackage.internal.Arguments.generateBundle(Arguments.java:699)
	at jdk.jpackage/jdk.jpackage.internal.Arguments.processArguments(Arguments.java:565)
	at jdk.jpackage/jdk.jpackage.main.Main.execute(Main.java:91)
	at jdk.jpackage/jdk.jpackage.main.Main.main(Main.java:52)
Caused by: java.io.IOException: Cannot run program "fakeroot": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at jdk.jpackage/jdk.jpackage.internal.Executor.execute(Executor.java:116)
	at jdk.jpackage/jdk.jpackage.internal.ToolValidator.validate(ToolValidator.java:104)
	... 5 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:319)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:249)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 8 more
```

Rerun jdk_tools at: https://ci.adoptium.net/job/Grinder/6728 for a fresh run on test-docker-ubuntu2204-armv8-2 to check if it is still an issue.  Rerun just the failing testcases at this [link](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=nightly&TARGET=jdk_custom&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=arm_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&LABEL=test-docker-ubuntu2204-armv8-2&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=19&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk19u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=tools/jpackage/linux/jdk/jpackage/tests/UsrTreeTest.java+tools/jpackage/linux/AppCategoryTest.java+tools/jpackage/linux/LinuxBundleNameTest.java+tools/jpackage/linux/LinuxResourceTest.java+tools/jpackage/linux/MaintainerTest.java+tools/jpackage/linux/PackageDepsTest.java+tools/jpackage/share/jdk/jpackage/tests/BasicTest.java+tools/jpackage/share/AddLShortcutTest.java+tools/jpackage/share/AppContentTest.java+tools/jpackage/share/AppImagePackageTest.java+tools/jpackage/share/EmptyFolderPackageTest.java+tools/jpackage/share/IconTest.java+tools/jpackage/share/MultiLauncherTwoPhaseTest.java+tools/jpackage/share/MultiNameTwoPhaseTest.java+tools/jpackage/share/PerUserCfgTest.java+tools/jpackage/share/ServiceTest.java+tools/jpackage/share/SimplePackageTest.java&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-19.0.2%2B7_adopt&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=true&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None).

**Comment by smlambert** [comment]
https://ci.adoptium.net/job/Test_openjdk20_hs_extended.openjdk_aarch64_linux/22/testReport/tools_jpackage_linux_LinuxBundleNameTest/java/LinuxBundleNameTest_2/

**Comment by smlambert** [comment]
This will affect the JDK 20 release if not addressed.  We may want to disable machines in order to avoid sending test jobs off to certain failure.

**Comment by sxa** [comment]
Hmmm - test-docker-ubuntu2204-armv8-2 appears to incorrectly have the `hw.arch.aarch32` tag on it (as per the hostname, it's armv8 which =aarch64) so the job shouldn't even be trying to run there. I'll remove that label (although that doesn't directly explain why `fakeroot` wasn't able to be executed as it seems to be present...) It's (wrongly) running https://ci.adoptium.net/job/Test_openjdk19_hs_extended.openjdk_arm_linux_testList_0/38/ just now

Note to self: Using this to check the docker containers on each host: `docker ps | grep -v NAMES | awk '{print$NF}' | while read X; do docker exec $X sh -c "which fakeroot >/dev/null || echo Nothing on $X"; done`

Running through the dockerhost systems:
- [test-equinix-ubuntu2004-armv8l-02](https://ci.adoptium.net/label/hw.dockerhost.dockerhost-equinix-ubuntu2004-armv8-1) 147.75.35.203 (3 remediated, [U2010_2231](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2010%2Darmv8l%2D2/configure) shut down as it's out of support)
- dockerhost-equinix-ubuntu2204-armv8-1 (No issues)
- dockerhost-equinix-ubuntu2004-x64-1 (No issues)
- dockerhost-equinix-ubuntu2204-x64-1 (No issues)
- dockerhost-osuosl-ubuntu2204-ppc64le-1 ([U2010_2225](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2010%2Dppc64le%2D1/) obsolete OS - disabled, [U1804_2223](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu1804%2Dppc64le%2D1/markOffline) fixed, [F33_2227](https://ci.adoptium.net/computer/test%2Ddocker%2Dfedora33%2Dppc64le%2D1/) fixed)
- dockerhost-marist-ubuntu2204-s390x-1 - All OK (Only SLES)
- docker-skytap-ubuntu2004-ppc64le-1 - All OK
- dockerhost-skytap-ubuntu2004-ppc64le-2 - All OK

**Comment by sxa** [comment]
Disappearing down a rabbit hole - [test-docker-ubuntu2204-armv8-2](https://ci.adoptium.net/computer/test-docker-ubuntu2204-armv8-2/) is actually an ARM32 container which is why the arm32 jobs are running ok on it - I've just renamed it to https://ci.adoptium.net/computer/test-docker-ubuntu2204-armv7l-1/

**Comment by sxa** [comment]
Also installed on [test-marist-rhel8-s390x-2](https://ci.adoptium.net/computer/test%2Dmarist%2Drhel8%2Ds390x%2D2) and [test-marist-sles15-s390x-2](https://ci.adoptium.net/computer/test%2Dmarist%2Dsles15%2Ds390x%2D2) although it does not seem to be installable on [test-marist-rhel7-s390x-2](https://ci.adoptium.net/computer/test%2Dmarist%2Drhel7%2Ds390x%2D2) so I'm going to mark that one offline for now...

**Comment by sxa** [comment]
Sine the only remaining machine which isn't set up with this is the RHEL7 one and we can't easily install it from the repositories on there at the moment, I'm going to create another issue for that one.
