### ISSUE TITLE
Nagios: Create Documentation Around New Nagios Playbook & Automation

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#2960]
To finalise the nagios automation project, the following areas require documentation

Documentation Required For Automation

1.  How To Use - What Each Playbook Does ( Pre-Reqs etc )  
    2) How To Update - Default Templates ( Commands, etc )  
    3) How To Update - Host / Check Template Rules etc  
    4) Test Approach & Validating  
    5)  Functional Documentation

**Comment by steelhead31** [comment]
@lumuchris256  please comment on this issue, so I can assign it to you as well as myself. Its the next/final stage of the automation project.

**Comment by lumuchris256** [comment]
Next task in line ,can I be assigned?
