### ISSUE TITLE
Update jenkins to latest LTS

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2961]
Related:
- https://github.com/adoptium/infrastructure/issues/2108
- https://github.com/adoptium/infrastructure/issues/2763
- https://github.com/adoptium/infrastructure/issues/2950

The latest jenkins LTS requires that all agents are running JDK11 or later. This has now been achieved so we are looking to schedule an upgrade next week to the current LTS (2.365.3 - we are currently on 2.346.3) - precise time/date TBC but likely early morning UTC.

As part of this work we should also ensure that the agent version used on machines that aren't launched over ssh are updated (Some of them are already out of date) Perhaps this could be checked and if necessary auto-updated on each launch in the future?)

**Comment by sxa** [comment]
Scheduled to start at 0930 GMT/UTC on Thursday

**Comment by sxa** [comment]
NOTE: This has been deferred to next week

**Comment by sxa** [comment]
Advisory from today: https://www.jenkins.io/security/advisory/2023-03-08/

**Comment by sxa** [comment]
We had some issues with the upgrade and failures with the GitHub plugin, possibly as a result of the plugins not having been upgraded prior to attempting the upgrade. We have managed to back everything out, and upgraded the plugins, but will reschedule the upgrade again for a future date.

**Comment by sxa** [comment]
@karianna This is our server (still on jenkins [Jenkins 2.346.3](https://www.jenkins.io/)) GHA plugin 0.39
![image](https://user-images.githubusercontent.com/6487691/224369880-c13e2b1b-b514-40d6-a043-3608d03519b2.png)

On another server running [Jenkins 2.361.4](https://www.jenkins.io/) which has 0.37 it says 0.39 requires  Jenkins 2.375.1 - quite a surprise that it's working for us :-)
![image](https://user-images.githubusercontent.com/6487691/224370192-8125dff4-e4ae-4341-a80a-9d6b66722f69.png)

**Comment by karianna** [comment]
This is why we can't have nice things

**Comment by sxa** [comment]
Having done some experiments today with a near-replica on another instances, I'm reasonably confident that this upgrade will now work. Suggest we target the upgrade for the earliest opportunity on the week after the release (starts 27th March)

**Comment by sxa** [comment]
Plugin advisory due tomorrow: https://groups.google.com/g/jenkinsci-advisories/c/oADJ7nuLF48/m/eHcQwSZ7FAAJ

**Comment by sxa** [comment]
Upgrade to 2.387.1 complete. We have left the folloowing two plugins which seemed particularly risky to try and do within our allocated on hour slot but a large number of other plugins have been updated so hopefully they are all working as exepcted:
- SAML 2.333.vc81e525974a_c -> 4.385.v4dea_91565e9d `Warning: The new version of this plugin is marked as incompatible with the installed version. This is usually the case because its behavior changed, or because it uses a different settings format than the installed version. Jobs using this plugin may need to be reconfigured, and/or you may not be able to cleanly revert to the prior version without manually restoring old settings. Consult the plugin release notes for details. `
- SSH Build Agents 2.333.vc81e525974a_c -> 2.877.v365f5eb_a_b_eec `Warning: The new version of this plugin is marked as incompatible with the installed version. This is usually the case because its behavior changed, or because it uses a different settings format than the installed version. Jobs using this plugin may need to be reconfigured, and/or you may not be able to cleanly revert to the prior version without manually restoring old settings. Consult the plugin release notes for details.`

Two new plugins were installed:
- https://plugins.jenkins.io/job-restrictions/ (Ref https://github.com/adoptium/infrastructure/issues/2108#issuecomment-1474073224)
- https://plugins.jenkins.io/build-name-setter/ (Ref: https://github.com/adoptium/infrastructure/issues/434)
