### ISSUE TITLE
Identify tooling for auditing access controls to infrastructure

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2968]
In order to detect threats and understand the use of our machines we need to identify what attempts are being made to access our machines and ensure we follow up on entries in the logs. Some of this may be feasible with Nagios, or we can identify other tooling that fulfils this role. Eclipse have some tooling in this area, but it is closed and not directly available for us to use at present.

**Comment by sxa** [comment]
Note: Eclipse have a `logscan` tool that they use internally but it has not been open-sourced

**Comment by steelhead31** [comment]
Miro diagram of potential monitoring approaches.. https://miro.com/app/board/uXjVMSLkAYY=/  , currently working on a document with some details and potential options for discussion.

**Comment by steelhead31** [comment]
Document.. https://docs.google.com/document/d/1LagjwclS9U0LCELML9yGAihr8eeb3j7pnVw1NcTVMxo/edit?usp=sharing

**Comment by steelhead31** [comment]
As this has now been discussed, the next step is to provide a detailed breakdown of the next steps. This will be covered by this Epic #3047 and particular task 2, next steps and more detailed breakdown of tasks required to implement.
