### ISSUE TITLE
Define/document linter policy and other validation checks on automation

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#2971]
We have frequent issues with the linter "suddenly" breaking. We should look at taking pre-emptive action to avoid the first person who submits a PR after a change being hit with it.

In addition we should audit our scripts to ensure that they perform as much input validation and produce reasonable error messages as is practical for the critical parts of the build process (This will likely require other issues to be created across the repositories)

This will likely involve some code reviews on the scripts to identify potentially problematic code paths and/or identifying situations where things are not as clear as they could be under error conditions (perhaps generate a "failing" scenario and see if the root cause could be easily identified.

See also the SSDF PO5.2 issue at https://github.com/adoptium/infrastructure/issues/2502

**Comment by sxa** [comment]
Question: Could checks have detected the vulnerability in the CycloneDX dependencies which was resolved in https://github.com/adoptium/temurin-build/pull/3275?

**Comment by sxa** [comment]
Ref: Allstar tool which may also be useful https://github.com/adoptium/adoptium/issues/220
Will be discussed at PMC meeting this week.

**Comment by sxa** [comment]
This hasn't been progressed so bumping to April

**Comment by sxa** [comment]
For whoever picks this up, a list of some potential tools is at https://owasp.org/www-community/Source_Code_Analysis_Tools

**Comment by steelhead31** [comment]
First part of the linter/action document is now available here: https://docs.google.com/document/d/1GJ9bwvmKtrHglo2v5WnJ_Ky9F43ZIfEkv2O6oEwGpqc/edit?usp=sharing

**Comment by steelhead31** [comment]
The document is now considered review ready, and will be first issued for internal review, ahead of external review. https://docs.google.com/document/d/1GJ9bwvmKtrHglo2v5WnJ_Ky9F43ZIfEkv2O6oEwGpqc/edit?usp=sharing

**Comment by steelhead31** [comment]
Document issued
