### ISSUE TITLE
No space left on dockerhost-equinix-ubuntu2004-armv8-1

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2974]
No space left on dockerhost-equinix-ubuntu2004-armv8-1, a dockerhost machine which runs about 11 static docker conainters.

```
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0 894.3G  0 disk 
├─nvme0n1p1 259:2    0   500M  0 part /boot/efi
├─nvme0n1p2 259:3    0     9G  0 part [SWAP]
└─nvme0n1p3 259:4    0 884.8G  0 part /
nvme1n1     259:1    0 894.3G  0 disk 

root@test-equinix-ubuntu2004-armv8l-02:/home/jenkins/workspace# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            251G     0  251G   0% /dev
tmpfs            51G  4.2G   47G   9% /run
/dev/nvme0n1p3  871G  821G  6.0G 100% /
tmpfs           251G  213M  251G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           251G     0  251G   0% /sys/fs/cgroup
/dev/nvme0n1p1  500M  7.3M  492M   2% /boot/efi
tmpfs            51G     0   51G   0% /run/user/1000
tmpfs            51G     0   51G   0% /run/user/0
```
(The docker service is stopped which is why you are not seeing each of the containers in the output of the df command)
I noticed that there is a 900g spare disk nvme1n1 which isnt being used. It should be mounted to /var/lib/docker, allowing docker to make full use of that disk, preventing it from using anything in / (which is what it is doing currently)

**Comment by Haroon-Khel** [comment]
`docker system prune` just reclaimed 400g of space. This should keep the machine running for a while, but its spare disk needs to be put to use to avoid hitting this problem in the near future

**Comment by Haroon-Khel** [comment]
```
root@test-equinix-ubuntu2004-armv8l-02:/home/jenkins/workspace# df -h /var/lib/docker
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p3  871G  381G  446G  47% /
```

**Comment by jiekang** [comment]
Is this something that Nagios alerted to? How was it discovered?

**Comment by smlambert** [comment]
I raised this recently: https://github.com/adoptium/infrastructure/issues/2984
but not sure if this issue was raised as an outcome of it or something else.

**Comment by sxa** [comment]
Closing as the immediate issue has been closed and [#docker](https://github.com/adoptium/infrastructure/issues/3007) will cover related future investigation.
