### ISSUE TITLE
Dockerhost setup of dockerhost-osuosl-ubuntu2204-aarch64-1

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#2991]
The dockerhost [dockerhost-osuosl-ubuntu2204-aarch64-1](https://ci.adoptium.net/computer/dockerhost-osuosl-ubuntu2204-aarch64-1/) is setup (with Ansible), but has only 1 centos8 container running. 

Its container setup needs to be completed

**Comment by Haroon-Khel** [comment]
ref https://github.com/adoptium/infrastructure/issues/2975#issuecomment-1452097293

**Comment by sxa** [comment]
(Noting also that CentOS8 is unsupported so we should even ditch the one that's currently on there :-) )

**Comment by sxa** [comment]
This machine is mostly unused at present but is likely a good choice of test system for the work under #3368

**Comment by sxa** [comment]
> Just had a look at this machine. It has 8 cpus and a 80g disk. Seems a bit low to be used as a dockerhost machine no?

It should be ok for hosting 2-4 containers - mostly as a backup in case of a problem with equinix. I think 80Gb is probably ok if we're not running builds on it sine the dockerstatic containers are pretty small.

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/computer/test%2Ddocker%2Dcentos8%2Darmv8%2D1/log and https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2204%2Darmv8%2D4/log, both of which are hosted on dockerhost-osuosl-ubuntu2204-aarch64-1, cannot connect. Connection times out

**Comment by sxa** [comment]
I assume this isn't specific to jenkins and you can't establish a connection to that port from the comment line either?
In which case it'll be a firewall issue - likely at the provider. If you got to the OSUOSL arm-openstack UI (Ping me via DM if you can't access it)  then we'll need to either:

1. adjust the `default` "security group" (see below) or define a new one with a suitable set of inbound (ingress) firewall holes - the screenshot below shows what it looks like currently):
2. Create a new security group with a suitable set of holes and apply that to the dockerhost systems

![image](https://github.com/adoptium/infrastructure/assets/6487691/18801cd1-70da-4ca5-a4d8-26cf4ecc87b4)

**Comment by Haroon-Khel** [comment]
Im not sure if im reading it wrong, but the 3rd security rule suggests the firewall allows all inbound ipv4 to any port?

Either way, I added a specific rule to allow ipv4 traffic to port 2226 specifically (a port on which a docker container is running), and still no luck.

In the mean time I have changed the jenkins config of the 2 nodes to connect to the controller so we can have them running as nodes

https://ci.adoptium.net/computer/test-docker-centos8-armv8-1/
https://ci.adoptium.net/computer/test-docker-ubuntu2204-armv8-4/

**Comment by sxa** [comment]
`Remote IP Prefix` in the 3rd security rule and your new one was blank, so it presumably wasn't accepting connections from any IP address. The `test sxa` rule in the screen shot below seems to allow 2226 to work (See ssh attempt below - feel free to delete that rule and adjust to add a small range in instead):
![image](https://github.com/adoptium/infrastructure/assets/6487691/cd0316dd-f452-4a35-9ee0-07b9a9ee9110)

```
sxa@fedora:~$ ssh 140.211.167.67 -l ubuntu -p 2226
The authenticity of host '[140.211.167.67]:2226 ([140.211.167.67]:2226)' can't be established.
ED25519 key fingerprint is SHA256:...
```

**Comment by Haroon-Khel** [comment]
Closing this as the dockerhost is completely setup
