### ISSUE TITLE
test-docker-fedora35-armv8l-1 unable to complete extended.openjdk in under 10hrs

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3001]
Node test-docker-fedora35-armv8l-1 always aborts after 10hrs:
https://ci.adoptium.net/job/Test_openjdk20_hs_extended.openjdk_aarch64_linux/26/

**Comment by sxa** [comment]
As with https://github.com/adoptium/infrastructure/issues/2996 this should be considered a duplicate of https://github.com/adoptium/infrastructure/issues/2893 and dealt with in there.
