### ISSUE TITLE
test-marist-ubuntu2204-s390x-1 has run out of storage space

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3003]
- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
extended.openjdk
- a link into recent `Test_` job on https://ci.adoptium.net which showed the failure
https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_2/81/console
- Is there an existing issue elsewhere covering this?
Not that I can find.
- Which machine(s) does it work on?
All other machines, it appears.
- Which machine(s) does it fail on?
test-marist-ubuntu2204-s390x-1

Any other details:
```
java.nio.file.FileSystemException: /home/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_2: No space left on device
```

**Comment by sxa** [comment]
build cache was using 86Gb. Cleared it down to 840Mb with `docker builder prune -f --keep-storage 1000000000`.

Since we've had a few occurrences of this we should look at understanding and mitigating it. I've created a separate issue to do that.

**Comment by adamfarley** [comment]
Thanks Stewart. :)
