### ISSUE TITLE
Grinder x86-64_linux: No space left on device (Intel host)

### ISSUE THREAD

**Issue by zzambers** [adoptium/infrastructure#3006]
Grinder x86-64_linux jobs fail with `No space left on device`

Seen for:
 test-docker-debian11-x64-1:
https://ci.adoptium.net/view/Test_grinder/job/Grinder/7030/console
 test-docker-ubuntu2204-x64-1:
https://ci.adoptium.net/view/Test_grinder/job/Grinder/7031/console

aarch64 seems ok:
https://ci.adoptium.net/view/Test_grinder/job/Grinder/7032/console

**Comment by sophia-guo** [comment]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/7048/console
https://ci.adoptium.net/view/Test_grinder/job/Grinder/7044/console

label : ci.role.test&&hw.arch.x86&&sw.os.linux

**Comment by sxa** [comment]
Issued `docker builder prune` on the Intel machine [dockerhost-equinix-ubuntu2004-x64-1](https://nagios.adoptopenjdk.net/nagios/cgi-bin/extinfo.cgi?type=1&host=dockerhost-equinix-ubuntu2004-x64-1) to reclaim 300Gb.

**Comment by sophia-guo** [comment]
Still happened on March 29th. https://ci.adoptium.net/view/Test_system/job/Test_openjdk20_hs_sanity.system_x86-64_linux/97/console

Grinder today: https://ci.adoptium.net/view/Test_grinder/job/Grinder/7062/console

**Comment by smlambert** [comment]
https://ci.adoptium.net/computer/test-docker-alpine317-x64-1/ - No space left on device (see https://ci.adoptium.net/view/Test_grinder/job/Test_Job_Auto_Gen/985/console), marking it offline until resolved.

**Comment by sxa** [comment]
> > Issued `docker builder prune`
> 
> Is this something that could be scheduled regularly on all dockerhost machines as this seems to recur regularly?

Yes I expect this can be done easily with Nagios - I was hesitating on it due to not understanding why we're only seeing this as an issue now and whether there is an underlying issue that may need to be addressed.

> marking it offline until resolved.

Bear in mind that since this will affect all containers on a host system, marking just one of them offline will do very little to alleviate the problem.

**Comment by sxa** [comment]
It looks like the machine hosting the systems from the last two comments is currently in a healthy state with only 10% used on the docker file system, so I'm going to reclose this again. Someone was logged in on Friday so presumably dealt with this.
