### ISSUE TITLE
arm32 nodes not accessible or disk issue? https://ci.adoptium.net/label/sw.os.linux&&hw.arch.aarch32&&ci.role.perf/

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3023]
https://ci.adoptium.net/label/sw.os.linux&&hw.arch.aarch32&&ci.role.perf/

- Link to any log file showing the problem: https://ci.adoptium.net/job/Test_openjdk17_hs_extended.perf_arm_linux/93/console

- Please describe the issue:
The arm32 nodes both have issues, possibly a file system problem?:
```
18:20:32  Exception: java.nio.file.AccessDeniedException: /ssd/jenkins
[Pipeline] sh
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
18:20:33  ERROR: Execution failed
18:20:33  Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from cpc145836-warw19-2-0-cust71.3-2.cable.virginm.net/80.2.248.72:53274
```

**Comment by sxa** [comment]
> The arm32 nodes both have issues

What makes you say that? https://ci.adoptium.net/job/openjdk_build_docker_multiarch/958/console has been running successfully on the `-2` node since yesterday.

`-1` has lost it's SSD - I'll get it recovered.

**Comment by sxa** [comment]
`-1` is now back online and running https://ci.adoptium.net/job/Test_openjdk17_hs_extended.perf_arm_linux/95/console
`-2` seems ok so I'm going to close this
