### ISSUE TITLE
Smoke test failing due to missing library on test-docker-sles12-s390x-1

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3026]
JDK8 s390x Linux smoke test is failing on [test-docker-sles12-s390x-1](https://ci.adoptium.net/computer/test-docker-sles12-s390x-1/) due to a missing library

```
15:38:03  Run /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-s390x-temurin_SmokeTests/openjdkbinary/j2sdk-image/bin/java -version
15:38:03  =JAVA VERSION OUTPUT BEGIN=
15:38:03  Error: dl failure on line 894
15:38:03  Error: failed /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-s390x-temurin_SmokeTests/openjdkbinary/j2sdk-image/jre/lib/s390x/server/libjvm.so, because libffi.so.6: cannot open shared object file: No such file or directory
```

Latest failure https://ci.adoptium.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-temurin/262/console

**Comment by sxa** [comment]
@Haroon-Khel I believe this is the machine that was removed this week under https://github.com/adoptium/infrastructure/pull/3022 - it was one of the old machines that were replaced as part of https://github.com/adoptium/infrastructure/issues/2673 but was seemingly left live (To be honest I'm amazed it was still there...)
If this works on the other SLES12 systems (may need to be temporarily re-enabled) then we can consider this to not be a problem.

**Comment by Haroon-Khel** [comment]
Are you sure? The one removed in https://github.com/adoptium/infrastructure/pull/3022 is test-marist, this is test-docker which is a static docker container hosted on dockerhost-marist-ubuntu2204-s390x-1

**Comment by sxa** [comment]
Yes you're right - ignore me I'm talking nonsense ;-)

**Comment by Haroon-Khel** [comment]
Made the link, running a smoke test on the machine https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-temurin_SmokeTests/182/console

**Comment by Haroon-Khel** [comment]
Looks good. Will add the solution to the Sles 12 dockerfile. Thanks

**Comment by adamfarley** [comment]
@Haroon-Khel - Could you please apply the fix to test-docker-sles15-s390x-1? Appears to be the same issue. [Link](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-temurin_SmokeTests/210/console).

```
19:51:21  =JAVA VERSION OUTPUT BEGIN=
19:51:21  Error: dl failure on line 894
19:51:21  Error: failed /long_path_goes_here/libjvm.so, because libffi.so.6: cannot open shared object file: No such file or directory
```

**Comment by Haroon-Khel** [comment]
made the link from libffi.so.6 to libffi.so.7 as 4 is not present
`/usr/lib64/libffi.so.6 -> libffi.so.7`

rebuilt job
https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-temurin_SmokeTests/212/console

**Comment by Haroon-Khel** [comment]
/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-s390x-temurin_SmokeTests@tmp/durable-9eb8412b/script.sh: line 1: awk: command not found

installing awk and rerunning
https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-temurin_SmokeTests/213/console

**Comment by adamfarley** [comment]
Thanks Haroon! 😃

**Comment by sxa** [comment]
Please ensure this is added to the SLES15 dockerstatic image - unusual not to have `awk` installed by default but if it's not on SLES we should have it in the dockerfile.

**Comment by sxa** [comment]
@adamfarley Ref the original problem with `libffi` - was that only occurring on JDK8 on this machine (i.e. the one [we're switching off](https://github.com/adoptium/temurin-build/issues/3381))?

**Comment by adamfarley** [comment]
It was only seen on JDK8, yes.

However, I did a search, and it appears that (other than the JDK21 run that failed with the awk issue) no other smoke tests ever ran on test-docker-sles15-s390x-1 (passed or failed).

**Comment by adamfarley** [comment]
Assuming you mean my original issue there. The one on test-docker-sles15-s390x-1.

The original problem for which this issue was raised was Haroon's issue on test-docker-sles12-s390x-1, which has had three recent smoke test runs on non-JDK8 Temurin builds, and they all passed.

**Comment by Haroon-Khel** [comment]
Can be closed since https://github.com/adoptium/infrastructure/pull/3109 is merged
