### ISSUE TITLE
alpine-linux containers need fonts installed 

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#3039]
Please set the title to indicate the test name and machine name where known.

jdk11, jdk17 jdk_imageio and jdk_beans failures on x86-64_alpine-linux are related to machine config, no fonts on machine / in containers (see also https://bugs.openjdk.org/browse/JDK-8304054), as seen in https://github.com/adoptium/aqa-tests/issues/4515#issuecomment-1512408680.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
- a link into recent `Test_` job on https://ci.adoptium.net which showed the failure - https://ci.adoptium.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_1/67/
- **Hyperlink** to re-run in Grinder:  [Rerun link](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=jdk_custom&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_alpine-linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=v0.9.7-release&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=11&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk11u&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk11u%2Fjdk11u-release-alpine-linux-x64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=java/beans/PropertyChangeSupport/Test4682386.java+java/beans/XMLEncoder/javax_swing_DefaultCellEditor.java+java/beans/XMLEncoder/javax_swing_JTree.java+java/beans/XMLEncoder/Test4631471.java+java/beans/XMLEncoder/Test4903007.java+javax/imageio/plugins/shared/ImageWriterCompressionTest.java&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-11.0.19%2B7_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=82&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=4&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=15&JVM_OPTIONS=&PARALLEL=None)
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on? None
- Which machine(s) does it fail on? [All](https://ci.adoptium.net/label/ci.role.test&&hw.arch.x86&&sw.os.alpine-linux/) 

Any other details:
These failures block the release of jdk11 and jdk17 x86-64_alpine-linux builds.

**Comment by smlambert** [comment]
FYI @Haroon-Khel

**Comment by sxa** [comment]
I'm a little confused - if this is a known upstream issue with a fix that's just gone in then why would we wish to correct it?
Since the Alpine builds are headless I wouldn't typically expect it to reuire installation of fonts.
Was it a failure in the January cycle too?

**Comment by smlambert** [comment]
Did not see it in January for JDK20.  Strangely we are running the jtreg tests as headless, so perhaps this is an upstream issue of those tests not being tagged properly as not applicable for headless.

**Comment by sxa** [comment]
That would be my initial feeling on it. Interesting that it wasn't seen in January though so perhaps it was broken between now and then. Can we run it against the material from January?
Are you currently happy to treat this as an exception and exclude it for now?

**Comment by sxa** [comment]
> Did not see it in January for JDK20

January for 11/17 or March for 20? (Presumably both since it hasn't been raised til now!)

**Comment by smlambert** [comment]
As mentioned, its the first I remember seeing it, and yes, perhaps the raiser of https://bugs.openjdk.org/browse/JDK-8304054 isn't running alpine-linux on 11, but I would also be surprised if they were running a headful build of it.

**Comment by sxa** [comment]
Noting here that comparable symptoms were also seen by @steelhead31 elsewhere.

**Comment by steelhead31** [comment]
All alpine images & containers on x64 and aarch64 have now been updated with the missing fonts.

**Comment by sxa** [comment]
@steelhead31 I guess we can close this issue now? Or is there still some additional verification to do?

**Comment by steelhead31** [comment]
I was leaving it open as a reminder to check on the EF issue, but other than that it can be closed.

**Comment by steelhead31** [comment]
EF have recreated this docker container jck-equinix\_esxi-containerized-alpine317-x64-1 with the new docker files, tests have been run in this grinder,  although there are 2 individual test failures, they are known/recurring issues and have nothing to do with fonts...  [https://ci.eclipse.org/temurin-compliance/job/Grinder/3476/](https://ci.eclipse.org/temurin-compliance/job/Grinder/3476/)  EF will now roll this fix out to the remaining containers.
