### ISSUE TITLE
System unavailable: Repeated "Cannot contact node" at 2am ?

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3055]
- Please put the system name in the title of this issue.
Several nodes:
test-docker-debian11-x64-2 : https://ci.adoptium.net/job/Test_openjdk21_hs_extended.system_x86-64_linux/34/console
test-docker-fedora35-x64-1 : https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.openjdk_x86-64_linux/35/console
test-docker-fedora37-x64-2 : https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.system_x86-64_linux/34/console

- Please describe the issue:
I have seen this issue at 1 or 2am in the past. I am suspecting at this particular time the "hosting" systems are being diconnected for some reason? Should we enable some sort of Jenkins reconnect? or a more extended HEARTBEAT_CHECK_INTERVAL to handle these drops?

**Comment by andrew-m-leonard** [comment]
on ci.adoptium.net we currently use:
```
-Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=300 
```
So 5mins, wondering if this needs to be longer? How long does the connection to these docker host go down for?

**Comment by sxa** [comment]
Interesting ... Since this is only happening on JDK21 have we tried kicking off a JDK21 pipeline at another time of the day to verify that it's not a problem with load induced by that java version when all the test jobs are initiated?

**Comment by sxa** [comment]
@andrew-m-leonard I've kicked off another "nightly" at https://ci.adoptium.net/job/build-scripts/job/openjdk21-pipeline/60/ (Linux/x64 only) to see if it occurs during the day.

**Comment by sxa** [comment]
No obvious problem with the above run. For reference, the problematic ones occurred on Tuesday 9th May so the equivalent test will happen tonight.

**Comment by sxa** [comment]
So it ran ok last night with the exception of [sanity.system](https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.system_x86-64_linux/39/console) which failed a couple of the suites, but it doesn't look like the same connection issue that this description is about:

```
05:29:38  FAILED test targets:
05:29:38  	ClassLoadingTest_5m_0 
05:29:38  	ClassLoadingTest_5m_1 
```
Some debug from earlier:
```
04:28:40  CLT Test failed:
04:28:40  CLT java.lang.ClassNotFoundException: Failed to find Class: java.lang.Compilerjava.lang.ClassNotFoundException: java.lang.Compiler
04:28:40  CLT 	at net.adoptopenjdk.test.classloading.ClassHog.run(ClassHog.java:87)
04:28:40  CLT 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
04:28:40  CLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
04:28:40  CLT 	at net.adoptopenjdk.loadTest.adaptors.ArbitraryJavaAdaptor.executeTest(ArbitraryJavaAdaptor.java:102)
04:28:40  CLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
04:28:40  CLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
04:28:40  CLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
04:28:40  CLT 	at java.base/java.lang.Thread.run(Thread.java:1583)
04:28:40  CLT <<<
```

**Comment by sxa** [comment]
> wondering if it's a day of week thing

That's why I wanted to see it last night which matches the previous failure (Tuesday morning) and it passed overnight this week, so it doesn't seem to be directly related to that on every Tuesday.

**Comment by sxa** [comment]
Note that the sanity.system failure is unrelated and has been failing since April 8th: https://trss.adoptium.net/deepHistory?testId=64606a1717052c6715315b68

**Comment by adamfarley** [comment]
Not that I've seen. Andrew?

**Comment by andrew-m-leonard** [comment]
no, not seen any recently, but not been looking recently

**Comment by sxa** [comment]
Sine it's now over six months on from the last conversation where we hadn't noticed any, I'm going to assume this is no longer a problem and close it.

**Comment by adamfarley** [comment]
Fair. If we see something like this again, I'll put it into the networking issue.
