### ISSUE TITLE
Docker on SLES12?

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3057]
ref our docker ansible role for SLES12 https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Docker/tasks/sles.yml

We add the docker repos for SLES12 on any architecture, but we install docker only on x64. 

@sxa Do we require docker on SLES12 s390x?

**Comment by sxa** [comment]
Can it be installed and used for the tests that require it? I'd say it's not critical that we have it, but ultimately the decision should come down to whether it can be installed on those systems and is usable.

**Comment by Haroon-Khel** [comment]
Can't seem to install `container-selinux` which is a dependency for `docker-ce`
```
test-marist-sles15-s390x-2:~ # zypper install docker-ce
Refreshing service 'SMT-http_lxslsmt'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...
Problem: nothing provides 'container-selinux' needed by the to be installed docker-ce-3:23.0.3-1.s390x
 Solution 1: do not install docker-ce-3:23.0.3-1.s390x
 Solution 2: break docker-ce-3:23.0.3-1.s390x by ignoring some of its dependencies
```

**Comment by Haroon-Khel** [comment]
It can install on sles15 by adding the `https://download.opensuse.org/repositories/security:SELinux/SLE_15_SP3/security:SELinux.repo` repo

**Comment by Haroon-Khel** [comment]
I can't find anything by googling, but I would assume installing docker on the sles12 box using container-selinux from a sles15 repo would cause issues?

**Comment by sxa** [comment]
I would expect so, so let's not do it on 12

**Comment by Haroon-Khel** [comment]
I'll put the changes into the playbook
