### ISSUE TITLE
build-osuosl-ubuntu2204-aarch64-1: No space left on device

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3070]
build-osuosl-ubuntu2204-aarch64-1 ran out of disc space during a test as seen [here](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_aarch64_linux_testList_0/13/console).

Please investigate. Thank you. :)

**Comment by sxa** [comment]
There is 17Gb used in `/tmp`, mostly from eight `dst*.dat` files chewing 2.1Gb eachdated March 5, March 12 and April 19th so presumably the last one has blown the limit. Although it's not immediately clear where the rest of the 80Gb of space on that machine might have gone ...

**Comment by sxa** [comment]
Cleared up some of the `dst*dat` files, docker has about 44Gb in use, although I suspect a lot of that can be cleared up - I've done an initial prune to get rid of 13Gb of build cache, although we have a variety of build images on there which are chewing up quite a bit. I'll remove the test tags from this system. 35Gb now available.

The host seems to have one docker container on it although it's not currently got an agent running in it. @Haroon-Khel Do you know what the state of this system is just now - it's got the build tags disabled on it but has been enabled for test despite its name? It looks like we had https://github.com/adoptium/infrastructure/issues/2808 which concluded it was ok for running tests but we should revisit the state of this system to see if it makes sense to get it enabled for build, test, or as a host for a test container.

**Comment by steelhead31** [comment]
Closing as disk space issue has been resolved.
