### ISSUE TITLE
Update Ant version to 1.10.14

### ISSUE THREAD

**Issue by karianna** [adoptium/infrastructure#3074]
> Ant version

I would suggest that we put the security checks in place and then discuss that as a separate issue. I'd want there to be additional testing on a new ant version in order to ensure we don't have compatibility issues before just bumping it up (especially sine this PR is specific to Windows and we use the same fixed version across all platforms IIRC) - perhaps create a new issue proposing an upgrade? It's probably about time we did look at that.

`ant` is critical to the test case executions and also now for the SBOM generation.

_Originally posted by @sxa in https://github.com/adoptium/infrastructure/issues/3018#issuecomment-1556909641_

**Comment by sxa** [comment]
@smlambert @andrew-m-leonard What are your thoughts on this? Changing the version could obviously introduce behaviour differences (albeit low risk). Have newer versions been tested with the AQA/TC suites and SBOM generation processes?

**Comment by andrew-m-leonard** [comment]
Would seem sensible, i've not tested anything new though

**Comment by sxa** [comment]
This has resurfaced as a question after [I queried that we'd updated it in the Fedora static docker images](https://github.com/adoptium/infrastructure/pull/3694#pullrequestreview-2221690877).
The fact we've been using 1.10.12 on some of them already suggests that an upgrade is likely quite safe.
I believe that ant on the machines is used for the SBoM generation and the test suites.

@smlambert Would you have any concerns related to moving up to 1.10.12 or the latest one in light of the fact we've already bumped to 1.10.12 in some cases. 1.10.14 is the latest.

@andrew-m-leonard We should likelly verify that later versions do not break the SBoM generation too before switching over. If a playbook change is made here then the build process will be first to see it.

If we do this we should also consider whether to switch existing installations up or leave them as-is.

**Comment by smlambert** [comment]
> Would you have any concerns related to moving up to 1.10.12 or the latest one in light of the fact we've already bumped to 1.10.12 in some cases. 1.10.14 is the latest.

Bumping to newer or latest is likely fine, we should verify that test pipelines still function as expected before delivering the change broadly.

**Comment by sxa** [comment]
@Haroon-Khel - do you think you can look at trialling this for an AQA_Test_Pipeline on a static docker container with the latest ant release? If that works we can bump it in all the static dockerfiles for new machines (I don't mind too much if older ones are left as-is) then we can also look at making sure the build+SBoM generation work with an updated version before changing it in the playbooks.

**Comment by sxa** [comment]
Verified that the SBoM generation in a build of jdk21u on Linux/aarch64 is fine with ant 1.10.14 (released yesterday), so this should be good from a build perspective, so it just needs to be verified for test.

**Comment by sxa** [comment]
@Haroon-Khel Can you take a look at these AIX runs please? Not sure if ant-contrib is missing, or if it's related to the recent PATH changes or some other upstream change in TKG:
- [JDK11 extended/system](https://ci.adoptium.net/job/Test_openjdk11_hs_extended.system_ppc64_aix/483/consoleText) on [test-osuosl-aix72-ppc64-3](https://ci.adoptium.net/computer/test%2Dosuosl%2Daix72%2Dppc64%2D3)
- JDk11 extended/functional](https://ci.adoptium.net/job/Test_openjdk11_hs_extended.functional_ppc64_aix/427/consoleText] on [test-osuosl-aix72-ppc64-4](https://ci.adoptium.net/computer/test%2Dosuosl%2Daix72%2Dppc64%2D4/)

**Comment by Haroon-Khel** [comment]
Not sure how I missed ant-contrib.jar on some of those machines, but it is now on those machines. Ill respin those test jobs
