### ISSUE TITLE
System unavailable: https://ci.adoptium.net/job/centos7_docker_image_updater/

### ISSUE THREAD

**Issue by pshipton** [adoptium/infrastructure#3083]
I noticed the docker images at https://hub.docker.com/r/adoptopenjdk/centos7_build_image/tags hadn't been updated in 3 months (since 5th March), even though I had made the change https://github.com/adoptium/infrastructure/pull/3014 in April. @sxa started a build of https://ci.adoptium.net/job/centos7_docker_image_updater/ and now I see the latest docker image contains perl-IPC-cmd as expected. This issue is to investigate why the updater isn't being run when infra changes are made.

**Comment by sxa** [comment]
Seems to be working now and it has triggered five times in the last two days so this can be closed ... for now.
