### ISSUE TITLE
System unavailable: /tmp appears inaccessible on test-osuosl-aix72-ppc64-2

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3089]
- Please put the system name in the title of this issue.

- Link to any log file showing the problem:
https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk20u/job/jdk20u-aix-ppc64-temurin/22/consoleFull

- Please describe the issue:
```
00:30:59  find: 0652-081 cannot change directory to </tmp/.workdir.14090694.20250938_1>:
00:30:59    : The file access permissions do not allow the specified action.
00:30:59  find: 0652-081 cannot change directory to </tmp/.workdir.19202390.15073570_1>:
00:30:59    : The file access permissions do not allow the specified action.
00:30:59  find: 0652-081 cannot change directory to </tmp/BES/ClientUI>:
00:30:59    : The file access permissions do not allow the specified action.
etc etc etc
```

Please check if there's something wrong with /tmp on this machine. Thank you.

**Comment by sxa** [comment]
The messages described above are not a failure. `/tmp` is a file system for use by anyone and it has files in it which are not accessible to all users, so if you run something that tries to scan and descend into all directories it will likely give you access failures.

**Comment by sxa** [comment]
Looking further down it looks like this is the issue you've got https://github.com/adoptium/temurin-build/pull/3383 in to fix:

```
00:35:14  Generating runnable configure script at /home/jenkins/workspace/build-scripts/jobs/jdk20u/jdk20u-aix-ppc64-temurin/workspace/build/src/build/.configure-support/generated-configure.sh
00:35:14  Using autoconf at /opt/freeware/bin/autoconf [autoconf (GNU Autoconf) 2.69]
00:35:21  configure: error: unrecognized options: --with-extra-cflags-qnotimestamp, --with-extra-cxxflags-qnotimestamp
00:35:21  configure exiting with result code 1
00:35:21  Error: No configurations found for /home/jenkins/workspace/build-scripts/jobs/jdk20u/jdk20u-aix-ppc64-temurin/workspace/build/src.
00:35:21  Please run 'bash configure' to create a configuration.
00:35:21  
00:35:21  /home/jenkins/workspace/build-scripts/jobs/jdk20u/jdk20u-aix-ppc64-temurin/workspace/build/src/make/Init.gmk:124: *** Cannot continue.  Stop.
```

**Comment by aixtools** [comment]
I guess you mean - for simple folk like me - that #3383 fixes this. ?

**Comment by sxa** [comment]
> I guess you mean - for simple folk like me - that #3383 (above) fixes this. ?

"Probably" ... I certainly wouldn't worry about looking into it more until 3383 is merged and tested to see if there is still a problem.
