### ISSUE TITLE
Setup of new build Windows 2022 machine

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3091]
Using this issue to document the progress of the setup of win2022x64-adopt-bld-1 (will probably rename this to build-ibmcloud-win2022-x64-1)

**Comment by Haroon-Khel** [comment]
Currently unreachable due to a possible firewall issue. Is being looked at

**Comment by Haroon-Khel** [comment]
```
TASK [MSVS_2013 : Transfer VS2013_COMMUNITY_LOCAL_MEDIA] ***********************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [52.118.206.11]: FAILED! => {"changed": false, "dest": "C:\\TEMP\\VS2013_CE_MEDIA.zip", "msg": "Could not find or access '/Vendor_Files/windows/VS2013_CE_MEDIA.zip' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option", "src": "/Vendor_Files/windows/VS2013_CE_MEDIA.zip"}
```

**Comment by Haroon-Khel** [comment]
```
TASK [MSVS_2019 : Exit With Error When No Layout Within AdoptOpenJDK] **********************************************************************************************************************************************
fatal: [52.118.206.11]: FAILED! => {"changed": false, "msg": "The VS2019 Layout File Appears To Be Missing From Vendor_Files"}
```

**Comment by Haroon-Khel** [comment]
As of now I have been setting this machine up from my macbook which does not have the required vendor files, hence I have skipped the MSVS 2013 and 2019 tasks. Once this machine gets added to [inventory.yml](https://github.com/adoptium/infrastructure/blob/master/ansible/inventory.yml) I can execute the playbooks from awx which should have the required vendor files

**Comment by gdams** [comment]
@Haroon-Khel just checking, did you successfully manage to use the [Jenkins Service Installation role](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Jenkins_Service_Installation)? I didn't see the secret pushed to the secrets repo

**Comment by Haroon-Khel** [comment]
I used the method of defining `jenkins_secret` as an environment variable , the role worked fine

**Comment by Haroon-Khel** [comment]
2013 compiler installed. The 2019 compiler did not install, my suspicion is C drive ran out of space. Ive cleared some space by removing the [2019 layout file](https://github.com/adoptium/infrastructure/blob/348b26cbc5914a1936e8b2cac89df822923e029f/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/MSVS_2019/tasks/main.yml#L21) (I assume it is no longer needed after its use in the playbook) and am reinstalling the 2019 compiler

**Comment by AdamBrousseau** [comment]
>my suspicion is C drive ran out of space.

C drive should be 250GB. If it's not, you may have to do something to increase it because the space is allocated on the cloud side.

**Comment by Haroon-Khel** [comment]
Setup complete https://ci.adoptium.net/computer/build-ibmcloud-win2022-x64-1/
