### ISSUE TITLE
Unix Playbook Fails When Attempting To Download Maven

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#3097]
It appears apache have archived the 3.6.3 download of maven, this URL:

[https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz](https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz)

Should now be:

https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz

**Comment by sxa** [comment]
Good to see VPC working again - it was all over the place when I was trying to run it at the end of last week :-)

**Comment by steelhead31** [comment]
> Good to see VPC working again - it was all over the place when I was trying to run it at the end of last week :-)

Yup, there's a couple of issues with a platform or two (Solaris and Ubuntu 22.04).. if I get a chance, I'll see if I can get those 2 working again this week.
