### ISSUE TITLE
build-azure-win2012r2-x64-2 fails to delete old workspace

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3099]
Please set the title to indicate the test name and machine name where known.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
extended.openjdk
- a link into recent `Test_` job on https://ci.adoptium.net which showed the failure
https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2/95/console
- **Hyperlink** to re-run in Grinder: 
https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2/95/rebuild
- Is there an existing issue elsewhere covering this?
https://github.com/adoptium/temurin-build/issues/3389#issuecomment-1587266403
- Which machine(s) does it work on?
All other machines, as far as I can tell.
- Which machine(s) does it fail on?
build-azure-win2012r2-x64-2

Any other details:

Error message:
```
ERROR: Cannot delete workspace :Unable to delete 'J:\jenkins\workspace\Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2\openjdkbinary\j2sdk-image\lib\modules'.
```

Likely a lingering process is preventing file deletion. Please restart the machine, and the next test that runs on it should clean up.

**Comment by steelhead31** [comment]
Rogue process killed, which has allowed the directories to be removed.  I've also rebooted the machine to allow some windows updates to complete.

**Comment by adamfarley** [comment]
Thanks Scott! :smile:
