### ISSUE TITLE
Ansible request for: Missing Endian.h on build-osuosl-aix72-ppc64-1

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3100]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

Delete as appropriate from this list:

- Missing install

Details:
An AIX build of JDK21 ([link](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21/job/jdk21-aix-ppc64-temurin/3/consoleFull)) has failed to find endian.h on build-osuosl-aix72-ppc64-1. 

endian.h appears to be the file that indicates the endian-ness of the system, and also provides conversion tooling (turning big-endian data into little-endian, and visa-versa).

Ansible playbook omission/bug perhaps? Requesting investigation.

**Comment by sxa** [comment]
Is this a new requirement in the codebase? (Seems plausible sine it's It may be that it's a file which simply isn't available on AIX.

**Comment by sxa** [comment]
Upstream issue - should be fixed for next build: https://bugs.openjdk.org/browse/JDK-8309703

**Comment by sxa** [comment]
Build -6 passed: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21/job/jdk21-aix-ppc64-temurin/6/
```
01:22:49  openjdk version "21-beta" 2023-09-19
01:22:49  OpenJDK Runtime Environment Temurin-21+26-202306142334 (build 21-beta+26-202306142334)
01:22:49  OpenJDK 64-Bit Server VM Temurin-21+26-202306142334 (build 21-beta+26-202306142334, mixed mode)
```
