### ISSUE TITLE
Ansible request for: awk command not found on test-docker-sles15-s390x-1

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3102]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

Delete as appropriate from this list:

- Missing install

Details:

As you can see [here](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21/job/jdk21-linux-s390x-temurin_SmokeTests/3/console), an awk command fails because the command cannot be found. 

Here is the full error:

```
00:54:23  + awk '{print $9}'
00:54:23  /home/jenkins/workspace/build-scripts/jobs/jdk21/jdk21-linux-s390x-temurin_SmokeTests@tmp/durable-abb65f25/script.sh: line 1: awk: command not found
```

Could this be a playbook omission/bug?

**Comment by Haroon-Khel** [comment]
Ive fixed this just now as a fix for this issue https://github.com/adoptium/infrastructure/issues/3026#issuecomment-1589281911

**Comment by adamfarley** [comment]
Thanks Haroon! 😃
