### ISSUE TITLE
Win2019 Playbook Check fails at MSVS2017 install

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3106]
The MSVS_2017 role fails to register the compiler files during the win2019 pr check

Latest failure https://github.com/adoptium/infrastructure/actions/runs/5311897200/jobs/9615704927?pr=3105

```
TASK [MSVS_2017 : Register Visual Studio Community 2017 DIA SDK shared libraries] ***
failed: [127.0.0.1] (item=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\DIA SDK\bin\msdia140.dll) => {"ansible_loop_var": "item", "changed": true, "cmd": "regsvr32 /s \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\DIA SDK\\bin\\msdia140.dll\"", "delta": "0:00:00.153459", "end": "2023-06-19 12:49:26.706224", "item": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\DIA SDK\\bin\\msdia140.dll", "msg": "non-zero return code", "rc": 3, "start": "2023-06-19 12:49:26.552765", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
failed: [127.0.0.1] (item=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\DIA SDK\bin\amd64\msdia140.dll) => {"ansible_loop_var": "item", "changed": true, "cmd": "regsvr32 /s \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\DIA SDK\\bin\\amd64\\msdia140.dll\"", "delta": "0:00:00.062899", "end": "2023-06-19 12:49:28.031979", "item": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\DIA SDK\\bin\\amd64\\msdia140.dll", "msg": "non-zero return code", "rc": 3, "start": "2023-06-19 12:49:27.969080", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

My guess is that the install of the compiler does not succeed completely despite ansible saying its `changed`
```
TASK [MSVS_2017 : Install Visual Studio Community 2017] ************************
changed: [127.0.0.1]
```
I saw something like this during the setup of the new 2022 windows build machine https://github.com/adoptium/infrastructure/issues/3091. Ansible returned `changed` during the install of the 2019 compiler yet the files were not present in C:\Program Files (x86)\Microsoft Visual Studio\2019. The install did not succeed due to the machine running out of space and then caused the following register task to fail in this same way as this issue

**Comment by steelhead31** [comment]
```
I've spent some time debugging through this, and have found that the 2 DLLs that need to be registered aren't being installed, I suspect the installation of VS2017 is not completing on this Github runner ( despite it working on 2019, and other machines.. )

TASK [MSVS_2017 : Download Visual Studio Community 2017] ***********************
371changed: [127.0.0.1]
372TASK [MSVS_2017 : Install Visual Studio Community 2017] ************************
374changed: [127.0.0.1]
375TASK [MSVS_2017 : Test if VS 2017 DLL 1 is installed] **************************
377ok: [127.0.0.1]
378TASK [MSVS_2017 : Test if VS 2017 DLL 2 is installed] **************************
380ok: [127.0.0.1]
381TASK [MSVS_2017 : Register Visual Studio Community 2017 DIA SDK shared libraries] ***
382skipping: [127.0.0.1] => (item=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\DIA SDK\bin\msdia140.dll)
383skipping: [127.0.0.1] => (item=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\DIA SDK\bin\amd64\msdia140.dll)
```

**Comment by steelhead31** [comment]
I've done a lot of investigation, and discovered that the Github Windows 2022 runner, now contains VS2022 by default, I've not been able to install VS2017 once VS2022 is already installed. I propose to skip the installation of VS2017 on the windows 2022 runners.

**Comment by steelhead31** [comment]
Also propose the inclusion of an additional check to run via vagrant on a windows 2022 server.

**Comment by steelhead31** [comment]
I believe the installation of VS2017 is now passing ( as per the Github actions on this PR https://github.com/adoptium/infrastructure/actions/runs/6123694305/job/16622122766?pr=3172 )... however with the addition of VS2022, I believe the standard github runners are not large enough to allow the download & unzip of the >10Gb zip file ( even before the installation )

**Comment by steelhead31** [comment]
Closing this, as the MSVS_2017 install is now passing
