### ISSUE TITLE
Nagios monitoring request for jenkins server

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3107]
In addition to monitoring the `/` file system on the jenkins server we should monitor the following:
- `/home/jenkins/.jenkins/jobs`
- `/home/jenkins/.jenkins/workspace`
- `/mnt/backup-server`

**Comment by steelhead31** [comment]
Added these checks to the production nagios server, ( [https://nagios.adoptopenjdk.net/nagios/cgi-bin/status.cgi?host=Jenkins-hetzner-ubuntu2004-x64-1](https://nagios.adoptopenjdk.net/nagios/cgi-bin/status.cgi?host=Jenkins-hetzner-ubuntu2004-x64-1) ) , however Im going to also reflect these changes into the nagios configuration playbook.
