### ISSUE TITLE
Various windows playbook errors

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3123]
Now that automated windows playbook deployment is setup via AWX, we can find all the bugs in our playbooks alot quicker than before :)

Fixed ✅ Affects test-azure-win2012r2-x64-3
https://github.com/adoptium/infrastructure/blob/9c7b1e1d26395098459dbcc7e5e54cc6e1d5f9a4/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/WMF_5.1/tasks/main.yml#L24
```
FAILED! => {"changed": false, "msg": "failed to run expand.exe C:\\temp\\WMFinstaller.msu 
C:\\Users\\adoptopenjdk\\AppData\\Local\\Temp\\44e08ea9-494f-4ea4-b61e-765587cef97c -F:*: expand: unknown option -- F", 
"reboot_required": false
```

Fixed ✅ Affects build-ibmcloud-win2012r2-x64-2
https://github.com/adoptium/infrastructure/blob/9c7b1e1d26395098459dbcc7e5e54cc6e1d5f9a4/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/7-Zip/tasks/main.yml#L7
```
7-Zip : Download 7-Zip
FAILED! => {"changed": false, "dest": "C:\\temp\\7z.exe", "elapsed": 0.0670207, "msg": "Error when requesting 'Last-Modified'
 date from 'https://www.7-zip.org/a/7z2201-x64.exe'. The remote name could not be resolved: 'www.7-zip.org'", "status_code": 
null, "url": "https://www.7-zip.org/a/7z2201-x64.exe"
```

Fixed ✅ Affects build-ibmcloud-win2012r2-x64-1 build-azure-win2012r2-x64-1 test-ibmcloud-win2012r2-x64-1 test-ibmcloud-win2012r2-x64-2
https://github.com/adoptium/infrastructure/blob/9c7b1e1d26395098459dbcc7e5e54cc6e1d5f9a4/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Rust/tasks/main.yml#L12
```
Rust : Download Rust installer
FAILED! => {"changed": false, "dest": "C:\\temp\\rust.msi", "elapsed": 0.1219919, "msg": "Error downloading 'https://static.rust-
lang.org/dist/rust-1.33.0-x86_64-pc-windows-msvc.msi' to 'C:\\temp\\rust.msi': The request was aborted: Could not create 
SSL/TLS secure channel.", "status_code": null, "url": "https://static.rust-lang.org/dist/rust-1.33.0-x86_64-pc-windows-msvc.msi
```

Fixed ✅ Affects test-azure-win11-aarch64-1 and -2
https://github.com/adoptium/infrastructure/blob/9c7b1e1d26395098459dbcc7e5e54cc6e1d5f9a4/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/NSClient/tasks/main.yml#L32
```
NSClient : Install NSClient 
FAILED! => {"changed": false, "msg": "the file at the path 'C:\\temp\\nscp.msi' cannot be reached", "reboot_required": false}
```

**Comment by sxa** [comment]
Moving to after the release cycle, when this should be a priority if any of the original issues are outstanding.

**Comment by Haroon-Khel** [comment]
https://github.com/adoptium/infrastructure/pull/3244 This fixes an issue where the msvs2019 install part of the playbook tries to get the sha checksum of a msvs2019 file that isnt there (because it is already installed)

**Comment by Haroon-Khel** [comment]
The WMF 5.1 install error affecting test-azure-win2012r2-x64-3 is resolved. Required a manual installation of powershell 5 on the machine

**Comment by Haroon-Khel** [comment]
The NSclient installation errors affecting the win aarch machines were fixed by https://github.com/adoptium/infrastructure/pull/3154
