### ISSUE TITLE
Extended.system fails on build-azure-win2012r2-x64-2 due to a read-only file system

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3124]
Please set the title to indicate the test name and machine name where known.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
extended.system (specifically DBBLoadTest_5m_0)
- a link into recent `Test_` job on https://ci.adoptium.net which showed the failure
https://ci.adoptium.net/job/Test_openjdk11_hs_extended.system_x86-32_windows/418/consoleFull
- **Hyperlink** to re-run in Grinder: 
[Link](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=DBBLoadTest_5m_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-32_windows&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v0.9.8-release&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=11&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk11u&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk11u%2Fjdk11u-release-windows-x86-32-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-11.0.20%2B6_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=9&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)
- Is there an existing issue elsewhere covering this?
No.
- Which machine(s) does it work on?
All the other machines.
- Which machine(s) does it fail on?
build-azure-win2012r2-x64-2

Any other details:
```
11:17:01        1 [main] sh 1454 dofork: child -1 - CreateProcessW failed for 'C:\cygwin64\bin\sh.exe', errno 30
11:17:01  /bin/sh: /cygdrive/c/Strawberry/perl/bin/perl: Read-only file system
11:17:01  /bin/sh: fork: Read-only file system
11:17:01  make[4]: *** [autoGen.mk:191: DBBLoadTest_5m_0] Error 254
```
Also, ConcurrentLoadTest_5m_2 ran and failed due to a SIGTERM(15) prior to the execution of DBBLoadTest_5m_0, so you may want to run both targets (in that order) to verify any fix.

**Comment by sxa** [comment]
I've knocked this machine offline as we're likely to replace it with a win2022 system soon :-)

**Comment by smlambert** [comment]
Also seen in other jobs:
https://ci.adoptium.net/job/Test_openjdk17_hs_sanity.openjdk_x86-64_windows/316/console

**Comment by smlambert** [comment]
https://ci.adoptium.net/job/Test_openjdk17_hs_extended.system_x86-64_windows/314/
running on 
[test-azure-win2012r2-x64-3](https://ci.adoptium.net/computer/test-azure-win2012r2-x64-3)

**Comment by steelhead31** [comment]
Tests now running clean on [test-azure-win2012r2-x64-1  as seen in this run](https://ci.adoptium.net/computer/test-azure-win2012r2-x64-1) [https://ci.adoptium.net/job/Test_openjdk17_hs_extended.system_x86-64_windows/320/](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.system_x86-64_windows/320/)

We should probably look to replace one or both of the test-azure-win2012 boxes with test-azure-win2022 machines.

**Comment by adamfarley** [comment]
Thanks Scott! :)
