### ISSUE TITLE
Requesting edit access to adoptium/adoptium for adamfarley

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3137]
I'm working on the release checklist with Stewart, and I'm asking to be given the right permissions to let me edit the release checklist in https://github.com/adoptium/adoptium/issues/238

Also, can I have permissions to edit issue properties? I raise issues (e.g. retrospectives) in adoptium/adoptium, and I'd like to be able to claim ownership without having to ask.

**Comment by adamfarley** [comment]
I'm told this isn't possible, as you need to be a project lead (and I am not). Closing.

**Comment by sxa** [comment]
I've looked at this again after some extra information came to light and it looks like you're not a member of the top level adoptium project, only the temurin sub-project, so we probably can resolve this. Re-opening.

**Comment by sxa** [comment]
This was discussed on the latest PMC meeting where it was agreed that we should create a `adoptium/temurin` repository within the temurin project where we would store the status issues.

**Comment by sxa** [comment]
We have created a new repository at https://github.com/adoptium/temurin which has access for all Temurin committers and should be used for all subsequent releases.

**Comment by adamfarley** [comment]
Thanks Stewart! :)
