### ISSUE TITLE
Add DNF installation steps to AIX playbook for AIX7.3

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3149]
ref https://github.com/adoptium/infrastructure/issues/3142

Error when using Yum on an AIX 7.3 machine
```
root@adopt01:[/root]yum --version
There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:

   No module named rpm

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
2.7.10 (default, Jun 22 2016, 05:57:59) [C]

If you cannot solve this problem yourself, please go to 
the yum faq at:
  http://yum.baseurl.org/wiki/Faq
```

The thread in https://community.ibm.com/community/user/power/discussion/yum-broken-after-aix-73-upgrade suggests yum is not supported for AIX7.3. and dnf is recommended. The steps to install dnf are here https://community.ibm.com/community/user/power/blogs/sangamesh-mallayya1/2021/05/28/dnf-is-now-available-on-aix-toolbox?CommunityKey=10c1d831-47ee-4d92-a138-b03f7896f7c9&tab=recentcommunityblogsdashboard

I installed dnf onto https://ci.adoptium.net/computer/test-osuosl-aix73-ppc64-1/, it installed without error and the packages updated without error. 

The install steps need to be added to the AIX playbook for 7.3 machines

**Comment by aixtools** [comment]
Actually, I would prefer to see the steps used for both AIX 7.2 and 7.3 - and forget settings specific for AIX 7.1 - as unsupported.

In short, only use dnf.

And, if possible, continue to download the files the "dnf.sh" aka "yum.sh" downloaded using ftp, expect, etc..

- ignore comment above if you have already written it that way. (I haven't looked yet).

**Comment by aixtools** [comment]
Remember - a big difference between AIX 7.2 and 7.3 is that 7.3 has 'native' Python 3.9 (or later). Ideally, the dnf package will (eventually) use the native Python, rather than a Python for dnf. That will only confuse projects re: which Python to use - imho: native Python on AIX 7.3.

**Comment by sxa** [comment]
@Haroon-Khel I believe this is complete now so can be closed? So the only thing left related to this is to resolve the problems on the new AIX 7.3 system? https://github.com/adoptium/infrastructure/issues/3142
