### ISSUE TITLE
test-packet-ubuntu1604-x64-1 failure - /usr/bin/dockerd (deleted) 

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#315]
This issue has happened previously (see infra issue #145) -  /usr/bin/dockerd (deleted) 
This is causing Docker-based tests to fail (see [openjdk8_hs_externaltest_x86-64_linux/52](https://ci.adoptopenjdk.net/view/External%20tests/job/openjdk8_hs_externaltest_x86-64_linux/52/console))

Comment from previous infra issue: 
"Apparently the error fork/exec /usr/bin/dockerd (deleted): no such file or directory can be caused by something deleting and recreating /usr/bin/dockerd whilst it's still running, so that the inode of /usr/bin/dockerd doesn't match the inode of the existing dockerd process."

The quick fix is to restart Docker on the machine.  

The longer term solution is to correct the Ansible scripts to restart Docker after an update occurs (or some similar approach).

**Comment by smlambert** [comment]
Whenever we happen to land on this machine to run the app / thirdparty_container tests (aka external tests), they fail:
OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 0 caused \\\"fork/exec /usr/bin/dockerd (deleted): no such file or directory\\\"\"": unknown

Again last night:
https://ci.adoptopenjdk.net/view/External%20tests/job/openjdk8_hs_externaltest_x86-64_linux/60/console

**Comment by pnstanton** [comment]
Same issue as before, dockerd has been running since February 22nd, docker package was updated on March 2nd. Someone did an upgrade recently as I can see `apt-get update && apt-get upgrade -y` in root's command line history. 
I'll bring it up at the next infrastructure hangout.
I've restarted the docker service.

**Comment by smlambert** [comment]
thanks @pnstanton !

**Comment by sxa555** [comment]
Recurred in https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk-9-ev3-test/ job 29 - same machine. Reopening

**Comment by sxa555** [comment]
Issues `service docker restart` and seems a bit happier again ... for now.

**Comment by sxa555** [comment]
I'm going to reopen this to do a proper fix - detect if `docker-ce` has been updated in the nightly updates and if so restart it

**Comment by karianna** [comment]
Kalyan is going to pick this one up.

**Comment by sxa** [comment]
@karianna For the purposes of anyone reading this issue, I assume Kalyan is not working this issue so it is awaiting someone else to pick it up now?

**Comment by karianna** [comment]
Yeah, that's fair - he hopes to come back in a break from his studies.

**Comment by sxa** [comment]
I'm going to close this for now as we have not seen any problems related to this for a while, and it can be reopened if it recurs
