### ISSUE TITLE
Improve Windows GitHub Action / Vagrant / Playbook - Ansible Script Dependency

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#3157]
As per this issue (#3155) which fixed an issue whereby the URL for the ConfigureRemotingForAnsible.ps1 scripts URL has changed and required updating, it was noted that we should tie the downloading of this script to a specific SHA and if necessary validate the download to match a checksum, to harden the process and improve security.

**Comment by profhenry** [comment]
Ping
