### ISSUE TITLE
Ansible request for `automake` on macos

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3167]
Please put the name of the software product (and affected platforms if relevant) in the title of this issue

Delete as appropriate from this list:

- Missing install

Details:
The setup of the build on macos (at least for JDK8) fails if automake is missing:
```
test-macincloud-macos1201-x64-1:freetype jenkins$ ./autogen.sh 
./autogen.sh: line 102: aclocal: command not found
./autogen.sh: line 55: test: 1: unary operator expected
./autogen.sh: line 59: test: 1: unary operator expected
./autogen.sh: line 67: test: 10: unary operator expected
./autogen.sh: line 71: test: 10: unary operator expected
generating `configure.ac'
running `aclocal -I . --force'
./autogen.sh: line 15: aclocal: command not found
error while running `aclocal -I . --force'
test-macincloud-macos1201-x64-1:freetype jenkins$
```
It looks like this has been installed on the build machines at some point, but is not in the playbooks for new machine installs.

**Comment by Haroon-Khel** [comment]
automake is certainly present on our current macos machines as per https://github.com/adoptium/infrastructure/blame/7d50c49814d9484a57148e52ab00e94ce1efd0b3/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/vars/MacOSX.yml#L10. And we build on orka now so this issue is outdated
