### ISSUE TITLE
test-osuosl-aix72-ppc64-4 fails to create temporary file

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3179]
Please set the title to indicate the test name and machine name where known.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
sanity.system
- a link into recent `Test_` job on https://ci.adoptium.net which showed the failure
https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.system_ppc64_aix/89/consoleFull
- **Hyperlink** to re-run in Grinder: 
[Link.](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.system&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64_aix&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=test-osuosl-aix72-ppc64-4&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk21&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk21%2Fjdk21-aix-ppc64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-21%2B35_adopt&LABEL_ADDITION=sw.os.aix.7_2&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=67&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)
- Is there an existing issue elsewhere covering this?
I did not find one.
- Which machine(s) does it work on?
Not seen elsewhere
- Which machine(s) does it fail on?
test-osuosl-aix72-ppc64-4

Any other details:
```
00:16:40  BUILD FAILED
00:16:40  /home/jenkins/workspace/Test_openjdk21_hs_sanity.system_ppc64_aix/aqa-tests/TKG/scripts/build_test.xml:95: The following error occurred while executing this line:
00:16:40  /home/jenkins/workspace/Test_openjdk21_hs_sanity.system_ppc64_aix/aqa-tests/system/common.xml:367: The following error occurred while executing this line:
00:16:40  /home/jenkins/workspace/Test_openjdk21_hs_sanity.system_ppc64_aix/aqa-tests/system/common.xml:358: The following error occurred while executing this line:
00:16:40  /home/jenkins/workspace/Test_openjdk21_hs_sanity.system_ppc64_aix/aqa-tests/system/aqa-systemtest/openjdk.build/build.xml:59: The following error occurred while executing this line:
00:16:40  /home/jenkins/workspace/Test_openjdk21_hs_sanity.system_ppc64_aix/aqa-tests/system/aqa-systemtest/openjdk.test.nio/build.xml:104: Error creating temporary file
```

Attempting to reproduce [here](https://ci.adoptium.net/job/Grinder/7515/).

**Comment by adamfarley** [comment]
@steelhead31 @aixtools 

Heya, this seems to overlap with a change made to the ansible inventory file back in May: [Link.](https://github.com/adoptium/infrastructure/pull/3053)

Should this machine have been manually removed from Jenkins as a follow-on to the linked PR?

If yes, please remove the machine and clear up the file system on -1 if needed. Thank you. :)

**Comment by aixtools** [comment]
iirc, the correction was to build the systems AND remove the double link. afaik, there is no duplication in the inventory re: osuosl hosted AIX systems.

**Comment by adamfarley** [comment]
Ah, the machines that were removed [here](https://github.com/adoptium/infrastructure/pull/3053) were replaced [here](https://github.com/adoptium/infrastructure/commit/e9c555980680e72a4ecb748d254fec942761ef8f) by different machines that now have the same host names.

**Comment by sxa** [comment]
Need to verify that this is no longer a problem - likely won't fail in the same way again.

**Comment by steelhead31** [comment]
Tests now pass on this machine : https://ci.adoptium.net/job/Grinder/11395/console

**Comment by steelhead31** [comment]
2nd run also passes, so closing, as suspect this has been resolved. https://ci.adoptium.net/job/Grinder/11401/console
