### ISSUE TITLE
Node build-azure-win2022-x64-2 is timing out after 8hours build openjdk

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3186]
Repeated builds of jdk11, jdk17 failed after very slowly building, and were timed out after 8hours, jdk21 got terminated ?:
- https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-temurin/289
- https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-windows-x64-temurin/324
- https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21/job/jdk21-windows-x64-temurin/81/

Is this node an Azure "Burstable" node that has run out of credits?

**Comment by steelhead31** [comment]
Machines switched to non burstable, and rebooted. All builds have now run successfully.
