### ISSUE TITLE
Prune C3Jenkins adoptium mirror workspace of old versions to save space

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3195]
The adoptium mirrors and the older non-Adoptium old mirrors, keep a workspace for each version, we may have workspaces on C3Jenkins for old versions we no longer mirror (jdk-15,16,18,....) ?

To save space these old workspaces can be deleted:
/home/jenkins/.jenkins/workspace/git-mirrors/adoptium/git-skara-jdkNN[u]
```
drwxr-xr-x 5 jenkins ciagent 4096 Jun 23  2022 git-skara-jdk18u
drwxr-xr-x 2 jenkins ciagent 4096 Sep 28  2022 git-skara-jdk18u@tmp
drwxr-xr-x 5 jenkins ciagent 4096 Oct 13  2022 git-skara-jdk19
drwxr-xr-x 2 jenkins ciagent 4096 Oct 13  2022 git-skara-jdk19@tmp
drwxr-xr-x 7 jenkins ciagent 4096 Sep 15 13:41 git-skara-jdk19u
drwxr-xr-x 2 jenkins ciagent 4096 Sep 26 07:41 git-skara-jdk19u@tmp
drwxr-xr-x 7 jenkins ciagent 4096 Mar 10  2023 git-skara-jdk20
drwxr-xr-x 2 jenkins ciagent 4096 Apr  4 14:11 git-skara-jdk20@tmp
drwxr-xr-x 7 jenkins ciagent 4096 Sep 15 13:49 git-skara-jdk20u
drwxr-xr-x 2 jenkins ciagent 4096 Sep 26 07:49 git-skara-jdk20u@tmp
drwxr-xr-x 7 jenkins ciagent 4096 Sep 15 14:08 git-skara-jdk21
drwxr-xr-x 2 jenkins ciagent 4096 Sep 26 08:08 git-skara-jdk21@tmp
```

Also, there are some of the **older** non-Adoptium mirror job output under
/home/jenkins/.jenkins/workspace/git-mirrors : 
```
drwxr-xr-x  6 jenkins ciagent 4096 Sep 16 00:03 git-hg-aarch32-jdk8u
drwxr-xr-x  6 jenkins ciagent 4096 Sep 15 22:01 git-hg-aarch64-jdk8u
drwxr-xr-x  6 jenkins ciagent 4096 Sep 26 08:07 git-hg-freebsd
drwxr-xr-x  7 jenkins ciagent 4096 Sep 15 20:24 git-hg-jdk11u
drwxr-xr-x  7 jenkins ciagent 4096 Sep 15 14:47 git-hg-jdk13u
drwxr-xr-x  6 jenkins ciagent 4096 Sep 15 23:07 git-hg-jdk8u
drwxr-xr-x  7 jenkins ciagent 4096 Sep 15 13:31 git-skara-jdk
drwxr-xr-x  7 jenkins ciagent 4096 Sep 15 14:03 git-skara-jdk14u
drwxr-xr-x  7 jenkins ciagent 4096 Sep 15 14:12 git-skara-jdk15u
drwxr-xr-x  7 jenkins ciagent 4096 Sep 15 14:08 git-skara-jdk16u
```

**Comment by sxa** [comment]
The stuff under `git-mirrors` directly is pretty small - about 5Mb each. I'll clear them up too though along with the others you mentioned.
Sizes below for historic reference:
```
# du -sk git-mirrors/adoptium/* | grep -v tmp
860276	git-mirrors/adoptium/git-skara-aarch32-jdk8u
1626084	git-mirrors/adoptium/git-skara-alpine-jdk8
5556640	git-mirrors/adoptium/git-skara-jdk
1282376	git-mirrors/adoptium/git-skara-jdk11u
1273980	git-mirrors/adoptium/git-skara-jdk11u-fast-startup-incubator
1887216	git-mirrors/adoptium/git-skara-jdk17u
1863968	git-mirrors/adoptium/git-skara-jdk18u
1943972	git-mirrors/adoptium/git-skara-jdk19
1948784	git-mirrors/adoptium/git-skara-jdk19u
1985712	git-mirrors/adoptium/git-skara-jdk20
1990464	git-mirrors/adoptium/git-skara-jdk20u
2065608	git-mirrors/adoptium/git-skara-jdk21
2047192	git-mirrors/adoptium/git-skara-jdk21u
816456	git-mirrors/adoptium/git-skara-jdk8u
```

**Comment by sxa** [comment]
Hmm they all seem to have been updated fairly recently (Most on September 15th) including the ones that aren't in the adoptium directory. Are they definitely not being run? If I delete them and the jobs are still active they'll just be regenerated.

**Comment by andrew-m-leonard** [comment]
> Hmm they all seem to have been updated fairly recently (Most on September 15th) including the ones that aren't in the adoptium directory. Are they definitely not being run? If I delete them and the jobs are still active they'll just be regenerated.

They were still running, and failing..! I disabled them when I discovered them...

**Comment by sxa** [comment]
I've left 21 in place just now in case something odd happens before 21.0.1 but the others have now been cleared - good spot on this one!

**Comment by sxa** [comment]
Pruned workspace/build-scripts-pr-tester/build-test/*@* (i.e. when multiple jobs run in parallel) which cleared another 30Gb or so.
