### ISSUE TITLE
Adoptium Centos 6 docker build image in docker hub not updated since last 9 months

### ISSUE THREAD

**Issue by aswinkr77** [adoptium/infrastructure#3211]
The Adoptium Centos 6 docker build image has not gotten the infrastructure updates for the last 9 months. Looks like something is broken.

https://hub.docker.com/r/adoptopenjdk/centos6_build_image

<img width="1369" alt="centos6" src="https://github.com/adoptium/infrastructure/assets/13417260/2fe590ee-2a68-4c99-84dd-43680d7af358">

**Comment by karianna** [comment]
Adoptopenjdk is no longer supported.  The images you want are for Eclipse Temurin under the Adoptium project.

**Comment by sxa** [comment]
@karianna OP is talking about the images we use for building which are created and stored within the adoptopenjdk repository.
They are the ones referred to in the [infrastructure FAQ](https://github.com/adoptium/infrastructure/blob/master/FAQ.md#what-about-the-builds-that-use-the-dockerbuild-tag) and something within the [github action](https://github.com/adoptium/infrastructure/actions/workflows/build.yml) that produces that particular one is not doing the right thing. The same is true of the Alpine3 x64 image which is built in the same place
```
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
```

**Comment by sxa** [comment]
@gdams As you are more familiar with GitHub actions than many of us, are you able to take a look at this?

**Comment by steelhead31** [comment]
@gdams / @sxa I have a draft PR in #3263, which should work when a PR is merged to docker hub ( this doesn't happen from this process for Alpine, I believe that gets updated via the docker/multiarch process )..   

For Centos6 However it does require authorisation to login to docker hub, and references the variables for these things, but don't believe these are defined.

Any idea how/where we can define these to fix this process, or alternatively, I guess we could keep this action as a check, and move the CentOS6 docker image updater into the multiarch job with the others.

Let me know what your thoughts are.

Thanks!

**Comment by steelhead31** [comment]
Previous logic did not work on push to master.

**Comment by sxa** [comment]
Related: We're having issues pushing the riscv64 image too that was added under https://github.com/adoptium/infrastructure/pull/3240 ... See [slack thread](https://adoptium.slack.com/archives/C53GHCXL4/p1699553550720389)

**Comment by steelhead31** [comment]
This is still an issue, so continuing to investigate... the logic now works correctly on merge, however the credentials required appear to have changed...

```
Logging into Docker Hub...
Error: Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: your account must log in with a Personal Access Token (PAT) - learn more at docs.docker.com/go/access-tokens```
```

**Comment by steelhead31** [comment]
Given that this will be added to the multiarch job as part of PR #3296, I propose to move the github action to not push to dockerhub, as the alpine one already doesn't push, aligning the centos 6 GHA to not push in addition, and effectively only run as a check seems like a good idea.

**Comment by sxa** [comment]
Has this not been resolved as a result of the work done last night?

**Comment by steelhead31** [comment]
> Has this not been resolved as a result of the work done last night?

I dont believe so ( though I will check ) the issue with pushing as part of a github action requires a change to the Github credentials... do you think we still need to push to dockerhub as part of the GHA ?, if so I think I'll need to log an EF infra call to have the credentials that are used by Github Actions updated.

**Comment by sxa** [comment]
> > Has this not been resolved as a result of the work done last night?
> do you think we still need to push to dockerhub as part of the GHA ?

IMHO no (which is why I raised the issue to move it) but others may disagree ...

**Comment by steelhead31** [comment]
I've pinged @netomi to see if he can updated the credentials stored in Github, I'll then pop a PR in to move this to just a simple check, but if the credentials can be updated, it should be simple to switch it back on should it be required.

**Comment by Haroon-Khel** [comment]
> Has this not been resolved as a result of the work done last night?

Yes. Updated last night by the `adoptopenjdkuser` user

https://hub.docker.com/repository/docker/adoptopenjdk/centos6_build_image/tags?page=1&ordering=last_updated

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/job/centos7_docker_image_updater/420/console kicked off due to merging of https://github.com/adoptium/infrastructure/pull/3296

**Comment by Haroon-Khel** [comment]
The centos6 part of the job succeeded https://ci.adoptium.net/job/centos7_docker_image_updater/420/execution/node/244/log/

**Comment by Haroon-Khel** [comment]
This can be closed now that the centos6 image can be updated with the automated user
