### ISSUE TITLE
test-azure-win2016-x64-1 - Out of storage

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3215]
Please set the title to indicate the test name and machine name where known.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
Test_openjdk17_hs_extended.openjdk_x86-64_windows
- a link into recent `Test_` job on https://ci.adoptium.net which showed the failure
https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1/116/console
- **Hyperlink** to re-run in Grinder: 
[Link.](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=-f+parallelList.mk+testList_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk17_hs_extended.openjdk_x86-64_windows&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_windows&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=test-azure-win2016-x64-1&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk17u&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=dev&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=135&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=362&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=15&JVM_OPTIONS=&PARALLEL=None)
- Is there an existing issue elsewhere covering this?
Not that I found.
- Which machine(s) does it work on?
All other machines.
- Which machine(s) does it fail on?
test-azure-win2016-x64-1

Any other details:
```
22:54:34  TEST: jdk/jfr/api/recording/dump/TestDump.java
22:54:34  TEST JDK: D:\jenkins\workspace\Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1\openjdkbinary\j2sdk-image
22:54:34  tee: 'standard output': No space left on device
22:54:34  tee: 'D:/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1/aqa-tests/\TKG\output_1696773622489\TestTargetResult': No space left on device
22:55:24  make[4]: *** [autoGen.mk:437: jdk_jfr_0] Error 1
22:55:24  make[4]: Leaving directory '/cygdrive/d/jenkins/workspace/Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1/aqa-tests/openjdk'
```

Please fix if this issue is still present. Thank you. :)

**Comment by sxa** [comment]
Machine has been deprovisioned - closing
