### ISSUE TITLE
Document schedules used for AWX regular deployments

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3220]
There was a lot of work done to get us to a stage where we are doing regular ansible deployments under https://github.com/adoptium/infrastructure/issues/695 but it doesn't look like we explicitly documented the schedules that we have in progress. We should update
https://github.com/adoptium/infrastructure/wiki/Ansible-AWX#schedules to clarify what the server is running on a regular basis.

It may be useful to reference this information from the FAQ too so it is more easily discoverable. where we have referenced the schedules for [dockerhost patching](https://github.com/adoptium/infrastructure/blob/master/FAQ.md#dockerhost-patching).

Related: https://github.com/adoptium/infrastructure/issues/3218

@Haroon-Khel Since you put most of these in place you're likely to be best placed to make these changes :-)

**Comment by Haroon-Khel** [comment]
Closed as https://github.com/adoptium/infrastructure/pull/3247 is in
