### ISSUE TITLE
release dry run jdk17  got git error message 

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#3223]
linux-x64 on dockerhost-equinix-ubuntu2204-x64-1:

release dry run jdk17 linux-x64 on [dockerhost-equinix-ubuntu2204-x64-1](https://ci.adoptium.net/computer/dockerhost-equinix-ubuntu2204-x64-1) got message `
stderr: fatal: unable to access 'https://github.com/adoptium/ci-jenkins-pipelines.git/': Empty reply from server `
https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-linux-x64-temurin/12/console

**Comment by sophia-guo** [comment]
mac 64: 

```
stderr: fatal: unable to access 'https://github.com/adoptium/ci-jenkins-pipelines.git/': Failed to connect to github.com port 443: Operation timed out
16:59:48  

```

**Comment by sophia-guo** [comment]
windows [build-azure-win2022-x64-2](https://ci.adoptium.net/computer/build-azure-win2022-x64-2)

```
stderr: fatal: unable to access 'https://github.com/adoptium/ci-jenkins-pipelines.git/': Empty reply from server
```

https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-windows-x64-temurin/13/console

**Comment by sophia-guo** [comment]
similar issue with aix,  arm-linux

**Comment by sophia-guo** [comment]
Similar test run https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_1/109/console

**Comment by sophia-guo** [comment]
same for jdk11 arm, windows32, x86-64_alpine, windows

**Comment by sxa** [comment]
@sophia-guo Did these all happen at the same time, and have there been any instances since?

**Comment by sxa** [comment]
Closing since I haven't seen a reply to the previous comment or heard about any instances since, so assumed to be a github glitch on the day.
