### ISSUE TITLE
"Fix" libpng on mac/aarch64 cross-compilation machines

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3231]
Mote details in https://github.com/adoptium/temurin-build/issues/3509 but I'm overloaded today so not replicating the appropriate bits.  We need to determine if libpng is really required and either:

1. Undo the removal of the symlinks mentioned in there on armv8 build machine -2 if required
2. See if there are any problems by removing the x64 brew's libpng and if not do so on both machines.

**Comment by sxa** [comment]
Related slack link: https://adoptium.slack.com/archives/C09NW3L2J/p1693398336324819?thread_ts=1693390210.191789&cid=C09NW3L2J

**Comment by Haroon-Khel** [comment]
Can be closed since https://github.com/adoptium/temurin-build/issues/3509 is closed
