### ISSUE TITLE
Decommision older windows systems

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3238]
Our Windows builds are now all running on Windows Server 2022 systems. Now that 2012 as reached the end of extended support we should decommission those and, if required, replace with later versions.

We should also aim to replace the one Server 2016 machine that we have with a Server 2019 system.

It may make sense to try replacing some of the old server 2012 boxes with Windows 11 systems to cover testing on there too, but that should be evaluated to ensure that the playbooks run on that platform and we dont' get any unexpected issues.

So a phased approach to the machine we no longer want:
- [x] Mark them offline in jenkins
- [x] Run AQA tests on the TC win11 systems in preparation to see if Windows11 is a viable test platform
- [ ] Switch them off
- [x] Create and activate replacement systems in jenkins
- [ ] Delete old ones at the providers

**Comment by steelhead31** [comment]
All Windows TCK machines except one are Windows 11 as per https://ci.eclipse.org/temurin-compliance/computer/

**Comment by steelhead31** [comment]
Currently Running 32 bit tests on Win2022, with WSL disabled

**Comment by steelhead31** [comment]
test-azure-win2022-x64-1 has been commisioned following successful testing.

**Comment by steelhead31** [comment]
test-azure-win2022-x64-2 has been created and is in jenkins : [https://ci.adoptium.net/computer/test%2Dazure%2Dwin2022%2Dx64%2D2/](https://ci.adoptium.net/computer/test%2Dazure%2Dwin2022%2Dx64%2D2/)  
 

Testing of the new node in progress...

**Comment by steelhead31** [comment]
test-azure-win2022-x64-2 has been commisioned following successful testing.

**Comment by steelhead31** [comment]
Powered off:  
[test-azure-win2012r2-x64-1](https://ci.adoptium.net/computer/test%2Dazure%2Dwin2012r2%2Dx64%2D1/) &  [test-azure-win2012r2-x64-3](https://ci.adoptium.net/computer/test%2Dazure%2Dwin2012r2%2Dx64%2D3/)

**Comment by sxa** [comment]
@AdamBrousseau We have four windows server 2012r2 machines defined int eh IBM Cloud - am I right in saying that we can't update / reprovision as 2022 systems ourselves so you would have to manage that for us?

**Comment by AdamBrousseau** [comment]
>I right in saying that we can't update / reprovision as 2022 systems ourselves so you would have to manage that for us?

Correct, I can delete the old ones and provision the new ones for you (not necessarily in that order). Possibly based on a snapshot of an existing one, if that is of interest. It is on my radar as I have to do the ones for the OpenJ9 project as well. I just don't know when that will be as nobody is pushing hard on me for it yet.

**Comment by sxa** [comment]
> Correct, I can delete the old ones and provision the new ones for you (not necessarily in that order). Possibly based on a snapshot of an existing one, if that is of interest. It is on my radar as I have to do the ones for the OpenJ9 project as well. I just don't know when that will be as nobody is pushing hard on me for it yet.

From my perspective we've now shut off all of the win2012 ones from active service so it can be switched over any time. Since this means we're down to only one provider for Windows systems at the moment (Azure) it would be good to get them replaced and verified before the next quarterly release in January. I don't think we have a suitable system to clone at the moment, but it's probably just as easy to give us clean ones and let us fire the Ansible AWX server at them. I'll let @steelhead31 object to that if he wishes ;-)

**Comment by steelhead31** [comment]
Sounds like a plan to me.. :)

**Comment by sxa** [comment]
The IP address `20.108.178.21` (consistent with https://github.com/adoptium/infrastructure/blob/b728c86a1b2fe798c29cae85f7b23e50ff9686fa/ansible/inventory.yml#L45) is repeatedly (once per minute) trying to access it's slave-agent.jnlp in jenkins and receiving a 404. We should stop this or (most likely) fully decommission the machine now.

**Comment by AdamBrousseau** [comment]
I missed the last few comments. Is my understanding correct that I can shutdown all your windows build and test systems that are running win2012? @sxa

**Comment by sxa** [comment]
I'm 99% certain that'll be fine but I suggest we hold off to next week when @steelhead31 is back if that's ok but I believe the intention was to replace them all with something else (potentially a mix of Win2022 and RHEL? Can't recall where we discussed that)

**Comment by AdamBrousseau** [comment]
Likely discussed over slack but I thought the plan was to do 1-1 replacement with win2022's. I'm open to discussion.

**Comment by AdamBrousseau** [comment]
Friendly bump @steelhead31

**Comment by sxa555** [comment]
I think that's reasonable (and I guess this explains why Nagios is showing
formals against the machines!) Will be interesting to see the timings for
Windows systems coming out of my dry ribs tonight for all for releases and
32+64 bit.

For RHEL we should have at least one RHEL9 now I think and the 8 or 9. Will
be good to have more systems using podman by default (although the test
jobs may require some updates - there's an aqa-tests issue about that)

**Comment by sxa** [comment]
Spotted today: The build-azure-win2012-x64-2 machine (as opposed to 2022) is still live and should be decommissioned and removed from the inventory. Also we have some cases where the machine's hostname does not match the name in the inventory/jenkins (May not be easy to change, but just worth being aware of)

**Comment by sxa** [comment]
Noting also that the win2022 build machines still have the [ci.role.test](https://ci.adoptium.net/label/ci.role.test&&sw.os.windows&&hw.arch.x86/) label which we should look at removing to ensure the build machines are dedicated as far as possible (I've just had a build fail to be scheduled because of it) ... Although looking at that list we do seem horribly low on Windows test systems just now ...

**Comment by steelhead31** [comment]
I've stopped (2016 - 172.172.147.29 ) and (2019 - 13.92.177.186 )  both test machines in the public inventory.

However there are 2 other windows machines... ( 2016 - 40.121.207.47 , 2019 - 13.68.197.156 ) still running, that arent in either inventory too.. anybody know what these are for ?

**Comment by steelhead31** [comment]
These 2 windows machines have now been shutdown ( 2016 - 40.121.207.47 , 2019 - 13.68.197.156 )  to potentially identify any issues.

**Comment by sxa** [comment]
I think we're done with this now aren't we @steelhead31? All the old ones have now gone as per our recent tracking spreadsheet.

**Comment by steelhead31** [comment]
Yes, all old windows machines have been decomissioned.
