### ISSUE TITLE
build-ibmcloud-win2022-x64-1 : Unable to remove directory E:\Jenkins\workspace\temp 

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3264]
- Please put the system name in the title of this issue.
build-ibmcloud-win2022-x64-1

- Link to any log file showing the problem: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-temurin/330/console

- Please describe the issue:
Locked files? Unable to remove directory E:\Jenkins\workspace\temp

**Comment by steelhead31** [comment]
Temp directory had an odd set of permissions, meaning even the Admin user couldn't remove.

I have now removed the directory and returned the node to service.
