### ISSUE TITLE
Add steps to install OpenSSL 3 on AIX 7.2 machines

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3274]
ref https://github.com/adoptium/infrastructure/pull/3271#issuecomment-1836115340

Dnf requires openssl 1.1.x while on our 7.2 machines we have 1.0.2t. OpenSSL 3 can be downloaded here https://www.ibm.com/resources/mrs/assets/DownloadList?source=aixbp&lang=en_US

Openssl 3 install steps can be found here https://www.ibm.com/support/pages/downloading-and-installing-or-upgrading-openssl-and-openssh

All thats left is to update the existing [openssl role](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_AIX_Playbook/roles/openssl/tasks/main.yml) to accommodate this new version. It might be best for the `openssl-3.0.10.1000.tar.Z` binary to be in `Vendor_Files` and transferred over when necessary

**Comment by aixtools** [comment]
The problem with vendor_files, imho, is that they are not kept current.

The safe step is to have the playbook verify that a minimal version of OpenSSL is installed - and let the system administration handle resolving it when it does not pass muster.

p.s. putting this here, rather than on the PR.

p.p.s. researching this - and prepping to make the update as system administrator - and not being able to do so due to #1544 only stresses how important it is to take the steps to correct an ancient issue. The problem it causes just keeps recurring.

**Comment by sxa** [comment]
The SSL3 role is failing on the new build72-3 machine:

```
TASK [openssl3 : Transfer openssl binary] **************************************
fatal: [build-osuosl-aix72-ppc64-3]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/root/.ansible/tmp/ansible-tmp-1703709557.6199305-3073340-55459161035460/source\". Make sure the required command to extract the file is installed. Command \"/usr/bin/tar\" detected as tar type None. GNU tar required. Unable to find required 'unzip' or 'zipinfo' binary in the path."}
``

**Comment by Haroon-Khel** [comment]
Update: Ive installed openssl3 manually. Kicked off a playbook run here, https://awx2.adoptopenjdk.net/#/jobs/playbook/2425?job_search=page_size:20;order_by:-finished;not__launch_type:sync, to finish off the setup

**Comment by Haroon-Khel** [comment]
```
TASK [dnf : Fail if python3 is not available] **********************************
fatal: [build-osuosl-aix72-ppc64-3]: FAILED! => {"changed": false, "failed_when_result": true, "stat": {"exists": false}}
```
Fails because it expects python3 to be in /opt/freeware/bin, its in /opt/bin on the machine. Should be fixed to use any python3 it finds. Will install dnf manually in the meantime

**Comment by Haroon-Khel** [comment]
rebuild after manual install of dnf
https://awx2.adoptopenjdk.net/#/jobs/playbook/2427?job_search=page_size:20;order_by:-finished;not__launch_type:sync

**Comment by sxa** [comment]
> rebuild after manual install of dnf https://awx2.adoptopenjdk.net/#/jobs/playbook/2427?job_search=page_size:20;order_by:-finished;not__launch_type:sync

That run failed on GPG signature check of the ant download. I've re-run the job and if it fails we should create an issue and reference it from the issue regarding that machine setup: https://github.com/adoptium/infrastructure/issues/3208

**Comment by Haroon-Khel** [comment]
The machine in question, build-osuosl-aix72-ppc64-3, is having problems with its gpg package. It comes with gpg (GnuPG) 2.4.3 which is giving this error when trying to importing keys

`gpg: keyserver receive failed: No such file or directory`

 I've tried downgrading to a version which the other machines have gnupg2-2.0.30 but Im getting package conflicts

```
root@adopt09:[/root]dnf downgrade gnupg2-2.0.30-1
Last metadata expiration check: 0:17:17 ago on Wed May 22 16:14:23 2024.
Error: 
 Problem: problem with installed package gpgme-1.13.1-101.ppc
  - package gpgme-1.13.1-101.ppc requires gnupg2 >= 2.2.23, but none of the providers can be installed
  - package gpgme-1.13.1-100.ppc requires gnupg2 >= 2.2.23, but none of the providers can be installed
  - cannot install both gnupg2-2.0.30-1.ppc and gnupg2-2.2.23-1.ppc
  - cannot install both gnupg2-2.2.23-1.ppc and gnupg2-2.0.30-1.ppc
  - cannot install both gnupg2-2.2.35-1.ppc and gnupg2-2.0.30-1.ppc
  - cannot install both gnupg2-2.4.3-1.ppc and gnupg2-2.0.30-1.ppc
  - conflicting requests
```

And I cant remove gnupg2 altogether to do a clean install to version 2.0.30-1 because then it tries to remove dnf itself and cant (even with  --noautoremove)

``` 
Problem: The operation would result in removing the following protected packages: dnf
```
So im pretty much stuck

**Comment by Haroon-Khel** [comment]
The gnupg2-2.0.30-1 rpm can be downloaded here https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/ppc/gnupg2/

So thats an option, manual installation and resolving the dependencies manually

**Comment by Haroon-Khel** [comment]
This issue can be closed because the steps to install Openssl3 were added with the related pr https://github.com/adoptium/infrastructure/pull/3278, this was tested and works. This issue is left open due to build-osuosl-aix72-ppc64-3 being complicated with gnupg2, which I think should be in its own issue
