### ISSUE TITLE
aqa-tests/terminateTestProcesses.sh terminating executors on linux host dockerhost-equinix-ubuntu2004-x64-1

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3280]
dockerhost-equinix-ubuntu2004-x64-1 is a docker "host" with 5 container executors, however it seems test jobs are running "directly" on dockerhost-equinix-ubuntu2004-x64-1, which means the aqa-tests/terminateTestProcesses.sh terminates other test jobs, see:
Teminating job: https://ci.adoptium.net/job/Test_openjdk11_hs_sanity.external_x86-64_linux/613/consoleFull
"Terminated" job: https://ci.adoptium.net/job/Test_openjdk11_hs_extended.system_x86-64_linux/865/consoleFull

Has the docker host being incorrectly labelled?
From the config log history looks like "ci.role.test" got added to the host node on 20th Nov 2023: https://ci.adoptium.net/computer/dockerhost%2Dequinix%2Dubuntu2004%2Dx64%2D1/jobConfigHistory/configOutput?type=xml&timestamp=2023-11-20_18-30-39

**Comment by sxa** [comment]
Reverted the label changes.
Noting that https://github.com/adoptium/infrastructure/issues/3279 is related as those jobs were (incorrectly I expect) running on this machine too.
