### ISSUE TITLE
Define ssh key distribution process

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3323]
This is part of [SSDF](https://github.com/adoptium/adoptium/issues/120#issuecomment-1443690953) PO 5.1  and has been flagged elsewhere. We should have a process for distributing ssh keys wherever they are used to avoid having to bypass the checks on first connect. For example:
- Nagios
- Jenkins
- Infrastructure team
This could be via explicitly adding the host key into the [inventory file](https://github.com/adoptium/infrastructure/blob/master/ansible/inventory.yml).

**Comment by sxa** [comment]
Note: Jenkins won't accept an `ssh-rsa` or `ssh-dss` key and will therefore requre the contents of `ssh_host_ecdsa_key.pub` or `ssh_host_ed25519_key.pub` to be used in the agent configuration

**Comment by sxa** [comment]
@Haroon-Khel is going to look at implementing the changes for the other jenkins nodes which we connect to over ssh (The `test-` ones) and look at ensuring that any nodes created as part of the dockerstatic node automation will support this too.

**Comment by steelhead31** [comment]
@sxa do we have an existing document for this?, otherwise I'll write a document with our current policy and processes for handling these things.

**Comment by sxa** [comment]
Sounds good thanks - we have no such document currently. This is very much a "let's define and document the process" issue :-)

**Comment by Haroon-Khel** [comment]
All of the static docker containers have been restarted and are connected to jenkins with host key verification, **except** for the nodes on https://ci.adoptium.net/label/hw.dockerhost.dockerhost-skytap-ubuntu2204-x64-1/. I think that dockerhost is down as are its nodes

**Comment by steelhead31** [comment]
New document for SSH key management is here.. [https://docs.google.com/document/d/1ltGOhmRKkcN-CvafiNRDZwGKCyUC8xb8lCLWBh1VJEI/edit?usp=sharing](https://docs.google.com/document/d/1ltGOhmRKkcN-CvafiNRDZwGKCyUC8xb8lCLWBh1VJEI/edit?usp=sharing)  
  
@sxa would you mind reviewing, I think that means this issue might be complete.

**Comment by sxa** [comment]
I've added a few comments. On making them, I'm thinking that it might make sense to have separate recommendations for infrastructure team access (where root access is typically granted to the whole team) and for people who have "temporary" access to a user account on a machine, which I wouldn't necessarily hold to such high standards (e.g. I wouldn't mandate a particular cipher or passphrase for such an account, which would raise the barrier for access)

**Comment by steelhead31** [comment]
Updates have been made, following review comments, 2 new sections added , regarding temporary/additional access and jenkins host key management.

**Comment by steelhead31** [comment]
Closing, as I believe this is completed.

**Comment by sxa** [comment]
@steelhead31 Has that document been put anywhere or is it still just in google doc? It looks like it's restricted access at the moment.

**Comment by steelhead31** [comment]
@sxa, I think the google doc is it at the moment, Im sure I asked if there was a suitable public space... let me know where if such a place exists! :)
