### ISSUE TITLE
System unavailable: dockerhost-equinix-ubuntu2204-armv8-1 cannot run docker image

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3338]
- Please put the system name in the title of this issue.

- Link to any log file showing the problem:

https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-linux-aarch64-temurin/456/
https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-alpine-linux-aarch64-temurin/48/

- Please describe the issue:

We appear to timeout when attempting to run a docker image. Previous "passes" on this machine took up to 90 seconds to run, while the other armv8 machine (dockerhost-equinix-ubuntu2004-armv8-1) takes about a second to do the same thing.

Example of the failure:

```
12:05:50  dockerhost-equinix-ubuntu2204-armv8-1 does not seem to be running inside a container
12:05:51  $ docker run -t -d -u 1000:1000 -e BUILDIMAGESHA=adoptopenjdk/centos7_build_image@sha256:c43c55daac22a8f0d4a16fa550ce916e81d101bb80f80452319120aeeb9a15a2
12:05:51   -w /home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-linux-aarch64-temurin -v /home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-linux-aarch64-temurin:/home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-linux-aarch64-temurin:rw,z -v /home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-linux-aarch64-temurin@tmp:/home/jenkins/workspace/build-scripts/jobs/jdk17u/jdk17u-linux-aarch64-temurin@tmp:rw,z -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** adoptopenjdk/centos7_build_image cat
12:08:51  ERROR: Timeout after 180 seconds
```

Some websites online ([example](https://forums.gentoo.org/viewtopic-t-1142901-postdays-0-postorder-asc-start-0.html?sid=7674a9192e3e9c54a55fbd275ce4a578)) suggest that this issue could be resolved by:
- Running [docker system prune](https://docs.docker.com/engine/reference/commandline/system_prune/).
- Or recompiling the docker kernel. This seems overkill, but perhaps a docker reinstall is in order?

A third suggestion is to delete the affected image and re-download from scratch. I see that we "docker pull" the image every time, but then the output suggests that this pull merely validates the existing image.

@Haroon-Khel - Tagging you as promised.

**Comment by Haroon-Khel** [comment]
I think this issue and https://github.com/adoptium/infrastructure/issues/3337 have the same root cause. The problem machine is dockerhost-equinix-ubuntu2204-armv8-1. Progress will be documented in https://github.com/adoptium/infrastructure/issues/3337 since it was posted first

**Comment by Haroon-Khel** [comment]
The machine should be in working order. I restarted the docker service
