### ISSUE TITLE
New Machine requirement: Replacement for C3jenkins

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3340]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Potentially any, but linux preferred
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): n/a
- Provider (leave blank if it does not matter):
- Desired usage: Replacement for [C3jenkins node](https://ci.adoptium.net/computer/C3jenkins/) which is currently hosted on an Equinix x86 server
- Any unusual specification/setup required:
- How many of them are required: 1

Please explain what this machine is needed for:
- Replacement for the node in jenkins which is going to be taken away soon as per https://github.com/adoptium/infrastructure/issues/3292
- Shouldn't require too much additional setup other than java for the agent and git since it doesn't need to do too much ... But this will be a good chance to document any additional requirements.

**Comment by sxa** [comment]
Testing on an OSUOSL aarch64 machine - 2 core, 4GB, 30Gb  with a 250GB volume attached for the jenkins workspace - 140.211.169.21

**Comment by sxa** [comment]
Steps taken:
1. `apt-get update && apt-get upgrade` plus `apt install joe` because I use it a lot, but that's not strictly required
2. Edit /etc/motd to add a file indicating what the machine is used for that will be displayed on login
3. Create jenkins user and add it's public key to ~jenkins/.ssh/authorized_keys
4. Use 250GB disk to create a 4GB swap partition (/dev/sdb1) and the remainer as an ext4 file system mounted on /home/jenkins/workspace. Prior to mounting I created a file /home/jenkins/workspace/ - add both to `/etc/fstab`
5. Install `temurin-21-jdk` using the instructions in https://adoptium.net/installation/linux#_deb_installation_on_debian_or_ubuntu
6. Attach to jenkins as jenkins-worker with [git-hg](https://ci.adoptium.net/label/git-hg) [gpgsign](https://ci.adoptium.net/label/gpgsign)[worker](https://ci.adoptium.net/label/worker) [master](https://ci.adoptium.net/label/master) labels (Not added yet as we're entering a release cycle.

**Comment by sxa** [comment]
A few jobs running on the new node:
- https://ci.adoptium.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk8u/1066/console
- https://ci.adoptium.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk17u/815/console
- https://ci.adoptium.net/job/nightlyBuildAndTestStats_temurin/1335/console
- https://ci.adoptium.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk/715/console
- https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk22/job/jdk22-evaluation-windows-aarch64-temurin/8/console

**Comment by sxa** [comment]
Ref the issue linked above I've got the key accepted now but there is a potential security concern as discussed in my DM with @andrew-m-leonard that I'd like to get clarity on first.

**Comment by sxa** [comment]
Inventory PR for this system: https://github.com/adoptium/infrastructure/pull/3367
I've added it to Bastillion, @steelhead31 is managing Nagios installation prior to merging that PR

**Comment by steelhead31** [comment]
Nagios & Wazuh now installed and working correctly on this host.

**Comment by andrew-m-leonard** [comment]
The Adoptium mirror needs the local git config user/email set so it can push the merge commits, so i’ve set them on jenkins-worker as per the old node:
  println "git config --global user.email temurin-bot@eclipse.org".execute().text
  println "git config --global user.name eclipse-temurin-bot".execute().text

**Comment by sxa** [comment]
> Increased executors from 10 to 12

Noting that https://github.com/adoptium/ci-jenkins-pipelines/pull/920 should have partially resolved this and significantly reduced the executor requirement now.

**Comment by sxa** [comment]
I'm going to close this as I don't believe we have had any problems with this so far.

**Comment by sxa** [comment]
Added `jq` from apt (which installed `jq` `libjq1` `libonig5` to order to support the [download_and_sbom_validation job](https://ci.adoptium.net/job/build-scripts/job/release/job/download_and_sbom_validation/) which is best tied to that node (was previously tied to `aarch64&&dockerhost` which didn't work on the OSUOSL machine which didn't have `jq`
