### ISSUE TITLE
System unavailable: dockerhost-equinix-ubuntu2004-armv8-1 : Out of disk space

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3343]
dockerhost-equinix-ubuntu2004-armv8-1 is out of disk space
https://nagios.adoptopenjdk.net/nagios/cgi-bin/status.cgi?host=dockerhost-equinix-ubuntu2004-armv8-1

**Taken offline:** https://ci.adoptium.net/computer/dockerhost%2Dequinix%2Dubuntu2004%2Darmv8%2D1/

**Comment by Haroon-Khel** [comment]
The system and its nodes are back online after clearing 131G of space from the workspaces of the nodes
