### ISSUE TITLE
System unavailable: test-equinix_esxi-ubuntu2204-x64-1 appears out of space

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3346]
- Please put the system name in the title of this issue.

- Link to any log file showing the problem:
  - https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.perf_x86-64_linux/148/console
  - https://ci.adoptium.net/job/Test_openjdk21_hs_dev.openjdk_x86-64_linux/5/console
  - https://ci.adoptium.net/job/Test_openjdk21_hs_extended.perf_x86-64_linux/34/console

- Please describe the issue:
As it sounds. Example:

```
09:48:44  java.nio.file.FileSystemException: /home/jenkins/workspace/Test_openjdk21_hs_extended.perf_x86-64_linux/aqa-tests: No space left on device
```

Might be related to [this previous issue](https://github.com/adoptium/infrastructure/issues/3275), if the solution didn't solve the issue as planned.

**Comment by sxa** [comment]
Hmmm it has 30Gb free ...

**Comment by adamfarley** [comment]
The latest three runs of [this failing job](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.perf_x86-64_linux/) passed on that machine, so I'll agree that the issue has gone away.
