### ISSUE TITLE
New Machine requirement: Solaris/x64 systems (Equinix replacement)

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3347]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Solaris
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): x64
- Provider (leave blank if it does not matter):
- Desired usage: Build, test and TC
- Any unusual specification/setup required: Can be separate servers or hosted on a hypervisor. Exising ones are on an ESXi server
- How many of them are required: 4 (minimum) - one build, 2 test, 1 TC

Please explain what this machine is needed for:
- Replacement for Equinix systems which we have to decomission as per https://github.com/adoptium/infrastructure/issues/3292

**Comment by sxa** [comment]
Noting that the licensing for ESXi was recently changed by Broadcom so it is likely that it will not be possible to utilise that for the replacement.

**Comment by sxa** [comment]
@steelhead31 Have you used Solaris VMs with the libvirt/kvm provider instead of virtualbox?

**Comment by Haroon-Khel** [comment]
I have not

**Comment by steelhead31** [comment]
Nor I, there are some libvirt vagrant boxes available on vagrantup though.

**Comment by sxa** [comment]
<details>
<summary>Ubuntu EFI secure boot warning with Azure trusted VMs</summary>

 │ UEFI Secure Boot requires additional configuration to work with third-party drivers.       
 │                                                                                            
 │ The system will assist you in configuring UEFI Secure Boot. To permit the use of           
 │ third-party drivers, a new Machine-Owner Key (MOK) has been generated. This key now        
 │ needs to be enrolled in your system's firmware.                                            
 │                                                                                            
 │ To ensure that this change is being made by you as an authorized user, and not by an       
 │ attacker, you must choose a password now and then confirm the change after reboot using    
 │ the same password, in both the "Enroll MOK" and "Change Secure Boot state" menus that      
 │ will be presented to you when this system reboots.                
 │ If you proceed but do not confirm the password upon reboot, Ubuntu will still be able      
 │ to boot on your system but any hardware that requires third-party drivers to work          
 │ correctly may not be usable.          

If you try to bring up a VM without additional work, then you'll get this error:

> Error while connecting to Libvirt: Error making a connection to libvirt URI qemu:///system: Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

In theory this can be mitigated by: `/usr/src/linux-headers-6.5.0-1015-azure/scripts/sign-file sha256 /var/lib/shim-signed/mok/MOK.der /var/lib/shim-signed/mok/MOK.priv /var/lib/dkms/virtualbox/6.1.50/6.5.0-1015-azure/x86_64/module/vboxdrv.ko` but I haven't got that to work yet ... Probably because the MOK password hasn't been entered on startup (You're prompted to set up MOK during the install of virtualbox)

</details>

Using a "standard" VM of a D4 specification (which [supports nested virtualisation](https://azure.microsoft.com/en-us/blog/nested-virtualization-in-azure/)) allows vagrant to work successfully without a reboot loop. Note that a d3as-V4 or B4ls_V2 will not work and gives the message `Stderr: VBoxManage: error: AMD-V is not available (VERR_SVM_NO_SVM)` when attempting to start the VM from Vagrant. `Standard D16ds v4 (16 vcpus, 64 GiB memory)` works ok.

To connect the default ssh configuration on the Ubuntu client will not work so you need to connect with:
- `ssh vagrant@127.0.0.1 -p 2222 -o HostKeyAlgorithms=ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519 -o PubKeyAcceptedKeyTypes=ssh-rsa -i /home/azureuser/infrastructure/ansible/vagrant/.vagrant/machines/adoptopenjdkSol10/virtualbox/private_key` (We should probably see if this can be set in the Vagrantfile)

Noting that `vagrant ssh` by default also uses ` -o LogLevel=FATAL -o Compression=yes -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null` but those aren't mandatory

Steps to recreate
```
scp 150.239.60.120:/home/will/solaris10_homemade_v2.box . 
sudo apt-get -y update && sudo apt install -y joe vagrant virtualbox
vagrant box add --name solaris10 solaris10_homemade_v2.box
wget -O Vagrantfile https://raw.githubusercontent.com/adoptium/infrastructure/master/ansible/vagrant/Vagrantfile.Solaris10
vagrant up
```

Working system types (Numbers in brackets are cores/memGB):
- D16ds_V4 (16/64)
- D2s_V3 (2/8)
- d8s_V3 (8/32)
- f4s_V2 (4/8)

Failing system types (reboot loop in the VM)
- D8ls_V5 (8/16)
- D16dsV5 (16/64)

Failures with no VMX/SVM:
- d3as-V4
- B4ls_V2

I'd ideally have a 8/16 or 16/32 but this seem only available in configurations that don't work from the ones I've found so far :-(

**Comment by sxa** [comment]
Created new system on dockerhost-azure-ubuntu2204-x64-1 which has had `vagrant` and `virtualbox` installed from the adoptium repositories. This machine has had ssh exposed via port 2200 on the host, although the algorithm requirements mean there are issues connecting to it. I have a set it up in jenkins using JNLP for now.

A build ran locally completed in about 20 minutes.

The AQA pipeline job has been run at https://ci.adoptium.net/job/AQA_Test_Pipeline/220/ although that may need a re-run since it was running during today's jenkins update:

Job | First run | Second run
---|---|---
sanity.openjdk | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_solaris/376/) | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.openjdk_x86-64_solaris/377/)
extended.openjdk | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_solaris/129/) | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_solaris/130/)
sanity.perf | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.perf_x86-64_solaris/373/) | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.perf_x86-64_solaris/374/)
extended.perf | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.perf_x86-64_solaris/123/) | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.perf_x86-64_solaris/124/)
sanity.system | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.system_x86-64_solaris/379/) | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.system_x86-64_solaris/380/)
extended.system | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.system_x86-64_solaris/374/) | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.system_x86-64_solaris/375/)
sanity.functional | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.functional_x86-64_solaris/371/) | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.functional_x86-64_solaris/372/)
extended.functional | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.functional_x86-64_solaris/372/)  | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.functional_x86-64_solaris/373/)
special.functional | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_special.functional_x86-64_solaris/126/) | [link](https://ci.adoptium.net/job/Test_openjdk8_hs_special.functional_x86-64_solaris/127/)

**Comment by sxa** [comment]
So we're left with the ten failures from extended.openjdk. Re-running the appropriate targets in Grinder:

Grinder | machine | Time | Result
--- | --- | --- | --- |
9047 | azure-1 | m |
9048 | esxi-bld-1 | m |
9049 | esxi-test-1 | m |

**Comment by sxa** [comment]
Starting over with a cleaner setup now that we have prototyped this. Both of the dockerhost machines have had a `/home/solaris` file system created with enough space to host the VMs. The vagrant processes will run as that user:

Host | Guest
---|---
dockerhost-skytap-ubuntu2204-x64-1 | build-skytap-solaris10-x64-1
dockerhost-azure-ubuntu2204-x64-1 | test-skytap-solaris10-x64-1

**Comment by steelhead31** [comment]
When creating an Azure VM that supports nested virtualization, the following restrictions are in place:

Must be a TYPE D or TYPE £ machine, of Version 3.
Must only use the "Standard" security model, trusted launch should not be used/enabled.
