### ISSUE TITLE
Mac Xcode 15.0.1 needs upgrading to Xcode 15.2 to resolve TCK failures due to Xcode new linker crashes

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3353]
Xcode 15.0.1 has a known bug with the new linker that causes SIGSEGV crashes for some native libraries.

Suggest moving to Xcode 15.2 and running full AQA and TCK testing (including auto manuals)

**Comment by gdams** [comment]
@andrew-m-leonard I can update the Orka base image to have 15.2. Let me know when you want me to do it

**Comment by gdams** [comment]
I’ve just realised I didn’t put xcode on the intel VM, we’ve been using the command-line tools. I’ll run an update of those and then commit the image but I’d say lets not put full xcode on unless we need to

**Comment by gdams** [comment]
@andrew-m-leonard can I close this out now?

**Comment by andrew-m-leonard** [comment]
> @andrew-m-leonard can I close this out now?

yes, thank you @gdams
