### ISSUE TITLE
jdk_time target fails on some arm32_linux nodes

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#3360]
Please set the title to indicate the test name and machine name where known.

As indicated by Jan 2024 CPU triage, in https://github.com/adoptium/aqa-tests/issues/4982#issuecomment-1896615489, the jdk_time test target was failing with timeouts on ci.adoptium.net arm32 nodes.  It was able to pass on the temurin-compliance arm32 linux node.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? BUILD_LIST=openjdk, TARGET=jdk_time
- a link into recent `Test_` job on https://ci.adoptium.net which showed the failure
  - https://ci.adoptium.net/job/Test_openjdk11_hs_extended.openjdk_arm_linux/127/
  - https://ci.adoptium.net/job/Grinder/8603
- **Hyperlink** to re-run in Grinder: 
  - rerun [link](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST=jdk_custom_0&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk11_hs_extended.openjdk_arm_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=1&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=arm_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&LABEL=test-docker-ubuntu2004-armv7l-1&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v1.0.0-release&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=11&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk11u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk11u%2Fjdk11u-release-linux-arm-temurin&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=java%2Fnet%2Fhttpclient%2FManyRequests2.java+java%2Fnet%2Fhttpclient%2FManyRequests.java+java%2Fnet%2Fhttpclient%2FManyRequestsLegacy.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKDateTimeFormatterBuilder.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKInstantPrinterParser.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKDateTimeParseResolver.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKChronoLocalDateTime.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKChronoLocalDate.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2Fserial%2FTCKChronologySerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FCopticEra.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2Fserial%2FTCKChronoLocalDateTimeSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKThaiBuddhistEra.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKJapaneseEra.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FCopticChronology.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKTestServiceLoader.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKChronology.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKHijrahEra.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FCopticDate.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKPadPrinterParser.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKDateTimeTextPrinting.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKDecimalStyle.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2Fserial%2FTCKCopticSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKChronoZonedDateTime.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2Fserial%2FTCKEraSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKIsoChronology.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKMinguoEra.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fserial%2FTCKInstantSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fzone%2Fserial%2FTCKZoneOffsetTransitionSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKFormatStyle.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Ftemporal%2FTCKChronoField.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fserial%2FTCKClockSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKMinguoChronology.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKDateTimeFormatters.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Ftemporal%2FTCKTemporalAdjusters.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fserial%2FTCKZoneIdSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fserial%2FTCKOffsetDateTimeSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKIsoEra.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2Fserial%2FTCKChronoZonedDateTimeSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Ftemporal%2FTCKIsoFields.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKLocalizedFieldPrinter.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fserial%2FTCKYearSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fserial%2FTCKDurationSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKDateTimeFormatter.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fserial%2FTCKLocalTimeSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2Fserial%2FTCKChronoLocalDateSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKLocalizedFieldParser.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKThaiBuddhistChronology.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fzone%2FTCKZoneRulesProvider.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fzone%2FTCKZoneRules.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKJapaneseChronology.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKHijrahChronology.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fserial%2FTCKOffsetTimeSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKTextStyle.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKSignStyle.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKChronoPrinterParser.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKDTFParsedInstant.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fchrono%2FTCKChronoPeriod.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fzone%2Fserial%2FTCKZoneOffsetTransitionRuleSerialization.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKZoneIdPrinterParser.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fformat%2FTCKLocalizedPrinterParser.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Ftemporal%2FTCKChronoUnit.java+java%2Ftime%2Ftck%2Fjava%2Ftime%2Fzone%2FTCKZoneOffsetTransition.java+javax%2Fmanagement%2Fmonitor%2FDerivedGaugeMonitorTest.java+javax%2Fmanagement%2Fmonitor%2FStartStopTest.java+tools%2Fjmod%2Fhashes%2FHashesOrderTest.java+jdk%2Fjfr%2Fevent%2Fcompiler%2FTestCodeCacheConfig.java&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-11.0.22%2B7_adopt&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=127&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=true&UPSTREAM_JOB_NUMBER=13&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=15&JVM_OPTIONS=&PARALLEL=None)
- Is there an existing issue elsewhere covering this? No
- Which machine(s) does it work on?  [jck-equinix-containerized-ubuntu2004-aarch32-1](https://ci.eclipse.org/temurin-compliance/computer/jck-equinix-containerized-ubuntu2004-aarch32-1)
- Which machine(s) does it fail on? https://ci.adoptium.net/label/hw.arch.aarch32&&ci.role.test&&sw.os.linux/

Any other details:
Suspect related to the findings in https://github.com/adoptium/infrastructure/issues/2002 but not confirmed

**Comment by sxa** [comment]
Will be part of the top level #2662

**Comment by Haroon-Khel** [comment]
Some jdk_time_2 tests failed on test-docker-ubuntu2004-armv7l-4 with the last jdk17 release
https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux/137/tapResults 

```
Failed test cases: 
TEST: java/time/tck/java/time/format/TCKLocalizedOffsetIdPrinterParser.java
TEST: java/time/tck/java/time/serial/TCKZonedDateTimeSerialization.java
TEST: java/time/tck/java/time/format/TCKLocalizedPrinterParser.java
TEST: java/time/tck/java/time/serial/TCKOffsetDateTimeSerialization.java
TEST: java/time/tck/java/time/temporal/TCKChronoUnit.java
TEST: java/time/tck/java/time/serial/TCKLocalTimeSerialization.java
TEST: java/time/tck/java/time/serial/TCKZoneIdSerialization.java
TEST: java/time/tck/java/time/format/TCKInstantPrinterParser.java
TEST: java/time/tck/java/time/serial/TCKLocalDateSerialization.java
TEST: java/time/tck/java/time/serial/TCKYearSerialization.java
TEST: java/time/tck/java/time/format/TCKSignStyle.java
TEST: java/time/tck/java/time/format/TCKFormatStyle.java
TEST: java/time/tck/java/time/temporal/TCKChronoField.java
TEST: java/time/tck/java/time/format/TCKZoneIdPrinterParser.java
TEST: java/time/tck/java/time/format/TCKPadPrinterParser.java
TEST: java/time/tck/java/time/format/TCKTextStyle.java
TEST: java/time/tck/java/time/serial/TCKPeriodSerialization.java
TEST: java/time/tck/java/time/serial/TCKLocalDateTimeSerialization.java
TEST: java/time/nontestng/java/time/chrono/HijrahConfigTest.java
TEST: java/time/tck/java/time/format/TCKDateTimeParseResolver.java
TEST: java/time/tck/java/time/zone/serial/TCKZoneOffsetTransitionRuleSerialization.java
Test results: passed: 163; error: 23
```

However all of these tests passed when run individually on the machine itself

```
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/format/TCKLocalizedPrinterParser.java    
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/serial/TCKOffsetDateTimeSerialization.java
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/temporal/TCKChronoUnit.java               
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/serial/TCKLocalTimeSerialization.java
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/serial/TCKZoneIdSerialization.java   
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/format/TCKInstantPrinterParser.java
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/format/TCKInstantPrinterParser.java
^Cjenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/serial/TCKLocalDateSerialization.java
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/serial/TCKYearSerialization.java     
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/format/TCKSignStyle.java        
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/format/TCKFormatStyle.java
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/temporal/TCKChronoField.java
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/format/TCKZoneIdPrinterParser.java
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/format/TCKPadPrinterParser.java   
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/format/TCKTextStyle.java       
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/serial/TCKPeriodSerialization.java
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/serial/TCKLocalDateTimeSerialization.java
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/nontestng/java/time/chrono/HijrahConfigTest.java       
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/format/TCKDateTimeParseResolver.java
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
jenkins@1a14546b3875:~/test$ $JAVA -jar jtreg/lib/jtreg.jar jdk17u/test/jdk/java/time/tck/java/time/zone/serial/TCKZoneOffsetTransitionRuleSerialization.java
Test results: passed: 1
Report written to /home/jenkins/test/JTreport/html/report.html
Results written to /home/jenkins/test/JTwork
```

using the latest jdk17 release

```
jenkins@1a14546b3875:~/test$ $JAVA -version 
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
OpenJDK Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)
```

**Comment by Haroon-Khel** [comment]
Looks like it times out when you run them in jdk_time together, but pass when running them individually. 

https://ci.adoptium.net/job/Grinder/8698/console

```
16:17:12  
16:17:12  TEST RESULT: Error. Agent error: java.lang.Exception: Agent 52 timed out with a timeout of 960 seconds; check console log for any additional details
16:17:12  --------------------------------------------------
16:17:45  TEST: java/time/tck/java/time/serial/TCKZonedDateTimeSerialization.java
16:17:45  TEST JDK: /home/jenkins/workspace/Grinder/jdkbinary/j2sdk-image
16:17:45  
16:17:45  ACTION: build -- Error. Agent error: java.lang.Exception: Agent 53 timed out with a timeout of 960 seconds; check console log for any additional details
16:17:45  REASON: Named class compiled on demand
16:17:45  TIME:   2073.694 seconds
```

**Comment by Haroon-Khel** [comment]
Running jdk_time_2 from my own branch, with `JTREG_TIMEOUT_OPTION` increased to 40 (I dont know how to do it from the grinder)
https://ci.adoptium.net/job/Grinder/8700/console

**Comment by Haroon-Khel** [comment]
`htop` on the dockerhost machine while the above grinder is running

<img width="1113" alt="image" src="https://github.com/adoptium/infrastructure/assets/34969545/b41e8cd4-f4bb-452b-bddf-6205784fc93f">

grinder 8700 has lost contact with test-docker-ubuntu2004-armv7l-4
```
17:27:15  XML output with verification to /home/jenkins/workspace/Grinder/aqa-tests/TKG/output_17067220302633/jdk_time_2/work
17:47:17  Cannot contact test-docker-ubuntu2004-armv7l-4: java.lang.InterruptedException
```

**Comment by Haroon-Khel** [comment]
I think the jdk_time test target might be a bit much for the docker static containers. 

The grinder has caused test-docker-ubuntu2004-armv7l-4 to disconnect from jenkins
https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2004%2Darmv7l%2D4/log

```
SSH Connection failed with IOException: "The kexTimeout (65000 ms) expired.", retrying in 15 seconds. There are 1 more retries left.
The kexTimeout (65000 ms) expired.
ERROR: Connection is not established!
java.lang.IllegalStateException: Connection is not established!
	at com.trilead.ssh2.Connection.getRemainingAuthMethods(Connection.java:989)
```

**Comment by Haroon-Khel** [comment]
Rerunning on a non docker container (odroid machine) https://ci.adoptium.net/job/Grinder/8702/console

**Comment by Haroon-Khel** [comment]
Passed on the odroid machine. Also passed on [test-docker-ubuntu2004-armv7l-2](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2004%2Darmv7l%2D2/) https://ci.adoptium.net/job/Grinder/8701/console

**Comment by sxa** [comment]
Interesting ...

@Haroon-Khel Are they all new containers and did you cap the CPU/memory on them? From the Grinder logs the run on both containers as mentioned in https://github.com/adoptium/infrastructure/issues/3360#issuecomment-1919713225 and https://github.com/adoptium/infrastructure/issues/3360#issuecomment-1919654121 were both running with `-concurrency:81` on the jtreg command line (CPU cores/2+1. Those machines have 160 physical cores) but most of the containers should be started with [options that restrict the containers to less than that](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/DockerStatic/tasks/main.yml). I'm not quite sure why the two container Grinders didn't show the same behaviour, but the odroid system had concurrency:1 so were potentially safer. I'm slightly surprised that a time related test would give a large load, but maybe we need to restrict those tests. I would have expected similar results on the aarch64 systems though, which are run on the same host 🤷🏻 

Noting that the calculation for currency is the one I was looking at adjusting in https://github.com/adoptium/aqa-tests/pull/4792 (in case you want to see where it is and play with it) but I don't think that will affect this particular situation.

**Comment by Haroon-Khel** [comment]
Ive updated my branch to run the test with concurrency:2
Rerunning on test-docker-ubuntu2004-armv7l-4 https://ci.adoptium.net/job/Grinder/8703/console

> Are they all new containers and did you cap the CPU/memory on them?

Yes, the images are built with
`docker build --cpu-period=100000 --cpu-quota=800000`

And are run with
`docker run --restart unless-stopped --cpus=4.0 --memory=6G`

Bear in mind the jdk_time_2 tests passed on [test-docker-ubuntu2004-armv7l-2](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2004%2Darmv7l%2D2/), another static container but running on dockerhost-equinix-ubuntu2004-armv8-1 not dockerhost-equinix-ubuntu2204-armv8-1. Link to the grinder https://ci.adoptium.net/job/Grinder/8701/console `-concurrency:81` is used

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/job/Grinder/8703/console passed. So we need to limit concurrency on the docker static containers, and eventhough its passes with -concurrency:81 on some, it shouldnt be using a value this high

**Comment by Haroon-Khel** [comment]
https://github.com/adoptium/aqa-tests/pull/4792 looks good, but I want to first look at why the test scripts are reporting 160 cores and not the set 4 (or whatever) cores of the docker containers

**Comment by sxa** [comment]
> [adoptium/aqa-tests#4792](https://github.com/adoptium/aqa-tests/pull/4792) looks good

Unfortunately I'm not yet convinced which is why it's still in draft, but I need to get back to it ;-)
It will be getting 160 cores from `/proc/cpuinfo` by default which is ok, but it ought to be reading the memory size from `/sys/fs/cgroup/memory/memory.limit_in_bytes` in the container (`8589934592` bytes, converting to to Mb (`8192` which goes into `MEMORY_SIZE` - this is the bit that will go wrong on the arm systems if my PR goes in) and then should set `CONC` (the value for concurrency) to 4 (Half the memory in Gb) as that's less than the number of cores (160)
All that logic is in https://github.com/adoptium/aqa-tests/blob/c27e9e649919f839444c638844e133a0d13edd04/openjdk/openjdk.mk#L52

**Comment by Haroon-Khel** [comment]
Im having some luck with `--cpuset-cpus="0-3"` instead of `--cpus=4.0` to assign cpus to containers, and with `nproc` to find the number of processors 

Container started with `--cpus=4.0`
```
root@d0a2dceb584c:/# nproc
160
```
Container started with `--cpuset-cpus="0-3"`
```
root@91b440680d8b:/# nproc
4
```

So a solution is to change https://github.com/adoptium/aqa-tests/blob/c27e9e649919f839444c638844e133a0d13edd04/openjdk/openjdk.mk#L22 to use `nproc` to find the number of cpus and to restart our arm32 containers with `--cpuset-cpus="0-3"`

**Comment by Haroon-Khel** [comment]
I've redeployed test-docker-ubuntu2004-armv7l-4 with `--cpuset-cpus="0-3"` 

Rerunning jdk_time_2 from my branch on it, `JTREG_TIMEOUT_OPTION` is set back to normal. https://ci.adoptium.net/job/Grinder/8710/console

Concurrency should be 4/2 +1 =3 which shouldn't cause a timeout

**Comment by Haroon-Khel** [comment]
Looks good `-timeoutFactor:8 -xml:verify  -concurrency:3`

**Comment by Haroon-Khel** [comment]
Grinder passed 👍🏻

**Comment by Haroon-Khel** [comment]
Passes for jdk11 too https://ci.adoptium.net/job/Grinder/8711/console

**Comment by sxa** [comment]
Do you know what the difference in behaviour is between the two options i.e. is there likely to be any downside to this change? We should check whether this is happening elsewhere too e g. X64 and ppcle systems to see if they are the same (trying to use more cores than they should be at present)

Nice find!
