### ISSUE TITLE
Adoptium mirrors failing due to: Host key verification failed.

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3364]
Looks like the new jenkins-worker node needs host verification?
https://ci.adoptium.net/view/git-mirrors/job/git-mirrors/job/adoptium/job/git-skara-jdk21u/5668/console
```
+ git clone git@github.com:adoptium/jdk21u jdk21u
Cloning into 'jdk21u'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
+ exit 1
```

**Comment by sxa** [comment]
I want to cover any such issues under https://github.com/adoptium/infrastructure/issues/3340 so we understand the setup required and the information is all in once place.
