### ISSUE TITLE
compiler/loopopts/superword/TestMovingLoadBeforeStore.java.TestMovingLoadBeforeStore failure on x64 linux jdk17

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3377]
Continuation of https://github.com/adoptium/infrastructure/issues/2360

compiler/loopopts/superword/TestMovingLoadBeforeStore.java is failing on most of our x64 nodes. 

https://ci.adoptium.net/job/Grinder/8787/console [test-ibmcloud-rhel7-x64-1](https://ci.adoptium.net/computer/test%2Dibmcloud%2Drhel7%2Dx64%2D1/) Failed
https://ci.adoptium.net/job/Grinder/8788/console [test-docker-debian12-x64-1](https://ci.adoptium.net/computer/test%2Ddocker%2Ddebian12%2Dx64%2D1/) Passed
https://ci.adoptium.net/job/Grinder/8789/console [test-equinix_esxi-ubuntu2204-x64-1](https://ci.adoptium.net/computer/test%2Dequinix%5Fesxi%2Dubuntu2204%2Dx64%2D1/) Failed
https://ci.adoptium.net/job/Grinder/8790/console [test-docker-ubi8-x64-2](https://ci.adoptium.net/computer/test%2Ddocker%2Dubi8%2Dx64%2D2/) Failed
https://ci.adoptium.net/job/Grinder/8791/console [test-docker-ubuntu2204-x64-4](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2204%2Dx64%2D4/) Passed
https://ci.adoptium.net/job/Grinder/8792/console [test-ibmcloud-rhel6-x64-1](https://ci.adoptium.net/computer/test%2Dibmcloud%2Drhel6%2Dx64%2D1/) Failed
https://ci.adoptium.net/job/Grinder/8795/console [test-docker-ubuntu2204-x64-5](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2204%2Dx64%2D5/) Passed
https://ci.adoptium.net/job/Grinder/8796/console [test-docker-debian11-x64-2](https://ci.adoptium.net/computer/test%2Ddocker%2Ddebian11%2Dx64%2D2/) Failed
https://ci.adoptium.net/job/Grinder/8797/console [test-docker-fedora35-x64-2](https://ci.adoptium.net/computer/test%2Ddocker%2Dfedora35%2Dx64%2D2/) Failed
https://ci.adoptium.net/job/Grinder/8799/console [test-docker-ubi8-x64-2](https://ci.adoptium.net/computer/test%2Ddocker%2Dubi8%2Dx64%2D2/) Failed

Nodes hosted on dockerhost-skytap-ubuntu2204-x64-1 are passing the test.

The test code is found here https://github.com/adoptium/jdk17u/blob/master/test/hotspot/jtreg/compiler/loopopts/superword/TestMovingLoadBeforeStore.java

**Comment by sxa** [comment]
> The test code is found here https://github.com/adoptium/jdk17u/blob/master/test/hotspot/jtreg/compiler/loopopts/superword/TestMovingLoadBeforeStore.java

I've just tried this on the dockerhost-equinix-ubuntu2004-x64-1 hsot (replacing jdk.test.lib.Utils with new `java.security.SecureRandom();`) and it seems to work ok.

Things to check:
- Is it specific to running in a docker container?
- Are we hitting something that could be CPU specific (Noting that the two Equinix x64 dockerhosts are different - one's an Intel chip and the other is AMD)?

**Comment by sxa** [comment]
Needs further investigation and to record the console output / test result

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/job/Grinder/11959/console [test-docker-ubi9-x64-1](https://ci.adoptium.net/computer/test%2Ddocker%2Dubi9%2Dx64%2D1/)

https://ci.adoptium.net/job/Grinder/11960/ [test-ibmcloud-ubuntu1604-x64-1](https://ci.adoptium.net/computer/test%2Dibmcloud%2Dubuntu1604%2Dx64%2D1/)

https://ci.adoptium.net/job/Grinder/11961/console [test-azure-ubuntu2404-x64-1](https://ci.adoptium.net/computer/test%2Dazure%2Dubuntu2404%2Dx64%2D1/)

https://ci.adoptium.net/job/Grinder/11962/console [test-docker-ubuntu2404-x64-1](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2404%2Dx64%2D1/)

https://ci.adoptium.net/job/Grinder/11963/console [test-docker-centos7-x64-1](https://ci.adoptium.net/computer/test%2Ddocker%2Dcentos7%2Dx64%2D1/)

https://ci.adoptium.net/job/Grinder/11964/console [test-docker-ubuntu2004-x64-5](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2004%2Dx64%2D5/)

https://ci.adoptium.net/job/Grinder/11965/console [test-aws-rhel8-x64-1](https://ci.adoptium.net/computer/test%2Daws%2Drhel8%2Dx64%2D1/)

https://ci.adoptium.net/job/Grinder/11966/console [test-docker-ubuntu2004-x64-2](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2004%2Dx64%2D2/)

https://ci.adoptium.net/job/Grinder/11967/console  [test-ibmcloud-rhel7-x64-1](https://ci.adoptium.net/computer/test%2Dibmcloud%2Drhel7%2Dx64%2D1

https://ci.adoptium.net/job/Grinder/11968/console [test-ibmcloud-rhel6-x64-1](https://ci.adoptium.net/computer/test%2Dibmcloud%2Drhel6%2Dx64%2D1/)

https://ci.adoptium.net/job/Grinder/11969/console [test-docker-fedora39-x64-2](https://ci.adoptium.net/computer/test%2Ddocker%2Dfedora39%2Dx64%2D2/)
