### ISSUE TITLE
New Machine requirement - Second Linux/x64 dockerhost/build host

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3378]
I need to request a new machine:

-  New machine operating system (e.g. linux/windows/macos/solaris/aix): Linux
-  New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): x64
-  Provider (leave blank if it does not matter): Probably skytap
-  Desired usage: Replacement for the two dockerhost x64 systems currently hosted on Equinix
-  Any unusual specification/setup required: docker for running dockerhost containers and build pipelines
-  How many of them are required: 1 (To replicate the work in https://github.com/adoptium/infrastructure/issues/3352)

Please explain what this machine is needed for: Replacement for Equinix systems which we have to decommission as per https://github.com/adoptium/infrastructure/issues/3292

Potentially linked to https://github.com/adoptium/infrastructure/issues/3368

**Comment by sxa** [comment]
@Haroon-Khel Let me know if you want to take this one on as part of your static docker work, otherwise I can just replicate what we currently have. We're looking at having something equivalent to the machine created in 3352. If we're going to host this at Skytap we should probably aim to [decommission the skytap AIX 7.1 TC machines first](https://github.com/temurin-compliance/temurin-compliance/issues/470) before adding the additional system.

Noting that as part of this we should start taking some of the containers hosted on the two existing machines offline now that we have the capacity on the first box.:
- https://ci.adoptium.net/label/hw.dockerhost.dockerhost-equinix-ubuntu2004-x64-1/
- https://ci.adoptium.net/label/hw.dockerhost.dockerhost-equinix-ubuntu2204-x64-1/

**Comment by Haroon-Khel** [comment]
>  otherwise I can just replicate what we currently have

It makes sense to replicate dockerhost-skytap-ubuntu2204-x64-1. Once you have it up I can deploy containers onto it

**Comment by sxa** [comment]
It's not quite ready yet but the second dockerhost has been provisioned at 20.61.136.213 (I'm writing this comment mostly for my own reference!)
I think we're going to need to look at how to run a solaris VM on these systems too ...

**Comment by sxa** [comment]
Machine is offline due to quota issues at Skytap

**Comment by sxa** [comment]
Trying a few different options as vagrant didn't work on the initial machine ...

**Comment by sxa** [comment]
Reprovisioned as an AMD system (The Skytap one is Intel so we've got both types covered) with 16 cores, 64GB of RAM and in a configuration which will work with Vagrant (`D16as v4`) at 20.40.219.35

**Comment by sxa** [comment]
FYI @Haroon-Khel the machine in the previous comment is now ready for setup :-)
Note that I have installed the `vagrant` and `virtualbox` packages on it too with the intention of using it to configure a solaris system.

**Comment by sxa** [comment]
Scrap that ... The AMD ones don't allow virtualisation so I've switched it to an Intel Xeon(R) Platinum 8272CL at 52.180.147.157 - @Haroon-Khel This should now be ready for setup. I've also installed `vagrant` and `virtualbox` with a view to using it to satisfy [the solaris requirement](https://github.com/adoptium/infrastructure/issues/3347)

**Comment by Haroon-Khel** [comment]
Ive set up the 52.180.147.157 machine with the dockerhost playbook. In light of https://github.com/adoptium/infrastructure/issues/3412, ill put some containers on the machine too

**Comment by sxa** [comment]
Machine is now hosting one of the two Solaris vagrant machines. I'll close this for now and we can continue any discussion on the enabling of new AQA Static Docker containers in the issue mentioned in the previous comment.

**Comment by Haroon-Khel** [comment]
100g disk added to 52.180.147.157, mounted on /home/jenkins
