### ISSUE TITLE
centos7_docker_image_updater rarely completes Manifest Update

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3388]
https://ci.adoptium.net/job/centos7_docker_image_updater/
The Manifest Update only completes if all the image uploads complete successfully, however riscv64 nearly always fails, and others periodically fail

**Comment by sxa** [comment]
Please add and discussion on this as part of https://github.com/adoptium/infrastructure/issues/2760

**Comment by sxa** [comment]
(Noting that the latest run today has completed with a green status)
