### ISSUE TITLE
jenkins: dependency_pipeline job is using close to 100Gb of space

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3408]
Spun out of https://github.com/adoptium/infrastructure/issues/3285#issuecomment-1957046869:
```
94298548	dependency_pipeline
282769152	build-scripts/jobs/jobs/jobs
```
I suspect the [dependency pipeline job](https://ci.adoptium.net/job/dependency_pipeline/) is not set to discard old artifacts. Can we implement some form of cleanup policy on those or is there a reason that it needs to use that amount of space?

**Comment by smlambert** [comment]
I have configured that job to Discard old builds, Max days to keep a build is 30 days, number of builds to keep as 10.

**Comment by sxa** [comment]
> I have configured that job to Discard old builds, Max days to keep a build is 30 days, number of builds to keep as 10.

Thanks for the quick fix on this - it's down to using 3Gb now by the look of it - good to hear there wasn't a strong reason to retain them :-)

I've now got 679Gb on the jobs file system so I feel we'll been fine for a while!
