### ISSUE TITLE
Decommission containers hosted on x64 equinix dockerhost machines

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3412]
ref https://github.com/adoptium/infrastructure/issues/3378#issuecomment-1938595634

With the x64 equinix dockerhost machines being replaced by skytap machines we need to begin to decommission the jenkins nodes of the containers hosted on the equinix machines.

🛑 = marked offline in jenkins
✅ = decommissioned
```
    {
        "name": "dockerhost-equinix-ubuntu2204-x64-1",
        "ip": "145.40.113.173",
        "containers": [
            "test-docker-alpine314-x64-2", 🛑 
            "test-docker-alpine317-x64-2", 🛑 
            "test-docker-centos8-x64-2",
            "test-docker-debian11-x64-2", 🛑 
            "test-docker-fedora35-x64-2", 🛑 
            "test-docker-fedora37-x64-2",
            "test-docker-ubi8-x64-2", 🛑 
            "test-docker-ubuntu2004-x64-2",
            "test-docker-ubuntu2204-x64-2"
        ],
        "containersCount": 9
    }
    {
        "name": "dockerhost-equinix-ubuntu2004-x64-1",
        "ip": "145.40.114.58",
        "containers": [
            "test-docker-alpine314-x64-1",
            "test-docker-alpine317-x64-1",
            "test-docker-centos8-x64-1",
            "test-docker-debian11-x64-1", 🛑 
            "test-docker-fedora35-x64-1",
            "test-docker-fedora37-x64-1",
            "test-docker-fedora37-x64-3",
            "test-docker-ubi8-x64-1",
            "test-docker-ubuntu2004-x64-1",
            "test-docker-ubuntu2204-x64-1", 🛑 
            "test-docker-ubuntu2204-x64-3" 🛑 
        ],
        "containersCount": 11
    }
```

At the same time we need to increase the number of containers on the skytap replacements

```
    {
        "name": "dockerhost-skytap-ubuntu2204-x64-1",
        "ip": "20.61.136.254",
        "containers": [
            "test-docker-debian12-x64-1", 
            "test-docker-fedora39-x64-1", 
            "test-docker-ubuntu2204-x64-4", 
            "test-docker-ubuntu2204-x64-5" 
        ],
        "containersCount": 4
    }
```
Second x64 skytap replacement machine is almost ready https://github.com/adoptium/infrastructure/issues/3378

**Comment by Haroon-Khel** [comment]
@sxa Regarding dockerhost-skytap-ubuntu2204-x64-1, 20.61.136.254, the disk space allocated for docker might be too small to accommodate enough containers to replace the equinix dockerhosts
```
├─sdb2                8:18   0   135G  0 part /var/lib/docker
└─sdb3                8:19   0   105G  0 part /home/jenkins
```
For reference, both of the equinix dockerhosts have ~800g disks mapped to /var/lib/docker. Could the skytap disks be increased to 400g?

**Comment by sxa** [comment]
> @sxa Regarding dockerhost-skytap-ubuntu2204-x64-1, 20.61.136.254, the disk space allocated for docker might be too small to accommodate enough containers to replace the equinix dockerhosts
> 
> ```
> ├─sdb2                8:18   0   135G  0 part /var/lib/docker
> └─sdb3                8:19   0   105G  0 part /home/jenkins
> ```
> 
> For reference, both of the equinix dockerhosts have ~800g disks mapped to /var/lib/docker. Could the skytap disks be increased to 400g?

You have the same access to the skytap console that I do so feel free to do what is needed :-)

However bear in mind that the specification of the machine in terms of CPU and RAM does not match the Equinix ones, so we need to be mindful of exactly how many images we can have on each system. Do you have a feel for what the disk requirements are for a test image?  I would not expect each to use more than around 10GB while running a test (I don't recall what Nagios was set to alert at) but that would mean that even with 10 images there should still be a good amount of headroom with a 130Gb `/var/lib/docker`.

There are a couple of `wayland` images on there using 10Gb which can be removed.

**Comment by sxa** [comment]
Related (It's causing leakage of space): https://github.com/adoptium/infrastructure/issues/3416

**Comment by sxa** [comment]
Closing this as the host machines have been decommissioned now
