### ISSUE TITLE
Shutdown/Start dockerhost-rise-ubuntu2204-aarch64-1 on demand on Google Cloud

### ISSUE THREAD

**Issue by luhenry** [adoptium/infrastructure#3427]
RISE is requesting that [dockerhost-rise-ubuntu2204-aarch64-1](https://ci.adoptium.net/computer/dockerhost%2Drise%2Dubuntu2204%2Daarch64%2D1/) can be turned off when not in use to reduce their cloud bill. This machine is hosted on Google Cloud which supports starting VMs on demand.

https://cloud.google.com/architecture/using-jenkins-for-distributed-builds-on-compute-engine outlines how it should be setup.

I'm not entirely familiar with what should be done and what information would be needed, so I'm happy to work with RISE + Adoptium to make sure it happens.

Thanks!

**Comment by sxa** [comment]
By way of comparison this is a table of jdk21u build times on different machines for running the build (number in brackets includes things like checkout, SBoM generation etc:

Host | Time
---|---
[equinix-aarch64-1](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-riscv64-temurin/23/) (-j80) | 2h03 (2h25)
[equinix-aarch64-1](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-riscv64-temurin/21/consoleFull) (-j120) | Failed
[equinix-aarch64-1](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-riscv64-temurin/23/) (-j80) | 2h00 (2h30)
[azure-x64-1](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-riscv64-temurin/18/consoleFull) | 1h14 (1h33)
[rise-aarch64-1](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-riscv64-temurin/13/) (-j32) | 0h54 (1h22)
[scaleway-riscv64-1](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-riscv64-temurin/12/) | 2h24 (2h43)

**Comment by gdams** [comment]
> I'll soon need to decommission `dockerhost-rise-ubuntu2204` unless we can get this issue sorted. It should work on the existing boards we have, but that would create more load on them and may lead to flakiness due to board's instability. cc @gdams @sxa

sounds like we'd be better off shutting the service down and provisioning more scaleway machines

**Comment by sxa** [comment]
Given that the test above seemed to work ok with a default configuration under docker on the Scaleway machines that's certainly an option - I thought we had some issue under docker with certain configurations but that job looks to have gone through ok.
We could also potentially run them in an emulated environment elsewhere, as we do on the dockerhost-rise machine.

**Comment by sxa** [comment]
This machine is no longer being used and our Azure hosts are now configured to be able to run the builds. On that basis this will not be progressed therefore closing
