### ISSUE TITLE
Access to the Skytap console for the infrastructure team

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3430]
At the moment only @sxa has access to the access. Admin access for the rest of the infrastructure team needs to be setup

Skytap console https://cloud.skytap.com/login

**Comment by sxa** [comment]
@gdams Are you able / willing to give Haroon and Scott their own accounts on the skytap UI?
Obviously the alternative is to have a shared account as we do with most of the other providers.

**Comment by gdams** [comment]
@sxa no concerns from me. @Haroon-Khel @steelhead31 please ping me on Slack and I'll setup your accounts

**Comment by steelhead31** [comment]
My account has been setup OK.

**Comment by Haroon-Khel** [comment]
As has mine
