### ISSUE TITLE
Adoptium Alpine image need strace installing

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3452]
To support enabling SBOM strace, we need the Adoptium Alpine containers provisioned with strace

**Comment by andrew-m-leonard** [comment]
@sxa ah, just tried again, and currently failing with disk space issue, on dockerhost-skytap-ubuntu2204-x64-1:
https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-alpine-linux-x64-temurin/53/console
```
12:05:33  mktemp: (null): No space left on device
```

**Comment by andrew-m-leonard** [comment]
Running a test on the other node: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-alpine-linux-x64-temurin/54/console

**Comment by andrew-m-leonard** [comment]
Looks like it can't find "rpm", does that exist on Alpine ? : 
```
12:14:45  /home/jenkins/workspace/build-scripts/jobs/jdk21u/jdk21u-alpine-linux-x64-temurin/sbin/build.sh: line 658: rpm: command not found
```

**Comment by sxa** [comment]
> Looks like it can't find "rpm", does that exist on Alpine ? :

No it's not rpm based.

**Comment by sxa** [comment]
> @sxa ah, just tried again, and currently failing with disk space issue, on dockerhost-skytap-ubuntu2204-x64-1: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-alpine-linux-x64-temurin/53/console
> 
> ```
> 12:05:33  mktemp: (null): No space left on device
> ```

Sorted - stuff was being left over by some attempts to rebuild the build images.
Cache cleared with `docker buildx prune` - 55GB free now

**Comment by andrew-m-leonard** [comment]
> > Looks like it can't find "rpm", does that exist on Alpine ? :
> 
> No it's not rpm based.

Ok, thanks, we need to update the strace analysis to discover packages the "Alpine way.."

**Comment by sxa** [comment]
> Ok, thanks, we need to update the strace analysis to discover packages the "Alpine way.."

The equivalent of `rpm -qf` is `apk info --who-owns` so hopefully that will be most of what's needed to make it work :-)

**Comment by sxa** [comment]
@andrew-m-leonard You've moved this to Q2 but I'm not sure there's any further activity from the infrastructure side here. Do you have a separate issue to cover making the strace processes work with apk?

**Comment by andrew-m-leonard** [comment]
yes correct, i've raised this https://github.com/adoptium/temurin-build/issues/3750
