### ISSUE TITLE
VPC: Update win2022 image which currently takes ~40 minutes to perform windows updates

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3462]
This is causing a significantly delay in the testing of playbook changes on Windows. If we can do an update so that the Win2022 image has a later update then it will hopefully reduce the amount of time to get started.
```
14:06:57 TASK [Windows_Updates : Download and Install Windows Updates] ******************
14:42:35 changed: [127.0.0.1]
14:42:35 
14:42:35 TASK [Windows_Updates : Reboot machine if necessary] ***************************
14:47:52 changed: [127.0.0.1]
```

**Comment by sxa** [comment]
(Noting that the Win2022 VPC runs take over 20 minutes to get to the stage where they start yrunning the playbooks, and seemingly about one full minute for each ansible operation that runs on the virtual machine.

**Comment by steelhead31** [comment]
A new updated vagrant box has been added to the current VPC server, up to date with Windows 2022 as of 01/08/2024.
