### ISSUE TITLE
Orka mac x64 nodes don't always initialize successfully or take a very long time to...

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3484]
We have seen hung/timeout mac x64 Orka requests, eg: https://ci.adoptium.net/job/Test_openjdk22_hs_sanity.openjdk_x86-64_mac/30/console
```
14:21:55  Could not find any nodes with 'ci.role.test&&hw.arch.x86&&(sw.os.osx||sw.os.mac)&&!sw.os.osx.10_14' label
[Pipeline] timeout
14:21:55  Timeout set to expire in 5 min 0 sec
[Pipeline] {
[Pipeline] node
14:22:10  Still waiting to schedule task
14:22:10  All nodes of label ‘[ci.role.test&&hw.arch.x86&&(sw.os.osx||sw.os.mac)&&!sw.os.osx.10_14](https://ci.adoptium.net/label/ci.role.test&&hw.arch.x86&&(sw.os.osx%7C%7Csw.os.mac)&&!sw.os.osx.10_14/)’ are offline
14:26:55  Cancelling nested steps due to timeout
```
From watching the Jenkins node view, I can see the Orka Cloud initiates several times to attempt to start a VM, but each time the node fails to start the agent with message:
```
Waiting for SSH to be enabled
```
It eventually seems to give up, and try starting a new Orka VM.

@gdams I think we may need Orka support to take a look? again I think this is only an x64Mac problem.

**Comment by sxa** [comment]
Ref #2536 which is still open until the machines are confirmed as fully functional ;-)

**Comment by sxa** [comment]
@andrew-m-leonard @smlambert are we still seeing problems with this? Was any action taken to resolve it?

**Comment by smlambert** [comment]
I have not seen this issue in a long while.

Actions I am aware of: 
- https://github.com/adoptium/ci-jenkins-pipelines/pull/844
- https://github.com/adoptium/ci-jenkins-pipelines/pull/901

**Comment by andrew-m-leonard** [comment]
now seen for a long time, so hopefully not an issue now, lets close
