### ISSUE TITLE
Identify source of invalid crumb starting `6fc027348` and remediate

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3485]
We're getting one of these every five seconds in the jenkins system log and it's certainly been going for a few days and producing one of these roughly every five seconds and is accounting for about 25% of the lines in the log:

`2024-03-19 22:59:27.813+0000 [id=1216288]	WARNING	hudson.security.csrf.CrumbFilter#doFilter: Found invalid crumb 6fc027348e106dfb4ce52f6fbfc63c74dcae604f2e24e1efb46470f318326a67. If you are calling this URL with a script, please use the API Token instead. More information: https://www.jenkins.io/redirect/crumb-cannot-be-used-for-script`

We should identify the source of it and clean it up. It could just be someone's expired session.

**Comment by sxa** [comment]
Looks to be a session of @steelhead31 's relating to the [test-docker-sles12-s390x-1](https://ci.adoptium.net/computer/test%2Ddocker%2Dsles12%2Ds390x%2D1/) machine.

**Comment by steelhead31** [comment]
Think I've resolved this, a cached webpage I believe, in a crashed browser session, that wasn't visible
 anywhere...

**Comment by steelhead31** [comment]
Resolved.

**Comment by sxa** [comment]
Noting that the sensible string to check for if we want to identify this in the future is:
`WARNING	hudson.security.csrf.CrumbFilter#doFilter: No valid crumb was included in request for <jenkins url path> by <username>. Returning 403.`
Searching for `CrumbFilter.*403` works quite well.
