### ISSUE TITLE
ERROR: Cannot delete workspace: 

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#3489]
test-equinix_esxi-ubuntu2204-x64-1
test-ibmcloud-rhel7-x64-1

https://ci.adoptium.net/view/Test_grinder/job/Grinder/9283/console
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9280/console

Might be related with the reproducible comparing test run in docker.

**Comment by sophia-guo** [comment]
@sxa could anyone help this?

**Comment by sxa** [comment]
There's quite a lot of files on the equinix box which are owned by `root`:
- `jvmtest/system/reproducibleCompare/temurin-build` (March 22nd)
- `Test_openjdk17_hs_dev.openjdk_x86-64_linux/aqa-tests/TKG/output_17073971962040/hotspot_container_0/work/scratch/2/test-sharedtmp` (February 8th
- sophiag` (December 6th)

I've deleted all of those workspaces. Same for these on the `rhel7` system:

- `./DockerfileCheck/label/x64/variant/j9/version/jdk8u/pipelines` (March 4th)
- `Test_openjdk23_hs_dev.openjdk_x86-64_linux/aqa-tests/TKG/output_17080437741931/hotspot_container_0/work/scratch/2/sharedtmpdir` (Feb 15th)
- `Grinder/jvmtest/system/reproducibleCompare/openjdk-build` (March 22nd)

They've all been cleared now too
