### ISSUE TITLE
New Machine requirement: RHEL8 docker build machine for Linux/s390x

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3499]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): RHEL8+ Linux
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): s390x
- Provider (leave blank if it does not matter): Marist (All we have)
- Desired usage: Build machine running podman for the containers
- Any unusual specification/setup required: podman :-)
- How many of them are required: 1

Please explain what this machine is needed for: Build and use of a devkit on s390x. Our current build systems are RHEL7 and we need something with a usable docker/podman version supplied by RHEL. We have "hijacked" the RHEL8 test machine for builds for now, but we need a machine specced appropraitely for building. We should replace rhel79-2 first, and then look at replacing rhel79-1 (the previous live machine, as -2 was offline for a while) too

**Comment by steelhead31** [comment]
In progress, current plan is :  

1.  Decomission build-marist-rhel79-s390x-2 / 148.100.74.54 - to free up marist capacity for new machine
2.  Create new RHEL8 machine
3.  Run Ansbible playbooks, to build out standard machine
4.  Remove installed docker components
5.  Install podman 
6.  Commission in jenkins/wazuh/nagios
7.  Test :)
