### ISSUE TITLE
test-ibmcloud-ubuntu1604-x64-1 'Unable to delete '/home/jenkins/workspace/Grinder/jdkbinary''

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#3574]
test-ibmcloud-ubuntu1604-x64-1 'Unable to delete '/home/jenkins/workspace/Grinder/jdkbinary'', which makes it unavailable to use for test.

https://ci.adoptium.net/view/Test_grinder/job/Grinder/10140/console

**Comment by sophia-guo** [comment]
@Haroon-Khel Could you take a look to delete the workspace I suspect reproducible created something wrong?

**Comment by Haroon-Khel** [comment]
`j2sdk-image` in `/home/jenkins/workspace/Grinder/jdkbinary` is owned by root which is why jenkins is unable to delete it. Do you know how/why it was created?

**Comment by Haroon-Khel** [comment]
```
root@test-ibmcloud-ubuntu1604-x64-1:~# ls -la /home/jenkins/workspace/Grinder/jdkbinary
total 12
drwxr-xr-x 3 root    root    4096 May 29 20:09 .
drwxrwxr-x 4 jenkins jenkins 4096 May 29 20:09 ..
drwxr-xr-x 2 root    root    4096 May 29 20:09 j2sdk-image
```

**Comment by Haroon-Khel** [comment]
I've removed it so you can rerun your job

**Comment by sophia-guo** [comment]
> https://github.com/adoptium/infrastructure/issues/3574#issuecomment-2140162375

No, no idea.
