### ISSUE TITLE
New Machine requirement: Ubuntu 24.04 docker host systems

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3585]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Linux Ubuntu 24.04
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): All? But start with x64
- Provider (leave blank if it does not matter): Probably Azure for now
- Desired usage: dockerhost system
- Any unusual specification/setup required: Needs to be Ubuntu 24.04 and should have qemu-user-static installed
- How many of them are required: 1

Please explain what this machine is needed for:

Ubuntu is used for our docker host systems for running builds and hosting static docker containers. Ubuntu 24.04 is the new LTS version and therefore it makes sense to be doing some testing on this version. It has a later kernel than previous versions and will therefore be able to support more containerized distributions which may require features of the newer kernel (See [this comment](https://github.com/adoptium/infrastructure/issues/3501#issuecomment-2091101160) for the sort of potential effects of not running the newer kernels)

While Ubuntu 20.04 is not out of support until April next year, we should look at starting to migrate away from it to the newer LTS version where possible.

- [x] **x64** _(Maybe replace one of the Azure dockerhost systems that can't be used for VMs with an AMD one running Ubuntu 24.04?). Also noting that we have Solaris VMs on the Azure dockerhosts so we need to be careful when decommissioning any of the existing ones that we do not lose those VMs.
- [x] **aarch64** (Will require co-ordination with Equinix to see if there are any problems with updating the Ubuntu 20.04 Altra machines) although we can use OSUOSL in the meantime to do some testing)
- [x] **ppc64le**
- [x] **s390x**

**Comment by Haroon-Khel** [comment]
The s390x machine upgraded fine
```
root@dockerhost-marist-ubuntu2404-s390x-1:~# uname -r
6.8.0-41-generic
root@dockerhost-marist-ubuntu2404-s390x-1:~# cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

**Comment by Haroon-Khel** [comment]
The ppc64le dockerhost has been upgraded
```
root@dockerhost-osuosl-ubuntu2404-ppc64le-1:~# uname -r
6.8.0-41-generic
root@dockerhost-osuosl-ubuntu2404-ppc64le-1:~# cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```
Jenkins name and labels for each static docker container have been updated
