### ISSUE TITLE
New Machine requirement UBI static docker containers

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3586]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Linux UBI 8 and 9
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): x64, aarch64, ppc64le, s390x
- Provider (leave blank if it does not matter):
- Desired usage: Testing on this OS. 
- Any unusual specification/setup required:
- How many of them are required: 1 of each 

Please explain what this machine is needed for:

We ship and support ubi9-minimal docker containers with Temurin as official dockerhub images but currently do not perform any testing on UBI. There is currently [one UBI8 image](https://ci.adoptium.net/computer/test%2Ddocker%2Dubi8%2Dx64%2D3/) in jenkins but that is hosted on the skytap dockerhost machine which is offline due to insufficient credits being available to run it, so we are not running testing on any UBI versions just now. Since this is an official docker image which we shipped we are running quite a risk by  not actively testing on it on a regular basis.

The initial support for UBI8 images was created in https://github.com/adoptium/infrastructure/issues/2532 - this should be expanded to cover ubi9 (minimal version if possible, and if not ensure we understand why) and enable ubi8 again.

Related (other OSs)
- https://github.com/adoptium/infrastructure/issues/3041
- https://github.com/adoptium/infrastructure/issues/3501
- https://github.com/adoptium/infrastructure/issues/2478

**Comment by sxa** [comment]
FYI @Haroon-Khel this is the issue I mentioned earlier today

**Comment by Haroon-Khel** [comment]
x64 ubi9 container up https://ci.adoptium.net/computer/test-docker-ubi9-x64-1/
jdk21 v1.0.1-release branch https://ci.adoptium.net/job/AQA_Test_Pipeline/277/console

**Comment by Haroon-Khel** [comment]
s390x and arm64 images cant install `libnss3.so` 
```
1.962 No match for argument: libnss3.so
1.989 Error: Unable to find a match: libnss3.so
```
And even though the x64 image couldnt find libnss3.so, it didnt cause an error during building.

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/computer/test-docker-ubi9-armv8l-1/ without libnss3.so

https://ci.adoptium.net/job/AQA_Test_Pipeline/278/console (jdk21 v1.0.1-release branch)

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/computer/test-docker-ubi9-s390x-1/ without libnss3.so

https://ci.adoptium.net/job/AQA_Test_Pipeline/279/console (jdk21 v1.0.1-release branch)

**Comment by Haroon-Khel** [comment]
ppc64le ubi9 image finding it hard to install the last line of dependencies
```
 > [28/30] RUN dnf install -y git make gcc xorg-x11-server-Xvfb libXrender libXi libXtst fontconfig fakeroot procps-ng hostname diffutils:                                                                          
0.574 Updating Subscription Management repositories.                                                                                                                                                                
0.575 Unable to read consumer identity                                                                                                                                                                              
0.579 
0.579 This system is not registered with an entitlement server. You can use subscription-manager to register.
0.579 
10.85 CentOS Stream 9 - BaseOS                        393  B/s | 3.9 kB     00:10    
10.85 Errors during downloading metadata for repository 'baseos':
10.85   - Downloading successful, but checksum doesn't match. Calculated: 53823a7862af9565f586a1bca3e3e31582fd80f4429eda9a4bcb5bdf9369ecce281ef67aa6b356db4cb9653e210b487cdfdfc28718fe805a1f1ccf915d05e039(sha512)  Expected: 21b9e356f319100ed0373db6e66e1cfb275a907b82f0eb74ee18bcd25b95445a6c1a319dea65383bbc691375eab05838802b383a35fda74c1f49612c1c737fd1(sha512) 
10.86 Error: Failed to download metadata for repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**Comment by sxa** [comment]
> s390x and arm64 images cant install `libnss3.so`
> 
> ```
> 1.962 No match for argument: libnss3.so
> 1.989 Error: Unable to find a match: libnss3.so
> ```
> 
> And even though the x64 image couldnt find libnss3.so, it didnt cause an error during building.

`/usr/lib64/libnss3.so` is supplied in the `nss` package so that entry in the dockerfile probably shouldn't be there.
I'm a bit surprised that there is a difference in the same UBI version between architectures in how it handles this condition though, but 🤷🏻

**Comment by Haroon-Khel** [comment]
> x64 ubi9 container up https://ci.adoptium.net/computer/test-docker-ubi9-x64-1/ https://ci.adoptium.net/job/AQA_Test_Pipeline/277/console (jdk21 v1.0.1-release branch)

All tests passed

> https://ci.adoptium.net/computer/test-docker-ubi9-armv8l-1/ without libnss3.so
> 
> https://ci.adoptium.net/job/AQA_Test_Pipeline/278/console (jdk21 v1.0.1-release branch)

The only failure javax/imageio/plugins/png/ReadPngRGBImageWithTRNSChunk.java


> https://ci.adoptium.net/computer/test-docker-ubi9-s390x-1/ without libnss3.so
> 
> https://ci.adoptium.net/job/AQA_Test_Pipeline/279/console (jdk21 v1.0.1-release branch)

Only failure jdk/jfr/jcmd/TestJcmdDump.java

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/computer/test-docker–ubi9-ppc64le-1/ is up. Getting this error when updating openssl-libs
```
Error: Transaction test error:
  file /usr/lib64/ossl-modules/fips.so from install of openssl-libs-1:3.2.2-1.el9.ppc64le conflicts with file from package openssl-fips-provider-3.0.7-2.el9.ppc64le
```
https://ci.adoptium.net/job/AQA_Test_Pipeline/288/console (jdk21 v1.0.1-release branch)

**Comment by Haroon-Khel** [comment]
> https://ci.adoptium.net/job/AQA_Test_Pipeline/288/console (jdk21 v1.0.1-release branch)

ubi9 ppc64le jdk21 failures v1.0.1-release branch

```
compiler/rtm/locking/TestRTMSpinLoopCount.java
jdk/jfr/jcmd/TestJcmdDump.java
com/sun/jdi/FinalizerTest.java
```

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/computer/test-docker-ubi8-ppc64le-1/ is up
https://ci.adoptium.net/job/AQA_Test_Pipeline/289/console jdk21 v1.0.1-release

**Comment by sxa** [comment]
> > https://ci.adoptium.net/job/AQA_Test_Pipeline/288/console (jdk21 v1.0.1-release branch)
> 
> ubi9 ppc64le jdk21 failures v1.0.1-release branch

Can we try and get JDK17 and 8 kicked off over the weekend too? I'm expecting it to show the same failures as Amazon Linux 2023 but it would be good to be able to see if that's true in practice :-)

**Comment by sxa** [comment]
> > https://ci.adoptium.net/job/AQA_Test_Pipeline/288/console (jdk21 v1.0.1-release branch)
> ubi9 ppc64le jdk21 failures v1.0.1-release branch
> 
> ```
> compiler/rtm/locking/TestRTMSpinLoopCount.java
> ```
Interesting - don't think I've seen that one as a regular failure so it likelyt needs some investigating - I think the other two are known / intermittent.

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/computer/test-docker-ubi8-x64-1/ is up
https://ci.adoptium.net/job/AQA_Test_Pipeline/290/console (jdk21 v1.0.1-release branch)

**Comment by Haroon-Khel** [comment]
> Can we try and get JDK17 and 8 kicked off over the weekend too? I'm expecting it to show the same failures as Amazon Linux 2023 but it would be good to be able to see if that's true in practice :-)

Yep, I just want to get a single jdk version test pipeline done before running the rest over the weekend

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/computer/test-docker-ubi8-armv8-1/ is up
https://ci.adoptium.net/job/AQA_Test_Pipeline/291/console jdk21 v1.0.1-release branch

**Comment by Haroon-Khel** [comment]
AQA test pipelines for UBI8 and 9 machines. JDK 8 11 and 17 v1.0.1-release branch

test-docker-ubi9-x64-1
- https://ci.adoptium.net/job/AQA_Test_Pipeline/294/console

test-docker-ubi9-s390x-1
- https://ci.adoptium.net/job/AQA_Test_Pipeline/295/console

test-docker-ubi9-armv8l-1
- https://ci.adoptium.net/job/AQA_Test_Pipeline/296/console

test-docker-ubi9-ppc64le-1
- https://ci.adoptium.net/job/AQA_Test_Pipeline/297/console

test-docker-ubi8-x64-1
- https://ci.adoptium.net/job/AQA_Test_Pipeline/298/console

test-docker-ubi8-armv8-1
- https://ci.adoptium.net/job/AQA_Test_Pipeline/299/console

test-docker-ubi8-ppc64le-1
- https://ci.adoptium.net/job/AQA_Test_Pipeline/300/console

**Comment by sxa** [comment]
For consideration in terms of reporting: https://github.com/adoptium/infrastructure/issues/3600
This issue is a good example as it has lots of runs so it would be good to think about how best to summarise the information.

**Comment by Haroon-Khel** [comment]
# JDK8 11 17 v1.0.1-release branch failures only

## test-docker-ubi9-x64-1

Test suite | Result ✅⚠️❌ 
---|---
[JDK8 extended openjdk](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_linux/188/tapResults/) | java/net/Inet6Address/B6206527.java
java/net/ipv6tests/B6521014.java
java/nio/file/Files/probeContentType/Basic.java
jdk_security3
java/rmi/activation/rmidViaInheritedChannel/InheritedChannelNotServerSocket.java
java/rmi/activation/rmidViaInheritedChannel/RmidViaInheritedChannel.java

**Comment by Haroon-Khel** [comment]
Grouping all of the common failures:
Known issue https://github.com/adoptium/infrastructure/issues/2949
java/net/Inet6Address/B6206527.java
java/net/ipv6tests/B6521014.java

Known issue https://github.com/adoptium/infrastructure/issues/2631
java/nio/file/Files/probeContentType/Basic.java

jdk_security3

sun/security/krb5/auto/rcache_usemd5.sh

java/time/test/java/time/format/TestUTCParse.java

sun/security/tools/keytool/autotest.sh

**Comment by sxa** [comment]
@Haroon-Khel Is there any additional work needed here or do we have enough live UBI machines now?

**Comment by Haroon-Khel** [comment]
The machines are live, this can be closed
