### ISSUE TITLE
Ansibilize jenkins setup

### ISSUE THREAD

**Issue by gdams** [adoptium/infrastructure#359]
We should create an ansible playbook to create ci.adoptopenjdk.net and ci-jck.adoptopenjdk.net

**Comment by Willsparker** [comment]
I know this is on hold at the minute, but whats the list of requirements for a machine to run Jenkins?

**Comment by gdams** [comment]
See https://www.digitalocean.com/community/tutorials/how-to-install-jenkins-on-ubuntu-16-04 for the basic instructions. It's more about how we then restore the configuration from backup. And all the other crazy dependencies that we have installed on that machine.
