### ISSUE TITLE
update mac test agents  with jq installation

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#3593]
Reproducible comparing tests need jq installed. orka doesn't have jq installed. 

https://github.com/adoptium/temurin-build/pull/3844#issuecomment-2159163710

- Missing install - jq
- Platform - orka

@gdams 

Static ones also don't have jq installed [test-macincloud-macos1201-x64-2](https://ci.adoptium.net/computer/test-macincloud-macos1201-x64-2)

@steelhead31

**Comment by steelhead31** [comment]
Jq has been installed on the static test mac nodes.

**Comment by steelhead31** [comment]
@gdams is updating the orka templates to include jq. I'll close this issue when it is completed.

**Comment by steelhead31** [comment]
The orka base image has now been updated to include jq, so closing this issue. FYI @sophia-guo @smlambert
