### ISSUE TITLE
New Machine requirement: Alpine 3.20 on x64 and aarch64

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3605]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Alpine Linux
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): x64 and aarch64 (One of each)
- Provider (leave blank if it does not matter): 
- Desired usage: Docker static container to verify the new Alpine release
- Any unusual specification/setup required:
- How many of them are required: At least 1 of each architecture

Please explain what this machine is needed for: The New Alpine release came out a few weeks ago and there has been a request to bump the version we use: https://github.com/docker-library/official-images/pull/16989

Regardless of whether we look at adding that just now, we should aim to test on the latest Alpine.

**Comment by Haroon-Khel** [comment]
x64 https://ci.adoptium.net/computer/test-docker-alpine320-x64-1
  - AQA pipeline https://ci.adoptium.net/job/AQA_Test_Pipeline/327/console
aarch64 https://ci.adoptium.net/computer/test-docker-alpine320-armv8-1/
  - AQA pipeline https://ci.adoptium.net/job/AQA_Test_Pipeline/328/console

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/job/AQA_Test_Pipeline/329/console  Arm64 Alpine320 JDK21 Triage

**Extended openjdk**
`java/nio/file/DirectoryStream/SecureDS.java`, known issue https://github.com/adoptium/infrastructure/issues/3522, existing upstream issue for arm32 linux, https://bugs.openjdk.org/browse/JDK-8214078. Suspected that SecureDS is not supported on Alpine
`jdk/jfr/jcmd/TestJcmdDump.java`, we're seeing this failure on multiple platforms, not exclusive to alpine320

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/job/AQA_Test_Pipeline/329/console  Arm64 Alpine320 JDK21 Triage

**Extended openjdk**
`java/nio/file/DirectoryStream/SecureDS.java`, known issue https://github.com/adoptium/infrastructure/issues/3522, existing upstream issue for arm32 linux, https://bugs.openjdk.org/browse/JDK-8214078. Suspected that SecureDS is not supported on Alpine
`jdk/jfr/jcmd/TestJcmdDump.java`, we're seeing this failure on multiple platforms, not exclusive to alpine320

**Comment by Haroon-Khel** [comment]
We're still seeing [JDK11 tests fail to build](https://github.com/adoptium/infrastructure/issues/3529) on alpine when the default java on Alpine is JDK21, see the AQA pipeline for x64 in https://github.com/adoptium/infrastructure/issues/3605#issuecomment-2203047752

**Comment by Haroon-Khel** [comment]
x64 Alpine 320 Triage 

**JDK8**
Extended openjdk https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_alpine-linux/112/tapResults/

jdk/jfr/event/compiler/TestCompilerInlining.java https://github.com/adoptium/aqa-tests/issues/3730 suggests it fails intermittently

**JDK17**
Extended openjdk https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux/169/

java/nio/file/DirectoryStream/SecureDS.java see https://github.com/adoptium/infrastructure/issues/3605#issuecomment-2210806270

**JDK21**
Extended openjdk https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_x86-64_alpine-linux/52/tapResults/

java/nio/file/DirectoryStream/SecureDS.java see https://github.com/adoptium/infrastructure/issues/3605#issuecomment-2210806270

com/sun/jdi/FinalizerTest.java Intermittent failure https://github.com/adoptium/aqa-tests/issues/5300#issuecomment-2122878975

**Comment by Haroon-Khel** [comment]
This issue can be closed too. Both machines are live and the test failures are triaged
