### ISSUE TITLE
Update Adoptium s390x build machine with latest RHEL built DevKit b03

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3618]
The latest s390x DevKit b03 needs downloading onto the Adoptium s390x rhel build machines:
https://ci.adoptium.net/job/build-scripts/job/utils/job/devkit/job/gcc-11.3.0/job/devkit-gcc-11.3.0-linux-s390x/56/

into local location /usr/local/devkit/s390x-on-s390x.RH7

**Comment by sxa** [comment]
Updated on the build host machine (Copied tarball to /usr/local, re-run the [rhel7_docker_image_updater](https://ci.adoptium.net/job/rhel7_docker_image_updater) job). That ought to be enough but we'll see since it looks like [a JDk21 build](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-s390x-temurin/57/) has been scheduled on it

**Comment by andrew-m-leonard** [comment]
> Updated on the build host machine (Copied tarball to /usr/local, re-run the [rhel7_docker_image_updater](https://ci.adoptium.net/job/rhel7_docker_image_updater) job). That ought to be enough but we'll see since it looks like [a JDk21 build](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-s390x-temurin/57/) has been scheduled on it

@sxa  That's failed as devkit.info mismatches:
```
12:19:20  WARNING: Devkit /usr/local/devkit/s390x-on-s390x.RH7/devkit.info does not match required release and architecture:
12:19:20         Required:   ADOPTIUM_DEVKIT_RELEASE=s390x-on-s390x.RH7
12:19:20         /usr/local/devkit/s390x-on-s390x.RH7: ADOPTIUM_DEVKIT_RELEASE=gcc-11.3.0-Centos7.9.2009-b03
```

The DevKit build devkit.info will contain gcc-11.3.0-Centos7.9.2009-b03
Shall we change the folder to /usr/local/devkit/gcc-11.3.0-Centos7.9.2009-b03 ?

**Comment by andrew-m-leonard** [comment]
@sxa I have updated my devkit b03 PR to update s390x to use tag "gcc-11.3.0-Centos7.9.2009-b03", as that is what is built into the devkit.info.
   https://github.com/adoptium/ci-jenkins-pipelines/pull/1056/files
We just need to then rename the local devkit folder to: /usr/local/devkit/gcc-11.3.0-Centos7.9.2009-b03
?

**Comment by sxa** [comment]
I've rebuilt it under https://ci.adoptium.net/job/rhel7_docker_image_updater/label=build-marist-rhel8-s390x-1/31 so it will hopefully be ready to go now. It's a bit of a pain because it currently requires an update to the job if the name changes.

**Comment by sxa** [comment]
https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-s390x-temurin/58 is running on the new image with the new parameter.

**Comment by andrew-m-leonard** [comment]
> https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-linux-s390x-temurin/58 is running on the new image with the new parameter.

Looks good, thanks
```
16:25:40  ADOPTIUM_DEVKIT_RELEASE=gcc-11.3.0-Centos7.9.2009-b03
16:25:40  ADOPTIUM_DEVKIT_TARGET=s390x-linux-gnu
16:25:40  Using matching DevKit from location /usr/local/devkit/gcc-11.3.0-Centos7.9.2009-b03
```

**Comment by andrew-m-leonard** [comment]
Looks good thanks Stewart
