### ISSUE TITLE
Intermittent Orka VM issues

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/infrastructure#3620]
This issue is to log intermittent problems with Orka VMs

**Comment by andrew-m-leonard** [comment]
https://ci.adoptium.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk8u/job/jdk8u-mac-x64-temurin/164/console
```
12:41:37  clang: error: no such file or directory: '/dev/fd/8'
12:41:37  clang: error: no input files
12:41:37  dtrace: failed to compile script /Users/admin/workspace/workspace/build-scripts-pr-tester/build-test/jobs/jdk8u/jdk8u-mac-x64-temurin/workspace/build/src/hotspot/src/os/bsd/dtrace/hs_private.d: Preprocessor failed to process input program
12:41:37  make[6]: *** [/Users/admin/workspace/workspace/build-scripts-pr-tester/build-test/jobs/jdk8u/jdk8u-mac-x64-temurin/workspace/build/src/build/macosx-x86_64-normal-server-release/hotspot/bsd_amd64_compiler2/product/../generated/dtracefiles/hs_private.h] Error 1
```

**Comment by andrew-m-leonard** [comment]
https://ci.adoptium.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk8u/job/jdk8u-mac-x64-temurin/166/console
```
11:20:50  Checked out repo:
[Pipeline] sh
11:20:51  + git status
11:20:51  xcrun: error: unable to load libxcrun (dlopen(/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib, 0x0005): tried: '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (no such file), '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need ''))).
```

**Comment by gdams** [comment]
> https://ci.adoptium.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk8u/job/jdk8u-mac-x64-temurin/166/console
> 
> ```
> 11:20:50  Checked out repo:
> [Pipeline] sh
> 11:20:51  + git status
> 11:20:51  xcrun: error: unable to load libxcrun (dlopen(/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib, 0x0005): tried: '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (no such file), '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need ''))).
> ```

@andrew-m-leonard I know what's happening with the `git status` command on the JDK8u build. We need to switch xcode back to 15.1 once we've completed the build with `sudo xcode-select --switch /` otherwise it's trying to use a really old git from xcode 11.7 which won't work on Arm64.

**Comment by gdams** [comment]
> > > https://ci.adoptium.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk8u/job/jdk8u-mac-x64-temurin/166/console
> > > ```
> > > 11:20:50  Checked out repo:
> > > [Pipeline] sh
> > > 11:20:51  + git status
> > > 11:20:51  xcrun: error: unable to load libxcrun (dlopen(/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib, 0x0005): tried: '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (no such file), '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need ''))).
> > > ```
> > 
> > 
> > @andrew-m-leonard I know what's happening with the `git status` command on the JDK8u build. We need to switch xcode back to 15.1 once we've completed the build with `sudo xcode-select --switch /` otherwise it's trying to use a really old git from xcode 11.7 which won't work on Arm64.
> 
> @gdams thanks for the clue. It's odd it only happens for the pr-tester generated build jobs, the normal pipeline build jobs are fine. I am wondering if there's some Mac x64 arm cross compiling logic that's not run under pr-tester.......?

it's the `git status` command that is being run to get the commit to create the github PR status against AFAIK

**Comment by andrew-m-leonard** [comment]
> > > > https://ci.adoptium.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk8u/job/jdk8u-mac-x64-temurin/166/console
> > > > ```
> > > > 11:20:50  Checked out repo:
> > > > [Pipeline] sh
> > > > 11:20:51  + git status
> > > > 11:20:51  xcrun: error: unable to load libxcrun (dlopen(/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib, 0x0005): tried: '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (no such file), '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need ''))).
> > > > ```
> > > 
> > > 
> > > @andrew-m-leonard I know what's happening with the `git status` command on the JDK8u build. We need to switch xcode back to 15.1 once we've completed the build with `sudo xcode-select --switch /` otherwise it's trying to use a really old git from xcode 11.7 which won't work on Arm64.
> > 
> > 
> > @gdams thanks for the clue. It's odd it only happens for the pr-tester generated build jobs, the normal pipeline build jobs are fine. I am wondering if there's some Mac x64 arm cross compiling logic that's not run under pr-tester.......?
> 
> it's the `git status` command that is being run to get the commit to create the github PR status against AFAIK. I would say the most logical step would be to reset xcode after a build to `/` in the temurin build scripts

@gdams thanks, will give it a go, for review please: https://github.com/adoptium/temurin-build/pull/3873

**Comment by andrew-m-leonard** [comment]
> https://ci.adoptium.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk8u/job/jdk8u-mac-x64-temurin/166/console
> 
> ```
> 11:20:50  Checked out repo:
> [Pipeline] sh
> 11:20:51  + git status
> 11:20:51  xcrun: error: unable to load libxcrun (dlopen(/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib, 0x0005): tried: '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (no such file), '/Applications/Xcode-11.7.app/Contents/Developer/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need ''))).
> ```

This particular pr-tester failure is now fixed by https://github.com/adoptium/temurin-build/pull/3873
