### ISSUE TITLE
Upgrade Fedora 35 on the VPC to Fedora 40

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3662]
[Fedora 35](https://github.com/adoptium/infrastructure/blob/master/ansible/vagrant/Vagrantfile.Fedora35) on the VPC has been EOL for more than a year. It should be upgraded to one that is still maintained either 39 or 40. Preference is for 40 since it is the latest

**Comment by steelhead31** [comment]
CLOSED AS DONE, VPC supports F40
