### ISSUE TITLE
All test jobs failing on sparcv9-solaris machines - xvfb Error in setting egid to 0: Not owner

### ISSUE THREAD

**Issue by smlambert** [adoptium/infrastructure#3668]
Please set the title to indicate the test name and machine name where known.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
- a link into recent `Test_` job on https://ci.adoptium.net which showed the failure
  - https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.functional_sparcv9_solaris_testList_0/4/console
  - https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.openjdk_sparcv9_solaris_testList_0/4/console
- **Hyperlink** to re-run in Grinder: 
- Is there an existing issue elsewhere covering this?
- Which machine(s) does it work on? none
- Which machine(s) does it fail on? build-siteox-solaris10u11-sparcv9-1  and test-siteox-solaris10u11-sparcv9-1

Any other details:
```
10:32:21  Running tests...
[Pipeline] sh
10:32:22  + /usr/X11/bin/Xvfb :2 -screen 0 1024x768x24 
10:32:22  _XSERVTransmkdir: Mode of /tmp/.X11-unix should be set to 1777
10:32:22  _XSERVTransmkdir: this may cause subsequent errors
10:32:22  _XSERVTransSocketCreateListener: failed to bind listener
10:32:22  _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
10:32:22  _XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
10:32:22  _XSERVTransNAMEDOpenPipe: Can't open /tmp/.X11-pipe/X2
10:32:22  _XSERVTransOpen: transport open failed for named/build-siteox-solaris10u11-sparcv9-1:2
10:32:22  _XSERVTransMakeAllCOTSServerListeners: failed to open listener for named
10:32:22  Error in setting egid to 0: Not owner
[Pipeline] echo
10:32:22  env.DISPLAY is :2
```

**Comment by sxa** [comment]
@steelhead31 Could you take a look at this one please? IIRC xvfb is generally suid root so this error is surprising.

**Comment by steelhead31** [comment]
have investigated and corrected a missing sticky bit on /tmp/.X11 , a Test appears to work ok on test-siteox ..  [https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.functional_sparcv9_solaris_testList_0/5/](https://ci.adoptium.net/job/Test_openjdk8_hs_sanity.functional_sparcv9_solaris_testList_0/5/)

Just checking on build.. and then will do some further testing to ensure.

**Comment by smlambert** [comment]
Thanks @steelhead31 !

**Comment by steelhead31** [comment]
Last but not least, forgot to add this on.. this job has  NO Xvfb error..   
https://ci.adoptium.net/job/Grinder/10600/console
