### ISSUE TITLE
JDK22: Riscv: Test jobs randomly "Terminated" on specific riscv machines

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3669]
**Summary**
The JDK22 Riscv test jobs seem to fail near-constantly with makefile "Terminated" messages.

**Details**
Most JDK22 Riscv test jobs seem to fail near-constantly, but only after July 3rd mid-afternoon-ish, and only on specific machines.

This may or may not be a related issue, as the test jobs that pass are *only* run on a specific subset of the riscv machines, and the jobs that fail are *only* run on a separate subset. There doesn't appear to be a difference in tag, so it may just be random chance.

Machines where failures are seen:
- [test-rise-ubuntu2404-riscv64-7](https://ci.adoptium.net/computer/test-rise-ubuntu2404-riscv64-7)
- [test-rise-ubuntu2404-riscv64-6](https://ci.adoptium.net/computer/test-rise-ubuntu2404-riscv64-6)
- [test-rise-ubuntu2404-riscv64-4](https://ci.adoptium.net/computer/test-rise-ubuntu2404-riscv64-4)
- [test-rise-ubuntu2404-riscv64-5](https://ci.adoptium.net/computer/test-rise-ubuntu2404-riscv64-5)

Machines where passes are seen:
- [test-rise-ubuntu2310-riscv64-10](https://ci.adoptium.net/computer/test-rise-ubuntu2310-riscv64-10)
- [test-rise-ubuntu2310-riscv64-9](https://ci.adoptium.net/computer/test-rise-ubuntu2310-riscv64-9)
- [test-rise-ubuntu2310-riscv64-8](https://ci.adoptium.net/computer/test-rise-ubuntu2310-riscv64-8)
- [test-rise-ubuntu2404-riscv64-3](https://ci.adoptium.net/computer/test-rise-ubuntu2404-riscv64-3)
- [test-rise-ubuntu2310-riscv64-2](https://ci.adoptium.net/computer/test-rise-ubuntu2310-riscv64-2)
- [test-rise-ubuntu2404-riscv64-1](https://ci.adoptium.net/computer/test-rise-ubuntu2404-riscv64-1)

Example of a job where one testlist always seems to pass, and the other always seems to fail:
https://ci.adoptium.net/job/Test_openjdk22_hs_extended.perf_riscv64_linux/27/

**Error message**
Many look like this:
```
17:01:15  make[1]: *** [compile.mk:45: compile] Terminated
17:01:15  make: *** [makefile:87: compile] Terminated
17:01:15  Terminated
17:01:15  143
```

But there are variations, like this one:
```
16:51:40  make[2]: *** [settings.mk:356: testList-..] Terminated
16:51:40  make[1]: *** [makefile:70: _testList] Terminated
16:51:40  make: *** [parallelList.mk:8: testList_0] Terminated
16:51:40  Terminated
```

I'm lumping these all in together due to the similarity in jdk version, platform, and the "Terminated" part, but these may prove to be separate issues after the first problem is resolved.

**URLs**
- https://ci.adoptium.net/job/Test_openjdk22_hs_sanity.perf_riscv64_linux_testList_0/16/
- https://ci.adoptium.net/job/Test_openjdk22_hs_sanity.functional_riscv64_linux/27/
- https://ci.adoptium.net/job/Test_openjdk22_hs_extended.openjdk_riscv64_linux/29/
- https://ci.adoptium.net/job/Test_openjdk22_hs_extended.system_riscv64_linux_testList_0/17/
- https://ci.adoptium.net/job/Test_openjdk22_hs_special.openjdk_riscv64_linux_rerun/14/
- https://ci.adoptium.net/job/Test_openjdk22_hs_extended.perf_riscv64_linux_testList_0/7/
- https://ci.adoptium.net/job/Test_openjdk22_hs_sanity.system_riscv64_linux_testList_2/15/
- https://ci.adoptium.net/job/Test_openjdk22_hs_sanity.system_riscv64_linux_testList_0/16/
- https://ci.adoptium.net/job/Test_openjdk22_hs_sanity.openjdk_riscv64_linux_testList_0/16/
- https://ci.adoptium.net/job/Test_openjdk22_hs_sanity.openjdk_riscv64_linux_testList_1/15/

**Comment by sxa** [comment]
Had a (perhaps obvious) brainwave ... The issue is that some of the agent definitions are pointing to duplicate machines which is why we're getting terminations - two test jobs running on a single machine will be trying to clear up each others processes. The config in jenkins is correct, but i suspect when the definition was duplicated the machine started up connecting to the machine that was the source of the copy and didn't get a disconnect/reconnect cycle. `-7` was connected to `-4`'s IP,
Sorted (and for `-5`) so this should no longer occur. Please reopen if for some reason it's seen again.
