### ISSUE TITLE
Discuss upgrading Ansible on the VPC server

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3679]
The version of ansible on the [vpc server](https://github.com/adoptium/infrastructure/blob/490dcbac85b0246da0968474e5887f20a3c200c5/ansible/inventory.yml#L31) is outdated.
```
root@infra-ibmcloud-vagrant-x64:~# ansible --version
ansible 2.9.16
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
```
it does not work well with the python 3.12, which is the latest python version present on the vagrant boxes hosted on the vpc server. As a result we have to implement hacky solutions to get our playbooks to run on the hosted vagrant boxes, see https://github.com/adoptium/infrastructure/pull/3663

We should be using a version of ansible >2.15 at least. But before upgrading, we need to discuss if certain OSs/vagrant boxes will be affected

**Comment by Haroon-Khel** [comment]
ping @steelhead31

**Comment by steelhead31** [comment]
@Haroon-Khel , I've had a look into upgrading ansible on the host, but the O/S itself requires an upgrade..  see https://github.com/orgs/adoptium/projects/34/views/7?pane=issue&itemId=68479156 , the host upgrade is currently blocked, as Im awaiting an update on whether its possible to back up the host, prior to risking the host upgrade. Ping me if you fancy a chat about both of these issues, and we can do some planning/have some more discussion.

**Comment by sxa** [comment]
Related: Upgrade the OS on the vagrant host: https://github.com/adoptium/infrastructure/issues/3589

**Comment by sxa** [comment]
@steelhead31 I guess this is probably done now that the VPC server has been upgraded?

**Comment by steelhead31** [comment]
@sxa Indeed, ansible and the vagrant server are currently as up to date as we'd like :).

I'll close this issue,  fixed via https://github.com/adoptium/infrastructure/issues/3729
