### ISSUE TITLE
New Machine requirement: Fedora 40 static docker test system

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3689]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Linux, Fedora 40
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): at least x64 and aarch64.
- Provider (leave blank if it does not matter): 
- Desired usage: Testing on the current version of Fedora. This should probably result in any versions prior to 38 being replaced as they are now out of support
- Any unusual specification/setup required:
- How many of them are required: 1

**Comment by Haroon-Khel** [comment]
ref https://github.com/adoptium/infrastructure/pull/3694

https://ci.adoptium.net/computer/test-docker-fedora40-x64-1/ https://ci.adoptium.net/job/AQA_Test_Pipeline/343/console
https://ci.adoptium.net/computer/test-docker-fedora40-armv8-1/ https://ci.adoptium.net/job/AQA_Test_Pipeline/346/console

**Comment by Haroon-Khel** [comment]
The x64 aqa pipeline was aborted during its end due to the jenkins upgrade. I can check which jobs were aborted and rerun them

**Comment by Haroon-Khel** [comment]
test-docker-fedora40-armv8-1 Triage

#### Release Summary Report for AQA_Test_Pipeline 
**Report generated at:** Tue, 06 Aug 2024 11:03:20 GMT 
 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=66ad2660d24e1b006ea744ea&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=66ad2660d24e1b006ea744ea) 
Jenkins Build URL https://ci.adoptium.net/job/AQA_Test_Pipeline/346/ 
Started by user Haroon Khel at 02/08/2024, 19:20:39 

 --- 

 --- 

[**Test_openjdk11_hs_extended.openjdk_aarch64_linux**](https://ci.adoptium.net/job/Test_openjdk11_hs_extended.openjdk_aarch64_linux/203/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=testList+TESTLIST=jdk_tools_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=test-docker-fedora40-armv8-1&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=11&amp;USER_CREDENTIALS_ID=&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=200&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "11.0.24" 2024-07-16
OpenJDK Runtime Environment Temurin-11.0.24+8 (build 11.0.24+8)
OpenJDK 64-Bit Server VM Temurin-11.0.24+8 (build 11.0.24+8, mixed mode)
```
</details>

[jdk_tools_1](https://trss.adoptium.net/output/test?id=66af8a1cd24e1b006e71dae2) => [deep history 4/5 passed](https://trss.adoptium.net/deepHistory?testId=66af8a1cd24e1b006e71dae2) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28b0d24e1b006ea764f7&buildName=Test_openjdk11_hs_extended.openjdk_aarch64_linux&testId=66af8a1cd24e1b006e71dae2&testName=jdk_tools_1)

[**Test_openjdk11_hs_sanity.system_aarch64_linux**](https://ci.adoptium.net/job/Test_openjdk11_hs_sanity.system_aarch64_linux/890/) ❌ FAILURE ❌
Rerun [all](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=sanity.system&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=test-docker-fedora40-armv8-1&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=11&amp;USER_CREDENTIALS_ID=&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=system&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=200&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "11.0.24" 2024-07-16
OpenJDK Runtime Environment Temurin-11.0.24+8 (build 11.0.24+8)
OpenJDK 64-Bit Server VM Temurin-11.0.24+8 (build 11.0.24+8, mixed mode)
```
</details>

[TestJlmRemoteClassNoAuth_0](https://trss.adoptium.net/output/test?id=66b079cdd24e1b006e11bc07) => [deep history 8/9 passed](https://trss.adoptium.net/deepHistory?testId=66b079cdd24e1b006e11bc07) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28b0d24e1b006ea76501&buildName=Test_openjdk11_hs_sanity.system_aarch64_linux&testId=66b079cdd24e1b006e11bc07&testName=TestJlmRemoteClassNoAuth_0)

[**Test_openjdk8_hs_extended.openjdk_aarch64_linux**](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_aarch64_linux/183/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=testList+TESTLIST=hotspot_jre_0,jdk_net_0,jdk_net_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=test-docker-fedora40-armv8-1&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=8&amp;USER_CREDENTIALS_ID=&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=200&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "1.8.0_422"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_422-b05)
OpenJDK 64-Bit Server VM (Temurin)(build 25.422-b05, mixed mode)
```
</details>

[hotspot_jre_0](https://trss.adoptium.net/output/test?id=66b05e9dd24e1b006e03feb9) => [deep history 4/5 passed](https://trss.adoptium.net/deepHistory?testId=66b05e9dd24e1b006e03feb9) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28b0d24e1b006ea764f9&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66b05e9dd24e1b006e03feb9&testName=hotspot_jre_0)
[jdk_net_1](https://trss.adoptium.net/output/test?id=66b05e9dd24e1b006e03fecc) => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=66b05e9dd24e1b006e03fecc) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28b0d24e1b006ea764f9&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66b05e9dd24e1b006e03fecc&testName=jdk_net_1)
[jdk_net_0](https://trss.adoptium.net/output/test?id=66b05e9dd24e1b006e03fecb) => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=66b05e9dd24e1b006e03fecb) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28b0d24e1b006ea764f9&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66b05e9dd24e1b006e03fecb&testName=jdk_net_0)

**Comment by Haroon-Khel** [comment]
test-docker-fedora40-x64-1 Triage

#### Release Summary Report for AQA_Test_Pipeline 
**Report generated at:** Tue, 06 Aug 2024 13:58:42 GMT 
 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=66ad2227d24e1b006ea6ea86&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=66ad2227d24e1b006ea6ea86) 
Jenkins Build URL https://ci.adoptium.net/job/AQA_Test_Pipeline/343/ 
Started by user Haroon Khel at 02/08/2024, 19:06:28 

 --- 

 --- 

[**Test_openjdk11_hs_extended.system_x86-64_linux**](https://ci.adoptium.net/job/Test_openjdk11_hs_extended.system_x86-64_linux/919/) ❌ ABORTED ❌
Rerun [all](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=extended.system&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=test-docker-fedora40-x64-1&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=11&amp;USER_CREDENTIALS_ID=&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=system&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=200&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "11.0.24" 2024-07-16
OpenJDK Runtime Environment Temurin-11.0.24+8 (build 11.0.24+8)
OpenJDK 64-Bit Server VM Temurin-11.0.24+8 (build 11.0.24+8, mixed mode)
```
</details>

[MiniMix_10m_1](https://trss.adoptium.net/output/test?id=66b1dffcd24e1b006e9882bd) => [deep history 2/3 passed](https://trss.adoptium.net/deepHistory?testId=66b1dffcd24e1b006e9882bd) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2289d24e1b006ea70817&buildName=Test_openjdk11_hs_extended.system_x86-64_linux&testId=66b1dffcd24e1b006e9882bd&testName=MiniMix_10m_1)

[**Test_openjdk21_hs_extended.openjdk_x86-64_linux**](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_x86-64_linux/79/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=testList+TESTLIST=jdk_jdi_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=test-docker-fedora40-x64-1&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=21&amp;USER_CREDENTIALS_ID=&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=200&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)
```
</details>

[jdk_jdi_0](https://trss.adoptium.net/output/test?id=66b0851fd24e1b006e16dca5) => [deep history 2/3 passed](https://trss.adoptium.net/deepHistory?testId=66b0851fd24e1b006e16dca5) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2289d24e1b006ea7083b&buildName=Test_openjdk21_hs_extended.openjdk_x86-64_linux&testId=66b0851fd24e1b006e16dca5&testName=jdk_jdi_0)

[**Test_openjdk8_hs_extended.openjdk_x86-64_linux**](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_linux/199/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=testList+TESTLIST=jdk_net_0,jdk_net_1,jdk_security3_0,jdk_security3_1,jdk_jfr_0,jdk_jfr_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=test-docker-fedora40-x64-1&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=8&amp;USER_CREDENTIALS_ID=&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=200&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "1.8.0_422"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_422-b05)
OpenJDK 64-Bit Server VM (Temurin)(build 25.422-b05, mixed mode)
```
</details>

[jdk_net_0](https://trss.adoptium.net/output/test?id=66ade41ed24e1b006ebb2a59) => [deep history 2/6 passed](https://trss.adoptium.net/deepHistory?testId=66ade41ed24e1b006ebb2a59) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2289d24e1b006ea70801&buildName=Test_openjdk8_hs_extended.openjdk_x86-64_linux&testId=66ade41ed24e1b006ebb2a59&testName=jdk_net_0)
[jdk_security3_0](https://trss.adoptium.net/output/test?id=66ade41ed24e1b006ebb2a56) => [deep history 0/6 passed](https://trss.adoptium.net/deepHistory?testId=66ade41ed24e1b006ebb2a56) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2289d24e1b006ea70801&buildName=Test_openjdk8_hs_extended.openjdk_x86-64_linux&testId=66ade41ed24e1b006ebb2a56&testName=jdk_security3_0)
[jdk_net_1](https://trss.adoptium.net/output/test?id=66ade41ed24e1b006ebb2a51) => [deep history 2/6 passed](https://trss.adoptium.net/deepHistory?testId=66ade41ed24e1b006ebb2a51) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2289d24e1b006ea70801&buildName=Test_openjdk8_hs_extended.openjdk_x86-64_linux&testId=66ade41ed24e1b006ebb2a51&testName=jdk_net_1)
[jdk_security3_1](https://trss.adoptium.net/output/test?id=66ade41ed24e1b006ebb2a57) => [deep history 0/6 passed](https://trss.adoptium.net/deepHistory?testId=66ade41ed24e1b006ebb2a57) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2289d24e1b006ea70801&buildName=Test_openjdk8_hs_extended.openjdk_x86-64_linux&testId=66ade41ed24e1b006ebb2a57&testName=jdk_security3_1)
[jdk_jfr_0](https://trss.adoptium.net/output/test?id=66ade41ed24e1b006ebb2a71) => [deep history 2/5 passed](https://trss.adoptium.net/deepHistory?testId=66ade41ed24e1b006ebb2a71) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2289d24e1b006ea70801&buildName=Test_openjdk8_hs_extended.openjdk_x86-64_linux&testId=66ade41ed24e1b006ebb2a71&testName=jdk_jfr_0)
[jdk_jfr_1](https://trss.adoptium.net/output/test?id=66ade41ed24e1b006ebb2a72) => [deep history 2/5 passed](https://trss.adoptium.net/deepHistory?testId=66ade41ed24e1b006ebb2a72) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2289d24e1b006ea70801&buildName=Test_openjdk8_hs_extended.openjdk_x86-64_linux&testId=66ade41ed24e1b006ebb2a72&testName=jdk_jfr_1)

**Comment by Haroon-Khel** [comment]
Test failures are triaged and the containers are up and running
