### ISSUE TITLE
September 2024: New Machine requirement: Fedora 41 static docker test system

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3690]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Linux, Fedora 41
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): At least x64 and aarch64
- Provider (leave blank if it does not matter):
- Desired usage: Testing on the latest distribution version
- Any unusual specification/setup required:
- How many of them are required: 1

Note that any systems that are earlier than Fedora 39 should probably be decomissioned at this time as that will be out of support in November

**Comment by Haroon-Khel** [comment]
ref https://github.com/adoptium/infrastructure/pull/3694

https://ci.adoptium.net/computer/test-docker-fedora41-x64-1/ https://ci.adoptium.net/job/AQA_Test_Pipeline/344/console
https://ci.adoptium.net/computer/test-docker-fedora41-armv8-1/ https://ci.adoptium.net/job/AQA_Test_Pipeline/347/console

**Comment by Haroon-Khel** [comment]
test-docker-fedora41-x64-1 triage

#### Release Summary Report for AQA_Test_Pipeline 
**Report generated at:** Tue, 06 Aug 2024 11:10:19 GMT 
 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=66ad2227d24e1b006ea6ea84&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=66ad2227d24e1b006ea6ea84) 
Jenkins Build URL https://ci.adoptium.net/job/AQA_Test_Pipeline/344/ 
Started by user Haroon Khel at 02/08/2024, 19:07:02 

 --- 

 --- 

[**Test_openjdk21_hs_extended.openjdk_x86-64_linux**](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_x86-64_linux/80/) ❌ ABORTED ❌
Rerun [all](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=extended.openjdk&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=test-docker-fedora41-x64-1&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=21&amp;USER_CREDENTIALS_ID=&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=200&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)
```
</details>

[jdk_jfr_0](https://trss.adoptium.net/output/test?id=66b1e088d24e1b006e98832f) => [deep history 3/4 passed](https://trss.adoptium.net/deepHistory?testId=66b1e088d24e1b006e98832f) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2286d24e1b006ea707cd&buildName=Test_openjdk21_hs_extended.openjdk_x86-64_linux&testId=66b1e088d24e1b006e98832f&testName=jdk_jfr_0)

[**Test_openjdk21_hs_extended.perf_x86-64_linux**](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.perf_x86-64_linux/73/) ❌ ABORTED ❌

[**Test_openjdk21_hs_sanity.openjdk_x86-64_linux**](https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.openjdk_x86-64_linux/232/) ❌ ABORTED ❌
Rerun [all](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=sanity.openjdk&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=test-docker-fedora41-x64-1&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=21&amp;USER_CREDENTIALS_ID=&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=200&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)
```
</details>

[jdk_lang_0](https://trss.adoptium.net/output/test?id=66b1e5f9d24e1b006e9977b4) => [deep history 9/10 passed](https://trss.adoptium.net/deepHistory?testId=66b1e5f9d24e1b006e9977b4) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2286d24e1b006ea707ce&buildName=Test_openjdk21_hs_sanity.openjdk_x86-64_linux&testId=66b1e5f9d24e1b006e9977b4&testName=jdk_lang_0)

[**Test_openjdk8_hs_extended.openjdk_x86-64_linux**](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_linux/200/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=testList+TESTLIST=jdk_net_0,jdk_net_1,jdk_security3_0,jdk_security3_1,jdk_jfr_0,jdk_jfr_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=test-docker-fedora41-x64-1&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=8&amp;USER_CREDENTIALS_ID=&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=200&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "1.8.0_422"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_422-b05)
OpenJDK 64-Bit Server VM (Temurin)(build 25.422-b05, mixed mode)
```
</details>

[jdk_net_0](https://trss.adoptium.net/output/test?id=66adb875d24e1b006eb44024) => [deep history 2/6 passed](https://trss.adoptium.net/deepHistory?testId=66adb875d24e1b006eb44024) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2286d24e1b006ea707b6&buildName=Test_openjdk8_hs_extended.openjdk_x86-64_linux&testId=66adb875d24e1b006eb44024&testName=jdk_net_0)
[jdk_net_1](https://trss.adoptium.net/output/test?id=66adb875d24e1b006eb44025) => [deep history 2/6 passed](https://trss.adoptium.net/deepHistory?testId=66adb875d24e1b006eb44025) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2286d24e1b006ea707b6&buildName=Test_openjdk8_hs_extended.openjdk_x86-64_linux&testId=66adb875d24e1b006eb44025&testName=jdk_net_1)
[jdk_security3_0](https://trss.adoptium.net/output/test?id=66adb875d24e1b006eb44029) => [deep history 0/6 passed](https://trss.adoptium.net/deepHistory?testId=66adb875d24e1b006eb44029) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2286d24e1b006ea707b6&buildName=Test_openjdk8_hs_extended.openjdk_x86-64_linux&testId=66adb875d24e1b006eb44029&testName=jdk_security3_0)
[jdk_security3_1](https://trss.adoptium.net/output/test?id=66adb875d24e1b006eb4402a) => [deep history 0/6 passed](https://trss.adoptium.net/deepHistory?testId=66adb875d24e1b006eb4402a) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2286d24e1b006ea707b6&buildName=Test_openjdk8_hs_extended.openjdk_x86-64_linux&testId=66adb875d24e1b006eb4402a&testName=jdk_security3_1)
[jdk_jfr_0](https://trss.adoptium.net/output/test?id=66adb875d24e1b006eb44045) => [deep history 2/5 passed](https://trss.adoptium.net/deepHistory?testId=66adb875d24e1b006eb44045) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2286d24e1b006ea707b6&buildName=Test_openjdk8_hs_extended.openjdk_x86-64_linux&testId=66adb875d24e1b006eb44045&testName=jdk_jfr_0)
[jdk_jfr_1](https://trss.adoptium.net/output/test?id=66adb875d24e1b006eb44046) => [deep history 2/5 passed](https://trss.adoptium.net/deepHistory?testId=66adb875d24e1b006eb44046) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad2286d24e1b006ea707b6&buildName=Test_openjdk8_hs_extended.openjdk_x86-64_linux&testId=66adb875d24e1b006eb44046&testName=jdk_jfr_1)

**Comment by Haroon-Khel** [comment]
test-docker-fedora41-armv8-1 triage

#### Release Summary Report for AQA_Test_Pipeline 
**Report generated at:** Tue, 06 Aug 2024 11:11:03 GMT 
 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=66ad2660d24e1b006ea744e8&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=66ad2660d24e1b006ea744e8) 
Jenkins Build URL https://ci.adoptium.net/job/AQA_Test_Pipeline/347/ 
Started by user Haroon Khel at 02/08/2024, 19:21:41 

 --- 

 --- 

[**Test_openjdk21_hs_extended.openjdk_aarch64_linux**](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_aarch64_linux/98/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=testList+TESTLIST=jdk_jfr_1,jdk_imageio_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=test-docker-fedora41-armv8-1&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=21&amp;USER_CREDENTIALS_ID=&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=200&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)
```
</details>

[jdk_imageio_0](https://trss.adoptium.net/output/test?id=66b08db8d24e1b006e1b9127) => [deep history 2/4 passed](https://trss.adoptium.net/deepHistory?testId=66b08db8d24e1b006e1b9127) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28add24e1b006ea764b4&buildName=Test_openjdk21_hs_extended.openjdk_aarch64_linux&testId=66b08db8d24e1b006e1b9127&testName=jdk_imageio_0)
[jdk_jfr_1](https://trss.adoptium.net/output/test?id=66b08db8d24e1b006e1b911d) => [deep history 2/4 passed](https://trss.adoptium.net/deepHistory?testId=66b08db8d24e1b006e1b911d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28add24e1b006ea764b4&buildName=Test_openjdk21_hs_extended.openjdk_aarch64_linux&testId=66b08db8d24e1b006e1b911d&testName=jdk_jfr_1)

[**Test_openjdk8_hs_extended.openjdk_aarch64_linux**](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_aarch64_linux/184/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=testList+TESTLIST=jdk_net_0,jdk_net_1,jdk_security3_0,jdk_security3_1,jdk_jfr_0,jdk_imageio_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=test-docker-fedora41-armv8-1&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=8&amp;USER_CREDENTIALS_ID=&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=200&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "1.8.0_422"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_422-b05)
OpenJDK 64-Bit Server VM (Temurin)(build 25.422-b05, mixed mode)
```
</details>

[jdk_net_0](https://trss.adoptium.net/output/test?id=66adad04d24e1b006eb2ae04) => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=66adad04d24e1b006eb2ae04) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28add24e1b006ea7649b&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66adad04d24e1b006eb2ae04&testName=jdk_net_0)
[jdk_net_1](https://trss.adoptium.net/output/test?id=66adad04d24e1b006eb2ae05) => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=66adad04d24e1b006eb2ae05) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28add24e1b006ea7649b&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66adad04d24e1b006eb2ae05&testName=jdk_net_1)
[jdk_security3_0](https://trss.adoptium.net/output/test?id=66adad04d24e1b006eb2ae0a) => [deep history 3/5 passed](https://trss.adoptium.net/deepHistory?testId=66adad04d24e1b006eb2ae0a) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28add24e1b006ea7649b&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66adad04d24e1b006eb2ae0a&testName=jdk_security3_0)
[jdk_security3_1](https://trss.adoptium.net/output/test?id=66adad04d24e1b006eb2ae0b) => [deep history 3/5 passed](https://trss.adoptium.net/deepHistory?testId=66adad04d24e1b006eb2ae0b) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28add24e1b006ea7649b&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66adad04d24e1b006eb2ae0b&testName=jdk_security3_1)
[jdk_jfr_0](https://trss.adoptium.net/output/test?id=66adad04d24e1b006eb2ae25) => [deep history 3/5 passed](https://trss.adoptium.net/deepHistory?testId=66adad04d24e1b006eb2ae25) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28add24e1b006ea7649b&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66adad04d24e1b006eb2ae25&testName=jdk_jfr_0)
[jdk_imageio_0](https://trss.adoptium.net/output/test?id=66adad04d24e1b006eb2ae2b) => [deep history 3/5 passed](https://trss.adoptium.net/deepHistory?testId=66adad04d24e1b006eb2ae2b) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28add24e1b006ea7649b&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66adad04d24e1b006eb2ae2b&testName=jdk_imageio_0)

**Comment by Haroon-Khel** [comment]
Containers are up and tests are triaged
