### ISSUE TITLE
September 2024: New Machine requirement: Ubuntu 24.10 static docker machine

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3691]
I need to request a new machine:

- New machine operating system (e.g. linux/windows/macos/solaris/aix): Linux, Ubuntu 24.10
- New machine architecture (e.g. x64/aarch32/arm32/ppc64/ppc64le/sparc): At least x64 and aarch64
- Provider (leave blank if it does not matter):
- Desired usage: Testing on the latest distribution version
- Any unusual specification/setup required:
- How many of them are required: 1

**Comment by Haroon-Khel** [comment]
ref https://github.com/adoptium/infrastructure/pull/3694

https://ci.adoptium.net/computer/test-docker-ubuntu2410-x64-1/ https://ci.adoptium.net/job/AQA_Test_Pipeline/345/console

https://ci.adoptium.net/computer/test-docker-ubuntu2410-armv8-1/ https://ci.adoptium.net/job/AQA_Test_Pipeline/348/console

**Comment by Haroon-Khel** [comment]
test-docker-ubuntu2410-armv8-1 triage

#### Release Summary Report for AQA_Test_Pipeline 
**Report generated at:** Tue, 06 Aug 2024 16:56:09 GMT 
 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=66ad2660d24e1b006ea744e6&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=66ad2660d24e1b006ea744e6) 
Jenkins Build URL https://ci.adoptium.net/job/AQA_Test_Pipeline/348/ 
Started by user Haroon Khel at 02/08/2024, 19:28:20 

 --- 

 --- 

[**Test_openjdk17_hs_extended.openjdk_aarch64_linux**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux/187/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=testList+TESTLIST=jdk_nio_1,jdk_tools_0,jdk_tools_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=test-docker-ubuntu2410-armv8-1&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=17&amp;USER_CREDENTIALS_ID=&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=200&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment Temurin-17.0.12+7 (build 17.0.12+7)
OpenJDK 64-Bit Server VM Temurin-17.0.12+7 (build 17.0.12+7, mixed mode, sharing)
```
</details>

[jdk_nio_1](https://trss.adoptium.net/output/test?id=66af768bd24e1b006e6452b4) => [deep history 4/5 passed](https://trss.adoptium.net/deepHistory?testId=66af768bd24e1b006e6452b4) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28abd24e1b006ea76460&buildName=Test_openjdk17_hs_extended.openjdk_aarch64_linux&testId=66af768bd24e1b006e6452b4&testName=jdk_nio_1)
[jdk_tools_0](https://trss.adoptium.net/output/test?id=66af768bd24e1b006e6452d0) => [deep history 4/5 passed](https://trss.adoptium.net/deepHistory?testId=66af768bd24e1b006e6452d0) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28abd24e1b006ea76460&buildName=Test_openjdk17_hs_extended.openjdk_aarch64_linux&testId=66af768bd24e1b006e6452d0&testName=jdk_tools_0)
[jdk_tools_1](https://trss.adoptium.net/output/test?id=66af768bd24e1b006e6452c7) => [deep history 4/5 passed](https://trss.adoptium.net/deepHistory?testId=66af768bd24e1b006e6452c7) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28abd24e1b006ea76460&buildName=Test_openjdk17_hs_extended.openjdk_aarch64_linux&testId=66af768bd24e1b006e6452c7&testName=jdk_tools_1)

[**Test_openjdk21_hs_extended.openjdk_aarch64_linux**](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_aarch64_linux/99/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=testList+TESTLIST=jdk_jdi_0,jdk_jdi_1,jdk_imageio_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=test-docker-ubuntu2410-armv8-1&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=21&amp;USER_CREDENTIALS_ID=&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=200&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)
```
</details>

[jdk_jdi_0](https://trss.adoptium.net/output/test?id=66b06a66d24e1b006e09bfc5) => [deep history 3/4 passed](https://trss.adoptium.net/deepHistory?testId=66b06a66d24e1b006e09bfc5) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28abd24e1b006ea76473&buildName=Test_openjdk21_hs_extended.openjdk_aarch64_linux&testId=66b06a66d24e1b006e09bfc5&testName=jdk_jdi_0)
[jdk_jdi_1](https://trss.adoptium.net/output/test?id=66b06a66d24e1b006e09bfce) => [deep history 3/4 passed](https://trss.adoptium.net/deepHistory?testId=66b06a66d24e1b006e09bfce) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28abd24e1b006ea76473&buildName=Test_openjdk21_hs_extended.openjdk_aarch64_linux&testId=66b06a66d24e1b006e09bfce&testName=jdk_jdi_1)
[jdk_imageio_0](https://trss.adoptium.net/output/test?id=66b06a66d24e1b006e09bfcb) => [deep history 2/4 passed](https://trss.adoptium.net/deepHistory?testId=66b06a66d24e1b006e09bfcb) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28abd24e1b006ea76473&buildName=Test_openjdk21_hs_extended.openjdk_aarch64_linux&testId=66b06a66d24e1b006e09bfcb&testName=jdk_imageio_0)

[**Test_openjdk8_hs_extended.openjdk_aarch64_linux**](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_aarch64_linux/185/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&amp;TARGET=testList+TESTLIST=hotspot_jre_1,jdk_beans_1,jdk_net_0,jdk_net_1,jdk_jfr_0,jdk_imageio_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=test-docker-ubuntu2410-armv8-1&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.2-release&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=8&amp;USER_CREDENTIALS_ID=&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;UPSTREAM_JOB_NAME=&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;OPENJDK_SHA=&amp;NUM_MACHINES=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=200&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "1.8.0_422"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_422-b05)
OpenJDK 64-Bit Server VM (Temurin)(build 25.422-b05, mixed mode)
```
</details>

[hotspot_jre_1](https://trss.adoptium.net/output/test?id=66aea4dfd24e1b006ef26533) => [deep history 4/5 passed](https://trss.adoptium.net/deepHistory?testId=66aea4dfd24e1b006ef26533) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28abd24e1b006ea76456&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66aea4dfd24e1b006ef26533&testName=hotspot_jre_1)
[jdk_net_0](https://trss.adoptium.net/output/test?id=66aea4dfd24e1b006ef26549) => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=66aea4dfd24e1b006ef26549) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28abd24e1b006ea76456&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66aea4dfd24e1b006ef26549&testName=jdk_net_0)
[jdk_beans_1](https://trss.adoptium.net/output/test?id=66aea4dfd24e1b006ef26538) => [deep history 4/5 passed](https://trss.adoptium.net/deepHistory?testId=66aea4dfd24e1b006ef26538) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28abd24e1b006ea76456&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66aea4dfd24e1b006ef26538&testName=jdk_beans_1)
[jdk_net_1](https://trss.adoptium.net/output/test?id=66aea4dfd24e1b006ef26541) => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=66aea4dfd24e1b006ef26541) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28abd24e1b006ea76456&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66aea4dfd24e1b006ef26541&testName=jdk_net_1)
[jdk_jfr_0](https://trss.adoptium.net/output/test?id=66aea4dfd24e1b006ef26561) => [deep history 3/5 passed](https://trss.adoptium.net/deepHistory?testId=66aea4dfd24e1b006ef26561) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28abd24e1b006ea76456&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66aea4dfd24e1b006ef26561&testName=jdk_jfr_0)
[jdk_imageio_0](https://trss.adoptium.net/output/test?id=66aea4dfd24e1b006ef26567) => [deep history 3/5 passed](https://trss.adoptium.net/deepHistory?testId=66aea4dfd24e1b006ef26567) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66ad28abd24e1b006ea76456&buildName=Test_openjdk8_hs_extended.openjdk_aarch64_linux&testId=66aea4dfd24e1b006ef26567&testName=jdk_imageio_0)

**Comment by Haroon-Khel** [comment]
ref the jdk_tools failures, we are seeing the same failures in ubuntu2404 https://github.com/adoptium/aqa-tests/issues/5383#issue-2348320504

**Comment by Haroon-Khel** [comment]
Im going to close this issue since all of the failures have been triaged
