### ISSUE TITLE
Upgrade dockerhost-equinix-ubuntu2004-armv82-1 to Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3692]
Now that we have Ubuntu 24.04 we should look at upgrading one of the Altras up to this level. This will also support the requirements of https://github.com/adoptium/infrastructure/issues/3498.

Noting that we have previously had some problems with the boot process on these machines so it is essential that whoever does this is comfortable with connecting to the console of these machines.

Part of https://github.com/adoptium/infrastructure/issues/3588

**Comment by sxa** [comment]
@Haroon-Khel Can you add some notes in here for historic reference about some of the problems + solutions you hit while doing this please?

**Comment by Haroon-Khel** [comment]
Ill describe the kernel panic and go through solutions.

After upgrading the kernel and all of the packages, the machine required a reboot. During the reboot the system hit a kernel panic, which took me to the GRUB prompt.

At the GRUB prompt I set the vmlinuz and initrd paths

```
grub> linux /boot/vmlinuz-$new_kernel_version-generic root=/path/to/root-filesystem
grub> initrd /boot/initrd.img-$new_kernel_version-generic
```
This allowed the system to boot, but still hit the kernel panic on subsequent reboot. To fix this, boot back up using the above steps in the GRUB prompt. Then run update the initramfs
```
~# update-initramfs -u -k $new_kernel_version-generic
```
Then the system should be fine after a reboot
