### ISSUE TITLE
Upgrade one x64 dockerhost to ubuntu 24.04

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3693]
Now that we have Ubuntu 24.04 we should look at upgrading one of the x64 dockerhost systems up to this level as it is the latest LTS and likely to be consistent with the kernel version that many people will now be using. This will also support the requirements of https://github.com/adoptium/infrastructure/issues/3498.

I would naively suggest we do this with [dockerhost-azure-ubuntu2204-x64-2](https://ci.adoptium.net/computer/dockerhost%2Dazure%2Dubuntu2204%2Dx64%2D2) purely because it will keep the name of `ubuntu2204-x64-1` "reasonable" (if we upgraded -1 we'd be leaving a 2204-x64-2 without a -1 which always looks a bit odd ...)

Part of https://github.com/adoptium/infrastructure/issues/3588

**Comment by Haroon-Khel** [comment]
dockerhost-azure-ubuntu2204-x64-2 has been upgraded to [dockerhost-azure-ubuntu2404-x64-1](https://ci.adoptium.net/computer/dockerhost-azure-ubuntu2404-x64-1/). Its hw.dockerhost labels have been updated. The upgrade went smoothly, no errors

**Comment by sxa** [comment]
Awesome! Can you install `qemu-user-static` on it if it's not already there and see if the jdk11u/riscv64 build will run on it?
Ref: https://github.com/adoptium/infrastructure/issues/3498#issuecomment-2154226629

**Comment by Haroon-Khel** [comment]
https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk11u/job/jdk11u-evaluation-linux-riscv64-temurin/39/console failed

```
13:29:47  Compiling 7 properties into resource bundles for jdk.jshell
13:29:47  Compiling 13 properties into resource bundles for jdk.javadoc
13:29:47  /home/jenkins/workspace/build-scripts/jobs/evaluation/jobs/jdk11u/jdk11u-evaluation-linux-riscv64-temurin/workspace/build/src/build/linux-riscv64-normal-server-release/hotspot/variant-server/support/adlc/all-ad-src.ad(0) Semantic Error: :File read error, no input read
13:29:47  
13:29:47  gmake[3]: *** [gensrc/GensrcAdlc.gmk:182: /home/jenkins/workspace/build-scripts/jobs/evaluation/jobs/jdk11u/jdk11u-evaluation-linux-riscv64-temurin/workspace/build/src/build/linux-riscv64-normal-server-release/hotspot/variant-server/support/adlc/_adlc_run.marker] Error 1
13:29:47  gmake[3]: *** Waiting for unfinished jobs....
13:29:53  gmake[2]: *** [make/Main.gmk:265: hotspot-server-gensrc] Error 2
13:29:53  gmake[2]: *** Waiting for unfinished jobs....
13:29:53  Compiling 117 files for BUILD_java.compiler.interim
13:30:06  Compiling 394 files for BUILD_jdk.compiler.interim
13:31:39  Compiling 299 files for BUILD_jdk.javadoc.interim
13:32:20  
13:32:20  ERROR: Build failed for targets 'product-images legacy-jre-image test-image static-libs-image' in configuration 'linux-riscv64-normal-server-release' (exit code 2) 
13:32:20  
13:32:20  === Output from failing command(s) repeated here ===
13:32:20  * For target hotspot_variant-server_support_adlc_adlc_run:
13:32:20  /home/jenkins/workspace/build-scripts/jobs/evaluation/jobs/jdk11u/jdk11u-evaluation-linux-riscv64-temurin/workspace/build/src/build/linux-riscv64-normal-server-release/hotspot/variant-server/support/adlc/all-ad-src.ad(0) Semantic Error: :File read error, no input read
13:32:20  
13:32:20  
13:32:20  * All command lines available in /home/jenkins/workspace/build-scripts/jobs/evaluation/jobs/jdk11u/jdk11u-evaluation-linux-riscv64-temurin/workspace/build/src/build/linux-riscv64-normal-server-release/make-support/failure-logs.
13:32:20  === End of repeated output ===
```

**Comment by Haroon-Khel** [comment]
The previous job, https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk11u/job/jdk11u-evaluation-linux-riscv64-temurin/38/console which ran on dockerhost-azure-ubuntu2204-x64-1, failed in the same way

**Comment by sxa** [comment]
Given that https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk11u/job/jdk11u-evaluation-linux-riscv64-temurin/40/console from the HEAD of the repository I wonder if the `jdk-11.0.25+2_adopt` tags are not being generated in a useful way as part of the mirroring process. I think this can be split out into a separate issue.

**Comment by sxa** [comment]
@Haroon-Khel Can this be closed now that we have an x64 Ubuntu24.04 dockerhost machine available?
