### ISSUE TITLE
Docker error message with test-ibmcloud-rhel7-x64-1

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#3717]
Reproducible compare tests run on  https://ci.adoptium.net/computer/test-ibmcloud-rhel7-x64-1/ will consistently hit the issue with error message like

```
10:40:42  docker: failed to register layer: symlink ../a0b6a018cc497a3d95ea4f449e24cd883f3826647b7c3b469f05d683e56907ee/diff /var/lib/docker/overlay2/l/XVAC3AEAM6DZ4IXSKPGV2D7DZC: no such file or directory.
10:40:42  See 'docker run --help'.
```

https://ci.adoptium.net/job/Test_openjdk23_hs_special.system_x86-64_linux_testList_0/14/console

Which suggests the docker issue and need to restart the docker. It is not related with this PR, will open an separate issue in infra repo.Please set the title to indicate the test name and machine name where known.

No issue with another available agents https://ci.adoptium.net/computer/test%2Dibmcloud%2Dubuntu1604%2Dx64%2D1/, which has same lables
https://ci.adoptium.net/label/ci.role.test&&hw.arch.x86&&sw.os.linux&&!%28centos6%7C%7Crhel6%29&&sw.tool.docker/

**Comment by sophia-guo** [comment]
Reported from https://github.com/adoptium/temurin-build/pull/3913#issuecomment-2293645831

**Comment by sxa** [comment]
Docker restarted and I'm able to start a centos:7 container 👍🏻
