### ISSUE TITLE
Upgrade/Rebuild IBM VPC Host To Ubuntu 24.04

### ISSUE THREAD

**Issue by steelhead31** [adoptium/infrastructure#3729]
The old IBMCloud VPC host has been temporarily replaced with 2 x Azure hosts.

This should allow the IBMCloud host to be rebuilt in a clean fashion at Ubuntu 24.04

**Comment by AdamBrousseau** [comment]
@steelhead31 @sxa now that #3589 is resolved. Can this host be destroyed and replaced? Or do you need anything off of it first?

**Comment by steelhead31** [comment]
@AdamBrousseau yes I think it can, @Haroon-Khel can you confirm, that you have finished attempting to upgrade this machine , and that it can be rebuilt ?

**Comment by Haroon-Khel** [comment]
Yep. The machine can be rebuilt. Thanks Adam

**Comment by AdamBrousseau** [comment]
Can I get some system requirements so I can allocate the right machine?

Current machine is bare metal
2x 2.1GHz Intel Xeon-Skylake (4110-SILVER)
32GB Ram
1TB Disk

I will try to allocate a new machine of a similar cost which, I assume, will get you a newer/faster processor.
Is 32GB ram appropriate?
Is 1TB disk appropriate?

**Comment by steelhead31** [comment]
I think the 32Gb Ram and a 1Tb disk are perfectly fine,  it should allow us to run a few vagrant / qemu VMs simultaneously.

**Comment by sxa** [comment]
The only other comment is make is to make sure it had a good core count. The 4110 silver is 8-core, 16-thread according to https://ark.intel.com/content/www/us/en/ark/products/123547/intel-xeon-silver-4110-processor-11m-cache-2-10-ghz.html for comparison, but as you say I expect that something of similar cost will have at least those numbers too!

**Comment by AdamBrousseau** [comment]
Ok thanks for the feedback. It's looking more expensive for a new equivalent system. Possibly the quote does not take into account the IBM discount. Turns out I can reload the existing system with a new OS. I will go ahead and replace it with Ubuntu 24 and let you know when it's ready.

**Comment by AdamBrousseau** [comment]
I have added [Stewart's keys](https://github.com/sxa.keys) to the root account. Let me know if you need anything else.

**Comment by sxa** [comment]
> I have added [Stewart's keys](https://github.com/sxa.keys) to the root account. Let me know if you need anything else.

Thanks! I've added your keys too now @Haroon-Khel @steelhead31 :-)

**Comment by steelhead31** [comment]
@Haroon-Khel / @sxa  I'll build this machine out tomorrow.
