### ISSUE TITLE
`CURL_OPENSSL_3' not found` from git on test-osuosl-ubuntu1604-ppc64le-

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#3776]
Please set the title to indicate the test name and machine name where known.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)? sanity.system
- a link into recent `Test_` job on https://ci.adoptium.net which showed the failure 
- **Hyperlink** to re-run in Grinder: Can't get it from the testList_0 but [this](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=sanity.system&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&RERUN_ITERATIONS=0&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=11&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk11u&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-linux-ppc64le-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=dev&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&TEST_TIME=120&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=system&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=366&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=Dynamic) forced to the correct machine should reprocuce it
- Is there an existing issue elsewhere covering this? Unknown
- Which machine(s) does it fail on? [test-osuosl-ubuntu1604-ppc64le-](https://ci.adoptium.net/computer/test%2Dosuosl%2Dubuntu1604%2Dppc64le%2D1/)
- Which machine(s) does it work on? Presumably everything else if this hasn't been reported elsewhere

Any other details:
Here is the failure:
```
11:50:50  Cloning the remote Git repository
11:50:51  ERROR: Error cloning remote repo 'origin'
11:50:51  hudson.plugins.git.GitException: Command "git fetch --tags --progress -- https://github.com/adoptium/aqa-tests.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
11:50:51  stdout: 
11:50:51  stderr: /usr/local/libexec/git-core/git-remote-https: /usr/lib/powerpc64le-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/local/libexec/git-core/git-remote-https)
```

**Comment by sxa** [comment]
Machine was marked offline as this caused an issue during the release pipelines.

**Comment by sxa** [comment]
Related: https://github.com/adoptium/infrastructure/issues/3793

**Comment by sxa** [comment]
@smlambert to check if this happens on other machines, and if it's only happening on older LInux releases we can close this.

**Comment by smlambert** [comment]
https://github.com/adoptium/aqa-tests/issues/5691#issuecomment-2418401810
https://github.com/adoptium/aqa-tests/issues/5689#issuecomment-2417646340
https://github.com/adoptium/aqa-tests/issues/5690#issuecomment-2417430760 -  test-osuosl-ubuntu1604-ppc64le-1

**Comment by sxa** [comment]
This machine had a self-compiled git 2.15 in `/usr/local/bin` which was being used and was causing the problem. The system installed git was 2.25 and works well. I have therefore created `/usr/local/bin/git-broken` and moved the `git*` binaries from /usr/local/bin. The machine now works as tested at https://ci.adoptium.net/job/Grinder/11734/console

It is,. however, somewhat odd that the `test-osuosl-ubuntu1804-ppc64le-1` machine has 2.17 installed (it does not have another git in /usr/local/bin, therefore [this problem is not seen on there](https://ci.adoptium.net/job/Grinder/11735/console).
