### ISSUE TITLE
Remove redundant Alpine JDK installs

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/infrastructure#3804]
Looks like we're installing boot jdks on Alpine using two different roles in our playbooks

In the common role (zulu bianries and nightlies) https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Common/tasks/Alpine.yml 

and in the adoptopenjdk_install role (only for jdk17 and 21)
https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/adoptopenjdk_install/tasks/main.yml

I propose we use the adoptopenjdk_install to install bootjdks and not the common role, as we do with our other platforms. I assume we used the common role to install zulu binaries because there was no other option, so I reckon if these can now be replaced with our own binaries

**Comment by Haroon-Khel** [comment]
https://github.com/adoptium/infrastructure/pull/3805 in to stop the `adoptopenjdk_install` role from installing a non existent GA JDK17 on aarch64 alpine linux

**Comment by sxa** [comment]
Closing this as the PR has been closed (Noting that it was in iteration 3 but I can't currently select that as it's closed).

Haroon, I don't think there's any reason to but feel free to re-open if you believe there is more work here.
