### ISSUE TITLE
test-ibmcloud-rhel7-x64-1: Mere 13gb of free storage may be causing repro test to fail

### ISSUE THREAD

**Issue by adamfarley** [adoptium/infrastructure#3823]
Please set the title to indicate the test name and machine name where known.

To make it easy for the infrastructure team to repeat and diagnose, please
answer the following questions:

- test suite/name (e.g, BUILD_LIST, TARGET, CUSTOM_TARGET)?
Rebuild_Same_JDK_Reproducibility_Test_0
- a link into recent `Test_` job on https://ci.adoptium.net which showed the failure
https://ci.adoptium.net/job/Grinder/11811/consoleFull
- **Hyperlink** to re-run in Grinder: 
[Grinder rerun link](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=nightly&TARGET=special.system&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=%2Ftest%2Fsystem&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&LABEL=test-ibmcloud-rhel7-x64-1&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=21&ITERATIONS=1&VENDOR_TEST_REPOS=https%3A%2F%2Fgithub.com%2Fadoptium%2Ftemurin-build&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk21u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=master&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-21.0.6%2B3_adopt&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=%21%28centos6%7C%7Crhel6%29%26%26sw.tool.docker&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=120&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&OPENJDK_SHA=&NUM_MACHINES=&RERUN_FAILURE=false&BUILD_LIST=system&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=Dynamic)
- Is there an existing issue elsewhere covering this?
It was first seen [here](https://github.com/adoptium/temurin-build/issues/4056).
- Which machine(s) does it work on?
[test-ibmcloud-ubuntu1604-x64-1](https://ci.adoptium.net/computer/test-ibmcloud-ubuntu1604-x64-1) - This test passed here on November 6th. [Link.](https://ci.adoptium.net/job/Test_openjdk21_hs_special.system_x86-64_linux/32/)
- Which machine(s) does it fail on?
[test-ibmcloud-rhel7-x64-1](https://ci.adoptium.net/computer/test-ibmcloud-rhel7-x64-1)

Any other details:
The repro test completes the build and then fails with this error mid-sentence:
```
tee: write error
```

**Comment by adamfarley** [comment]
@steelhead31 - FYI

**Comment by steelhead31** [comment]
@adamfarley is there anyway to exclude the repro tests from running on this node? it has a small disk, and even with extreme levels of housekeeping, we'll struggle to get too much more.. if we cant, then we'll ask IBM if they can increase the size of the disk, as we don't have access to manage this machine.

**Comment by sxa** [comment]
There is a 100GiB disk that looks unused at the moment - that could be allocated to a separate docker or workspace file system.
`/var/lib/docker` is currently chewing about 47GiB so I suspect it just needs a bit of a prune - another case where we need to [start being better about docker disk management](https://github.com/adoptium/infrastructure/issues/3797) I feel.

Having said that, since `docker system df` is not showing information anywhere near `du` on the docker directory, it might be a good use case for shutting down the service, wiping that directory and starting it again ... I've done a cache prune but that has only yielded another 3GiB. Running another test job at https://ci.adoptium.net/job/Grinder/11842/

**Comment by steelhead31** [comment]
this machine has now been housekept, and the problematic overlay2 folder recreated, test running here [https://ci.adoptium.net/job/Grinder/11848/](https://ci.adoptium.net/job/Grinder/11848/) .  some additional housekeeping is being created and put in place in this issue.. #3797 ,
