### ISSUE TITLE
External tests hit a common error '.tmp-committed2602400920: no such file or directory`

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/infrastructure#3844]
https://ci.adoptium.net/view/Test_grinder/job/Grinder/12046/console
https://ci.adoptium.net/view/Test_grinder/job/Grinder/12073/console
https://ci.adoptium.net/view/Test_grinder/job/Grinder/12044/console

```
12:39:28       [exec] Dockerfile.hotspot.full:42
12:39:28       [exec] --------------------
12:39:28       [exec]   41 |     
12:39:28       [exec]   42 | >>> RUN apt-get update \
12:39:28       [exec]   43 | >>> 	&& apt-get install -qq -y --no-install-recommends software-properties-common \
12:39:28       [exec]   44 | >>> 	&& apt-get install -qq -y --no-install-recommends gnupg \
12:39:28       [exec]   45 | >>> 	&& add-apt-repository ppa:ubuntu-toolchain-r/test \
12:39:28       [exec]   46 | >>> 	&& apt-get update \
12:39:28       [exec]   47 | >>> 	&& apt-get install -y --no-install-recommends  git wget tar  \
12:39:28       [exec]   48 | >>> 	&& rm -rf /var/lib/apt/lists/*
12:39:28       [exec]   49 |     
12:39:28       [exec] --------------------
12:39:28       [exec] ERROR: failed to solve: failed to prepare sha256:974cf16e72adbb0cc871a0e864aecfdc1d174000630aa94501a0d735b8167e96 as ov873fsspmk3v3xy2diljezv0: open /var/lib/docker/overlay2/46b89910e858f1cc1c78151e5b7ea95763dce64e7ff1b96961f56e6a874bb75f/.tmp-committed2602400920: no such file or directory
```

```
10:27:48       [exec] Dockerfile.hotspot.full:36
10:27:48       [exec] --------------------
10:27:48       [exec]   34 |     ARG IMAGE_VERSION=nightly
10:27:48       [exec]   35 |     ARG TAG=11-jdk
10:27:48       [exec]   36 | >>> FROM $IMAGE
10:27:48       [exec]   37 |     
10:27:48       [exec]   38 |     ENV RESULT_COMMENT="IN CONTAINER(not-as-root/docker)"
10:27:48       [exec] --------------------
10:27:48       [exec] ERROR: failed to solve: failed to register layer: open /var/lib/docker/overlay2/37098fbd31f5602b08f427e434763843566aae07c289d03c3beb17229042a7e7/.tmp-committed1405576393: no such file or directory
10:27:48  
10:27:48  BUILD FAILED
```

**Comment by steelhead31** [comment]
I've corrected the issue with the docker/corrupted overlay directory..  rerunning in  these grinders,  [https://ci.adoptium.net/view/Test_grinder/job/Grinder/12084/](https://ci.adoptium.net/view/Test_grinder/job/Grinder/12084/) , [https://ci.adoptium.net/view/Test_grinder/job/Grinder/12085/](https://ci.adoptium.net/view/Test_grinder/job/Grinder/12085/) & [https://ci.adoptium.net/view/Test_grinder/job/Grinder/12086/](https://ci.adoptium.net/view/Test_grinder/job/Grinder/12086/) 

Will see how they work...

**Comment by steelhead31** [comment]
Despite clearing all docker cache, this error still occurs, I'll look into it further

**Comment by steelhead31** [comment]
Rebuild of this test still fails, [https://ci.adoptium.net/view/Test_grinder/job/Grinder/12046](https://ci.adoptium.net/view/Test_grinder/job/Grinder/12046) , not related to infra though.

Rebuild of this test [https://ci.adoptium.net/view/Test_grinder/job/Grinder/12073](https://ci.adoptium.net/view/Test_grinder/job/Grinder/12073) :  [https://ci.adoptium.net/view/Test_grinder/job/Grinder/12097/](https://ci.adoptium.net/view/Test_grinder/job/Grinder/12097/)

Rebuild of this test [https://ci.adoptium.net/view/Test_grinder/job/Grinder/12044](https://ci.adoptium.net/view/Test_grinder/job/Grinder/12044) :  here : [https://ci.adoptium.net/view/Test_grinder/job/Grinder/12093/](https://ci.adoptium.net/view/Test_grinder/job/Grinder/12093/) , which passed.
