### ISSUE TITLE
Decide where to host binaries that we're deploying via ansible

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#439]
Currently we have places in our ansible scripts that are [pulling from ci.adoptopenjdk.net](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/freemarker/tasks/main.yml) -  we need to decide if this is a sensible approach going forward or if we should host them somewhere else. Options?

- Keep them as-is on ci.adoptopenjdk.net (`~jenkins/.jenkins/userContent`)
- Keep them in github (Maybe a branch of openjdk-infrastructure?)
- Keep them on the AWX server since we'll be using that in order to deploy our machines, so it needs to be alive :-) (NOTE: Some packages used by the AIX playbooks are there)
- Store them on a custom server that we use for storing artefacts
- Anything else?

The following work items will be related to this:

- [Add extra windows dependencies](https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/300/files)
- [Install gcc 7.3.0 on Linux machines](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/438)
- [Remove dependency on University in Sweden](https://github.com/AdoptOpenJDK/openjdk-build/issues/441)

**Comment by karianna** [comment]
I have a slight preference for GitHub (their uptime is likely to be better than our own self hosted uptime). I think the ansible server is also a good place.

**Comment by jdekonin** [comment]
Storing on the ansible server will not help all use cases, for example I don't use the Adopt AWS server so I could then not use the playbooks without failures.

My typical use has been to run on the ansible-playbook on cmdln on a single machine as I don't perform bulk installs.  I think stashing the downloads (source or binaries) an excellent idea to prevent breakage though.  ant-contrib role for example.  I notice the other day that the url wasn't available and wasn't for many days.

I like the GitHub idea, its not hard pulling an individual file at all.  Example:
https://github.com/AdoptOpenJDK/openjdk-infrastructure/raw/master/CONTRIBUTING.md

**Comment by sxa555** [comment]
@jdekonin You appear to be assuming it wouldn't be accessible via straight HTTP on the AWX server. Whatever we do it needs to be a solution that works for everyone - I'm not proposing hiding it somewhere only available to processes running on the server.

**Comment by sxa555** [comment]
@jdekonin Ref your comment on ant-contrib, I had another similar issue which is documented in the third link of this issue

**Comment by neomatrix369** [comment]
AdoptOpenJDK already has a space on Bintray/JFrog/Artifactory whatever its called, see https://bintray.com/adoptopenjdk, we can store binaries that can be publically hosted on that box. Any other binaries with restrictive licenses should not be placed there unless we create a private area on that server. @karianna informs doing that is expensive on a monthly-basis.

**Comment by karianna** [comment]
bintray is $150 a month for private repos.  We can cover this with sponsorship but I'd rather wait until we're also hosting installers and/or actual adopt binaries there to justify the cost.

**Comment by sxa** [comment]
Going to close this. We're currently using ci.adoptopenjdk.net/userContent and that seems to be working and doesn't incur charges, and there are no short-term plans to change that.
