### ISSUE TITLE
Jenkins MacOS slaves might night an update / upgrade with software on them

### ISSUE THREAD

**Issue by neomatrix369** [adoptium/infrastructure#780]
_Raising this issue on the back of the Slack conversation (https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1556834573031000)._

Recently a graal build failed due to an outdated version of TLS / OpenSSL on it:

```bash
<==snipped==>
Could not download to /Users/jenkins/.mx/cache/NINJA_SYNTAX_702ca2d0ae93841c5ab75e4d119b29780ec0b7d9/ninja-syntax.tar.gz from any of the following URLs: https://pypi.org/packages/source/n/ninja_syntax/ninja_syntax-1.7.2.tar.gz
Error reading from https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-mac.zip: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
WARNING: ** If behind a firewall without direct internet access, use the http_proxy environment variable (e.g. "env http_proxy=proxy.company.com:80 mx ...") or download manually with a web browser.
WARNING: It seems that you have a version of python (/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python) that uses an older version of OpenSSL. This should be fixed by installing the latest 2.7 release from https://www.python.org/downloads
Could not download to /Users/jenkins/.mx/cache/NINJA_8142c497f7dfbdb052a1e31960fdfe2c6f9a5ca2/ninja.zip from any of the following URLs: https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-mac.zip
Downloading NINJA failed
<==snipped==>
```
rest of the logs can be seen at https://ci.adoptopenjdk.net/job/jdk8-with-graal_build_x86-64_macos/lastBuild/console

Possibly a manual or an ansible script update should help with this. As per the warning message Python / SSL / OpenSSL might need upgrading.

**Comment by karianna** [comment]
@neomatrix369 I've updated to 1.0.2r Can you try again?

**Comment by sxa555** [comment]
Tagging #554 so this can be added when appropriate

**Comment by neomatrix369** [comment]
It's failing for another reason, can't confirm yet if your fix worked @karianna. I'll come back to this again and let you know.

**Comment by neomatrix369** [comment]
On another note which is a separate issue. One or all of your Linux slaves are running python 2.6.x, instead of 2.7. In fact 3.7 should be a standard on all of them, unless there are apps that specifically need 2.7.

I'll raise a separate issue on that one.

**Comment by neomatrix369** [comment]
Looking at the logs on https://ci.adoptopenjdk.net/job/jdk8-with-graal_build_x86-64_macos/359/console, it seems `clang` is acting up, on this instance, we never had these errors before.

Any `clang` experts on the list?

**Comment by sxa555** [comment]
@neomatrix369 is there something blocking this at the moment - does the `clang` issue that you mentioned above still exist? (Not sure what it was from your previous comment)

**Comment by sxa** [comment]
I'm going to close this as we do not build GraalVM in any form at Adoptium.
