### ISSUE TITLE
Enable Huge Pages on 2 x86 Perf Machines (test-packet-ubuntu1604-x64-2 & test-softlayer-ubuntu1604-x64-1)

### ISSUE THREAD

**Issue by piyush286** [adoptium/infrastructure#786]
### Proposed Changes

I would request to enable huge pages on the perf machines. This would enhance our footprint measurements for Open Liberty with Daytrader7. Thanks!

Currently, we just have to machine labelled with `ci.role.perf`: https://ci.adoptopenjdk.net/label/ci.role.perf/

### Justification

Please refer to this prerequisite for perf testing: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1136. 
### Related Machines 
https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-2/
https://ci.adoptopenjdk.net/computer/test-softlayer-ubuntu1604-x64-1/

**Comment by sxa555** [comment]
Do you have the information on  how to enable it?

**Comment by piyush286** [comment]
@sxa555 I've listed some general notes on how to enable huge pages. Those steps might vary a bit depending on the OS version. We want to make these huge pages persistent so that they are enabled even after a reboot. 

- Set the number of hugepages accordingly depending on how much memory (i.e. MemTotal) the machine has. The system won't reboot if you allocate more hugepages than the system memory can support.
- Check memory
  - cat /proc/meminfo
- Hugepages formula:
  - HugePages_Total (i.e. # of hugepages)* Hugepagesize (i.e. Size of hugepage) =< MemTotal
- sudo sysctl -w vm.nr_hugepages=<HugePages_Total>
- echo "vm.nr_hugepages=<HugePages_Total>" >> /etc/sysctl.conf

**Comment by sxa555** [comment]
How much would you recommend for your use relative to the total memory? I could set the number of HugePages to `1` and that would meet your formula but I'm guessing you'd like more :-)

**Comment by piyush286** [comment]
Haha! For our internal perf machines, we usually set the total memory allocated for huge pages to around 70% of the total memory so I guess we can use a similar ratio for these machines if that sounds good to you.

**Comment by Haroon-Khel** [comment]
@piyush286 Could you post an output of `cat /proc/meminfo`? It will give me an idea of the MemTotal and Hugepagessize values

**Comment by piyush286** [comment]
Hugepagesize can be set to 2048 kB. We should set the total memory allocated for huge pages to around 70% of the total memory. 

Just an example from one of our machines:
```
[jbench@perfxposh ~]$ cat /proc/meminfo
MemTotal:       791701028 kB
Hugepagesize:       2048 kB
```

**Comment by sxa555** [comment]
So can probably do some sort of calculation along the lines of:
```
MEM=`awk '/^MemTotal:/{print$2}' /proc/meminfo`
HUGEPAGESIZE=`awk '/^Hugepagesize:/{print$2}' /proc/meminfo`
HUGEPAGES=`echo $MEM \* .7 / HUGEPAGESIZE | bc`
```
and set it to $HUGEPAGES (assuming you agree the logic looks sound ;-) )

**Comment by sxa555** [comment]
@Haroon-Khel Did we ever finish this? Do you have access to the machines and can implement this if it hasn't already been set?

**Comment by Haroon-Khel** [comment]
@sxa555 No, I was waiting for a response from @piyush286 to agree with the logic from your previous comment. But I can complete this now as the logic makes sense. However, I do not have root access to either machine

**Comment by sxa555** [comment]
Key added to [test-packet-ubuntu1604-x64-2](https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-2/configure) and [test-softlayer-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/test-softlayer-ubuntu1604-x64-1/)

Side note: We should also consider renaming these to be `perf-` instead of `test-` for consistency with some of the newer macstadium boxes ...

**Comment by Haroon-Khel** [comment]
For test-packet-ubuntu1604-x64-2 Ive set the `HugePages_Total` to 2789. Though its entry in /proc/meminfo has become 638. Though I suspect that this will correct itself after a reboot since I have also added `vm.nr_hugepages=2789` to `/etc/sysctl,conf`

**Comment by sxa555** [comment]
If you need to reboot the machines then feel to do it as long as the executors on the machine are idle in jenkins e.g. [test-packet-ubuntu1604-x64-1](https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-1/configure) and [test-packet-ubuntu1604-x64-2](https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-2)

**Comment by sxa555** [comment]
@piyush286 @Haroon-Khel Where are we with this one? Is it complete now or do I have to move it into the April milestone?

**Comment by Haroon-Khel** [comment]
It is still half complete. I couldnt figure out how to enable huge pages on `test-softlayer-ubuntu1604-x64-1` since its configuration was different than expected, as said above

**Comment by Willsparker** [comment]
As far as I can tell, the `test-softlayer-ubuntu1604-x64-1` machine doesn't exist anymore. I don't think this has been replaced? Or at least, it hasn't been labelled as such in the inventory, so I think we can close this issue

**Comment by sxa** [comment]
https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-1/ is the only xLinux machine that has `ci.role.perf` at present ... We need to sort out the OS on that, but this probably shouldn't be considered closed until that machine is verified to have had the changes.

**Comment by sxa** [comment]
@smlambert Is this still a requirement that we need to push forward with?

**Comment by smlambert** [comment]
Let's close for now.  We can come back and raise a new request at a later time if needed.
