### ISSUE TITLE
Install SSH Keys/STAF on test-packet-ubuntu1604-x64-2 & test-softlayer-ubuntu1604-x64-1

### ISSUE THREAD

**Issue by piyush286** [adoptium/infrastructure#787]
### Proposed Changes

I would request to install Software Testing Automation Framework (STAF) on 2 perf machines. This would allow us to run benchmarks such as Open Liberty with DayTrader that require 2 machines to communicate with each other. Thanks!

Currently, we just have 2 machines labelled with `ci.role.perf`: https://ci.adoptopenjdk.net/label/ci.role.perf/

We need to install STAF on those 2 machines. My team has been using STAF for quite sometime so I would be happy to help in setting it up.

### Justification

Please refer to this prerequisite for perf testing: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1138

### Related Machines 
https://ci.adoptopenjdk.net/computer/test-packet-ubuntu1604-x64-2/
https://ci.adoptopenjdk.net/computer/test-softlayer-ubuntu1604-x64-1/

**Comment by sxa555** [comment]
Hmmm I thought DayTrader was standalone and only used one machine. We need to think about the implications of this and how to set up authentication given that these machines are on the internet. Also:

- Do you just need the base STAF on it i.e. no  STAX etc.?
- If not already done, we need to consider the implications of running performance testing on machines that are connected to jenkins and so may have things run on machines that jenkins isn't aware of

FYI @smlambert

**Comment by piyush286** [comment]
@sxa555 We can use Liberty + Apps (i.e. DayTrader/AcmeAir) to do startup and throughput runs. While startup and footprint runs are standalone, requiring just one machine, we do need 2 machines for DayTrader throughput runs, one machine as the Liberty DayTrader server and another machine with the database for driving the load. So the setup would look like this:

Machine 1: Liberty Server (DayTrader)
Machine 2: Database + Client

Since we require 2 machines for setting up throughput runs, the machine would need some way to communicate with each other. We've been using STAF so far for running benchmarks that require more than one machine.

It's totally understandable if we decide to use SSH Keys instead of STAF to do such communication since SSH Keys might be slightly simpler to setup especially most people are familiar with it. I notice that Infrastructure team is using KeyBox (https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ONBOARDING.md#keybox) to manage SSH Keys. So if the machines can have other machines' keys, then we can use that for benchmarks that require multiple machines. I could experiment with it if we can enable the keys on these 2 machines for now. 

> Do you just need the base STAF on it i.e. no STAX etc.?

Just STAF! We don't need STAX for Liberty DayTrader. However, my team does use STAX for running benchmarks on WebSphere Application Server internally but for now, we don't plan to add support for it on Adopt.

> If not already done, we need to consider the implications of running performance testing on machines that are connected to jenkins and so may have things run on machines that jenkins isn't aware of

While running perf tests, we'll have to make sure that we aren't running any unnecessary processes, which could taint the perf results. 

So again, it's really up to you, @smlambert and other interested people/leads to decide whether we want to use SSH Keys, STAF or some other approach. I'm good with whatever seems to be the most reasonable solution to everyone :)

**Comment by sxa555** [comment]
I've manually created and stuck the ssh keys on both machines to allow them to communicate with each other for now to allow you to test  then I'll discuss the final strategy once I can talk to Shelley again since I need to ensure we have a solution to  both machines currently being controlled by jenkins too.

Give it a shot and let me know how it goes!

**Comment by piyush286** [comment]
Thanks a lot Stewart! Yeah we need to find some solution that prevents both machines (Server and client) from running anything besides the current benchmark job. 

While Jenkins will have control over one of the machine (i.e. Liberty server) which would be used to launch the benchmarks, it wouldn't have control over the slave machines (i.e. Liberty client) that are used through STAF or SSH commands.

**Comment by sxa555** [comment]
Yep - if the machiens were dedicated for these purposes that would be easy as we'd just have the jenkins slave active on one of them. We'll figure a way around it though - there are options ...

**Comment by piyush286** [comment]
> Yep - if the machiens were dedicated for these purposes that would be easy as we'd just have the jenkins slave active on one of them. We'll figure a way around it though - there are options ...

Yup that can partially resolve this issue. However, it's possible that 2 different server machines running at the same time could use the same slave machine, in which case we'll have to have some solution in order avoid that situation so that one slave can only be used by one benchmark run at a time.

**Comment by sxa** [comment]
@smlambert Is there any need for this now? I assume if there was someone would be shouting? :-)

**Comment by smlambert** [comment]
Close this for now... there may be a fresh request coming in relation to performance testing and supporting multiple machine configuration (especially if we get funding for an intern this year).
