### ISSUE TITLE
Re-label ssh key being used for jenkins auth so it does not have George's name in it

### ISSUE THREAD

**Issue by sxa** [adoptium/infrastructure#805]
At the moment the public ssh key named `george@Georges-MacBook-Pro-Work.local` is the one used for authenticating our Jenkins server to the agent on the machines. We should use something more descriptive and not user-specific (either by replacing the key or the label globally)

**Comment by gdams** [comment]
To be clear, it's not actually my personal key, it was just generated on my laptop, If you change the email address of the key then all will be fine

**Comment by sxa** [comment]
Jenkins and AWX are deploying with the key relabelled as `jenkins@ci.adoptopenjdk.net` - closing.
