### ISSUE TITLE
Add build machine supporting GTK3 to run the complete JMC test set

### ISSUE THREAD

**Issue by reinhapa** [adoptium/infrastructure#932]
In order to have the complete test suite for the Mission Control Project being run, I need a build Linux x64 build machine that supports GTK3 using Xvfb

**Comment by sxa555** [comment]
@reinhapa Do you know which specific packages are needed for this? We already put xvfb on the machines by default and the `jmc-build` jobs look to all be running on [build-scaleway-x64-ubuntu-16-04-2](https://ci.adoptopenjdk.net/computer/build-scaleway-x64-ubuntu-16-04-2) which has quite a few of the GTK3 packages installed:

```
jenkins@build-scaleway-ubuntu1604-x64-2:~$ dpkg -l | grep -i gtk
ii  gir1.2-gtk-2.0                        2.24.30-1ubuntu1.16.04.2                 amd64        GTK+ graphical user interface library -- gir bindings
ii  gir1.2-gtk-3.0:amd64                  3.18.9-1ubuntu3.3                        amd64        GTK+ graphical user interface library -- gir bindings
ii  libgtk-3-0:amd64                      3.18.9-1ubuntu3.3                        amd64        GTK+ graphical user interface library
ii  libgtk-3-bin                          3.18.9-1ubuntu3.3                        amd64        programs for the GTK+ graphical user interface library
ii  libgtk-3-common                       3.18.9-1ubuntu3.3                        all          common files for the GTK+ graphical user interface library
ii  libgtk-3-dev:amd64                    3.18.9-1ubuntu3.3                        amd64        development files for the GTK+ library
ii  libgtk2.0-0:amd64                     2.24.30-1ubuntu1.16.04.2                 amd64        GTK+ graphical user interface library
ii  libgtk2.0-bin                         2.24.30-1ubuntu1.16.04.2                 amd64        programs for the GTK+ graphical user interface library
ii  libgtk2.0-common                      2.24.30-1ubuntu1.16.04.2                 all          common files for the GTK+ graphical user interface library
ii  libgtk2.0-dev                         2.24.30-1ubuntu1.16.04.2                 amd64        development files for the GTK+ library
jenkins@build-scaleway-ubuntu1604-x64-2:~$ 
```
Is this adequate for this requirement?

**Comment by reinhapa** [comment]
@sxa555 I could run a test build enabling those tests again...

**Comment by sxa555** [comment]
@reinhapa Any luck?

**Comment by reinhapa** [comment]
oic, at the moment it is configured for `build-scaleway-x64-ubuntu-16-04-2` will switch over to `build-scaleway-x64-ubuntu-16-04-2` and give it a try...

**Comment by reinhapa** [comment]
@sxa555 I enabled the UI tests now ignoring any failures for further analysis. I guess that @thegreystone may has an idea, what the problem is...

**Comment by sxa555** [comment]
@reinhapa Any updates on this one? Do you believe there is a follow-on infrastructure issue with the setup or are the issues you're hitting potentially down to "real" code problems? Need to know if I can close this or if i have to move it to the April milestone now.

**Comment by reinhapa** [comment]
@sxa555 I did not get the cause of the failing tests as they seem to pass locally. As this issue is not that problematic at the moment, I got no problem to move this issue to the April now..

**Comment by sxa** [comment]
@reinhapa Is this still causing a problem?

**Comment by reinhapa** [comment]
@sxa the job is no longer built on Jenkins instead using github actions now...
