### ISSUE TITLE
Heart beat check causes intermittent test failures

### ISSUE THREAD

**Issue by johnoliver** [adoptium/infrastructure#941]
JENKINS-48300 issue seems to cause intermittent build failures

https://ci.adoptopenjdk.net/job/Test_openjdk13_hs_sanity.openjdk_x86-64_mac/49/console

```
07:27:54  Cannot contact test-macincloud-macos1013-x64-2: java.lang.InterruptedException
07:35:37  wrapper script does not seem to be touching the log file in /Users/jenkins/workspace/Test_openjdk13_hs_sanity.openjdk_x86-64_mac@tmp/durable-d48b539f
07:35:37  (JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
```

**Comment by Willsparker** [comment]
Seems the bug on [Jenkins has been resolved](https://issues.jenkins.io/browse/JENKINS-48300?attachmentViewMode=list). Does anybody know if this issue still affects our builds?

**Comment by smlambert** [comment]
I have not seen this recently at all, so agree it can be closed.
